# Generated by Django 4.2.1 on 2023-05-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0031_alter_historicalinvitation_first_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalaffiliation",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical affiliation",
                "verbose_name_plural": "historical affiliations",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalapplication",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical application",
                "verbose_name_plural": "historical applications",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcriterion",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical criterion",
                "verbose_name_plural": "historical criteria",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalevaluation",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical evaluation",
                "verbose_name_plural": "historical evaluations",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalinvitation",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical invitation",
                "verbose_name_plural": "historical invitations",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalmember",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical member",
                "verbose_name_plural": "historical members",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalnomination",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical nomination",
                "verbose_name_plural": "historical nominations",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalorganisation",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical organisation",
                "verbose_name_plural": "historical organisations",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpanellist",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical panellist",
                "verbose_name_plural": "historical panellists",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalprofile",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical profile",
                "verbose_name_plural": "historical profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalreferee",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical referee",
                "verbose_name_plural": "historical referees",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalround",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical round",
                "verbose_name_plural": "historical rounds",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaltestimonial",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical testimonial",
                "verbose_name_plural": "historical testimonials",
            },
        ),
        migrations.AddField(
            model_name="historicalround",
            name="has_for",
            field=models.BooleanField(
                default=False, help_text="Has Field of Research Categories", verbose_name="Has FoR"
            ),
        ),
        migrations.AddField(
            model_name="historicalround",
            name="has_seo",
            field=models.BooleanField(
                default=False,
                help_text="Has Socio-Economic Objective Categories",
                verbose_name="Has SEO",
            ),
        ),
        migrations.AddField(
            model_name="historicalround",
            name="has_toa",
            field=models.BooleanField(
                default=False, help_text="Has Type of Activity Categories", verbose_name="Has ToA"
            ),
        ),
        migrations.AddField(
            model_name="historicalround",
            name="has_vmt",
            field=models.BooleanField(
                default=False,
                help_text="Has Vision Mātauranga Theme Categories",
                verbose_name="Has VMT",
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="has_for",
            field=models.BooleanField(
                default=False, help_text="Has Field of Research Categories", verbose_name="Has FoR"
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="has_seo",
            field=models.BooleanField(
                default=False,
                help_text="Has Socio-Economic Objective Categories",
                verbose_name="Has SEO",
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="has_toa",
            field=models.BooleanField(
                default=False, help_text="Has Type of Activity Categories", verbose_name="Has ToA"
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="has_vmt",
            field=models.BooleanField(
                default=False,
                help_text="Has Vision Mātauranga Theme Categories",
                verbose_name="Has VMT",
            ),
        ),
        migrations.AlterField(
            model_name="historicalaffiliation",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalapplication",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalcriterion",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalevaluation",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalinvitation",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalmember",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalnomination",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisation",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalpanellist",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalprofile",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalreferee",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalround",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaltestimonial",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
