# Generated by Django 4.2.2 on 2023-07-03 05:30

import common.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import portal.models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0033_researchoffice_historicalresearchoffice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalround",
            name="application_template",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "doc",
                            "docx",
                            "dot",
                            "dotx",
                            "docm",
                            "dotm",
                            "docb",
                            "odt",
                            "ott",
                            "oth",
                            "odm",
                            "rtf",
                            "tex",
                        ]
                    )
                ],
                verbose_name="Application Template",
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="application_template",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=portal.models.round_template_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "doc",
                            "docx",
                            "dot",
                            "dotx",
                            "docm",
                            "dotm",
                            "docb",
                            "odt",
                            "ott",
                            "oth",
                            "odm",
                            "rtf",
                            "tex",
                        ]
                    )
                ],
                verbose_name="Application Template",
            ),
        ),
        migrations.CreateModel(
            name="ApplicationFormTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "template",
                    models.FileField(
                        upload_to=portal.models.round_template_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "doc",
                                    "docx",
                                    "dot",
                                    "dotx",
                                    "docm",
                                    "dotm",
                                    "docb",
                                    "odt",
                                    "ott",
                                    "oth",
                                    "odm",
                                    "rtf",
                                    "tex",
                                ]
                            )
                        ],
                        verbose_name="Template",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_form_templates",
                        to="portal.round",
                    ),
                ),
            ],
            options={
                "db_table": "application_form_template",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
    ]
