# Generated by Django 4.2.2 on 2023-07-04 03:08

import common.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import portal.models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0034_alter_historicalround_application_template_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurriculumVitaeTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "template",
                    models.FileField(
                        upload_to=portal.models.round_template_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "doc",
                                    "docx",
                                    "dot",
                                    "dotx",
                                    "docm",
                                    "dotm",
                                    "docb",
                                    "odt",
                                    "ott",
                                    "oth",
                                    "odm",
                                    "rtf",
                                    "tex",
                                ]
                            )
                        ],
                        verbose_name="Template",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculum_vitae_templates",
                        to="portal.round",
                    ),
                ),
            ],
            options={
                "db_table": "curriculum_vitae_template",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
    ]
