# Generated by Django 4.2.3 on 2023-07-06 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("portal", "0035_curriculumvitaetemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldofresearch",
            name="is_stem",
            field=models.BooleanField(
                default=False,
                help_text="Science, Technology, Engineering, and Mathematics..",
                verbose_name="is STEM",
            ),
        ),
        migrations.AddField(
            model_name="fieldofresearch",
            name="rcc",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="fieldofresearch",
            name="version",
            field=models.CharField(default="1.0.0", max_length=10),
        ),
        migrations.AlterField(
            model_name="fieldofresearch",
            name="definition",
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name="fieldofresearch",
            name="description",
            field=models.CharField(max_length=200, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="fieldofresearch",
            name="four_digit_description",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
