# Generated by Django 4.2.3 on 2023-07-28 08:29

import common.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import portal.models
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sites", "0004_auto_20210331_1418"),
        ("portal", "0036_fieldofresearch_is_stem_fieldofresearch_rcc_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "code",
                    models.CharField(
                        db_column="code", max_length=5, primary_key=True, serialize=False
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=10000, null=True, verbose_name="short description"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, max_length=10000, null=True, verbose_name="short description"
                    ),
                ),
                (
                    "description_mi",
                    models.TextField(
                        blank=True, max_length=10000, null=True, verbose_name="short description"
                    ),
                ),
            ],
            options={
                "db_table": "category",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AF", "Application Form"),
                            ("B", "Budget"),
                            ("CV", "Curriculum Vitae"),
                            ("F", "Form"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("name_en", models.CharField(max_length=200, null=True, verbose_name="Name")),
                ("name_mi", models.CharField(max_length=200, null=True, verbose_name="Name")),
            ],
            options={
                "db_table": "document_type",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Title",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("code", models.CharField(max_length=10, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=40)),
                ("name_en", models.CharField(max_length=40, null=True)),
                ("name_mi", models.CharField(max_length=40, null=True)),
            ],
            options={
                "db_table": "title",
                "ordering": ["code"],
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.RenameField(
            model_name="application",
            old_name="rationane_vm_na",
            new_name="vm_rationane",
        ),
        migrations.RenameField(
            model_name="applicationformtemplate",
            old_name="template",
            new_name="file",
        ),
        migrations.RenameField(
            model_name="curriculumvitaetemplate",
            old_name="template",
            new_name="file",
        ),
        migrations.RenameField(
            model_name="historicalapplication",
            old_name="rationane_vm_na",
            new_name="vm_rationane",
        ),
        migrations.AddField(
            model_name="application",
            name="research_experience_in_years",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="research experience in years "
            ),
        ),
        migrations.AddField(
            model_name="historicalapplication",
            name="research_experience_in_years",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="research experience in years "
            ),
        ),
        migrations.AddField(
            model_name="historicalreferee",
            name="survey_completed_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalreferee",
            name="survey_invitation_sent_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalreferee",
            name="survey_token",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="historicalreferee",
            name="survey_token_id",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalround",
            name="is_flexible_number_of_referees",
            field=models.BooleanField(default=False, verbose_name="Flexible number of referees"),
        ),
        migrations.AddField(
            model_name="historicalround",
            name="research_experience_in_years_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalround",
            name="survey_id",
            field=models.PositiveIntegerField(
                blank=True, help_text="LimeSurvey Survey ID", null=True
            ),
        ),
        migrations.AddField(
            model_name="referee",
            name="survey_completed_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="referee",
            name="survey_invitation_sent_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="referee",
            name="survey_token",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="referee",
            name="survey_token_id",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="round",
            name="is_flexible_number_of_referees",
            field=models.BooleanField(default=False, verbose_name="Flexible number of referees"),
        ),
        migrations.AddField(
            model_name="round",
            name="research_experience_in_years_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="round",
            name="survey_id",
            field=models.PositiveIntegerField(
                blank=True, help_text="LimeSurvey Survey ID", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalnomination",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Nominee",
            ),
        ),
        migrations.AlterField(
            model_name="nomination",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nominations_to_apply",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Nominee",
            ),
        ),
        migrations.CreateModel(
            name="RoundDocumentTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "file",
                    models.FileField(
                        upload_to=portal.models.round_template_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "csv",
                                    "ctv",
                                    "doc",
                                    "docb",
                                    "docm",
                                    "docx",
                                    "dot",
                                    "dotm",
                                    "dotx",
                                    "odm",
                                    "odt",
                                    "oth",
                                    "ott",
                                    "rtf",
                                    "tex",
                                    "xls",
                                    "xlsb",
                                    "xlsm",
                                    "xlsx",
                                    "xlt",
                                    "xltm",
                                    "xltx",
                                    "xlw",
                                    "xml",
                                ]
                            )
                        ],
                        verbose_name="Template",
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.documenttype"
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="portal.round",
                    ),
                ),
            ],
            options={
                "db_table": "round_document_template",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="RequiredDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("ordering", models.PositiveIntegerField(default=0, verbose_name="ordering")),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, null=True, verbose_name="Title"),
                ),
                (
                    "title_en",
                    models.CharField(blank=True, max_length=200, null=True, verbose_name="Title"),
                ),
                (
                    "title_mi",
                    models.CharField(blank=True, max_length=200, null=True, verbose_name="Title"),
                ),
                ("is_optional", models.BooleanField(default=False)),
                ("min_pages", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("max_pages", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.documenttype"
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="required_documents",
                        to="portal.round",
                    ),
                ),
            ],
            options={
                "db_table": "required_document",
                "ordering": ["ordering"],
                "abstract": False,
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Fund",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "code",
                    common.models.FixedCharField(
                        db_column="code", max_length=2, primary_key=True, serialize=False
                    ),
                ),
                ("code3", common.models.FixedCharField(blank=True, max_length=3, null=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=10000, null=True, verbose_name="description"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, max_length=10000, null=True, verbose_name="description"
                    ),
                ),
                (
                    "description_mi",
                    models.TextField(
                        blank=True, max_length=10000, null=True, verbose_name="description"
                    ),
                ),
                (
                    "cost_centre",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Cost Center"
                    ),
                ),
                (
                    "catalyst_cost_centre",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Catalyst Cost Center"
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        default=common.models.Model.get_current_site_id,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "db_table": "fund",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ApplicationDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("page_count", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "file",
                    private_storage.fields.PrivateFileField(
                        blank=True,
                        null=True,
                        storage=private_storage.storage.files.PrivateFileSystemStorage(),
                        upload_to="",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "csv",
                                    "ctv",
                                    "doc",
                                    "docb",
                                    "docm",
                                    "docx",
                                    "dot",
                                    "dotm",
                                    "dotx",
                                    "odm",
                                    "odt",
                                    "oth",
                                    "ott",
                                    "pdf",
                                    "rtf",
                                    "tex",
                                    "xls",
                                    "xlsb",
                                    "xlsm",
                                    "xlsx",
                                    "xlt",
                                    "xltm",
                                    "xltx",
                                    "xlw",
                                    "xml",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="portal.application",
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_documents",
                        to="portal.documenttype",
                    ),
                ),
                (
                    "required_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.requireddocument",
                    ),
                ),
            ],
            options={
                "db_table": "application_document",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.AddField(
            model_name="scheme",
            name="category",
            field=models.ForeignKey(
                blank=True,
                db_column="category",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portal.category",
            ),
        ),
        migrations.AddField(
            model_name="scheme",
            name="fund",
            field=models.ForeignKey(
                blank=True,
                db_column="fund",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portal.fund",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="title",
            field=models.ForeignKey(
                blank=True,
                db_column="title",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="portal.title",
                verbose_name="title",
            ),
        ),
        migrations.AlterField(
            model_name="historicalapplication",
            name="title",
            field=models.ForeignKey(
                blank=True,
                db_column="title",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="portal.title",
                verbose_name="title",
            ),
        ),
        migrations.AlterField(
            model_name="historicalnomination",
            name="title",
            field=models.ForeignKey(
                blank=True,
                db_column="title",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="portal.title",
                verbose_name="title",
            ),
        ),
        migrations.AlterField(
            model_name="nomination",
            name="title",
            field=models.ForeignKey(
                blank=True,
                db_column="title",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="portal.title",
                verbose_name="title",
            ),
        ),
    ]
