# Generated by Django 4.2.3 on 2023-07-19 06:39

import common.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import portal.models
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0036_fieldofresearch_is_stem_fieldofresearch_rcc_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AF", "Application Form"),
                            ("B", "Budget"),
                            ("CV", "Curriculum Vitae"),
                            ("F", "Form"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("name_en", models.CharField(max_length=200, null=True, verbose_name="Name")),
                ("name_mi", models.CharField(max_length=200, null=True, verbose_name="Name")),
            ],
            options={
                "db_table": "document_type",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.RenameField(
            model_name="applicationformtemplate",
            old_name="template",
            new_name="file",
        ),
        migrations.RenameField(
            model_name="curriculumvitaetemplate",
            old_name="template",
            new_name="file",
        ),
        migrations.AddField(
            model_name="historicalround",
            name="is_flexible_number_of_referees",
            field=models.BooleanField(default=False, verbose_name="Flexible number of referees"),
        ),
        migrations.AddField(
            model_name="round",
            name="is_flexible_number_of_referees",
            field=models.BooleanField(default=False, verbose_name="Flexible number of referees"),
        ),
        migrations.CreateModel(
            name="RoundDocumentTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "file",
                    models.FileField(
                        upload_to=portal.models.round_template_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "csv",
                                    "ctv",
                                    "doc",
                                    "docb",
                                    "docm",
                                    "docx",
                                    "dot",
                                    "dotm",
                                    "dotx",
                                    "odm",
                                    "odt",
                                    "oth",
                                    "ott",
                                    "rtf",
                                    "tex",
                                    "xls",
                                    "xlsb",
                                    "xlsm",
                                    "xlsx",
                                    "xlt",
                                    "xltm",
                                    "xltx",
                                    "xlw",
                                    "xml",
                                ]
                            )
                        ],
                        verbose_name="Template",
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.documenttype"
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="portal.round",
                    ),
                ),
            ],
            options={
                "db_table": "round_document_template",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="RequiredDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("ordering", models.PositiveIntegerField(default=0, verbose_name="ordering")),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, null=True, verbose_name="Title"),
                ),
                (
                    "title_en",
                    models.CharField(blank=True, max_length=200, null=True, verbose_name="Title"),
                ),
                (
                    "title_mi",
                    models.CharField(blank=True, max_length=200, null=True, verbose_name="Title"),
                ),
                ("is_optional", models.BooleanField(default=False)),
                ("min_pages", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("max_pages", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.documenttype"
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="required_documents",
                        to="portal.round",
                    ),
                ),
            ],
            options={
                "db_table": "required_document",
                "ordering": ["ordering"],
                "abstract": False,
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ApplicationDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("page_count", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "file",
                    private_storage.fields.PrivateFileField(
                        blank=True,
                        null=True,
                        storage=private_storage.storage.files.PrivateFileSystemStorage(),
                        upload_to="",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "csv",
                                    "ctv",
                                    "doc",
                                    "docb",
                                    "docm",
                                    "docx",
                                    "dot",
                                    "dotm",
                                    "dotx",
                                    "odm",
                                    "odt",
                                    "oth",
                                    "ott",
                                    "pdf",
                                    "rtf",
                                    "tex",
                                    "xls",
                                    "xlsb",
                                    "xlsm",
                                    "xlsx",
                                    "xlt",
                                    "xltm",
                                    "xltx",
                                    "xlw",
                                    "xml",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="portal.application",
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_documents",
                        to="portal.documenttype",
                    ),
                ),
                (
                    "required_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.requireddocument",
                    ),
                ),
            ],
            options={
                "db_table": "application_document",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
    ]
