# Generated by Django 4.2.3 on 2023-08-22 05:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import portal.models
import private_storage.fields
import private_storage.storage.files
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("portal", "0037_category_documenttype_title_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="academicrecord",
            old_name="converted_on",
            new_name="conferred_on",
        ),
        migrations.AddField(
            model_name="applicationdocument",
            name="converted_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portal.convertedfile",
                verbose_name="converted file",
            ),
        ),
        migrations.AddField(
            model_name="fieldofstudy",
            name="version",
            field=models.CharField(default="ISCED-F 2013", max_length=20),
        ),
        migrations.AddField(
            model_name="historicalinvitation",
            name="read_at",
            field=model_utils.fields.MonitorField(monitor="status", when={"read"}),
        ),
        migrations.AddField(
            model_name="historicalinvitation",
            name="status_changed_at",
            field=model_utils.fields.MonitorField(monitor="status"),
        ),
        migrations.AddField(
            model_name="historicalsocioeconomicobjective",
            name="definition",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalsocioeconomicobjective",
            name="version",
            field=models.CharField(default="1.0.0", max_length=10),
        ),
        migrations.AddField(
            model_name="invitation",
            name="read_at",
            field=model_utils.fields.MonitorField(monitor="status", when={"read"}),
        ),
        migrations.AddField(
            model_name="invitation",
            name="status_changed_at",
            field=model_utils.fields.MonitorField(monitor="status"),
        ),
        migrations.AddField(
            model_name="maillog",
            name="thread_index",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="maillog",
            name="thread_topic",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="socioeconomicobjective",
            name="definition",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="socioeconomicobjective",
            name="version",
            field=models.CharField(default="1.0.0", max_length=10),
        ),
        migrations.AlterField(
            model_name="application",
            name="state",
            field=portal.models.StatusField(
                choices=[
                    (None, None),
                    ("new", "new"),
                    ("draft", "draft"),
                    ("tac_accepted", "TAC accepted"),
                    ("submitted", "submitted"),
                    ("cancelled", "cancelled"),
                    ("withdrawn", "withdrawn"),
                    ("approved", "approved"),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="curriculumvitae",
            name="file",
            field=private_storage.fields.PrivateFileField(
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "doc",
                            "docb",
                            "docm",
                            "docx",
                            "dot",
                            "dotm",
                            "dotx",
                            "odm",
                            "odt",
                            "oth",
                            "ott",
                            "pdf",
                            "rtf",
                            "tex",
                        ]
                    )
                ],
                verbose_name="file",
            ),
        ),
        migrations.AlterField(
            model_name="curriculumvitae",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="A title or name you can assign to the upload CV file",
                max_length=200,
                null=True,
                verbose_name="title",
            ),
        ),
        migrations.AlterField(
            model_name="historicalaffiliation",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalapplication",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalapplication",
            name="state",
            field=portal.models.StatusField(
                choices=[
                    (None, None),
                    ("new", "new"),
                    ("draft", "draft"),
                    ("tac_accepted", "TAC accepted"),
                    ("submitted", "submitted"),
                    ("cancelled", "cancelled"),
                    ("withdrawn", "withdrawn"),
                    ("approved", "approved"),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcriterion",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalevaluation",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalinvitation",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalinvitation",
            name="status",
            field=portal.models.StatusField(
                choices=[
                    ("accepted", "accepted"),
                    ("autoreplied", "autoreplied"),
                    ("bounced", "bounced"),
                    ("draft", "draft"),
                    ("expired", "expired"),
                    ("read", "read"),
                    ("revoked", "revoked"),
                    ("sent", "sent"),
                    ("submitted", "submitted"),
                ],
                default="draft",
                max_length=100,
                no_check_for_status=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalmember",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalnomination",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisation",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalpanellist",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalprofile",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalreferee",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalreferee",
            name="survey_token",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="historicalresearchoffice",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalround",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="short description"),
        ),
        migrations.AlterField(
            model_name="historicalround",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="short description"),
        ),
        migrations.AlterField(
            model_name="historicalround",
            name="description_mi",
            field=models.TextField(blank=True, null=True, verbose_name="short description"),
        ),
        migrations.AlterField(
            model_name="historicalround",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalsocioeconomicobjective",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="historicaltestimonial",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="status",
            field=portal.models.StatusField(
                choices=[
                    ("accepted", "accepted"),
                    ("autoreplied", "autoreplied"),
                    ("bounced", "bounced"),
                    ("draft", "draft"),
                    ("expired", "expired"),
                    ("read", "read"),
                    ("revoked", "revoked"),
                    ("sent", "sent"),
                    ("submitted", "submitted"),
                ],
                default="draft",
                max_length=100,
                no_check_for_status=True,
            ),
        ),
        migrations.AlterField(
            model_name="referee",
            name="survey_token",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="requireddocument",
            name="document_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="required_documents",
                to="portal.documenttype",
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="short description"),
        ),
        migrations.AlterField(
            model_name="round",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="short description"),
        ),
        migrations.AlterField(
            model_name="round",
            name="description_mi",
            field=models.TextField(blank=True, null=True, verbose_name="short description"),
        ),
        migrations.CreateModel(
            name="HistoricalRecognition",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("updated_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "recognized_in",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="year of recognition"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=9,
                        null=True,
                        verbose_name="amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True, max_length=3, null=True, verbose_name="Currency code"
                    ),
                ),
                ("put_code", models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "award",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.award",
                        verbose_name="award",
                    ),
                ),
                (
                    "awarded_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.organisation",
                        verbose_name="awarded by",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical recognition",
                "verbose_name_plural": "historical recognitions",
                "db_table": "recognition_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalApplicationNumber",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("updated_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=24,
                        null=True,
                        verbose_name="number",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.application",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical application number",
                "verbose_name_plural": "historical application numbers",
                "db_table": "application_number_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAcademicRecord",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("updated_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "start_year",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1960),
                            django.core.validators.MaxValueValidator(2099),
                        ],
                        verbose_name="start year",
                    ),
                ),
                (
                    "conferred_on",
                    models.DateField(blank=True, null=True, verbose_name="conferred on"),
                ),
                (
                    "research_topic",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="research topic"
                    ),
                ),
                (
                    "put_code",
                    models.PositiveIntegerField(
                        blank=True, editable=False, null=True, verbose_name="put-code"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "awarded_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.organisation",
                        verbose_name="awarded by",
                    ),
                ),
                (
                    "discipline",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.fieldofstudy",
                        verbose_name="discipline",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.profile",
                    ),
                ),
                (
                    "qualification",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.qualification",
                        verbose_name="qualification",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical academic record",
                "verbose_name_plural": "historical academic records",
                "db_table": "academic_record_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
