# Generated by Django 4.2.4 on 2023-09-04 09:12

import common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import portal.models
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("portal", "0038_remove_academicrecord_converted_on_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="maillog",
            name="html_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="maillog",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="academicrecord",
            name="conferred_on",
            field=models.DateField(blank=True, null=True, verbose_name="conferred on"),
        ),
        migrations.AlterField(
            model_name="criterion",
            name="comment",
            field=models.BooleanField(
                default=True, help_text="The panellist should comment on their score"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcriterion",
            name="comment",
            field=models.BooleanField(
                default=True, help_text="The panellist should comment on their score"
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisation",
            name="code",
            field=models.CharField(blank=True, db_index=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="historicalreferee",
            name="email",
            field=common.models.EmailField(max_length=120, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="historicalreferee",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="historicalreferee",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="last name"
            ),
        ),
        migrations.AlterField(
            model_name="historicalreferee",
            name="status",
            field=portal.models.StateField(
                blank=True,
                choices=[
                    ("accepted", "accepted"),
                    ("bounced", "bounced"),
                    ("new", "new"),
                    ("opted_out", "opted out"),
                    ("sent", "sent"),
                    ("testified", "testified"),
                    (None, None),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                null=True,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="code",
            field=models.CharField(blank=True, default="", max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="profilepersonidentifier",
            name="value",
            field=models.CharField(
                max_length=100, verbose_name="Identifier or reference (e.g. reference/ID number)"
            ),
        ),
        migrations.AlterField(
            model_name="referee",
            name="email",
            field=common.models.EmailField(max_length=120, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="referee",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="referee",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="last name"
            ),
        ),
        migrations.AlterField(
            model_name="referee",
            name="status",
            field=portal.models.StateField(
                blank=True,
                choices=[
                    ("accepted", "accepted"),
                    ("bounced", "bounced"),
                    ("new", "new"),
                    ("opted_out", "opted out"),
                    ("sent", "sent"),
                    ("testified", "testified"),
                    (None, None),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                null=True,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="requireddocument",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Title (e.g. Dr, Professor",
                max_length=200,
                null=True,
                verbose_name="Title",
            ),
        ),
        migrations.AlterField(
            model_name="requireddocument",
            name="title_en",
            field=models.CharField(
                blank=True,
                help_text="Title (e.g. Dr, Professor",
                max_length=200,
                null=True,
                verbose_name="Title",
            ),
        ),
        migrations.AlterField(
            model_name="requireddocument",
            name="title_mi",
            field=models.CharField(
                blank=True,
                help_text="Title (e.g. Dr, Professor",
                max_length=200,
                null=True,
                verbose_name="Title",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalEmailAddress",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True, max_length=254, verbose_name="e-mail address"
                    ),
                ),
                ("verified", models.BooleanField(default=False, verbose_name="verified")),
                ("primary", models.BooleanField(default=False, verbose_name="primary")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical email address",
                "verbose_name_plural": "historical email addresses",
                "db_table": "email_address_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
