# Generated by Django 4.2.4 on 2023-09-20 01:15

import common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import portal.models
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "__first__"),
        ("sites", "0004_auto_20210331_1418"),
        ("portal", "0039_maillog_html_message_maillog_message_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalinvitation",
            old_name="status",
            new_name="state",
        ),
        migrations.RenameField(
            model_name="historicalinvitation",
            old_name="status_changed_at",
            new_name="state_changed_at",
        ),
        migrations.RenameField(
            model_name="historicalmember",
            old_name="status",
            new_name="state",
        ),
        migrations.RenameField(
            model_name="historicalmember",
            old_name="status_changed_at",
            new_name="state_changed_at",
        ),
        migrations.RenameField(
            model_name="historicalnomination",
            old_name="status",
            new_name="state",
        ),
        migrations.RenameField(
            model_name="historicalpanellist",
            old_name="status",
            new_name="state",
        ),
        migrations.RenameField(
            model_name="historicalpanellist",
            old_name="status_changed_at",
            new_name="state_changed_at",
        ),
        migrations.RenameField(
            model_name="historicalreferee",
            old_name="status",
            new_name="state",
        ),
        migrations.RenameField(
            model_name="historicalreferee",
            old_name="status_changed_at",
            new_name="state_changed_at",
        ),
        migrations.RenameField(
            model_name="invitation",
            old_name="status",
            new_name="state",
        ),
        migrations.RenameField(
            model_name="invitation",
            old_name="status_changed_at",
            new_name="state_changed_at",
        ),
        migrations.RenameField(
            model_name="member",
            old_name="status",
            new_name="state",
        ),
        migrations.RenameField(
            model_name="member",
            old_name="status_changed_at",
            new_name="state_changed_at",
        ),
        migrations.RenameField(
            model_name="nomination",
            old_name="status",
            new_name="state",
        ),
        migrations.RenameField(
            model_name="panellist",
            old_name="status",
            new_name="state",
        ),
        migrations.RenameField(
            model_name="panellist",
            old_name="status_changed_at",
            new_name="state_changed_at",
        ),
        migrations.RenameField(
            model_name="referee",
            old_name="status",
            new_name="state",
        ),
        migrations.RenameField(
            model_name="referee",
            old_name="status_changed_at",
            new_name="state_changed_at",
        ),
        migrations.AddField(
            model_name="historicalpanellist",
            name="elected_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalpanellist",
            name="expires_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalpanellist",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="is active"),
        ),
        migrations.AddField(
            model_name="historicalpanellist",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CHAIR", "Chair"),
                    ("COCONVENOR", "Co-convenor"),
                    ("COMMITTEE", "Committee"),
                    ("CONVENOR", "Convenor"),
                    ("PANELLIST", "Panellist"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="panellist",
            name="elected_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="panellist",
            name="expires_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="panellist",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="is active"),
        ),
        migrations.AddField(
            model_name="panellist",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CHAIR", "Chair"),
                    ("COCONVENOR", "Co-convenor"),
                    ("COMMITTEE", "Committee"),
                    ("CONVENOR", "Convenor"),
                    ("PANELLIST", "Panellist"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="curriculumvitae",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="A title or name you can assign to the upload CV file",
                max_length=200,
                null=True,
                verbose_name="Title or name",
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvitation",
            name="accepted_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"accepted"}
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvitation",
            name="bounced_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"bounced"}
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvitation",
            name="expired_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"expired"}
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvitation",
            name="read_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"read"}
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvitation",
            name="sent_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"sent"}
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvitation",
            name="submitted_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"submitted"}
            ),
        ),
        migrations.AlterField(
            model_name="historicalmember",
            name="authorized_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"authorized"}
            ),
        ),
        migrations.AlterField(
            model_name="historicalreferee",
            name="testified_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"testified"}
            ),
        ),
        migrations.AlterField(
            model_name="historicaltestimonial",
            name="state",
            field=portal.models.StateField(
                choices=[
                    (None, None),
                    ("new", "new"),
                    ("draft", "draft"),
                    ("submitted", "submitted"),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="accepted_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"accepted"}
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="bounced_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"bounced"}
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="expired_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"expired"}
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="read_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"read"}
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="sent_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"sent"}
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="submitted_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"submitted"}
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="authorized_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"authorized"}
            ),
        ),
        migrations.AlterField(
            model_name="referee",
            name="testified_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"testified"}
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="state",
            field=portal.models.StateField(
                choices=[
                    (None, None),
                    ("new", "new"),
                    ("draft", "draft"),
                    ("submitted", "submitted"),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                verbose_name="state",
            ),
        ),
        migrations.CreateModel(
            name="Panel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "state",
                    portal.models.StateField(
                        choices=[
                            ("new", "new"),
                            ("draft", "draft"),
                            ("preliminary", "preliminary"),
                            ("active", "active"),
                            ("archived", "archived"),
                        ],
                        default="new",
                        max_length=100,
                        no_check_for_status=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=3, null=True, verbose_name="code"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="description"
                    ),
                ),
                (
                    "fund",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portal.fund",
                    ),
                ),
            ],
            options={
                "db_table": "panel",
            },
            bases=(portal.models.PanelMixin, common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPanel",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("updated_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "state",
                    portal.models.StateField(
                        choices=[
                            ("new", "new"),
                            ("draft", "draft"),
                            ("preliminary", "preliminary"),
                            ("active", "active"),
                            ("archived", "archived"),
                        ],
                        default="new",
                        max_length=100,
                        no_check_for_status=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=3, null=True, verbose_name="code"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="description"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "fund",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.fund",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical panel",
                "verbose_name_plural": "historical panels",
                "db_table": "panel_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(
                simple_history.models.HistoricalChanges,
                portal.models.PanelMixin,
                common.models.HelperMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="HistoricalFund",
            fields=[
                ("created_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("updated_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "code",
                    common.models.FixedCharField(db_column="code", db_index=True, max_length=2),
                ),
                ("code3", common.models.FixedCharField(blank=True, max_length=3, null=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=10000, null=True, verbose_name="description"
                    ),
                ),
                (
                    "cost_centre",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Cost Center"
                    ),
                ),
                (
                    "catalyst_cost_centre",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Catalyst Cost Center"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        default=common.models.Model.get_current_site_id,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical fund",
                "verbose_name_plural": "historical funds",
                "db_table": "fund_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name="historicalpanellist",
            name="panel",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="portal.panel",
            ),
        ),
        migrations.AddField(
            model_name="panellist",
            name="panel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="panellists",
                to="portal.panel",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="state",
            field=portal.models.StateField(
                choices=[
                    (None, None),
                    ("new", "new"),
                    ("draft", "draft"),
                    ("tac_accepted", "TAC accepted"),
                    ("submitted", "submitted"),
                    ("cancelled", "cancelled"),
                    ("withdrawn", "withdrawn"),
                    ("approved", "approved"),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="state",
            field=portal.models.StateField(
                blank=True,
                choices=[
                    (None, None),
                    ("new", "new"),
                    ("draft", "draft"),
                    ("submitted", "submitted"),
                    ("accepted", "accepted"),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalapplication",
            name="state",
            field=portal.models.StateField(
                choices=[
                    (None, None),
                    ("new", "new"),
                    ("draft", "draft"),
                    ("tac_accepted", "TAC accepted"),
                    ("submitted", "submitted"),
                    ("cancelled", "cancelled"),
                    ("withdrawn", "withdrawn"),
                    ("approved", "approved"),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="historicalevaluation",
            name="state",
            field=portal.models.StateField(
                blank=True,
                choices=[
                    (None, None),
                    ("new", "new"),
                    ("draft", "draft"),
                    ("submitted", "submitted"),
                    ("accepted", "accepted"),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvitation",
            name="state",
            field=portal.models.StateField(
                choices=[
                    ("accepted", "accepted"),
                    ("autoreplied", "autoreplied"),
                    ("bounced", "bounced"),
                    ("draft", "draft"),
                    ("expired", "expired"),
                    ("read", "read"),
                    ("revoked", "revoked"),
                    ("sent", "sent"),
                    ("submitted", "submitted"),
                ],
                default="draft",
                max_length=100,
                no_check_for_status=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvitation",
            name="state_changed_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalmember",
            name="state",
            field=portal.models.StateField(
                blank=True,
                choices=[
                    ("accepted", "accepted"),
                    ("authorized", "authorized"),
                    ("bounced", "bounced"),
                    ("new", "new"),
                    ("opted_out", "opted out"),
                    ("sent", "sent"),
                    (None, None),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalmember",
            name="state_changed_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalnomination",
            name="state",
            field=portal.models.StateField(
                blank=True,
                choices=[
                    ("accepted", "accepted"),
                    ("bounced", "bounced"),
                    ("draft", "draft"),
                    ("new", "new"),
                    ("sent", "sent"),
                    ("submitted", "submitted"),
                    (None, None),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                null=True,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpanellist",
            name="state",
            field=portal.models.StateField(
                blank=True,
                choices=[
                    (None, None),
                    ("new", "new"),
                    ("sent", "sent"),
                    ("accepted", "accepted"),
                    ("bounced", "bounced"),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalpanellist",
            name="state_changed_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalreferee",
            name="state",
            field=portal.models.StateField(
                blank=True,
                choices=[
                    ("accepted", "accepted"),
                    ("bounced", "bounced"),
                    ("new", "new"),
                    ("opted_out", "opted out"),
                    ("sent", "sent"),
                    ("testified", "testified"),
                    (None, None),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                null=True,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreferee",
            name="state_changed_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="state",
            field=portal.models.StateField(
                choices=[
                    ("accepted", "accepted"),
                    ("autoreplied", "autoreplied"),
                    ("bounced", "bounced"),
                    ("draft", "draft"),
                    ("expired", "expired"),
                    ("read", "read"),
                    ("revoked", "revoked"),
                    ("sent", "sent"),
                    ("submitted", "submitted"),
                ],
                default="draft",
                max_length=100,
                no_check_for_status=True,
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="state_changed_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="state",
            field=portal.models.StateField(
                blank=True,
                choices=[
                    ("accepted", "accepted"),
                    ("authorized", "authorized"),
                    ("bounced", "bounced"),
                    ("new", "new"),
                    ("opted_out", "opted out"),
                    ("sent", "sent"),
                    (None, None),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="state_changed_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True
            ),
        ),
        migrations.AlterField(
            model_name="panellist",
            name="state",
            field=portal.models.StateField(
                blank=True,
                choices=[
                    (None, None),
                    ("new", "new"),
                    ("sent", "sent"),
                    ("accepted", "accepted"),
                    ("bounced", "bounced"),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="panellist",
            name="state_changed_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True
            ),
        ),
        migrations.AlterField(
            model_name="referee",
            name="state",
            field=portal.models.StateField(
                blank=True,
                choices=[
                    ("accepted", "accepted"),
                    ("bounced", "bounced"),
                    ("new", "new"),
                    ("opted_out", "opted out"),
                    ("sent", "sent"),
                    ("testified", "testified"),
                    (None, None),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                null=True,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="referee",
            name="state_changed_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True
            ),
        ),
    ]
