# Generated by Django 4.2.4 on 2023-10-03 03:09

import common.models
from django.conf import settings
import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import portal.models
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0004_auto_20210331_1418"),
        ("users", "__first__"),
        ("portal", "0039_maillog_html_message_maillog_message_and_more"),
        ("users", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("number", models.CharField(max_length=40, unique=True, verbose_name="number")),
                (
                    "refcode",
                    models.CharField(
                        blank=True, help_text="IE-Contracts REFCODE", max_length=40, null=True
                    ),
                ),
                ("year", models.CharField(blank=True, max_length=4, null=True)),
                (
                    "project_title",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="project title"
                    ),
                ),
                (
                    "state",
                    portal.models.StateField(
                        choices=[
                            (None, None),
                            ("ASD", "Awaiting start date"),
                            ("COM", "Completed"),
                            ("CUR", "Current "),
                            ("DCL", "Declined"),
                            ("SUS", "Suspended"),
                            ("TER", "Terminated"),
                            ("TRN", "Transferred"),
                            ("WTH", "Withdrawn"),
                            ("accepted", "accepted"),
                            ("approved", "approved"),
                            ("archived", "archived"),
                            ("cancelled", "cancelled"),
                            ("draft", "draft"),
                            ("new", "new"),
                            ("preliminary", "preliminary"),
                            ("submitted", "submitted"),
                        ],
                        default="new",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="state",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("duration", models.PositiveIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("abstract", models.TextField(blank=True, null=True)),
                ("completed_on", models.DateField(blank=True, null=True)),
                ("url", models.CharField(blank=True, max_length=120, null=True)),
                ("fin_received", models.BooleanField(blank=True, null=True)),
                ("fin_supp", models.BooleanField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.application",
                    ),
                ),
            ],
            options={
                "db_table": "contract",
            },
            bases=(
                portal.models.ContractMixin,
                common.models.PersonMixin,
                portal.models.PdfFileMixin,
                common.models.HelperMixin,
                models.Model,
            ),
            managers=[
                ("objects", django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.CreateModel(
            name="Rcc",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("rcc", models.CharField(max_length=8)),
                ("description", models.CharField(blank=True, max_length=80, null=True)),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                ("code", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "RCC",
                "verbose_name_plural": "RCCs",
                "db_table": "rcc",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.RenameField(
            model_name="historicalinvitation",
            old_name="status",
            new_name="state",
        ),
        migrations.RenameField(
            model_name="historicalinvitation",
            old_name="status_changed_at",
            new_name="state_changed_at",
        ),
        migrations.RenameField(
            model_name="historicalmember",
            old_name="status",
            new_name="state",
        ),
        migrations.RenameField(
            model_name="historicalmember",
            old_name="status_changed_at",
            new_name="state_changed_at",
        ),
        migrations.RenameField(
            model_name="historicalnomination",
            old_name="status",
            new_name="state",
        ),
        migrations.RenameField(
            model_name="historicalpanellist",
            old_name="status",
            new_name="state",
        ),
        migrations.RenameField(
            model_name="historicalpanellist",
            old_name="status_changed_at",
            new_name="state_changed_at",
        ),
        migrations.RenameField(
            model_name="historicalreferee",
            old_name="status",
            new_name="state",
        ),
        migrations.RenameField(
            model_name="historicalreferee",
            old_name="status_changed_at",
            new_name="state_changed_at",
        ),
        migrations.RenameField(
            model_name="invitation",
            old_name="status",
            new_name="state",
        ),
        migrations.RenameField(
            model_name="invitation",
            old_name="status_changed_at",
            new_name="state_changed_at",
        ),
        migrations.RenameField(
            model_name="member",
            old_name="status",
            new_name="state",
        ),
        migrations.RenameField(
            model_name="member",
            old_name="status_changed_at",
            new_name="state_changed_at",
        ),
        migrations.RenameField(
            model_name="nomination",
            old_name="status",
            new_name="state",
        ),
        migrations.RenameField(
            model_name="panellist",
            old_name="status",
            new_name="state",
        ),
        migrations.RenameField(
            model_name="panellist",
            old_name="status_changed_at",
            new_name="state_changed_at",
        ),
        migrations.RenameField(
            model_name="referee",
            old_name="status",
            new_name="state",
        ),
        migrations.RenameField(
            model_name="referee",
            old_name="status_changed_at",
            new_name="state_changed_at",
        ),
        migrations.AddField(
            model_name="historicalpanellist",
            name="elected_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalpanellist",
            name="expires_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalpanellist",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="is active"),
        ),
        migrations.AddField(
            model_name="historicalpanellist",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CHAIR", "Chair"),
                    ("COCONVENOR", "Co-convenor"),
                    ("COMMITTEE", "Committee"),
                    ("CONVENOR", "Convenor"),
                    ("PANELLIST", "Panellist"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalround",
            name="duration",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Default contract duration",
                null=True,
                verbose_name="Duration",
            ),
        ),
        migrations.AddField(
            model_name="panellist",
            name="elected_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="panellist",
            name="expires_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="panellist",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="is active"),
        ),
        migrations.AddField(
            model_name="panellist",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CHAIR", "Chair"),
                    ("COCONVENOR", "Co-convenor"),
                    ("COMMITTEE", "Committee"),
                    ("CONVENOR", "Convenor"),
                    ("PANELLIST", "Panellist"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="duration",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Default contract duration",
                null=True,
                verbose_name="Duration",
            ),
        ),
        migrations.AlterField(
            model_name="curriculumvitae",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="A title or name you can assign to the upload CV file",
                max_length=200,
                null=True,
                verbose_name="Title or name",
            ),
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="state",
            field=portal.models.StateField(
                blank=True,
                choices=[
                    (None, None),
                    ("new", "new"),
                    ("draft", "draft"),
                    ("submitted", "submitted"),
                    ("accepted", "accepted"),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalapplication",
            name="state",
            field=portal.models.StateField(
                choices=[
                    (None, None),
                    ("new", "new"),
                    ("draft", "draft"),
                    ("tac_accepted", "TAC accepted"),
                    ("submitted", "submitted"),
                    ("cancelled", "cancelled"),
                    ("withdrawn", "withdrawn"),
                    ("approved", "approved"),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="historicalevaluation",
            name="state",
            field=portal.models.StateField(
                blank=True,
                choices=[
                    (None, None),
                    ("new", "new"),
                    ("draft", "draft"),
                    ("submitted", "submitted"),
                    ("accepted", "accepted"),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvitation",
            name="accepted_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"accepted"}
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvitation",
            name="bounced_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"bounced"}
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvitation",
            name="expired_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"expired"}
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvitation",
            name="read_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"read"}
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvitation",
            name="sent_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"sent"}
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvitation",
            name="submitted_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"submitted"}
            ),
        ),
        migrations.AlterField(
            model_name="historicalmember",
            name="authorized_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"authorized"}
            ),
        ),
        migrations.AlterField(
            model_name="historicalreferee",
            name="testified_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"testified"}
            ),
        ),
        migrations.AlterField(
            model_name="historicalround",
            name="required_referees",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)],
                default=0,
                help_text="Minimum of referees the application needs to nominate",
                null=True,
                verbose_name="Required number of referees",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltestimonial",
            name="state",
            field=portal.models.StateField(
                choices=[
                    (None, None),
                    ("new", "new"),
                    ("draft", "draft"),
                    ("submitted", "submitted"),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="accepted_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"accepted"}
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="bounced_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"bounced"}
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="expired_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"expired"}
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="read_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"read"}
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="sent_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"sent"}
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="submitted_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"submitted"}
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="authorized_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"authorized"}
            ),
        ),
        migrations.AlterField(
            model_name="referee",
            name="testified_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"testified"}
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="required_referees",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)],
                default=0,
                help_text="Minimum of referees the application needs to nominate",
                null=True,
                verbose_name="Required number of referees",
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="state",
            field=portal.models.StateField(
                choices=[
                    (None, None),
                    ("new", "new"),
                    ("draft", "draft"),
                    ("submitted", "submitted"),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                verbose_name="state",
            ),
        ),
        migrations.CreateModel(
            name="Panel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "state",
                    portal.models.StateField(
                        choices=[
                            ("new", "new"),
                            ("draft", "draft"),
                            ("preliminary", "preliminary"),
                            ("active", "active"),
                            ("archived", "archived"),
                        ],
                        default="new",
                        max_length=100,
                        no_check_for_status=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=3, null=True, verbose_name="code"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="description"
                    ),
                ),
                (
                    "fund",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portal.fund",
                    ),
                ),
            ],
            options={
                "db_table": "panel",
            },
            bases=(portal.models.PanelMixin, common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPanel",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("updated_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "state",
                    portal.models.StateField(
                        choices=[
                            ("new", "new"),
                            ("draft", "draft"),
                            ("preliminary", "preliminary"),
                            ("active", "active"),
                            ("archived", "archived"),
                        ],
                        default="new",
                        max_length=100,
                        no_check_for_status=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=3, null=True, verbose_name="code"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="description"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "fund",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.fund",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical panel",
                "verbose_name_plural": "historical panels",
                "db_table": "panel_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(
                simple_history.models.HistoricalChanges,
                portal.models.PanelMixin,
                common.models.HelperMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="HistoricalMemberEffort",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("updated_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("period", models.PositiveSmallIntegerField()),
                (
                    "fte",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Full-Time Equivalent",
                        max_digits=3,
                        verbose_name="FTE",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical member effort",
                "verbose_name_plural": "historical member efforts",
                "db_table": "member_effort_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalFund",
            fields=[
                ("created_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("updated_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "code",
                    common.models.FixedCharField(db_column="code", db_index=True, max_length=2),
                ),
                ("code3", common.models.FixedCharField(blank=True, max_length=3, null=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=10000, null=True, verbose_name="description"
                    ),
                ),
                (
                    "cost_centre",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Cost Center"
                    ),
                ),
                (
                    "catalyst_cost_centre",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Catalyst Cost Center"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        default=common.models.Model.get_current_site_id,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical fund",
                "verbose_name_plural": "historical funds",
                "db_table": "fund_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ContractSeo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("share", models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                (
                    "code",
                    models.ForeignKey(
                        db_column="code",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.socioeconomicobjective",
                        verbose_name="SEO",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_seos",
                        to="portal.contract",
                    ),
                ),
            ],
            options={
                "verbose_name": "contract SEO",
                "verbose_name_plural": "contract SEOs",
                "db_table": "contract_seo",
                "unique_together": {("contract", "code")},
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ContractKeyword",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.contract"
                    ),
                ),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.keyword"
                    ),
                ),
            ],
            options={
                "db_table": "contract_keyword",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ContractFor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("share", models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                (
                    "code",
                    models.ForeignKey(
                        db_column="code",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.fieldofresearch",
                        verbose_name="FoR",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_fors",
                        to="portal.contract",
                    ),
                ),
            ],
            options={
                "verbose_name": "contract FOR",
                "verbose_name_plural": "contract FoRs",
                "db_table": "contract_for",
                "unique_together": {("contract", "code")},
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.AddField(
            model_name="contract",
            name="fors",
            field=models.ManyToManyField(
                blank=True,
                related_name="contracts",
                through="portal.ContractFor",
                to="portal.fieldofresearch",
                verbose_name="FoRs",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="fund",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="portal.fund",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="keywords",
            field=models.ManyToManyField(
                blank=True,
                related_name="contracts",
                through="portal.ContractKeyword",
                to="portal.keyword",
                verbose_name="Keywords",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="org",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="portal.organisation",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="panel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portal.panel",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="panels",
            field=models.ManyToManyField(
                blank=True, db_table="contract_panel", related_name="contracts", to="portal.panel"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="rccs",
            field=models.ManyToManyField(
                blank=True, db_table="contract_rcc", related_name="contracts", to="portal.rcc"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="seos",
            field=models.ManyToManyField(
                blank=True,
                related_name="contracts",
                through="portal.ContractSeo",
                to="portal.socioeconomicobjective",
                verbose_name="SEOs",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="site",
            field=models.ForeignKey(
                default=common.models.Model.get_current_site_id,
                on_delete=django.db.models.deletion.PROTECT,
                to="sites.site",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="submitted by",
            ),
        ),
        migrations.AddField(
            model_name="historicalpanellist",
            name="panel",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="portal.panel",
            ),
        ),
        migrations.AddField(
            model_name="panellist",
            name="panel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="panellists",
                to="portal.panel",
            ),
        ),
        migrations.CreateModel(
            name="MemberEffort",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("period", models.PositiveSmallIntegerField()),
                (
                    "fte",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Full-Time Equivalent",
                        max_digits=3,
                        verbose_name="FTE",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="efforts",
                        to="portal.member",
                    ),
                ),
            ],
            options={
                "db_table": "member_effort",
                "unique_together": {("member", "period")},
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.AlterField(
            model_name="application",
            name="state",
            field=portal.models.StateField(
                choices=[
                    (None, None),
                    ("new", "new"),
                    ("draft", "draft"),
                    ("tac_accepted", "TAC accepted"),
                    ("submitted", "submitted"),
                    ("cancelled", "cancelled"),
                    ("withdrawn", "withdrawn"),
                    ("approved", "approved"),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvitation",
            name="state",
            field=portal.models.StateField(
                choices=[
                    ("accepted", "accepted"),
                    ("autoreplied", "autoreplied"),
                    ("bounced", "bounced"),
                    ("draft", "draft"),
                    ("expired", "expired"),
                    ("read", "read"),
                    ("revoked", "revoked"),
                    ("sent", "sent"),
                    ("submitted", "submitted"),
                ],
                default="draft",
                max_length=100,
                no_check_for_status=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvitation",
            name="state_changed_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalmember",
            name="state",
            field=portal.models.StateField(
                blank=True,
                choices=[
                    ("accepted", "accepted"),
                    ("authorized", "authorized"),
                    ("bounced", "bounced"),
                    ("new", "new"),
                    ("opted_out", "opted out"),
                    ("sent", "sent"),
                    (None, None),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalmember",
            name="state_changed_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalnomination",
            name="state",
            field=portal.models.StateField(
                blank=True,
                choices=[
                    ("accepted", "accepted"),
                    ("bounced", "bounced"),
                    ("draft", "draft"),
                    ("new", "new"),
                    ("sent", "sent"),
                    ("submitted", "submitted"),
                    (None, None),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                null=True,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpanellist",
            name="state",
            field=portal.models.StateField(
                blank=True,
                choices=[
                    (None, None),
                    ("new", "new"),
                    ("sent", "sent"),
                    ("accepted", "accepted"),
                    ("bounced", "bounced"),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalpanellist",
            name="state_changed_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalreferee",
            name="state",
            field=portal.models.StateField(
                blank=True,
                choices=[
                    ("accepted", "accepted"),
                    ("bounced", "bounced"),
                    ("new", "new"),
                    ("opted_out", "opted out"),
                    ("sent", "sent"),
                    ("testified", "testified"),
                    (None, None),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                null=True,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreferee",
            name="state_changed_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="state",
            field=portal.models.StateField(
                choices=[
                    ("accepted", "accepted"),
                    ("autoreplied", "autoreplied"),
                    ("bounced", "bounced"),
                    ("draft", "draft"),
                    ("expired", "expired"),
                    ("read", "read"),
                    ("revoked", "revoked"),
                    ("sent", "sent"),
                    ("submitted", "submitted"),
                ],
                default="draft",
                max_length=100,
                no_check_for_status=True,
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="state_changed_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="state",
            field=portal.models.StateField(
                blank=True,
                choices=[
                    ("accepted", "accepted"),
                    ("authorized", "authorized"),
                    ("bounced", "bounced"),
                    ("new", "new"),
                    ("opted_out", "opted out"),
                    ("sent", "sent"),
                    (None, None),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="state_changed_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True
            ),
        ),
        migrations.AlterField(
            model_name="nomination",
            name="state",
            field=portal.models.StateField(
                blank=True,
                choices=[
                    ("accepted", "accepted"),
                    ("bounced", "bounced"),
                    ("draft", "draft"),
                    ("new", "new"),
                    ("sent", "sent"),
                    ("submitted", "submitted"),
                    (None, None),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                null=True,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="panellist",
            name="state",
            field=portal.models.StateField(
                blank=True,
                choices=[
                    (None, None),
                    ("new", "new"),
                    ("sent", "sent"),
                    ("accepted", "accepted"),
                    ("bounced", "bounced"),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="panellist",
            name="state_changed_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True
            ),
        ),
        migrations.AlterField(
            model_name="referee",
            name="state",
            field=portal.models.StateField(
                blank=True,
                choices=[
                    ("accepted", "accepted"),
                    ("bounced", "bounced"),
                    ("new", "new"),
                    ("opted_out", "opted out"),
                    ("sent", "sent"),
                    ("testified", "testified"),
                    (None, None),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                null=True,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="referee",
            name="state_changed_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="state",
            field=portal.models.StateField(
                choices=[
                    (None, None),
                    ("ASD", "Awaiting start date"),
                    ("COM", "Completed"),
                    ("CUR", "Current "),
                    ("DCL", "Declined"),
                    ("SUS", "Suspended"),
                    ("TER", "Terminated"),
                    ("TRN", "Transferred"),
                    ("WTH", "Withdrawn"),
                    ("accepted", "accepted"),
                    ("approved", "approved"),
                    ("archived", "archived"),
                    ("cancelled", "cancelled"),
                    ("draft", "WIP"),
                    ("new", "new"),
                    ("preliminary", "preliminary"),
                    ("submitted", "submitted"),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                verbose_name="state",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalContract",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("updated_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("number", models.CharField(db_index=True, max_length=40, verbose_name="number")),
                (
                    "refcode",
                    models.CharField(
                        blank=True, help_text="IE-Contracts REFCODE", max_length=40, null=True
                    ),
                ),
                ("year", models.CharField(blank=True, max_length=4, null=True)),
                (
                    "project_title",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="project title"
                    ),
                ),
                (
                    "state",
                    portal.models.StateField(
                        choices=[
                            (None, None),
                            ("ASD", "Awaiting start date"),
                            ("COM", "Completed"),
                            ("CUR", "Current "),
                            ("DCL", "Declined"),
                            ("SUS", "Suspended"),
                            ("TER", "Terminated"),
                            ("TRN", "Transferred"),
                            ("WTH", "Withdrawn"),
                            ("accepted", "accepted"),
                            ("approved", "approved"),
                            ("archived", "archived"),
                            ("cancelled", "cancelled"),
                            ("draft", "WIP"),
                            ("new", "new"),
                            ("preliminary", "preliminary"),
                            ("submitted", "submitted"),
                        ],
                        default="new",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="state",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("duration", models.PositiveIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("abstract", models.TextField(blank=True, null=True)),
                ("completed_on", models.DateField(blank=True, null=True)),
                ("url", models.CharField(blank=True, max_length=120, null=True)),
                ("fin_received", models.BooleanField(blank=True, null=True)),
                ("fin_supp", models.BooleanField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.application",
                    ),
                ),
                (
                    "fund",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.fund",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.organisation",
                    ),
                ),
                (
                    "panel",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.panel",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        default=common.models.Model.get_current_site_id,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="sites.site",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="submitted by",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical contract",
                "verbose_name_plural": "historical contracts",
                "db_table": "contract_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(
                simple_history.models.HistoricalChanges,
                portal.models.ContractMixin,
                common.models.PersonMixin,
                portal.models.PdfFileMixin,
                common.models.HelperMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="HistoricalAllocation",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("updated_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("period", models.PositiveSmallIntegerField(verbose_name="period")),
                (
                    "allocation",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="allocation"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.contract",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical allocation",
                "verbose_name_plural": "historical allocations",
                "db_table": "allocation_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Allocation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("period", models.PositiveSmallIntegerField(verbose_name="period")),
                (
                    "allocation",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="allocation"
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.contract"
                    ),
                ),
            ],
            options={
                "db_table": "allocation",
                "unique_together": {("contract", "period")},
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalReportingScheduleEntry",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("updated_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("period", models.PositiveSmallIntegerField(verbose_name="period")),
                (
                    "type",
                    common.models.FixedCharField(
                        choices=[
                            ("A", "Annual"),
                            ("E", "Exchange"),
                            ("F", "Final"),
                            ("I", "Interim"),
                            ("L", "Follow up"),
                        ],
                        help_text="Reporting Type",
                        max_length=1,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "request_info_date",
                    models.DateField(
                        blank=True,
                        help_text="Date that RO/applicants is first emailed for more information",
                        null=True,
                    ),
                ),
                ("date_first_remind", models.DateField(blank=True, null=True)),
                (
                    "state",
                    portal.models.StateField(
                        choices=[
                            ("accepted", "accepted"),
                            ("acknowledged", "acknowledged"),
                            ("approved", "approved"),
                            ("archived", "archived"),
                            ("cancelled", "cancelled"),
                            ("draft", "draft"),
                            ("new", "new"),
                            ("submitted", "submitted"),
                        ],
                        default="new",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="state",
                    ),
                ),
                (
                    "acknowledged_at",
                    model_utils.fields.MonitorField(
                        blank=True, default=None, monitor="state", null=True, when={"acknowledged"}
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.contract",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical reporting schedule entry",
                "verbose_name_plural": "historical reporting schedule entrys",
                "db_table": "reporting_schedule_entry_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(
                simple_history.models.HistoricalChanges,
                portal.models.ReportingScheduleEntryMixin,
                common.models.HelperMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="ReportingScheduleEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("period", models.PositiveSmallIntegerField(verbose_name="period")),
                (
                    "type",
                    common.models.FixedCharField(
                        choices=[
                            ("A", "Annual"),
                            ("E", "Exchange"),
                            ("F", "Final"),
                            ("I", "Interim"),
                            ("L", "Follow up"),
                        ],
                        help_text="Reporting Type",
                        max_length=1,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "request_info_date",
                    models.DateField(
                        blank=True,
                        help_text="Date that RO/applicants is first emailed for more information",
                        null=True,
                    ),
                ),
                ("date_first_remind", models.DateField(blank=True, null=True)),
                (
                    "state",
                    portal.models.StateField(
                        choices=[
                            ("accepted", "accepted"),
                            ("acknowledged", "acknowledged"),
                            ("approved", "approved"),
                            ("archived", "archived"),
                            ("cancelled", "cancelled"),
                            ("draft", "draft"),
                            ("new", "new"),
                            ("submitted", "submitted"),
                        ],
                        default="new",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="state",
                    ),
                ),
                (
                    "acknowledged_at",
                    model_utils.fields.MonitorField(
                        blank=True, default=None, monitor="state", null=True, when={"acknowledged"}
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reporting_schedule",
                        to="portal.contract",
                    ),
                ),
            ],
            options={
                "db_table": "reporting_schedule_entry",
                "unique_together": {("contract", "period", "type", "due_date")},
            },
            bases=(
                portal.models.ReportingScheduleEntryMixin,
                common.models.HelperMixin,
                models.Model,
            ),
        ),
    ]
