# Generated by Django 4.2.6 on 2023-10-11 00:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0040_contract_contractmember_rcc_roletype_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contractmember",
            unique_together={("contract", "email", "role")},
        ),
    ]
