# Generated by Django 5.0.2 on 2024-02-29 02:57

import common.models
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0040_protectionpatternperson_allocation_contract_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalorganisation",
            name="city",
        ),
        migrations.RemoveField(
            model_name="historicalorganisation",
            name="country",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="city",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="country",
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("address", models.TextField(verbose_name="address")),
                (
                    "postcode",
                    models.CharField(
                        blank=True, max_length=12, null=True, verbose_name="postcode"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=42, null=True, verbose_name="city"),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        db_column="country",
                        default="NZ",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="addresses",
                        to="portal.country",
                        verbose_name="country",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "addresses",
                "db_table": "address",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.AddField(
            model_name="application",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications",
                to="portal.address",
            ),
        ),
        migrations.AddField(
            model_name="historicalapplication",
            name="address",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="portal.address",
            ),
        ),
        migrations.AddField(
            model_name="historicalperson",
            name="address",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="portal.address",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="people",
                to="portal.address",
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisation",
            name="address",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="portal.address",
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organisations",
                to="portal.address",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalAddress",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("updated_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("address", models.TextField(verbose_name="address")),
                (
                    "postcode",
                    models.CharField(
                        blank=True, max_length=12, null=True, verbose_name="postcode"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=42, null=True, verbose_name="city"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        db_column="country",
                        db_constraint=False,
                        default="NZ",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.country",
                        verbose_name="country",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical address",
                "verbose_name_plural": "historical addresses",
                "db_table": "address_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
