# Generated by Django 4.2.6 on 2023-10-26 03:10

import common.models
from django.db import migrations, models
import django.db.models.deletion
import portal.migration_utils
import portal.models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0040_contract_contractmember_rcc_roletype_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EducationLevel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "code",
                    models.PositiveSmallIntegerField(
                        primary_key=True, serialize=False, verbose_name="code"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("name_en", models.CharField(max_length=100, null=True, verbose_name="Name")),
                ("name_mi", models.CharField(max_length=100, null=True, verbose_name="Name")),
            ],
            options={
                "db_table": "education_level",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.AlterModelManagers(
            name="application",
            managers=[
                ("objects", portal.models.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="convertedfile",
            managers=[
                ("objects", portal.models.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="invitation",
            managers=[
                ("objects", portal.models.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="maillog",
            managers=[
                ("objects", portal.models.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="nomination",
            managers=[
                ("objects", portal.models.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="panellist",
            managers=[
                ("objects", portal.models.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="round",
            managers=[
                ("objects", portal.models.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="scheme",
            managers=[
                ("objects", portal.models.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="subscription",
            managers=[
                ("objects", portal.models.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="testimonial",
            managers=[
                ("objects", portal.models.CurrentSiteManager()),
            ],
        ),
        migrations.AlterField(
            model_name="contract",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="portal.application",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contractmember",
            unique_together={("contract", "email", "role")},
        ),
        migrations.RunPython(
            code=portal.migration_utils.add_education_level_data,
            reverse_code=portal.migration_utils.dummy,
        ),
    ]
