# Generated by Django 4.2.7 on 2023-11-09 00:11

import common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import portal.migration_utils
import portal.models
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0040_contract_contractmember_rcc_roletype_and_more"),
        ("users", "__first__"),
        ("users", "__first__"),
        ("users", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="EducationLevel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "code",
                    models.PositiveSmallIntegerField(
                        primary_key=True, serialize=False, verbose_name="code"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("name_en", models.CharField(max_length=100, null=True, verbose_name="Name")),
                ("name_mi", models.CharField(max_length=100, null=True, verbose_name="Name")),
            ],
            options={
                "db_table": "education_level",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.AlterModelManagers(
            name="application",
            managers=[
                ("objects", portal.models.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="convertedfile",
            managers=[
                ("objects", portal.models.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="invitation",
            managers=[
                ("objects", portal.models.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="maillog",
            managers=[
                ("objects", portal.models.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="nomination",
            managers=[
                ("objects", portal.models.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="panellist",
            managers=[
                ("objects", portal.models.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="round",
            managers=[
                ("objects", portal.models.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="scheme",
            managers=[
                ("objects", portal.models.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="subscription",
            managers=[
                ("objects", portal.models.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="testimonial",
            managers=[
                ("objects", portal.models.CurrentSiteManager()),
            ],
        ),
        migrations.AlterField(
            model_name="contract",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="portal.application",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contractmember",
            unique_together={("contract", "email", "role")},
        ),
        migrations.RunPython(
            code=portal.migration_utils.add_education_level_data,
            reverse_code=portal.migration_utils.dummy,
        ),
        migrations.AddField(
            model_name="requireddocument",
            name="exclude",
            field=models.BooleanField(default=False, help_text="Exclude from the final export"),
        ),
        migrations.AlterField(
            model_name="application",
            name="number",
            field=models.CharField(
                blank=True, max_length=24, null=True, unique=True, verbose_name="number"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="state",
            field=portal.models.StateField(
                choices=[
                    (None, None),
                    ("new", "new"),
                    ("draft", "draft"),
                    ("tac_accepted", "TAC accepted"),
                    ("submitted", "submitted"),
                    ("cancelled", "cancelled"),
                    ("withdrawn", "withdrawn"),
                    ("approved", "approved"),
                    ("accepted", "accepted"),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="submitted by",
            ),
        ),
        migrations.AlterField(
            model_name="historicalapplication",
            name="number",
            field=models.CharField(
                blank=True, db_index=True, max_length=24, null=True, verbose_name="number"
            ),
        ),
        migrations.AlterField(
            model_name="historicalapplication",
            name="state",
            field=portal.models.StateField(
                choices=[
                    (None, None),
                    ("new", "new"),
                    ("draft", "draft"),
                    ("tac_accepted", "TAC accepted"),
                    ("submitted", "submitted"),
                    ("cancelled", "cancelled"),
                    ("withdrawn", "withdrawn"),
                    ("approved", "approved"),
                    ("accepted", "accepted"),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ContractComment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "token",
                    models.CharField(
                        default=portal.models.get_unique_invitation_token,
                        max_length=42,
                        unique=True,
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, max_length=1000, null=True, verbose_name="comment"
                    ),
                ),
                (
                    "attachment",
                    private_storage.fields.PrivateFileField(
                        blank=True,
                        null=True,
                        storage=private_storage.storage.files.PrivateFileSystemStorage(),
                        upload_to="",
                        verbose_name="attachment",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="portal.contract",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="submitted by",
                    ),
                ),
            ],
            options={
                "verbose_name": "comment",
                "db_table": "contract_comment",
                "ordering": ["-id"],
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
    ]
