# Generated by Django 4.2.6 on 2023-11-29 01:17

import common.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import portal.migration_utils
import portal.models
import private_storage.fields
import private_storage.storage.files
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0040_contract_contractmember_rcc_roletype_and_more"),
        ("users", "__first__"),
        ("users", "__first__"),
        ("users", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EducationLevel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "code",
                    models.PositiveSmallIntegerField(
                        primary_key=True, serialize=False, verbose_name="code"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("name_en", models.CharField(max_length=100, null=True, verbose_name="Name")),
                ("name_mi", models.CharField(max_length=100, null=True, verbose_name="Name")),
            ],
            options={
                "db_table": "education_level",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.AlterModelManagers(
            name="application",
            managers=[
                ("objects", portal.models.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="convertedfile",
            managers=[
                ("objects", portal.models.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="invitation",
            managers=[
                ("objects", portal.models.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="maillog",
            managers=[
                ("objects", portal.models.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="nomination",
            managers=[
                ("objects", portal.models.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="panellist",
            managers=[
                ("objects", portal.models.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="round",
            managers=[
                ("objects", portal.models.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="scheme",
            managers=[
                ("objects", portal.models.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="subscription",
            managers=[
                ("objects", portal.models.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="testimonial",
            managers=[
                ("objects", portal.models.CurrentSiteManager()),
            ],
        ),
        migrations.AlterField(
            model_name="contract",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="portal.application",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contractmember",
            unique_together={("contract", "email", "role")},
        ),
        migrations.RunPython(
            code=portal.migration_utils.add_education_level_data,
            reverse_code=portal.migration_utils.dummy,
        ),
        migrations.RunPython(
            code=portal.migration_utils.add_document_type_data,
            reverse_code=portal.migration_utils.dummy,
        ),
        migrations.AddField(
            model_name="requireddocument",
            name="exclude",
            field=models.BooleanField(default=False, help_text="Exclude from the final export"),
        ),
        migrations.AlterField(
            model_name="application",
            name="number",
            field=models.CharField(
                blank=True, max_length=24, null=True, unique=True, verbose_name="number"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="state",
            field=portal.models.StateField(
                choices=[
                    (None, None),
                    ("new", "new"),
                    ("draft", "draft"),
                    ("tac_accepted", "TAC accepted"),
                    ("submitted", "submitted"),
                    ("cancelled", "cancelled"),
                    ("withdrawn", "withdrawn"),
                    ("approved", "approved"),
                    ("accepted", "accepted"),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="submitted by",
            ),
        ),
        migrations.AlterField(
            model_name="historicalapplication",
            name="number",
            field=models.CharField(
                blank=True, db_index=True, max_length=24, null=True, verbose_name="number"
            ),
        ),
        migrations.AlterField(
            model_name="historicalapplication",
            name="state",
            field=portal.models.StateField(
                choices=[
                    (None, None),
                    ("new", "new"),
                    ("draft", "draft"),
                    ("tac_accepted", "TAC accepted"),
                    ("submitted", "submitted"),
                    ("cancelled", "cancelled"),
                    ("withdrawn", "withdrawn"),
                    ("approved", "approved"),
                    ("accepted", "accepted"),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ContractComment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "token",
                    models.CharField(
                        default=portal.models.get_unique_invitation_token,
                        max_length=42,
                        unique=True,
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, max_length=1000, null=True, verbose_name="comment"
                    ),
                ),
                (
                    "attachment",
                    private_storage.fields.PrivateFileField(
                        blank=True,
                        null=True,
                        storage=private_storage.storage.files.PrivateFileSystemStorage(),
                        upload_to="contracts",
                        verbose_name="attachment",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="portal.contract",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="submitted by",
                    ),
                ),
            ],
            options={
                "verbose_name": "comment",
                "db_table": "contract_comment",
                "ordering": ["-id"],
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.AddField(
            model_name="contract",
            name="host_contact_email",
            field=common.models.EmailField(
                blank=True, max_length=120, null=True, verbose_name="host contact email address"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="host_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="host_number"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="host_contact_email",
            field=common.models.EmailField(
                blank=True, max_length=120, null=True, verbose_name="host contact email address"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="host_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="host_number"
            ),
        ),
        migrations.AlterField(
            model_name="affiliation",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="affiliations",
                to="portal.organisation",
                verbose_name="organisation",
            ),
        ),
        migrations.AddField(
            model_name="requiredpart",
            name="title_en",
            field=models.CharField(
                blank=True,
                help_text="Contract part title",
                max_length=200,
                null=True,
                verbose_name="Title",
            ),
        ),
        migrations.AddField(
            model_name="requiredpart",
            name="title_mi",
            field=models.CharField(
                blank=True,
                help_text="Contract part title",
                max_length=200,
                null=True,
                verbose_name="Title",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="budget",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                help_text="Please upload completed application budget spreadsheet",
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="budgets",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "xls",
                            "xlw",
                            "xlt",
                            "xml",
                            "xlsx",
                            "xlsm",
                            "xltx",
                            "xltm",
                            "xlsb",
                            "csv",
                            "ctv",
                        ]
                    )
                ],
                verbose_name="completed application budget spreadsheet",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="file",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                help_text="Please upload completed application form",
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="applications",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "odt",
                            "ott",
                            "oth",
                            "odm",
                            "doc",
                            "docx",
                            "docm",
                            "docb",
                        ]
                    )
                ],
                verbose_name="completed application form",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="photo_identity",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                help_text=portal.models.photo_identity_help_text,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="ids",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
                verbose_name="Photo Identity",
            ),
        ),
        migrations.AlterField(
            model_name="applicationdocument",
            name="file",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="applications",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "csv",
                            "ctv",
                            "doc",
                            "docb",
                            "docm",
                            "docx",
                            "dot",
                            "dotm",
                            "dotx",
                            "odm",
                            "odt",
                            "oth",
                            "ott",
                            "pdf",
                            "rtf",
                            "tex",
                            "xls",
                            "xlsb",
                            "xlsm",
                            "xlsx",
                            "xlt",
                            "xltm",
                            "xltx",
                            "xlw",
                            "xml",
                        ]
                    )
                ],
            ),
        ),
        migrations.CreateModel(
            name="ContractCommentAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "attachment",
                    private_storage.fields.PrivateFileField(
                        blank=True,
                        null=True,
                        storage=private_storage.storage.files.PrivateFileSystemStorage(),
                        upload_to="contracts",
                        verbose_name="attachment",
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="portal.contractcomment",
                    ),
                ),
            ],
            options={
                "verbose_name": "attachment",
                "db_table": "contract_comment_attachment",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.AlterField(
            model_name="curriculumvitae",
            name="file",
            field=private_storage.fields.PrivateFileField(
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="cv",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "doc",
                            "docb",
                            "docm",
                            "docx",
                            "dot",
                            "dotm",
                            "dotx",
                            "odm",
                            "odt",
                            "oth",
                            "ott",
                            "pdf",
                            "rtf",
                            "tex",
                        ]
                    )
                ],
                verbose_name="file",
            ),
        ),
        migrations.AlterField(
            model_name="ethicsstatement",
            name="file",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                help_text="Please upload human or animal ethics statement.",
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="statements",
                verbose_name="ethics statement",
            ),
        ),
        migrations.AlterField(
            model_name="identityverification",
            name="file",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="ids",
                verbose_name="Photo Identity",
            ),
        ),
        migrations.AlterField(
            model_name="letterofsupport",
            name="file",
            field=private_storage.fields.PrivateFileField(
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="letters_of_support",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "odt",
                            "ott",
                            "oth",
                            "odm",
                            "doc",
                            "docx",
                            "docm",
                            "docb",
                        ]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="nomination",
            name="file",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                help_text="Upload filled-in nominator form",
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="nominations",
                verbose_name="Nominator form",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="file",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="contracts",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "csv",
                            "ctv",
                            "doc",
                            "docb",
                            "docm",
                            "docx",
                            "dot",
                            "dotm",
                            "dotx",
                            "odm",
                            "odt",
                            "oth",
                            "ott",
                            "pdf",
                            "rtf",
                            "tex",
                            "xls",
                            "xlsb",
                            "xlsm",
                            "xlsx",
                            "xlt",
                            "xltm",
                            "xltx",
                            "xlw",
                            "xml",
                        ]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="scoresheet",
            name="file",
            field=private_storage.fields.PrivateFileField(
                help_text="Upload filled-in for all the applications in bulk",
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="score-sheets",
                verbose_name="Score Sheet",
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="file",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                help_text="Please upload your endorsement, testimonial, or feedback",
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="testimonials",
                verbose_name="endorsement, testimonial, or feedback",
            ),
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "code",
                    common.models.FixedCharField(max_length=2, primary_key=True, serialize=False),
                ),
                ("code3", common.models.FixedCharField(max_length=3, unique=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("num", models.FloatField(blank=True, null=True)),
                ("itu", models.CharField(blank=True, max_length=255, null=True)),
                ("fips", models.CharField(blank=True, max_length=255, null=True)),
                ("ioc", models.CharField(blank=True, max_length=255, null=True)),
                ("fifa", models.CharField(blank=True, max_length=255, null=True)),
                ("ds", models.CharField(blank=True, max_length=255, null=True)),
                ("wmo", models.CharField(blank=True, max_length=255, null=True)),
                ("gaul", models.FloatField(blank=True, null=True)),
                ("marc", models.CharField(blank=True, max_length=255, null=True)),
                ("dial", models.CharField(blank=True, max_length=255, null=True)),
                ("independent", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name_plural": "countries",
                "db_table": "country",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="alt_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="grid",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="gst",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="legal_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="nz_ris_type",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="nzbn",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="ror",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="website",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="alt_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="grid",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="gst",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="legal_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="nz_ris_type",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="nzbn",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="ror",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="website",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicalprofile",
            name="gender",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Prefer not to say"),
                    (1, "Male"),
                    (2, "Female"),
                    (3, "Gender diverse"),
                ],
                db_comment="0: Prefer not to say\n1: Male\n2: Female\n3: Gender diverse",
                default=0,
                null=True,
                verbose_name="gender",
            ),
        ),
        migrations.AlterField(
            model_name="maillog",
            name="subject",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Prefer not to say"),
                    (1, "Male"),
                    (2, "Female"),
                    (3, "Gender diverse"),
                ],
                db_comment="0: Prefer not to say\n1: Male\n2: Female\n3: Gender diverse",
                default=0,
                null=True,
                verbose_name="gender",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalCountry",
            fields=[
                ("created_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("updated_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("code", common.models.FixedCharField(db_index=True, max_length=2)),
                ("code3", common.models.FixedCharField(db_index=True, max_length=3)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("num", models.FloatField(blank=True, null=True)),
                ("itu", models.CharField(blank=True, max_length=255, null=True)),
                ("fips", models.CharField(blank=True, max_length=255, null=True)),
                ("ioc", models.CharField(blank=True, max_length=255, null=True)),
                ("fifa", models.CharField(blank=True, max_length=255, null=True)),
                ("ds", models.CharField(blank=True, max_length=255, null=True)),
                ("wmo", models.CharField(blank=True, max_length=255, null=True)),
                ("gaul", models.FloatField(blank=True, null=True)),
                ("marc", models.CharField(blank=True, max_length=255, null=True)),
                ("dial", models.CharField(blank=True, max_length=255, null=True)),
                ("independent", models.CharField(blank=True, max_length=255, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical country",
                "verbose_name_plural": "historical countries",
                "db_table": "country_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="country",
            field=models.ForeignKey(
                blank=True,
                db_column="country",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="portal.country",
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="country",
            field=models.ForeignKey(
                blank=True,
                db_column="country",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organisations",
                to="portal.country",
            ),
        ),
    ]
