# Generated by Django 5.0.2 on 2024-03-05 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0041_remove_historicalorganisation_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractmember",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="portal.address",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontractmember",
            name="address",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="portal.address",
            ),
        ),
    ]
