# Generated by Django 5.0 on 2023-12-08 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0041_educationlevel_alter_application_managers_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="academicrecord",
            old_name="profile",
            new_name="person",
        ),
        migrations.RenameField(
            model_name="affiliation",
            old_name="profile",
            new_name="person",
        ),
        migrations.RenameField(
            model_name="historicalacademicrecord",
            old_name="profile",
            new_name="person",
        ),
        migrations.RenameField(
            model_name="historicalaffiliation",
            old_name="profile",
            new_name="person",
        ),
        migrations.RenameField(
            model_name="historicalrecognition",
            old_name="profile",
            new_name="person",
        ),
        migrations.RenameField(
            model_name="profilecareerstage",
            old_name="profile",
            new_name="person",
        ),
        migrations.RenameField(
            model_name="profilepersonidentifier",
            old_name="profile",
            new_name="person",
        ),
        migrations.RenameField(
            model_name="recognition",
            old_name="profile",
            new_name="person",
        ),
        migrations.RenameField(
            model_name="curriculumvitae",
            old_name="profile",
            new_name="person",
        ),
        migrations.RenameField(
            model_name="profileprotectionpattern",
            old_name="profile",
            new_name="person",
        ),
        migrations.AlterUniqueTogether(
            name="profileprotectionpattern",
            unique_together={("person", "protection_pattern")},
        ),
        migrations.AlterField(
            model_name="profile",
            name="ethnicities",
            field=models.ManyToManyField(
                blank=True,
                db_table="person_ethnicity",
                to="portal.ethnicity",
                verbose_name="ethnicities",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="iwi_groups",
            field=models.ManyToManyField(
                blank=True,
                db_table="person_iwi_group",
                to="portal.iwigroup",
                verbose_name="iwi groups",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="person",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="profileprotectionpattern",
            name="protection_pattern",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="person_protection_patterns",
                to="portal.protectionpattern",
                verbose_name="protection pattern",
            ),
        ),
        migrations.AlterModelTable(
            name="historicalprofile",
            table="person_history",
        ),
        migrations.AlterModelTable(
            name="profile",
            table="person",
        ),
        migrations.AlterModelTable(
            name="profilecareerstage",
            table="person_career_stage",
        ),
        migrations.AlterModelTable(
            name="profilepersonidentifier",
            table="person_person_identifier",
        ),
        migrations.AlterModelTable(
            name="profileprotectionpattern",
            table="person_protection_pattern",
        ),
    ]
