# Generated by Django 5.0.3 on 2024-03-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0042_contractmember_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="convertedfile",
            name="page_count",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="number of pages"
            ),
        ),
    ]
