# Generated by Django 5.0 on 2023-12-08 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0042_rename_profile_academicrecord_person_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HistoricalProfile",
            new_name="HistoricalPerson",
        ),
        migrations.RenameModel(
            old_name="Profile",
            new_name="Person",
        ),
        migrations.AlterModelOptions(
            name="historicalperson",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical person",
                "verbose_name_plural": "historical persons",
            },
        ),
        migrations.AlterField(
            model_name="curriculumvitae",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="portal.profile",
                verbose_name="person",
            ),
        ),
        migrations.AlterField(
            model_name="profileprotectionpattern",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="person_protection_patterns",
                to="portal.profile",
            ),
        ),
    ]
