# Generated by Django 5.0.3 on 2024-03-11 04:27

import common.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0042_contractmember_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="convertedfile",
            name="page_count",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="number of pages"
            ),
        ),
        migrations.CreateModel(
            name="PersonCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("code", models.CharField(max_length=8)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="previous_codes",
                        to="portal.person",
                    ),
                ),
            ],
            options={
                "db_table": "person_code",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.AddField(
            model_name="roletype",
            name="role_code",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="SYS_ROLES.ROLECODE", null=True
            ),
        ),
        migrations.AddField(
            model_name="roletype",
            name="role_name",
            field=models.CharField(
                blank=True, help_text="SYS_ROLES.ROLETYPE", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="roletype",
            name="role_type",
            field=models.CharField(
                blank=True, help_text="SYS_ROLES.ROLETYPE", max_length=20, null=True
            ),
        ),
    ]
