# Generated by Django 5.0.3 on 2024-03-14 03:10

import common.models
import django.db.models.deletion
import portal.migration_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0042_contractmember_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="convertedfile",
            name="page_count",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="number of pages"
            ),
        ),
        migrations.CreateModel(
            name="PersonCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("code", models.CharField(max_length=8)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="previous_codes",
                        to="portal.person",
                    ),
                ),
            ],
            options={
                "db_table": "person_code",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.AddField(
            model_name="roletype",
            name="role_code",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="SYS_ROLES.ROLECODE", null=True
            ),
        ),
        migrations.AddField(
            model_name="roletype",
            name="role_name",
            field=models.CharField(
                blank=True, help_text="SYS_ROLES.ROLETYPE", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="roletype",
            name="role_type",
            field=models.CharField(
                blank=True, help_text="SYS_ROLES.ROLETYPE", max_length=20, null=True
            ),
        ),
        migrations.RunPython(
            code=portal.migration_utils.add_role_type_data,
            reverse_code=portal.migration_utils.dummy,
        ),
        migrations.AlterModelOptions(
            name="roletype",
            options={"ordering": ["code"]},
        ),
        migrations.AddField(
            model_name="roletype",
            name="for_application",
            field=models.BooleanField(
                default=True, verbose_name="Available for application stage"
            ),
        ),
        migrations.AddField(
            model_name="roletype",
            name="for_contracting",
            field=models.BooleanField(
                default=True, verbose_name="Available for contracting stage"
            ),
        ),
        migrations.RenameField(
            model_name="historicalmember",
            old_name="role",
            new_name="role_description",
        ),
        migrations.RenameField(
            model_name="member",
            old_name="role",
            new_name="role_description",
        ),
        migrations.AlterField(
            model_name="historicalmember",
            name="role_description",
            field=models.CharField(
                blank=True, editable=False, max_length=200, null=True, verbose_name="legacy role"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="role_description",
            field=models.CharField(
                blank=True, editable=False, max_length=200, null=True, verbose_name="legacy role"
            ),
        ),
        migrations.AddField(
            model_name="historicalmember",
            name="role",
            field=models.ForeignKey(
                blank=True,
                db_column="role",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="portal.roletype",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="role",
            field=models.ForeignKey(
                blank=True,
                db_column="role",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="application_personnel",
                to="portal.roletype",
            ),
        ),
        migrations.AlterField(
            model_name="roletype",
            name="role_name",
            field=models.CharField(
                blank=True, help_text="SYS_ROLES.ROLENAME", max_length=255, null=True
            ),
        ),
        migrations.CreateModel(
            name="ContractClause",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("ordering", models.PositiveIntegerField(default=0, verbose_name="ordering")),
                (
                    "type",
                    common.models.FixedCharField(
                        choices=[("A", "Addition"), ("V", "Variation")],
                        max_length=1,
                        verbose_name="Type",
                    ),
                ),
                ("clause", models.CharField(max_length=100, verbose_name="Clause Number")),
                ("term", models.TextField(max_length=2000, verbose_name="Term")),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_clauses",
                        to="portal.round",
                    ),
                ),
            ],
            options={
                "db_table": "contract_clause",
                "ordering": ["ordering"],
                "abstract": False,
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
    ]
