# Generated by Django 5.0.3 on 2024-03-21 22:24

import common.models
import django.core.validators
import django.db.models.deletion
import portal.migration_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0043_convertedfile_page_count_personcode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="education_level",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "No Qualification"),
                    (1, "Level 1 Certificate"),
                    (2, "Level 2 Certificate"),
                    (3, "Level 3 Certificate"),
                    (4, "Level 4 Certificate"),
                    (5, "Level 5 Diploma/Certificate"),
                    (6, "Level 6 Graduate Certificate, Level 6 Diploma/Certificate"),
                    (
                        7,
                        "Bachelor Degree, Level 7 Graduate Diploma/Certificate, Level 7 Diploma/ Certificate",
                    ),
                    (8, "Postgraduate Diploma/Certificate, Bachelor Honours"),
                    (9, "Masters Degree"),
                    (10, "Doctorate Degree"),
                    (23, "Overseas Secondary School Qualification"),
                    (94, "Don't Know"),
                ],
                db_comment="0: No Qualification\n1: Level 1 Certificate\n2: Level 2 Certificate\n3: Level 3 Certificate\n4: Level 4 Certificate\n5: Level 5 Diploma/Certificate\n6: Level 6 Graduate Certificate, Level 6 Diploma/Certificate\n7: Bachelor Degree, Level 7 Graduate Diploma/Certificate, Level 7 Diploma/ Certificate\n8: Postgraduate Diploma/Certificate, Bachelor Honours\n9: Masters Degree\n10: Doctorate Degree\n23: Overseas Secondary School Qualification\n94: Don't Know",
                null=True,
                verbose_name="education level",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="employment_status",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Paid employee"),
                    (2, "Employer"),
                    (3, "Self-employed and without employees"),
                    (4, "Unpaid family worker"),
                    (6, "Student"),
                    (5, "Not stated"),
                ],
                db_comment="1: Paid employee\n2: Employer\n3: Self-employed and without employees\n4: Unpaid family worker\n6: Student\n5: Not stated",
                null=True,
                verbose_name="employment status",
            ),
        ),
        migrations.AlterField(
            model_name="affiliation",
            name="type",
            field=models.CharField(
                choices=[
                    ("EDU", "Education"),
                    ("EMP", "Employment"),
                    ("MEM", "Membership"),
                    ("SER", "Service"),
                ],
                db_comment="EDU: Education\nEMP: Employment\nMEM: Membership\nSER: Service",
                max_length=10,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="historicalaffiliation",
            name="type",
            field=models.CharField(
                choices=[
                    ("EDU", "Education"),
                    ("EMP", "Employment"),
                    ("MEM", "Membership"),
                    ("SER", "Service"),
                ],
                db_comment="EDU: Education\nEMP: Employment\nMEM: Membership\nSER: Service",
                max_length=10,
                verbose_name="type",
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="signatory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="signatory_for",
                to="portal.person",
                verbose_name="signatory",
                limit_choices_to={"affiliations__type": "EMP"},
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                max_length=24,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
                verbose_name="Contact phone number",
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="email",
            field=common.models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Contact email address"
            ),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                max_length=24,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
                verbose_name="Contact phone number",
            ),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="email",
            field=common.models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Contact email address"
            ),
        ),
        migrations.AddField(
            model_name="affiliation",
            name="email",
            field=common.models.EmailField(
                blank=True, max_length=120, null=True, verbose_name="email address"
            ),
        ),
        migrations.AddField(
            model_name="historicalaffiliation",
            name="email",
            field=common.models.EmailField(
                blank=True, max_length=120, null=True, verbose_name="email address"
            ),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="signatory",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to={
                    "affiliations__type": "EMP",
                },
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="portal.person",
                verbose_name="signatory",
            ),
        ),
        migrations.RunPython(
            code=portal.migration_utils.add_RSTA,
            reverse_code=portal.migration_utils.dummy,
        ),
        migrations.AlterField(
            model_name="historicalperson",
            name="education_level",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "No Qualification"),
                    (1, "Level 1 Certificate"),
                    (2, "Level 2 Certificate"),
                    (3, "Level 3 Certificate"),
                    (4, "Level 4 Certificate"),
                    (5, "Level 5 Diploma/Certificate"),
                    (6, "Level 6 Graduate Certificate, Level 6 Diploma/Certificate"),
                    (
                        7,
                        "Bachelor Degree, Level 7 Graduate Diploma/Certificate, Level 7 Diploma/ Certificate",
                    ),
                    (8, "Postgraduate Diploma/Certificate, Bachelor Honours"),
                    (9, "Masters Degree"),
                    (10, "Doctorate Degree"),
                    (23, "Overseas Secondary School Qualification"),
                    (94, "Don't Know"),
                ],
                db_comment="0: No Qualification\n1: Level 1 Certificate\n2: Level 2 Certificate\n3: Level 3 Certificate\n4: Level 4 Certificate\n5: Level 5 Diploma/Certificate\n6: Level 6 Graduate Certificate, Level 6 Diploma/Certificate\n7: Bachelor Degree, Level 7 Graduate Diploma/Certificate, Level 7 Diploma/ Certificate\n8: Postgraduate Diploma/Certificate, Bachelor Honours\n9: Masters Degree\n10: Doctorate Degree\n23: Overseas Secondary School Qualification\n94: Don't Know",
                null=True,
                verbose_name="education level",
            ),
        ),
        migrations.AlterField(
            model_name="historicalperson",
            name="employment_status",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Paid employee"),
                    (2, "Employer"),
                    (3, "Self-employed and without employees"),
                    (4, "Unpaid family worker"),
                    (6, "Student"),
                    (5, "Not stated"),
                ],
                db_comment="1: Paid employee\n2: Employer\n3: Self-employed and without employees\n4: Unpaid family worker\n6: Student\n5: Not stated",
                null=True,
                verbose_name="employment status",
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="fund",
            name="name_en",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="fund",
            name="name_mi",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="historicalfund",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="historicalfund",
            name="name_en",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="historicalfund",
            name="name_mi",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="historicalround",
            name="required_submitted_testimonials",
            field=models.BooleanField(
                default=True,
                help_text="required submitted testimonials before submitting the applications",
                verbose_name="required submitted testimonials",
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="required_submitted_testimonials",
            field=models.BooleanField(
                default=True,
                help_text="required submitted testimonials before submitting the applications",
                verbose_name="required submitted testimonials",
            ),
        ),
        migrations.AddField(
            model_name="historicalround",
            name="contract_background",
            field=models.TextField(blank=True, null=True, verbose_name="contract background"),
        ),
        migrations.AddField(
            model_name="round",
            name="contract_background",
            field=models.TextField(blank=True, null=True, verbose_name="contract background"),
        ),
        migrations.RunPython(
            code=portal.migration_utils.update_round_required_submitted_testimonials,
            reverse_code=portal.migration_utils.dummy,
        ),
        migrations.AlterField(
            model_name="documenttype",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AB", "Award Budget"),
                    ("AF", "Application Form"),
                    ("AIMS", "Research Aims"),
                    ("B", "Budget"),
                    ("CV", "Curriculum Vitae"),
                    ("E", "Ethics Statement"),
                    ("F", "Form"),
                    ("HS", "Host Suitablity"),
                    ("PB", "Proposal Budget"),
                    ("PT", "Project Timeline"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalround",
            name="tac",
            field=models.TextField(
                blank=True,
                help_text="Terms and Conditions",
                max_length=100000,
                null=True,
                verbose_name="T&C",
            ),
        ),
        migrations.AlterField(
            model_name="historicalround",
            name="tac_en",
            field=models.TextField(
                blank=True,
                help_text="Terms and Conditions",
                max_length=100000,
                null=True,
                verbose_name="T&C",
            ),
        ),
        migrations.AlterField(
            model_name="historicalround",
            name="tac_mi",
            field=models.TextField(
                blank=True,
                help_text="Terms and Conditions",
                max_length=100000,
                null=True,
                verbose_name="T&C",
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="tac",
            field=models.TextField(
                blank=True,
                help_text="Terms and Conditions",
                max_length=100000,
                null=True,
                verbose_name="T&C",
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="tac_en",
            field=models.TextField(
                blank=True,
                help_text="Terms and Conditions",
                max_length=100000,
                null=True,
                verbose_name="T&C",
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="tac_mi",
            field=models.TextField(
                blank=True,
                help_text="Terms and Conditions",
                max_length=100000,
                null=True,
                verbose_name="T&C",
            ),
        ),
    ]
