# Generated by Django 5.0.3 on 2024-03-19 23:30

import common.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0043_convertedfile_page_count_personcode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorganisation",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                max_length=24,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
                verbose_name="Contact phone number",
            ),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="email",
            field=common.models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Contact email address"
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                max_length=24,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
                verbose_name="Contact phone number",
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="email",
            field=common.models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Contact email address"
            ),
        ),
        migrations.AddField(
            model_name="affiliation",
            name="email",
            field=common.models.EmailField(
                blank=True, max_length=120, null=True, verbose_name="email address"
            ),
        ),
        migrations.AddField(
            model_name="historicalaffiliation",
            name="email",
            field=common.models.EmailField(
                blank=True, max_length=120, null=True, verbose_name="email address"
            ),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="signatory",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to={
                    "affiliations__org": models.F("pk"),
                    "affiliations__type": "EMP",
                },
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="portal.person",
                verbose_name="signatory",
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="signatory",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "affiliations__org": models.F("pk"),
                    "affiliations__type": "EMP",
                },
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="signatory_for",
                to="portal.person",
                verbose_name="signatory",
            ),
        ),
    ]
