# Generated by Django 4.2.8 on 2023-12-11 00:14

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0043_rename_historicalprofile_historicalperson_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProtectionPatternPerson",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "code",
                    models.PositiveSmallIntegerField(
                        primary_key=True, serialize=False, verbose_name="code"
                    ),
                ),
                ("description", models.CharField(max_length=80, verbose_name="description")),
                (
                    "description_en",
                    models.CharField(max_length=80, null=True, verbose_name="description"),
                ),
                (
                    "description_mi",
                    models.CharField(max_length=80, null=True, verbose_name="description"),
                ),
                ("pattern", models.CharField(max_length=80, verbose_name="pattern")),
                ("comment", models.TextField(blank=True, null=True, verbose_name="comment")),
                ("comment_en", models.TextField(blank=True, null=True, verbose_name="comment")),
                ("comment_mi", models.TextField(blank=True, null=True, verbose_name="comment")),
                ("expires_on", models.DateField(blank=True, null=True, verbose_name="expires on")),
            ],
            options={
                "managed": False,
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.RenameModel(
            old_name="ProfileCareerStage",
            new_name="PersonCareerStage",
        ),
        migrations.RenameModel(
            old_name="ProfilePersonIdentifier",
            new_name="PersonPersonIdentifier",
        ),
        migrations.RenameModel(
            old_name="ProfileProtectionPattern",
            new_name="PersonProtectionPattern",
        ),
        migrations.DeleteModel(
            name="ProtectionPatternProfile",
        ),
        migrations.AlterField(
            model_name="person",
            name="languages_spoken",
            field=models.ManyToManyField(
                blank=True,
                db_table="person_language",
                to="portal.language",
                verbose_name="languages spoken",
            ),
        ),
    ]
