# Generated by Django 5.0.3 on 2024-04-29 00:49

import django.db.models.deletion
import portal.migration_utils
import portal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0044_historicalorganisation_contact_phone_and_more"),
        ("users", "__first__"),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttype",
            name="format",
            field=models.CharField(
                choices=[("I", "image"), ("S", "spreadsheet"), ("T", "text")],
                default="T",
                max_length=1,
            ),
        ),
        migrations.RunPython(
            code=portal.migration_utils.set_document_type_format,
            reverse_code=portal.migration_utils.dummy,
        ),
        migrations.AlterField(
            model_name="documenttype",
            name="format",
            field=models.CharField(
                choices=[("I", "Image"), ("S", "Spreadsheet"), ("T", "Text")],
                default="T",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="curriculumvitae",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="owner",
            ),
        ),
        migrations.AlterField(
            model_name="curriculumvitae",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portal.person",
                verbose_name="person",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="panel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="portal.panel",
            ),
        ),
        migrations.AddField(
            model_name="historicalapplication",
            name="panel",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="portal.panel",
            ),
        ),
        migrations.AddField(
            model_name="historicalround",
            name="can_specify_panel",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="round",
            name="can_specify_panel",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="application",
            name="state",
            field=portal.models.StateField(
                choices=[
                    (None, None),
                    ("new", "new"),
                    ("draft", "draft"),
                    ("tac_accepted", "TAC accepted"),
                    ("in_review", "in referee review"),
                    ("submitted", "submitted"),
                    ("cancelled", "cancelled"),
                    ("withdrawn", "withdrawn"),
                    ("approved", "approved"),
                    ("accepted", "accepted"),
                    ("funded", "funded"),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="historicalapplication",
            name="state",
            field=portal.models.StateField(
                choices=[
                    (None, None),
                    ("new", "new"),
                    ("draft", "draft"),
                    ("tac_accepted", "TAC accepted"),
                    ("in_review", "in referee review"),
                    ("submitted", "submitted"),
                    ("cancelled", "cancelled"),
                    ("withdrawn", "withdrawn"),
                    ("approved", "approved"),
                    ("accepted", "accepted"),
                    ("funded", "funded"),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                verbose_name="state",
            ),
        ),
    ]
