# Generated by Django 4.2.8 on 2023-12-11 03:46

import common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("portal", "0044_protectionpatternperson_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalperson",
            name="is_academic_records_completed",
        ),
        migrations.RemoveField(
            model_name="historicalperson",
            name="is_career_stages_completed",
        ),
        migrations.RemoveField(
            model_name="historicalperson",
            name="is_cvs_completed",
        ),
        migrations.RemoveField(
            model_name="historicalperson",
            name="is_employments_completed",
        ),
        migrations.RemoveField(
            model_name="historicalperson",
            name="is_ethnicities_completed",
        ),
        migrations.RemoveField(
            model_name="historicalperson",
            name="is_external_ids_completed",
        ),
        migrations.RemoveField(
            model_name="historicalperson",
            name="is_iwi_groups_completed",
        ),
        migrations.RemoveField(
            model_name="historicalperson",
            name="is_professional_bodies_completed",
        ),
        migrations.RemoveField(
            model_name="historicalperson",
            name="is_recognitions_completed",
        ),
        migrations.RemoveField(
            model_name="person",
            name="is_academic_records_completed",
        ),
        migrations.RemoveField(
            model_name="person",
            name="is_career_stages_completed",
        ),
        migrations.RemoveField(
            model_name="person",
            name="is_cvs_completed",
        ),
        migrations.RemoveField(
            model_name="person",
            name="is_employments_completed",
        ),
        migrations.RemoveField(
            model_name="person",
            name="is_ethnicities_completed",
        ),
        migrations.RemoveField(
            model_name="person",
            name="is_external_ids_completed",
        ),
        migrations.RemoveField(
            model_name="person",
            name="is_iwi_groups_completed",
        ),
        migrations.RemoveField(
            model_name="person",
            name="is_professional_bodies_completed",
        ),
        migrations.RemoveField(
            model_name="person",
            name="is_recognitions_completed",
        ),
        migrations.AddField(
            model_name="historicalperson",
            name="activity",
            field=common.models.FixedCharField(
                blank=True,
                choices=[("CE", "CE"), ("CO", "CO"), ("CP", "CP"), ("CU", "CU"), ("CW", "CW")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalperson",
            name="code",
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="historicalperson",
            name="email",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="historicalperson",
            name="first_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="historicalperson",
            name="friendly_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="historicalperson",
            name="initials",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="historicalperson",
            name="label_name",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="historicalperson",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="historicalperson",
            name="middle_names",
            field=models.CharField(
                blank=True,
                help_text="Comma separated list of middle names",
                max_length=280,
                null=True,
                verbose_name="middle names",
            ),
        ),
        migrations.AddField(
            model_name="historicalperson",
            name="orcid",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="historicalperson",
            name="other_names",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalperson",
            name="salutation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalperson",
            name="title",
            field=models.ForeignKey(
                blank=True,
                db_column="title",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="portal.title",
                verbose_name="title",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="activity",
            field=common.models.FixedCharField(
                blank=True,
                choices=[("CE", "CE"), ("CO", "CO"), ("CP", "CP"), ("CU", "CU"), ("CW", "CW")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="code",
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="person",
            name="email",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="first_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="friendly_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="initials",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="label_name",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="middle_names",
            field=models.CharField(
                blank=True,
                help_text="Comma separated list of middle names",
                max_length=280,
                null=True,
                verbose_name="middle names",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="orcid",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="other_names",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="salutation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="title",
            field=models.ForeignKey(
                blank=True,
                db_column="title",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="portal.title",
                verbose_name="title",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="person",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
