# Generated by Django 5.0.4 on 2024-04-16 03:02

import django.db.models.deletion
import portal.migration_utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0044_historicalorganisation_contact_phone_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttype",
            name="format",
            field=models.CharField(
                choices=[("I", "image"), ("S", "spreadsheet"), ("T", "text")],
                default="T",
                max_length=1,
            ),
        ),
        migrations.RunPython(
            code=portal.migration_utils.set_document_type_format,
            reverse_code=portal.migration_utils.dummy,
        ),
        migrations.AlterField(
            model_name="documenttype",
            name="format",
            field=models.CharField(
                choices=[("I", "Image"), ("S", "Spreadsheet"), ("T", "Text")],
                default="T",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="curriculumvitae",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="owner",
            ),
        ),
        migrations.AlterField(
            model_name="curriculumvitae",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portal.person",
                verbose_name="person",
            ),
        ),
    ]
