# Generated by Django 5.0.4 on 2024-04-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0044_historicalorganisation_contact_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttype",
            name="format",
            field=models.CharField(
                choices=[("I", "image"), ("S", "spreadsheet"), ("T", "text")],
                default="T",
                max_length=1,
            ),
        ),
    ]
