# Generated by Django 5.0.1 on 2024-01-17 01:08

import common.models
import django.db.models.deletion
import portal.models
import private_storage.fields
import private_storage.storage.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0045_remove_historicalperson_is_academic_records_completed_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalround",
            old_name="closes_on",
            new_name="closes_at",
        ),
        migrations.RenameField(
            model_name="round",
            old_name="closes_on",
            new_name="closes_at",
        ),
        migrations.AddField(
            model_name="historicalround",
            name="has_three_parties",
            field=models.BooleanField(default=False, verbose_name="has three party contracts"),
        ),
        migrations.AddField(
            model_name="round",
            name="has_three_parties",
            field=models.BooleanField(default=False, verbose_name="has three party contracts"),
        ),
        migrations.AlterField(
            model_name="historicalemailaddress",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="email address"),
        ),
        migrations.AlterField(
            model_name="historicalround",
            name="closes_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="closes at"),
        ),
        migrations.AlterField(
            model_name="round",
            name="closes_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="closes at"),
        ),
        migrations.CreateModel(
            name="ContractEthicsStatement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "file",
                    private_storage.fields.PrivateFileField(
                        blank=True,
                        help_text="Please upload human or animal ethics statement.",
                        null=True,
                        storage=private_storage.storage.files.PrivateFileSystemStorage(),
                        upload_to="contracts",
                        verbose_name="ethics statement",
                    ),
                ),
                (
                    "not_relevant",
                    models.BooleanField(default=False, verbose_name="Not Applicable"),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, max_length=1000, null=True, verbose_name="Comment"
                    ),
                ),
                (
                    "contract",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ethics_statement",
                        to="portal.contract",
                    ),
                ),
            ],
            options={
                "db_table": "contract_ethics_statement",
            },
            bases=(portal.models.PdfFileMixin, common.models.HelperMixin, models.Model),
        ),
    ]
