# Generated by Django 5.0.3 on 2024-05-17 00:59

import colorfield.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0045_auto_20240514_1634"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalround",
            name="colour",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                help_text="Colour used for text hearders and back-grounds",
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="colour",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                help_text="Colour used for text hearders and back-grounds",
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
            ),
        ),
        migrations.AlterField(
            model_name="panellist",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="panellists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
