# Generated by Django 4.2.8 on 2023-12-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0045_remove_historicalperson_is_academic_records_completed_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalround",
            old_name="closes_on",
            new_name="closes_at",
        ),
        migrations.RenameField(
            model_name="round",
            old_name="closes_on",
            new_name="closes_at",
        ),
        migrations.AddField(
            model_name="historicalround",
            name="has_three_parties",
            field=models.BooleanField(default=False, verbose_name="has three party contracts"),
        ),
        migrations.AddField(
            model_name="round",
            name="has_three_parties",
            field=models.BooleanField(default=False, verbose_name="has three party contracts"),
        ),
    ]
