# Generated by Django 5.0.3 on 2024-05-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0046_historicalround_colour_round_colour_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="round",
            options={"ordering": ["ordering"]},
        ),
        migrations.AddField(
            model_name="historicalround",
            name="ordering",
            field=models.PositiveIntegerField(default=0, verbose_name="ordering"),
        ),
        migrations.AddField(
            model_name="round",
            name="ordering",
            field=models.PositiveIntegerField(default=0, verbose_name="ordering"),
        ),
    ]
