# Generated by Django 5.0.6 on 2024-06-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0047_alter_round_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="title",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="title",
            name="name_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="title",
            name="name_mi",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
