# Generated by Django 5.0.6 on 2024-06-04 05:51

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0048_alter_title_name_alter_title_name_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorganisation",
            name="ro_email",
            field=common.models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="Research office email address",
                verbose_name="RO email address",
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="ro_email",
            field=common.models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="Research office email address",
                verbose_name="RO email address",
            ),
        ),
    ]
