# Generated by Django 5.0.6 on 2024-07-05 01:04

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0049_historicalorganisation_ro_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalnomination",
            name="position",
            field=models.CharField(
                blank=True,
                help_text="position or role or the nominee, e.g., student, postdoc, etc.",
                max_length=80,
                null=True,
                verbose_name="position",
            ),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nomination",
            name="position",
            field=models.CharField(
                blank=True,
                help_text="position or role or the nominee, e.g., student, postdoc, etc.",
                max_length=80,
                null=True,
                verbose_name="position",
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisation",
            name="grid",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisation",
            name="ro_email",
            field=common.models.EmailField(
                blank=True,
                help_text="Research office email address",
                max_length=254,
                null=True,
                verbose_name="RO email address",
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="grid",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="ro_email",
            field=common.models.EmailField(
                blank=True,
                help_text="Research office email address",
                max_length=254,
                null=True,
                verbose_name="RO email address",
            ),
        ),
    ]
