# Generated by Django 5.0.3 on 2024-06-28 01:22

import common.models
import django.db.models.deletion
import model_utils.fields
import portal.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0049_historicalorganisation_ro_email_and_more"),
        ("users", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalReport",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("updated_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("period", models.PositiveSmallIntegerField(verbose_name="period")),
                (
                    "type",
                    common.models.FixedCharField(
                        choices=[
                            ("A", "Annual"),
                            ("E", "Exchange"),
                            ("F", "Final"),
                            ("I", "Interim"),
                            ("L", "Follow up"),
                        ],
                        help_text="Reporting Type",
                        max_length=1,
                    ),
                ),
                (
                    "state",
                    portal.models.StateField(
                        choices=[
                            ("accepted", "accepted"),
                            ("acknowledged", "acknowledged"),
                            ("approved", "approved"),
                            ("archived", "archived"),
                            ("cancelled", "cancelled"),
                            ("draft", "draft"),
                            ("new", "new"),
                            ("submitted", "submitted"),
                            ("reported", "reported"),
                        ],
                        default="new",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="state",
                    ),
                ),
                (
                    "reported_at",
                    model_utils.fields.MonitorField(
                        blank=True,
                        default=None,
                        monitor="state",
                        null=True,
                        when={"reported", "submitted"},
                    ),
                ),
                (
                    "assessed_at",
                    model_utils.fields.MonitorField(
                        blank=True, default=None, monitor="state", null=True, when={"assessed"}
                    ),
                ),
                (
                    "vm_ecs",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Contributing to Economic Growth through Distinctive R&D. New Zealand needs its businesses and for-profit enterprises to perform at an optimum level and contribute to economic growth. This theme concerns the development of distinctive products, processes, systems and services from Māori knowledge, resources and people. Of particular interest are products that may be distinctive in the international marketplace.",
                        null=True,
                        verbose_name="Indigenous Innovation",
                    ),
                ),
                (
                    "vm_ens",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Achieving Environmental Sustainability through Iwi and Hapū relationships with land and sea. Like all communities, Māori communities aspire to live in sustainable communities dwelling in healthy environments. Much general environmental research is relevant to Māori. Distinctive environmental research arising in Māori communities relates to the expression of iwi and hapū knowledge, culture and experience – including Kaitiakitanga - in New Zealand land and seascapes.",
                        null=True,
                        verbose_name="Taiao",
                    ),
                ),
                (
                    "vm_hsw",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Improving Māori Health and Social Well-being. Distinctive challenges to Māori health and social well-being continue to arise within Māori communities disadvantaging them in relation to the general population. Research is needed to meet these ongoing needs.",
                        null=True,
                        verbose_name="Hauora/Oranga",
                    ),
                ),
                (
                    "vm_ink",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Exploring Indigenous Knowledge and RS&T. This exploratory theme aims to develop a body of knowledge, as a contribution to RS&T, at the interface between indigenous knowledge including mātauranga Māori – and research, science and technology.",
                        null=True,
                        verbose_name="Mātauranga",
                    ),
                ),
                (
                    "toa_basic",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Pure basic research",
                        null=True,
                        verbose_name="Basic",
                    ),
                ),
                (
                    "toa_experimental",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Experimental development",
                        null=True,
                        verbose_name="Experimental",
                    ),
                ),
                (
                    "toa_applied",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Applied research",
                        null=True,
                        verbose_name="Applied",
                    ),
                ),
                (
                    "toa_strategic",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Strategic basic research",
                        null=True,
                        verbose_name="Strategic",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "assessor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.contract",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schedule_entry",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.reportingscheduleentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical report",
                "verbose_name_plural": "historical reports",
                "db_table": "report_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(
                simple_history.models.HistoricalChanges,
                portal.models.ReportMixin,
                common.models.HelperMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("period", models.PositiveSmallIntegerField(verbose_name="period")),
                (
                    "type",
                    common.models.FixedCharField(
                        choices=[
                            ("A", "Annual"),
                            ("E", "Exchange"),
                            ("F", "Final"),
                            ("I", "Interim"),
                            ("L", "Follow up"),
                        ],
                        help_text="Reporting Type",
                        max_length=1,
                    ),
                ),
                (
                    "state",
                    portal.models.StateField(
                        choices=[
                            ("accepted", "accepted"),
                            ("acknowledged", "acknowledged"),
                            ("approved", "approved"),
                            ("archived", "archived"),
                            ("cancelled", "cancelled"),
                            ("draft", "draft"),
                            ("new", "new"),
                            ("submitted", "submitted"),
                            ("reported", "reported"),
                        ],
                        default="new",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="state",
                    ),
                ),
                (
                    "reported_at",
                    model_utils.fields.MonitorField(
                        blank=True,
                        default=None,
                        monitor="state",
                        null=True,
                        when={"reported", "submitted"},
                    ),
                ),
                (
                    "assessed_at",
                    model_utils.fields.MonitorField(
                        blank=True, default=None, monitor="state", null=True, when={"assessed"}
                    ),
                ),
                (
                    "vm_ecs",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Contributing to Economic Growth through Distinctive R&D. New Zealand needs its businesses and for-profit enterprises to perform at an optimum level and contribute to economic growth. This theme concerns the development of distinctive products, processes, systems and services from Māori knowledge, resources and people. Of particular interest are products that may be distinctive in the international marketplace.",
                        null=True,
                        verbose_name="Indigenous Innovation",
                    ),
                ),
                (
                    "vm_ens",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Achieving Environmental Sustainability through Iwi and Hapū relationships with land and sea. Like all communities, Māori communities aspire to live in sustainable communities dwelling in healthy environments. Much general environmental research is relevant to Māori. Distinctive environmental research arising in Māori communities relates to the expression of iwi and hapū knowledge, culture and experience – including Kaitiakitanga - in New Zealand land and seascapes.",
                        null=True,
                        verbose_name="Taiao",
                    ),
                ),
                (
                    "vm_hsw",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Improving Māori Health and Social Well-being. Distinctive challenges to Māori health and social well-being continue to arise within Māori communities disadvantaging them in relation to the general population. Research is needed to meet these ongoing needs.",
                        null=True,
                        verbose_name="Hauora/Oranga",
                    ),
                ),
                (
                    "vm_ink",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Exploring Indigenous Knowledge and RS&T. This exploratory theme aims to develop a body of knowledge, as a contribution to RS&T, at the interface between indigenous knowledge including mātauranga Māori – and research, science and technology.",
                        null=True,
                        verbose_name="Mātauranga",
                    ),
                ),
                (
                    "toa_basic",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Pure basic research",
                        null=True,
                        verbose_name="Basic",
                    ),
                ),
                (
                    "toa_experimental",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Experimental development",
                        null=True,
                        verbose_name="Experimental",
                    ),
                ),
                (
                    "toa_applied",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Applied research",
                        null=True,
                        verbose_name="Applied",
                    ),
                ),
                (
                    "toa_strategic",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Strategic basic research",
                        null=True,
                        verbose_name="Strategic",
                    ),
                ),
                (
                    "assessor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="portal.contract",
                    ),
                ),
                (
                    "schedule_entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="portal.reportingscheduleentry",
                    ),
                ),
            ],
            options={
                "db_table": "report",
            },
            bases=(portal.models.ReportMixin, common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ReportFor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("share", models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                (
                    "code",
                    models.ForeignKey(
                        db_column="code",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.fieldofresearch",
                        verbose_name="FoR",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_fors",
                        to="portal.report",
                    ),
                ),
            ],
            options={
                "verbose_name": "report FoR",
                "verbose_name_plural": "report FoRs",
                "db_table": "report_for",
                "unique_together": {("report", "code")},
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.AddField(
            model_name="report",
            name="fors",
            field=models.ManyToManyField(
                blank=True,
                related_name="reports",
                through="portal.ReportFor",
                to="portal.fieldofresearch",
                verbose_name="FoRs",
            ),
        ),
        migrations.CreateModel(
            name="ReportKeyword",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.keyword"
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.report"
                    ),
                ),
            ],
            options={
                "db_table": "report_keyword",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.AddField(
            model_name="report",
            name="keywords",
            field=models.ManyToManyField(
                blank=True,
                related_name="reports",
                through="portal.ReportKeyword",
                to="portal.keyword",
                verbose_name="Keywords",
            ),
        ),
        migrations.CreateModel(
            name="ReportSeo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("share", models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                (
                    "code",
                    models.ForeignKey(
                        db_column="code",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.socioeconomicobjective",
                        verbose_name="SEO",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_seos",
                        to="portal.report",
                    ),
                ),
            ],
            options={
                "verbose_name": "report SEO",
                "verbose_name_plural": "report SEOs",
                "db_table": "report_seo",
                "unique_together": {("report", "code")},
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.AddField(
            model_name="report",
            name="seos",
            field=models.ManyToManyField(
                blank=True,
                related_name="reports",
                through="portal.ReportSeo",
                to="portal.socioeconomicobjective",
                verbose_name="SEOs",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="report",
            unique_together={("contract", "period", "type")},
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisation",
            name="grid",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganisation",
            name="ro_email",
            field=common.models.EmailField(
                blank=True,
                help_text="Research office email address",
                max_length=254,
                null=True,
                verbose_name="RO email address",
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="grid",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="ro_email",
            field=common.models.EmailField(
                blank=True,
                help_text="Research office email address",
                max_length=254,
                null=True,
                verbose_name="RO email address",
            ),
        ),
    ]
