# Generated by Django 5.0.6 on 2024-07-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0050_historicalnomination_position_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalround",
            name="nomination_form_required",
            field=models.BooleanField(default=True, verbose_name="Nominion form required"),
        ),
        migrations.AddField(
            model_name="round",
            name="nomination_form_required",
            field=models.BooleanField(default=True, verbose_name="Nominion form required"),
        ),
    ]
