# Generated by Django 5.0.7 on 2024-07-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0051_historicalround_nomination_form_required_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="vm_rationane",
            new_name="vm_rationale",
        ),
        migrations.RenameField(
            model_name="historicalapplication",
            old_name="vm_rationane",
            new_name="vm_rationale",
        ),
        migrations.AlterField(
            model_name="historicalround",
            name="nomination_form_required",
            field=models.BooleanField(default=True, verbose_name="Nomination form required"),
        ),
        migrations.AlterField(
            model_name="round",
            name="nomination_form_required",
            field=models.BooleanField(default=True, verbose_name="Nomination form required"),
        ),
    ]
