# Generated by Django 5.0.7 on 2024-07-29 01:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0052_rename_vm_rationane_application_vm_rationale_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalround",
            name="testimonials_required",
            field=models.BooleanField(
                default=True,
                help_text="required submitted testimonials/referee reports",
                verbose_name="required submitted testimonials",
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="testimonials_required",
            field=models.BooleanField(
                default=True,
                help_text="required submitted testimonials/referee reports",
                verbose_name="required submitted testimonials",
            ),
        ),
        migrations.AlterField(
            model_name="historicalround",
            name="required_submitted_testimonials",
            field=models.BooleanField(
                default=True,
                help_text="required submitted testimonials or survey before submitting the applications",
                verbose_name="required submitted testimonials",
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="required_submitted_testimonials",
            field=models.BooleanField(
                default=True,
                help_text="required submitted testimonials or survey before submitting the applications",
                verbose_name="required submitted testimonials",
            ),
        ),
    ]
