# Generated by Django 5.0.7 on 2024-07-29 06:44

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0053_historicalround_testimonials_required_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalround",
            name="contact_email",
            field=common.models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="round contact email address"
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="contact_email",
            field=common.models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="round contact email address"
            ),
        ),
        migrations.AlterField(
            model_name="historicalround",
            name="testimonials_required",
            field=models.BooleanField(
                default=True,
                help_text="required testimonials/referee reports",
                verbose_name="testimonials required",
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="testimonials_required",
            field=models.BooleanField(
                default=True,
                help_text="required testimonials/referee reports",
                verbose_name="testimonials required",
            ),
        ),
        migrations.AddField(
            model_name="historicalround",
            name="limesurvey_server_url",
            field=models.CharField(
                blank=True, max_length=400, null=True, verbose_name="LimeSurvey URL"
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="limesurvey_server_url",
            field=models.CharField(
                blank=True, max_length=400, null=True, verbose_name="LimeSurvey URL"
            ),
        ),
    ]
