# Generated by Django 5.0.7 on 2024-07-31 05:21

import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0054_historicalround_contact_email_round_contact_email_and_more_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltestimonial",
            name="state_changed_at",
            field=model_utils.fields.MonitorField(monitor="state"),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="state_changed_at",
            field=model_utils.fields.MonitorField(monitor="state"),
        ),
    ]
