# Generated by Django 5.0.7 on 2024-08-07 01:01

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0055_historicaltestimonial_state_changed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalround",
            name="applicant_guidelines",
            field=models.URLField(
                blank=True,
                help_text="Applicant guidelines link URL",
                max_length=400,
                null=True,
                verbose_name="applicant guidelines",
            ),
        ),
        migrations.AddField(
            model_name="historicalround",
            name="panellist_guidelines",
            field=models.URLField(
                blank=True,
                help_text="Panellist guidelines link URL",
                max_length=400,
                null=True,
                verbose_name="panellist guidelines",
            ),
        ),
        migrations.AddField(
            model_name="historicalround",
            name="referee_guidelines",
            field=models.URLField(
                blank=True,
                help_text="Referee guidelines link URL",
                max_length=400,
                null=True,
                verbose_name="referee guidelines",
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="applicant_guidelines",
            field=models.URLField(
                blank=True,
                help_text="Applicant guidelines link URL",
                max_length=400,
                null=True,
                verbose_name="applicant guidelines",
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="panellist_guidelines",
            field=models.URLField(
                blank=True,
                help_text="Panellist guidelines link URL",
                max_length=400,
                null=True,
                verbose_name="panellist guidelines",
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="referee_guidelines",
            field=models.URLField(
                blank=True,
                help_text="Referee guidelines link URL",
                max_length=400,
                null=True,
                verbose_name="referee guidelines",
            ),
        ),
        migrations.AlterField(
            model_name="historicalround",
            name="colour",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                help_text="Colour used for text headers and back-grounds",
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
            ),
        ),
        migrations.AlterField(
            model_name="historicalround",
            name="guidelines",
            field=models.URLField(
                blank=True,
                help_text="Round guidelines link URL",
                max_length=400,
                null=True,
                verbose_name="round guidelines",
            ),
        ),
        migrations.AlterField(
            model_name="historicalround",
            name="limesurvey_server_url",
            field=models.URLField(
                blank=True,
                help_text="LimeSurvey Server URL",
                max_length=400,
                null=True,
                verbose_name="LimeSurvey URL",
            ),
        ),
        migrations.AlterField(
            model_name="historicalround",
            name="survey_id",
            field=models.PositiveIntegerField(
                blank=True, help_text="Referee LimeSurvey Survey ID", null=True
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="colour",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                help_text="Colour used for text headers and back-grounds",
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="guidelines",
            field=models.URLField(
                blank=True,
                help_text="Round guidelines link URL",
                max_length=400,
                null=True,
                verbose_name="round guidelines",
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="limesurvey_server_url",
            field=models.URLField(
                blank=True,
                help_text="LimeSurvey Server URL",
                max_length=400,
                null=True,
                verbose_name="LimeSurvey URL",
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="survey_id",
            field=models.PositiveIntegerField(
                blank=True, help_text="Referee LimeSurvey Survey ID", null=True
            ),
        ),
    ]
