# Generated by Django 5.0.7 on 2024-08-21 23:24

import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0056_historicalround_applicant_guidelines_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalround",
            name="testimonial_submission_closes_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Testimonial submission closes at"
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="testimonial_submission_closes_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Testimonial submission closes at"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="state",
            field=portal.models.StateField(
                choices=[
                    (None, None),
                    ("new", "new"),
                    ("draft", "draft"),
                    ("tac_accepted", "TAC accepted"),
                    ("in_review", "in referee review"),
                    ("submitted", "submitted"),
                    ("cancelled", "cancelled"),
                    ("withdrawn", "withdrawn"),
                    ("approved", "approved"),
                    ("accepted", "accepted"),
                    ("funded", "funded"),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                verbose_name="application state",
            ),
        ),
        migrations.AlterField(
            model_name="historicalapplication",
            name="state",
            field=portal.models.StateField(
                choices=[
                    (None, None),
                    ("new", "new"),
                    ("draft", "draft"),
                    ("tac_accepted", "TAC accepted"),
                    ("in_review", "in referee review"),
                    ("submitted", "submitted"),
                    ("cancelled", "cancelled"),
                    ("withdrawn", "withdrawn"),
                    ("approved", "approved"),
                    ("accepted", "accepted"),
                    ("funded", "funded"),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                verbose_name="application state",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreferee",
            name="state",
            field=portal.models.StateField(
                blank=True,
                choices=[
                    ("accepted", "accepted"),
                    ("bounced", "bounced"),
                    ("new", "new"),
                    ("opted_out", "opted out"),
                    ("sent", "sent"),
                    ("testified", "testified"),
                    (None, None),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                null=True,
                verbose_name="referee state",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltestimonial",
            name="state",
            field=portal.models.StateField(
                choices=[
                    (None, None),
                    ("new", "new"),
                    ("draft", "draft"),
                    ("submitted", "submitted"),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                verbose_name="testimonial state",
            ),
        ),
        migrations.AlterField(
            model_name="referee",
            name="state",
            field=portal.models.StateField(
                blank=True,
                choices=[
                    ("accepted", "accepted"),
                    ("bounced", "bounced"),
                    ("new", "new"),
                    ("opted_out", "opted out"),
                    ("sent", "sent"),
                    ("testified", "testified"),
                    (None, None),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                null=True,
                verbose_name="referee state",
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="state",
            field=portal.models.StateField(
                choices=[
                    (None, None),
                    ("new", "new"),
                    ("draft", "draft"),
                    ("submitted", "submitted"),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                verbose_name="testimonial state",
            ),
        ),
    ]
