# Generated by Django 5.0.7 on 2024-08-22 03:55

import common.models
import django.db.models.deletion
import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0057_historicalround_testimonial_submission_closes_at_and_more"),
        ("sites", "0004_auto_20210331_1418"),
    ]

    operations = [
        migrations.CreateModel(
            name="PanelDecision",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "number",
                    models.CharField(
                        db_column="number",
                        help_text="Application/proposal number",
                        max_length=24,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "grade",
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Grade%"),
                ),
                (
                    "decision",
                    common.models.FixedCharField(
                        choices=[
                            ("Y", "Yes, funded"),
                            ("N", "Not funded"),
                            ("R", "Reserve"),
                            ("I", "Ineligible"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "panel",
                    models.CharField(blank=True, max_length=3, null=True, verbose_name="panel"),
                ),
                ("rank", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "site",
                    models.ForeignKey(
                        default=common.models.Model.get_current_site_id,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "db_table": "panel_decision",
            },
            bases=(common.models.HelperMixin, models.Model),
            managers=[
                ("objects", portal.models.CurrentSiteManager()),
            ],
        ),
    ]
