# Generated by Django 5.1 on 2024-08-28 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0058_paneldecision"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreferee",
            name="org",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="portal.organisation",
                verbose_name="organisation",
            ),
        ),
        migrations.AddField(
            model_name="referee",
            name="org",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portal.organisation",
                verbose_name="organisation",
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisation",
            name="website",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="website",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
