# Generated by Django 5.1 on 2024-08-30 04:23

import common.models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import portal.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0059_historicalreferee_org_referee_org_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicationStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("code", models.CharField(db_index=True, max_length=3)),
                ("description", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name_plural": "publication statuses",
                "db_table": "publication_status",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PublicationType",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("code", models.CharField(max_length=10, primary_key=True, serialize=False)),
                ("code_2", models.CharField(blank=True, max_length=2, null=True, unique=True)),
                ("description", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "publication_type",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalReport",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("updated_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("period", models.PositiveSmallIntegerField(verbose_name="period")),
                (
                    "type",
                    common.models.FixedCharField(
                        choices=[
                            ("A", "Annual"),
                            ("E", "Exchange"),
                            ("F", "Final"),
                            ("I", "Interim"),
                            ("L", "Follow up"),
                        ],
                        help_text="Reporting Type",
                        max_length=1,
                    ),
                ),
                (
                    "state",
                    portal.models.StateField(
                        choices=[
                            ("accepted", "accepted"),
                            ("acknowledged", "acknowledged"),
                            ("approved", "approved"),
                            ("archived", "archived"),
                            ("cancelled", "cancelled"),
                            ("draft", "draft"),
                            ("new", "new"),
                            ("submitted", "submitted"),
                            ("reported", "reported"),
                        ],
                        default="new",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="state",
                    ),
                ),
                (
                    "reported_at",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="state",
                        when={"reported", "submitted"},
                    ),
                ),
                (
                    "assessed_at",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="state", when={"assessed"}
                    ),
                ),
                (
                    "vm_ecs",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Contributing to Economic Growth through Distinctive R&D. New Zealand needs its businesses and for-profit enterprises to perform at an optimum level and contribute to economic growth. This theme concerns the development of distinctive products, processes, systems and services from Māori knowledge, resources and people. Of particular interest are products that may be distinctive in the international marketplace.",
                        null=True,
                        verbose_name="Indigenous Innovation",
                    ),
                ),
                (
                    "vm_ens",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Achieving Environmental Sustainability through Iwi and Hapū relationships with land and sea. Like all communities, Māori communities aspire to live in sustainable communities dwelling in healthy environments. Much general environmental research is relevant to Māori. Distinctive environmental research arising in Māori communities relates to the expression of iwi and hapū knowledge, culture and experience – including Kaitiakitanga - in New Zealand land and seascapes.",
                        null=True,
                        verbose_name="Taiao",
                    ),
                ),
                (
                    "vm_hsw",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Improving Māori Health and Social Well-being. Distinctive challenges to Māori health and social well-being continue to arise within Māori communities disadvantaging them in relation to the general population. Research is needed to meet these ongoing needs.",
                        null=True,
                        verbose_name="Hauora/Oranga",
                    ),
                ),
                (
                    "vm_ink",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Exploring Indigenous Knowledge and RS&T. This exploratory theme aims to develop a body of knowledge, as a contribution to RS&T, at the interface between indigenous knowledge including mātauranga Māori – and research, science and technology.",
                        null=True,
                        verbose_name="Mātauranga",
                    ),
                ),
                (
                    "toa_basic",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Pure basic research",
                        null=True,
                        verbose_name="Basic",
                    ),
                ),
                (
                    "toa_experimental",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Experimental development",
                        null=True,
                        verbose_name="Experimental",
                    ),
                ),
                (
                    "toa_applied",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Applied research",
                        null=True,
                        verbose_name="Applied",
                    ),
                ),
                (
                    "toa_strategic",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Strategic basic research",
                        null=True,
                        verbose_name="Strategic",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "assessor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.contract",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schedule_entry",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.reportingscheduleentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical report",
                "verbose_name_plural": "historical reports",
                "db_table": "report_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(
                simple_history.models.HistoricalChanges,
                portal.models.ReportMixin,
                common.models.HelperMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="HistoricalReportedEffort",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("updated_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "fte",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Full-Time Equivalent",
                        max_digits=3,
                        verbose_name="FTE",
                    ),
                ),
                (
                    "state",
                    portal.models.StateField(
                        choices=[
                            ("accepted", "accepted"),
                            ("acknowledged", "acknowledged"),
                            ("approved", "approved"),
                            ("archived", "archived"),
                            ("cancelled", "cancelled"),
                            ("draft", "draft"),
                            ("new", "new"),
                            ("submitted", "submitted"),
                            ("reported", "reported"),
                        ],
                        default="new",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="state",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "planned_effort",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.contractmembereffort",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical reported effort",
                "verbose_name_plural": "historical reported efforts",
                "db_table": "reported_effort_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(
                simple_history.models.HistoricalChanges,
                portal.models.ReportedEffortMixin,
                common.models.HelperMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("period", models.PositiveSmallIntegerField(verbose_name="period")),
                (
                    "type",
                    common.models.FixedCharField(
                        choices=[
                            ("A", "Annual"),
                            ("E", "Exchange"),
                            ("F", "Final"),
                            ("I", "Interim"),
                            ("L", "Follow up"),
                        ],
                        help_text="Reporting Type",
                        max_length=1,
                    ),
                ),
                (
                    "state",
                    portal.models.StateField(
                        choices=[
                            ("accepted", "accepted"),
                            ("acknowledged", "acknowledged"),
                            ("approved", "approved"),
                            ("archived", "archived"),
                            ("cancelled", "cancelled"),
                            ("draft", "draft"),
                            ("new", "new"),
                            ("submitted", "submitted"),
                            ("reported", "reported"),
                        ],
                        default="new",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="state",
                    ),
                ),
                (
                    "reported_at",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="state",
                        when={"reported", "submitted"},
                    ),
                ),
                (
                    "assessed_at",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="state", when={"assessed"}
                    ),
                ),
                (
                    "vm_ecs",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Contributing to Economic Growth through Distinctive R&D. New Zealand needs its businesses and for-profit enterprises to perform at an optimum level and contribute to economic growth. This theme concerns the development of distinctive products, processes, systems and services from Māori knowledge, resources and people. Of particular interest are products that may be distinctive in the international marketplace.",
                        null=True,
                        verbose_name="Indigenous Innovation",
                    ),
                ),
                (
                    "vm_ens",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Achieving Environmental Sustainability through Iwi and Hapū relationships with land and sea. Like all communities, Māori communities aspire to live in sustainable communities dwelling in healthy environments. Much general environmental research is relevant to Māori. Distinctive environmental research arising in Māori communities relates to the expression of iwi and hapū knowledge, culture and experience – including Kaitiakitanga - in New Zealand land and seascapes.",
                        null=True,
                        verbose_name="Taiao",
                    ),
                ),
                (
                    "vm_hsw",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Improving Māori Health and Social Well-being. Distinctive challenges to Māori health and social well-being continue to arise within Māori communities disadvantaging them in relation to the general population. Research is needed to meet these ongoing needs.",
                        null=True,
                        verbose_name="Hauora/Oranga",
                    ),
                ),
                (
                    "vm_ink",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Exploring Indigenous Knowledge and RS&T. This exploratory theme aims to develop a body of knowledge, as a contribution to RS&T, at the interface between indigenous knowledge including mātauranga Māori – and research, science and technology.",
                        null=True,
                        verbose_name="Mātauranga",
                    ),
                ),
                (
                    "toa_basic",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Pure basic research",
                        null=True,
                        verbose_name="Basic",
                    ),
                ),
                (
                    "toa_experimental",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Experimental development",
                        null=True,
                        verbose_name="Experimental",
                    ),
                ),
                (
                    "toa_applied",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Applied research",
                        null=True,
                        verbose_name="Applied",
                    ),
                ),
                (
                    "toa_strategic",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Strategic basic research",
                        null=True,
                        verbose_name="Strategic",
                    ),
                ),
                (
                    "assessor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="portal.contract",
                    ),
                ),
                (
                    "schedule_entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="portal.reportingscheduleentry",
                    ),
                ),
            ],
            options={
                "db_table": "report",
            },
            bases=(portal.models.ReportMixin, common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "doi",
                    models.CharField(
                        blank=True,
                        help_text="Digital Object Identifier (DOI)",
                        max_length=400,
                        null=True,
                    ),
                ),
                ("rsnz_ref", models.IntegerField(blank=True, null=True)),
                ("status_date", models.DateField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=1000, null=True)),
                ("title2", models.CharField(blank=True, max_length=1000, null=True)),
                ("host", models.CharField(blank=True, max_length=100, null=True)),
                ("journal", models.CharField(blank=True, max_length=100, null=True)),
                ("publisher", models.CharField(blank=True, max_length=100, null=True)),
                ("editor", models.CharField(blank=True, max_length=100, null=True)),
                ("location", models.CharField(blank=True, max_length=60, null=True)),
                ("url", models.CharField(blank=True, max_length=150, null=True)),
                ("volume", models.CharField(blank=True, max_length=10, null=True)),
                ("year_ref", models.IntegerField(blank=True, null=True)),
                ("page_ref", models.CharField(blank=True, max_length=14, null=True)),
                ("host_ref", models.CharField(blank=True, max_length=10, null=True)),
                ("citations", models.IntegerField(blank=True, null=True)),
                ("citations_date", models.DateField(blank=True, null=True)),
                ("abstract", models.TextField(blank=True, null=True)),
                ("uid", models.CharField(blank=True, max_length=9, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("impact_factor", models.IntegerField(blank=True, null=True)),
                ("impact_year", models.IntegerField(blank=True, null=True)),
                ("xcr", models.FloatField(blank=True, null=True)),
                ("isi_loc", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        db_column="status",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="portal.publicationstatus",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        db_column="type",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portal.publicationtype",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publications",
                        to="portal.report",
                    ),
                ),
            ],
            options={
                "db_table": "publication",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ReportedEffort",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "fte",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Full-Time Equivalent",
                        max_digits=3,
                        verbose_name="FTE",
                    ),
                ),
                (
                    "state",
                    portal.models.StateField(
                        choices=[
                            ("accepted", "accepted"),
                            ("acknowledged", "acknowledged"),
                            ("approved", "approved"),
                            ("archived", "archived"),
                            ("cancelled", "cancelled"),
                            ("draft", "draft"),
                            ("new", "new"),
                            ("submitted", "submitted"),
                            ("reported", "reported"),
                        ],
                        default="new",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="state",
                    ),
                ),
                (
                    "planned_effort",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reported_efforts",
                        to="portal.contractmembereffort",
                    ),
                ),
            ],
            options={
                "db_table": "reported_effort",
            },
            bases=(portal.models.ReportedEffortMixin, common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ReportFor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("share", models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                (
                    "code",
                    models.ForeignKey(
                        db_column="code",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.fieldofresearch",
                        verbose_name="FoR",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_fors",
                        to="portal.report",
                    ),
                ),
            ],
            options={
                "verbose_name": "report FoR",
                "verbose_name_plural": "report FoRs",
                "db_table": "report_for",
                "unique_together": {("report", "code")},
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.AddField(
            model_name="report",
            name="fors",
            field=models.ManyToManyField(
                blank=True,
                related_name="reports",
                through="portal.ReportFor",
                to="portal.fieldofresearch",
                verbose_name="FoRs",
            ),
        ),
        migrations.CreateModel(
            name="ReportKeyword",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.keyword"
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.report"
                    ),
                ),
            ],
            options={
                "db_table": "report_keyword",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.AddField(
            model_name="report",
            name="keywords",
            field=models.ManyToManyField(
                blank=True,
                related_name="reports",
                through="portal.ReportKeyword",
                to="portal.keyword",
                verbose_name="Keywords",
            ),
        ),
        migrations.CreateModel(
            name="ReportSeo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("share", models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                (
                    "code",
                    models.ForeignKey(
                        db_column="code",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.socioeconomicobjective",
                        verbose_name="SEO",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_seos",
                        to="portal.report",
                    ),
                ),
            ],
            options={
                "verbose_name": "report SEO",
                "verbose_name_plural": "report SEOs",
                "db_table": "report_seo",
                "unique_together": {("report", "code")},
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.AddField(
            model_name="report",
            name="seos",
            field=models.ManyToManyField(
                blank=True,
                related_name="reports",
                through="portal.ReportSeo",
                to="portal.socioeconomicobjective",
                verbose_name="SEOs",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="report",
            unique_together={("contract", "period", "type")},
        ),
    ]
