# Generated by Django 5.1.2 on 2024-11-01 02:41

import common.models
import django.core.validators
import django.db.models.deletion
import model_utils.fields
import portal.models
import private_storage.fields
import private_storage.storage.files
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0059_historicalreferee_org_referee_org_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "doi",
                    models.CharField(
                        blank=True,
                        help_text="Digital Object Identifier (DOI)",
                        max_length=400,
                        null=True,
                    ),
                ),
                ("rsnz_ref", models.IntegerField(blank=True, null=True)),
                ("status_date", models.DateField(blank=True, null=True)),
                ("title", models.CharField(max_length=1000)),
                ("title2", models.CharField(blank=True, max_length=1000, null=True)),
                ("host", models.CharField(blank=True, max_length=100, null=True)),
                ("journal", models.CharField(blank=True, max_length=100, null=True)),
                ("publisher", models.CharField(blank=True, max_length=100, null=True)),
                ("editor", models.CharField(blank=True, max_length=100, null=True)),
                ("location", models.CharField(blank=True, max_length=60, null=True)),
                ("url", models.CharField(blank=True, max_length=150, null=True)),
                ("volume", models.CharField(blank=True, max_length=10, null=True)),
                ("year_ref", models.IntegerField(blank=True, null=True)),
                ("page_ref", models.CharField(blank=True, max_length=14, null=True)),
                ("host_ref", models.CharField(blank=True, max_length=10, null=True)),
                ("citations", models.IntegerField(blank=True, null=True)),
                ("citations_date", models.DateField(blank=True, null=True)),
                ("abstract", models.TextField(blank=True, null=True)),
                ("uid", models.CharField(blank=True, max_length=9, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("impact_factor", models.IntegerField(blank=True, null=True)),
                ("impact_year", models.IntegerField(blank=True, null=True)),
                ("xcr", models.FloatField(blank=True, null=True)),
                ("isi_loc", models.CharField(blank=True, max_length=50, null=True)),
                ("orcid", models.CharField(blank=True, editable=False, max_length=20, null=True)),
                (
                    "put_code",
                    models.PositiveIntegerField(
                        blank=True, editable=False, null=True, verbose_name="put-code"
                    ),
                ),
            ],
            options={
                "db_table": "publication",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PublicationStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("code", models.CharField(db_index=True, max_length=3)),
                ("description", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name_plural": "publication statuses",
                "db_table": "publication_status",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PublicationType",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("code", models.CharField(max_length=10, primary_key=True, serialize=False)),
                ("code_2", models.CharField(blank=True, max_length=2, null=True, unique=True)),
                ("description", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "orcid_type",
                    models.CharField(
                        blank=True,
                        help_text="ORCiD Work Type",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
            options={
                "db_table": "publication_type",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.RenameField(
            model_name="contract",
            old_name="involves_childeren",
            new_name="involves_children",
        ),
        migrations.RenameField(
            model_name="historicalcontract",
            old_name="involves_childeren",
            new_name="involves_children",
        ),
        migrations.AddField(
            model_name="address",
            name="region",
            field=models.CharField(
                blank=True,
                help_text="Region, State or County",
                max_length=100,
                null=True,
                verbose_name="region",
            ),
        ),
        migrations.AddField(
            model_name="historicaladdress",
            name="region",
            field=models.CharField(
                blank=True,
                help_text="Region, State or County",
                max_length=100,
                null=True,
                verbose_name="region",
            ),
        ),
        migrations.AddField(
            model_name="historicalround",
            name="report_template",
            field=models.TextField(
                blank=True,
                help_text="Research report template",
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "doc",
                            "docx",
                            "dot",
                            "dotx",
                            "docm",
                            "dotm",
                            "docb",
                            "odt",
                            "ott",
                            "oth",
                            "odm",
                            "rtf",
                            "tex",
                        ]
                    )
                ],
                verbose_name="Report Template",
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="report_template",
            field=models.FileField(
                blank=True,
                help_text="Research report template",
                null=True,
                upload_to=portal.models.round_template_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "doc",
                            "docx",
                            "dot",
                            "dotx",
                            "docm",
                            "dotm",
                            "docb",
                            "odt",
                            "ott",
                            "oth",
                            "odm",
                            "rtf",
                            "tex",
                        ]
                    )
                ],
                verbose_name="Report Template",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="middle_names",
            field=models.CharField(
                blank=True, max_length=280, null=True, verbose_name="middle names"
            ),
        ),
        migrations.AlterField(
            model_name="historicalapplication",
            name="middle_names",
            field=models.CharField(
                blank=True, max_length=280, null=True, verbose_name="middle names"
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvitation",
            name="middle_names",
            field=models.CharField(
                blank=True, max_length=280, null=True, verbose_name="middle names"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmember",
            name="middle_names",
            field=models.CharField(
                blank=True, max_length=280, null=True, verbose_name="middle names"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpanellist",
            name="middle_names",
            field=models.CharField(
                blank=True, max_length=280, null=True, verbose_name="middle names"
            ),
        ),
        migrations.AlterField(
            model_name="historicalperson",
            name="middle_names",
            field=models.CharField(
                blank=True, max_length=280, null=True, verbose_name="middle names"
            ),
        ),
        migrations.AlterField(
            model_name="historicalreferee",
            name="middle_names",
            field=models.CharField(
                blank=True, max_length=280, null=True, verbose_name="middle names"
            ),
        ),
        migrations.AlterField(
            model_name="historicaltestimonial",
            name="file",
            field=models.TextField(
                blank=True,
                help_text="Please upload your endorsement, testimonial, or feedback",
                max_length=200,
                null=True,
                verbose_name="endorsement, testimonial, or feedback",
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="middle_names",
            field=models.CharField(
                blank=True, max_length=280, null=True, verbose_name="middle names"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="middle_names",
            field=models.CharField(
                blank=True, max_length=280, null=True, verbose_name="middle names"
            ),
        ),
        migrations.AlterField(
            model_name="panellist",
            name="middle_names",
            field=models.CharField(
                blank=True, max_length=280, null=True, verbose_name="middle names"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="middle_names",
            field=models.CharField(
                blank=True, max_length=280, null=True, verbose_name="middle names"
            ),
        ),
        migrations.AlterField(
            model_name="personpersonidentifier",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="person_identifiers",
                to="portal.person",
            ),
        ),
        migrations.AlterField(
            model_name="referee",
            name="middle_names",
            field=models.CharField(
                blank=True, max_length=280, null=True, verbose_name="middle names"
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="file",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                help_text="Please upload your endorsement, testimonial, or feedback",
                max_length=200,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="testimonials",
                verbose_name="endorsement, testimonial, or feedback",
            ),
        ),
        migrations.CreateModel(
            name="ContractCommentRecipient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("email", common.models.EmailField(max_length=200)),
                ("is_cced", models.BooleanField(default=False)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="portal.contractcomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "recipient",
                "db_table": "contract_comment_recipient",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalReport",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("updated_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("period", models.PositiveSmallIntegerField(verbose_name="period")),
                (
                    "type",
                    common.models.FixedCharField(
                        choices=[
                            ("A", "Annual"),
                            ("E", "Exchange"),
                            ("F", "Final"),
                            ("I", "Interim"),
                            ("L", "Follow up"),
                        ],
                        help_text="Reporting Type",
                        max_length=1,
                    ),
                ),
                (
                    "state",
                    portal.models.StateField(
                        choices=[
                            ("accepted", "accepted"),
                            ("acknowledged", "acknowledged"),
                            ("approved", "approved"),
                            ("assessed", "assessed"),
                            ("archived", "archived"),
                            ("cancelled", "cancelled"),
                            ("draft", "draft"),
                            ("new", "new"),
                            ("submitted", "submitted"),
                            ("reported", "reported"),
                        ],
                        default="new",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="state",
                    ),
                ),
                (
                    "file",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "doc",
                                    "docx",
                                    "dot",
                                    "dotx",
                                    "docm",
                                    "dotm",
                                    "docb",
                                    "odt",
                                    "ott",
                                    "oth",
                                    "odm",
                                    "rtf",
                                    "tex",
                                ]
                            )
                        ],
                        verbose_name="Completed research report",
                    ),
                ),
                ("assessment", models.TextField(blank=True, null=True)),
                (
                    "reported_at",
                    model_utils.fields.MonitorField(
                        blank=True,
                        default=None,
                        monitor="state",
                        null=True,
                        when={"reported", "submitted"},
                    ),
                ),
                (
                    "assessed_at",
                    model_utils.fields.MonitorField(
                        blank=True, default=None, monitor="state", null=True, when={"assessed"}
                    ),
                ),
                (
                    "vm_ecs",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Contributing to Economic Growth through Distinctive R&D. New Zealand needs its businesses and for-profit enterprises to perform at an optimum level and contribute to economic growth. This theme concerns the development of distinctive products, processes, systems and services from Māori knowledge, resources and people. Of particular interest are products that may be distinctive in the international marketplace.",
                        null=True,
                        verbose_name="Indigenous Innovation",
                    ),
                ),
                (
                    "vm_ens",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Achieving Environmental Sustainability through Iwi and Hapū relationships with land and sea. Like all communities, Māori communities aspire to live in sustainable communities dwelling in healthy environments. Much general environmental research is relevant to Māori. Distinctive environmental research arising in Māori communities relates to the expression of iwi and hapū knowledge, culture and experience – including Kaitiakitanga - in New Zealand land and seascapes.",
                        null=True,
                        verbose_name="Taiao",
                    ),
                ),
                (
                    "vm_hsw",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Improving Māori Health and Social Well-being. Distinctive challenges to Māori health and social well-being continue to arise within Māori communities disadvantaging them in relation to the general population. Research is needed to meet these ongoing needs.",
                        null=True,
                        verbose_name="Hauora/Oranga",
                    ),
                ),
                (
                    "vm_ink",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Exploring Indigenous Knowledge and RS&T. This exploratory theme aims to develop a body of knowledge, as a contribution to RS&T, at the interface between indigenous knowledge including mātauranga Māori – and research, science and technology.",
                        null=True,
                        verbose_name="Mātauranga",
                    ),
                ),
                (
                    "toa_basic",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Pure basic research",
                        null=True,
                        verbose_name="Basic",
                    ),
                ),
                (
                    "toa_experimental",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Experimental development",
                        null=True,
                        verbose_name="Experimental",
                    ),
                ),
                (
                    "toa_applied",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Applied research",
                        null=True,
                        verbose_name="Applied",
                    ),
                ),
                (
                    "toa_strategic",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Strategic basic research",
                        null=True,
                        verbose_name="Strategic",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "assessor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.contract",
                    ),
                ),
                (
                    "converted_file",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.convertedfile",
                        verbose_name="converted file",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schedule_entry",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.reportingscheduleentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical report",
                "verbose_name_plural": "historical reports",
                "db_table": "report_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(
                simple_history.models.HistoricalChanges,
                portal.models.ReportMixin,
                common.models.HelperMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="PerformanceFlag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ordering", models.PositiveIntegerField(default=0, verbose_name="ordering")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=400)),
                (
                    "value_choices",
                    models.CharField(
                        blank=True,
                        help_text="given in the format: 'VALUE1:DESCRIPTION1;VALUE2:DESCRIPTION2;...', otherwise it is 'YES' or 'NO'",
                        max_length=400,
                        null=True,
                    ),
                ),
                ("is_optional", models.BooleanField(default=True)),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_flags",
                        to="portal.round",
                    ),
                ),
            ],
            options={
                "db_table": "performance_flag",
                "ordering": ["ordering"],
                "abstract": False,
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PublicationAuthor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=400)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("PRIMARY", "PRIMARY"), ("SECONDARY", "SECONDARY")],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authors",
                        to="portal.publication",
                    ),
                ),
            ],
            options={
                "db_table": "publication_author",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PublicationLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("link", models.URLField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("LINK", "LINK"), ("URL", "URL"), ("ATTACHMENT", "ATTACHMENT")],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="portal.publication",
                    ),
                ),
            ],
            options={
                "db_table": "publication_link",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.AddField(
            model_name="publication",
            name="status",
            field=models.ForeignKey(
                blank=True,
                db_column="status",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="portal.publicationstatus",
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="type",
            field=models.ForeignKey(
                blank=True,
                db_column="type",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portal.publicationtype",
            ),
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("period", models.PositiveSmallIntegerField(verbose_name="period")),
                (
                    "type",
                    common.models.FixedCharField(
                        choices=[
                            ("A", "Annual"),
                            ("E", "Exchange"),
                            ("F", "Final"),
                            ("I", "Interim"),
                            ("L", "Follow up"),
                        ],
                        help_text="Reporting Type",
                        max_length=1,
                    ),
                ),
                (
                    "state",
                    portal.models.StateField(
                        choices=[
                            ("accepted", "accepted"),
                            ("acknowledged", "acknowledged"),
                            ("approved", "approved"),
                            ("assessed", "assessed"),
                            ("archived", "archived"),
                            ("cancelled", "cancelled"),
                            ("draft", "draft"),
                            ("new", "new"),
                            ("submitted", "submitted"),
                            ("reported", "reported"),
                        ],
                        default="new",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="state",
                    ),
                ),
                (
                    "file",
                    private_storage.fields.PrivateFileField(
                        blank=True,
                        null=True,
                        storage=private_storage.storage.files.PrivateFileSystemStorage(),
                        upload_to="reports",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "doc",
                                    "docx",
                                    "dot",
                                    "dotx",
                                    "docm",
                                    "dotm",
                                    "docb",
                                    "odt",
                                    "ott",
                                    "oth",
                                    "odm",
                                    "rtf",
                                    "tex",
                                ]
                            )
                        ],
                        verbose_name="Completed research report",
                    ),
                ),
                ("assessment", models.TextField(blank=True, null=True)),
                (
                    "reported_at",
                    model_utils.fields.MonitorField(
                        blank=True,
                        default=None,
                        monitor="state",
                        null=True,
                        when={"reported", "submitted"},
                    ),
                ),
                (
                    "assessed_at",
                    model_utils.fields.MonitorField(
                        blank=True, default=None, monitor="state", null=True, when={"assessed"}
                    ),
                ),
                (
                    "vm_ecs",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Contributing to Economic Growth through Distinctive R&D. New Zealand needs its businesses and for-profit enterprises to perform at an optimum level and contribute to economic growth. This theme concerns the development of distinctive products, processes, systems and services from Māori knowledge, resources and people. Of particular interest are products that may be distinctive in the international marketplace.",
                        null=True,
                        verbose_name="Indigenous Innovation",
                    ),
                ),
                (
                    "vm_ens",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Achieving Environmental Sustainability through Iwi and Hapū relationships with land and sea. Like all communities, Māori communities aspire to live in sustainable communities dwelling in healthy environments. Much general environmental research is relevant to Māori. Distinctive environmental research arising in Māori communities relates to the expression of iwi and hapū knowledge, culture and experience – including Kaitiakitanga - in New Zealand land and seascapes.",
                        null=True,
                        verbose_name="Taiao",
                    ),
                ),
                (
                    "vm_hsw",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Improving Māori Health and Social Well-being. Distinctive challenges to Māori health and social well-being continue to arise within Māori communities disadvantaging them in relation to the general population. Research is needed to meet these ongoing needs.",
                        null=True,
                        verbose_name="Hauora/Oranga",
                    ),
                ),
                (
                    "vm_ink",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Exploring Indigenous Knowledge and RS&T. This exploratory theme aims to develop a body of knowledge, as a contribution to RS&T, at the interface between indigenous knowledge including mātauranga Māori – and research, science and technology.",
                        null=True,
                        verbose_name="Mātauranga",
                    ),
                ),
                (
                    "toa_basic",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Pure basic research",
                        null=True,
                        verbose_name="Basic",
                    ),
                ),
                (
                    "toa_experimental",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Experimental development",
                        null=True,
                        verbose_name="Experimental",
                    ),
                ),
                (
                    "toa_applied",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Applied research",
                        null=True,
                        verbose_name="Applied",
                    ),
                ),
                (
                    "toa_strategic",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Strategic basic research",
                        null=True,
                        verbose_name="Strategic",
                    ),
                ),
                (
                    "assessor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="portal.contract",
                    ),
                ),
                (
                    "converted_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portal.convertedfile",
                        verbose_name="converted file",
                    ),
                ),
                (
                    "publications",
                    models.ManyToManyField(
                        blank=True,
                        db_table="report_publication",
                        related_name="reports",
                        to="portal.publication",
                    ),
                ),
                (
                    "schedule_entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="portal.reportingscheduleentry",
                    ),
                ),
            ],
            options={
                "db_table": "report",
            },
            bases=(
                portal.models.ReportMixin,
                portal.models.PdfFileMixin,
                common.models.HelperMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="HistoricalReportedFunding",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("updated_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("orcid", models.CharField(blank=True, editable=False, max_length=20, null=True)),
                (
                    "put_code",
                    models.PositiveIntegerField(
                        blank=True, editable=False, null=True, verbose_name="put-code"
                    ),
                ),
                (
                    "state",
                    portal.models.StateField(
                        choices=[
                            ("accepted", "accepted"),
                            ("acknowledged", "acknowledged"),
                            ("approved", "approved"),
                            ("application", "application"),
                            ("archived", "archived"),
                            ("cancelled", "cancelled"),
                            ("draft", "draft"),
                            ("new", "new"),
                            ("submitted", "submitted"),
                        ],
                        default="new",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "type",
                    common.models.FixedCharField(
                        choices=[
                            ("A", "Award"),
                            ("C", "Contract"),
                            ("G", "Grant"),
                            ("S", "Salary award"),
                        ],
                        help_text="Funding Type",
                        max_length=1,
                        verbose_name="Type",
                    ),
                ),
                (
                    "subtype",
                    models.CharField(
                        blank=True,
                        help_text="Funding subtype",
                        max_length=100,
                        null=True,
                        verbose_name="Subtype",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Title of funded project",
                        max_length=400,
                        null=True,
                        verbose_name="Project",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, help_text="Project link URL", max_length=400, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total funding amount",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "share",
                    models.PositiveSmallIntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Share available",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "agency",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.organisation",
                        verbose_name="Funding agency",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        db_column="currency",
                        db_constraint=False,
                        default="NZD",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.currency",
                        verbose_name="Funding currency",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.report",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical reported funding",
                "verbose_name_plural": "historical reported fundings",
                "db_table": "reported_funding_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(
                simple_history.models.HistoricalChanges,
                portal.models.ReportedFundingMixin,
                common.models.HelperMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="HistoricalReportedEffort",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("updated_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=400, null=True, verbose_name="person name"
                    ),
                ),
                (
                    "fte",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Full-Time Equivalent from the contract",
                        max_digits=3,
                        null=True,
                        verbose_name="FTE",
                    ),
                ),
                (
                    "total_fte",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total Full-Time Equivalent",
                        max_digits=3,
                        null=True,
                        verbose_name="Total FTE",
                    ),
                ),
                (
                    "state",
                    portal.models.StateField(
                        choices=[
                            ("accepted", "accepted"),
                            ("acknowledged", "acknowledged"),
                            ("approved", "approved"),
                            ("archived", "archived"),
                            ("cancelled", "cancelled"),
                            ("draft", "draft"),
                            ("new", "new"),
                            ("submitted", "submitted"),
                            ("reported", "reported"),
                        ],
                        default="new",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="state",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member_effort",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.contractmembereffort",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.person",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        db_column="role",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.roletype",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.report",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical reported effort",
                "verbose_name_plural": "historical reported efforts",
                "db_table": "reported_effort_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(
                simple_history.models.HistoricalChanges,
                portal.models.ReportedEffortMixin,
                common.models.HelperMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="HistoricalAssessedPerformance",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("updated_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("value", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "comment",
                    models.TextField(
                        blank=True, max_length=1000, null=True, verbose_name="Comment"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "flag",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.performanceflag",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.report",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical assessed performance",
                "verbose_name_plural": "historical assessed performances",
                "db_table": "assessed_performance_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="AssessedPerformance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("value", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "comment",
                    models.TextField(
                        blank=True, max_length=1000, null=True, verbose_name="Comment"
                    ),
                ),
                (
                    "flag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.performanceflag"
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance",
                        to="portal.report",
                    ),
                ),
            ],
            options={
                "db_table": "assessed_performance",
                "ordering": ["flag__ordering"],
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ReportComment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "token",
                    models.CharField(
                        default=portal.models.get_unique_invitation_token,
                        max_length=42,
                        unique=True,
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, max_length=1000, null=True, verbose_name="comment"
                    ),
                ),
                (
                    "attachment",
                    private_storage.fields.PrivateFileField(
                        blank=True,
                        null=True,
                        storage=private_storage.storage.files.PrivateFileSystemStorage(),
                        upload_to="reports",
                        verbose_name="attachment",
                    ),
                ),
                (
                    "category",
                    common.models.FixedCharField(
                        blank=True,
                        choices=[("R", "Risk of variation"), ("O", "Other")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("alert_date", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="portal.reportcomment",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="portal.report",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="submitted by",
                    ),
                ),
            ],
            options={
                "verbose_name": "comment",
                "db_table": "report_comment",
                "ordering": ["-id"],
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ReportCommentAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "attachment",
                    private_storage.fields.PrivateFileField(
                        blank=True,
                        null=True,
                        storage=private_storage.storage.files.PrivateFileSystemStorage(),
                        upload_to="reports",
                        verbose_name="attachment",
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="portal.reportcomment",
                    ),
                ),
            ],
            options={
                "verbose_name": "attachment",
                "db_table": "report_comment_attachment",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ReportCommentRecipient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("email", common.models.EmailField(max_length=200)),
                ("is_cced", models.BooleanField(default=False)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="portal.reportcomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "recipient",
                "db_table": "report_comment_recipient",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ReportedEffort",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=400, null=True, verbose_name="person name"
                    ),
                ),
                (
                    "fte",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Full-Time Equivalent from the contract",
                        max_digits=3,
                        null=True,
                        verbose_name="FTE",
                    ),
                ),
                (
                    "total_fte",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total Full-Time Equivalent",
                        max_digits=3,
                        null=True,
                        verbose_name="Total FTE",
                    ),
                ),
                (
                    "state",
                    portal.models.StateField(
                        choices=[
                            ("accepted", "accepted"),
                            ("acknowledged", "acknowledged"),
                            ("approved", "approved"),
                            ("archived", "archived"),
                            ("cancelled", "cancelled"),
                            ("draft", "draft"),
                            ("new", "new"),
                            ("submitted", "submitted"),
                            ("reported", "reported"),
                        ],
                        default="new",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="state",
                    ),
                ),
                (
                    "member_effort",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_efforts",
                        to="portal.contractmembereffort",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_efforts",
                        to="portal.person",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="efforts",
                        to="portal.report",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        db_column="role",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="portal.roletype",
                    ),
                ),
            ],
            options={
                "db_table": "reported_effort",
            },
            bases=(portal.models.ReportedEffortMixin, common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ReportedCollaboration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("orcid", models.CharField(blank=True, editable=False, max_length=20, null=True)),
                (
                    "put_code",
                    models.PositiveIntegerField(
                        blank=True, editable=False, null=True, verbose_name="put-code"
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True, verbose_name="start date")),
                ("end_date", models.DateField(blank=True, null=True, verbose_name="end date")),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=2000, null=True, verbose_name="description"
                    ),
                ),
                (
                    "organisation",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="organisation"
                    ),
                ),
                ("full_name", models.CharField(max_length=400, verbose_name="collaborator")),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        db_column="country",
                        default="NZ",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="portal.country",
                        verbose_name="country",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portal.organisation",
                        verbose_name="organisation",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="portal.person",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborations",
                        to="portal.report",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portal.reportedeffort",
                    ),
                ),
            ],
            options={
                "db_table": "reported_collaboration",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ReportedAward",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("orcid", models.CharField(blank=True, editable=False, max_length=20, null=True)),
                (
                    "put_code",
                    models.PositiveIntegerField(
                        blank=True, editable=False, null=True, verbose_name="put-code"
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True, verbose_name="start date")),
                ("end_date", models.DateField(blank=True, null=True, verbose_name="end date")),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=2000, null=True, verbose_name="description"
                    ),
                ),
                (
                    "organisation",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="organisation"
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portal.organisation",
                        verbose_name="organisation",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="portal.report",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portal.reportedeffort",
                    ),
                ),
            ],
            options={
                "db_table": "reported_award",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ReportedFunding",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("orcid", models.CharField(blank=True, editable=False, max_length=20, null=True)),
                (
                    "put_code",
                    models.PositiveIntegerField(
                        blank=True, editable=False, null=True, verbose_name="put-code"
                    ),
                ),
                (
                    "state",
                    portal.models.StateField(
                        choices=[
                            ("accepted", "accepted"),
                            ("acknowledged", "acknowledged"),
                            ("approved", "approved"),
                            ("application", "application"),
                            ("archived", "archived"),
                            ("cancelled", "cancelled"),
                            ("draft", "draft"),
                            ("new", "new"),
                            ("submitted", "submitted"),
                        ],
                        default="new",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "type",
                    common.models.FixedCharField(
                        choices=[
                            ("A", "Award"),
                            ("C", "Contract"),
                            ("G", "Grant"),
                            ("S", "Salary award"),
                        ],
                        help_text="Funding Type",
                        max_length=1,
                        verbose_name="Type",
                    ),
                ),
                (
                    "subtype",
                    models.CharField(
                        blank=True,
                        help_text="Funding subtype",
                        max_length=100,
                        null=True,
                        verbose_name="Subtype",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Title of funded project",
                        max_length=400,
                        null=True,
                        verbose_name="Project",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, help_text="Project link URL", max_length=400, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total funding amount",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "share",
                    models.PositiveSmallIntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Share available",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "agency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portal.organisation",
                        verbose_name="Funding agency",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        db_column="currency",
                        default="NZD",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portal.currency",
                        verbose_name="Funding currency",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fundings",
                        to="portal.report",
                    ),
                ),
            ],
            options={
                "db_table": "reported_funding",
            },
            bases=(portal.models.ReportedFundingMixin, common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ReportedPublicity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("orcid", models.CharField(blank=True, editable=False, max_length=20, null=True)),
                (
                    "put_code",
                    models.PositiveIntegerField(
                        blank=True, editable=False, null=True, verbose_name="put-code"
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True, verbose_name="start date")),
                ("end_date", models.DateField(blank=True, null=True, verbose_name="end date")),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=2000, null=True, verbose_name="description"
                    ),
                ),
                (
                    "organisation",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="organisation"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portal.reportedeffort",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portal.organisation",
                        verbose_name="organisation",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publicities",
                        to="portal.report",
                    ),
                ),
            ],
            options={
                "db_table": "reported_publicity",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ReportedVisit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("orcid", models.CharField(blank=True, editable=False, max_length=20, null=True)),
                (
                    "put_code",
                    models.PositiveIntegerField(
                        blank=True, editable=False, null=True, verbose_name="put-code"
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True, verbose_name="start date")),
                ("end_date", models.DateField(blank=True, null=True, verbose_name="end date")),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=2000, null=True, verbose_name="description"
                    ),
                ),
                (
                    "organisation",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="organisation"
                    ),
                ),
                ("full_name", models.CharField(max_length=400, verbose_name="host")),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        db_column="country",
                        default="NZ",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="portal.country",
                        verbose_name="country",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portal.reportedeffort",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portal.organisation",
                        verbose_name="organisation",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="portal.person",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="portal.report",
                    ),
                ),
            ],
            options={
                "db_table": "reported_visit",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ReportFor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("share", models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                (
                    "code",
                    models.ForeignKey(
                        db_column="code",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.fieldofresearch",
                        verbose_name="FoR",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_fors",
                        to="portal.report",
                    ),
                ),
            ],
            options={
                "verbose_name": "report FoR",
                "verbose_name_plural": "report FoRs",
                "db_table": "report_for",
                "unique_together": {("report", "code")},
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.AddField(
            model_name="report",
            name="fors",
            field=models.ManyToManyField(
                blank=True,
                related_name="reports",
                through="portal.ReportFor",
                to="portal.fieldofresearch",
                verbose_name="FoRs",
            ),
        ),
        migrations.CreateModel(
            name="ReportKeyword",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.keyword"
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.report"
                    ),
                ),
            ],
            options={
                "db_table": "report_keyword",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.AddField(
            model_name="report",
            name="keywords",
            field=models.ManyToManyField(
                blank=True,
                related_name="reports",
                through="portal.ReportKeyword",
                to="portal.keyword",
                verbose_name="Keywords",
            ),
        ),
        migrations.CreateModel(
            name="ReportSeo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("share", models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                (
                    "code",
                    models.ForeignKey(
                        db_column="code",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.socioeconomicobjective",
                        verbose_name="SEO",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_seos",
                        to="portal.report",
                    ),
                ),
            ],
            options={
                "verbose_name": "report SEO",
                "verbose_name_plural": "report SEOs",
                "db_table": "report_seo",
                "unique_together": {("report", "code")},
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.AddField(
            model_name="report",
            name="seos",
            field=models.ManyToManyField(
                blank=True,
                related_name="reports",
                through="portal.ReportSeo",
                to="portal.socioeconomicobjective",
                verbose_name="SEOs",
            ),
        ),
        migrations.CreateModel(
            name="RisPublicationType",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "code",
                    models.CharField(
                        db_column="code",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name='Abbreviation ("Field Label")',
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name='Type ("Ref Type")'
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Category"
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        db_column="type",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portal.publicationtype",
                    ),
                ),
            ],
            options={
                "db_table": "ris_publication_type",
                "db_table_comment": "RIS reference types (https://en.wikipedia.org/wiki/RIS_(file_format))",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.AddField(
            model_name="publication",
            name="ris_type",
            field=models.ForeignKey(
                blank=True,
                db_column="ris_type",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portal.rispublicationtype",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="report",
            unique_together={("contract", "period", "type")},
        ),
    ]
