# Generated by Django 5.1.3 on 2024-11-07 22:37

import common.models
import django.core.validators
import django.db.models.deletion
import model_utils.fields
import portal.migration_utils
import private_storage.fields
import private_storage.storage.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0060_publication_publicationstatus_publicationtype_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ContractClause",
            new_name="RoundContractClause",
        ),
        migrations.AlterUniqueTogether(
            name="allocation",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="allocation",
            name="details",
            field=models.CharField(
                blank=True,
                help_text="Eg, on the 2nd Businees Day after the 20th day of each  month, or receipt of the 2024 interim / final report.",
                max_length=1000,
                null=True,
                verbose_name="Payment details",
            ),
        ),
        migrations.AddField(
            model_name="allocation",
            name="purpose",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="Purpose of Funding"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="cover",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="contracts",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "html",
                            "pdf",
                            "fodt",
                            "odt",
                            "ott",
                            "oth",
                            "odm",
                            "doc",
                            "docx",
                            "docm",
                            "docb",
                        ]
                    )
                ],
                verbose_name="Cover page",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="preamble",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="contracts",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "html",
                            "pdf",
                            "fodt",
                            "odt",
                            "ott",
                            "oth",
                            "odm",
                            "doc",
                            "docx",
                            "docm",
                            "docb",
                        ]
                    )
                ],
                verbose_name="Contract Preamble",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="schedule1",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="contracts",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "html",
                            "pdf",
                            "fodt",
                            "odt",
                            "ott",
                            "oth",
                            "odm",
                            "doc",
                            "docx",
                            "docm",
                            "docb",
                        ]
                    )
                ],
                verbose_name="Schedule 1",
            ),
        ),
        migrations.AddField(
            model_name="historicalallocation",
            name="details",
            field=models.CharField(
                blank=True,
                help_text="Eg, on the 2nd Businees Day after the 20th day of each  month, or receipt of the 2024 interim / final report.",
                max_length=1000,
                null=True,
                verbose_name="Payment details",
            ),
        ),
        migrations.AddField(
            model_name="historicalallocation",
            name="purpose",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="Purpose of Funding"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="cover",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "html",
                            "pdf",
                            "fodt",
                            "odt",
                            "ott",
                            "oth",
                            "odm",
                            "doc",
                            "docx",
                            "docm",
                            "docb",
                        ]
                    )
                ],
                verbose_name="Cover page",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="preamble",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "html",
                            "pdf",
                            "fodt",
                            "odt",
                            "ott",
                            "oth",
                            "odm",
                            "doc",
                            "docx",
                            "docm",
                            "docb",
                        ]
                    )
                ],
                verbose_name="Contract Preamble",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="schedule1",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "html",
                            "pdf",
                            "fodt",
                            "odt",
                            "ott",
                            "oth",
                            "odm",
                            "doc",
                            "docx",
                            "docm",
                            "docb",
                        ]
                    )
                ],
                verbose_name="Schedule 1",
            ),
        ),
        migrations.AddField(
            model_name="requiredcontractdocument",
            name="format",
            field=models.CharField(
                choices=[("I", "Image"), ("S", "Spreadsheet"), ("T", "Text"), ("-", "N/A")],
                default="-",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="requiredcontractdocument",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AB", "Award Budget"),
                    ("AF", "Application Form"),
                    ("AIMS", "Research Aims"),
                    ("B", "Budget"),
                    ("CV", "Curriculum Vitae"),
                    ("E", "Ethics Statement"),
                    ("F", "Form"),
                    ("HS", "Host Suitablity"),
                    ("PB", "Proposal Budget"),
                    ("PT", "Project Timeline"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="requireddocument",
            name="format",
            field=models.CharField(
                choices=[("I", "Image"), ("S", "Spreadsheet"), ("T", "Text"), ("-", "N/A")],
                default="-",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="requireddocument",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AB", "Award Budget"),
                    ("AF", "Application Form"),
                    ("AIMS", "Research Aims"),
                    ("B", "Budget"),
                    ("CV", "Curriculum Vitae"),
                    ("E", "Ethics Statement"),
                    ("F", "Form"),
                    ("HS", "Host Suitablity"),
                    ("PB", "Proposal Budget"),
                    ("PT", "Project Timeline"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="allocation",
            name="allocation",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Amouint of funding (GST excl.)",
                max_digits=15,
                verbose_name="allocation",
            ),
        ),
        migrations.AlterField(
            model_name="contractdocument",
            name="file",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="contracts",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "csv",
                            "ctv",
                            "doc",
                            "docb",
                            "docm",
                            "docx",
                            "fdot",
                            "dot",
                            "dotm",
                            "dotx",
                            "odm",
                            "odt",
                            "fodt",
                            "oth",
                            "ott",
                            "pdf",
                            "rtf",
                            "tex",
                            "xls",
                            "xlsb",
                            "xlsm",
                            "xlsx",
                            "xlt",
                            "xltm",
                            "xltx",
                            "xlw",
                            "xml",
                        ]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historicalallocation",
            name="allocation",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Amouint of funding (GST excl.)",
                max_digits=15,
                verbose_name="allocation",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontractdocument",
            name="file",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "csv",
                            "ctv",
                            "doc",
                            "docb",
                            "docm",
                            "docx",
                            "fdot",
                            "dot",
                            "dotm",
                            "dotx",
                            "odm",
                            "odt",
                            "fodt",
                            "oth",
                            "ott",
                            "pdf",
                            "rtf",
                            "tex",
                            "xls",
                            "xlsb",
                            "xlsm",
                            "xlsx",
                            "xlt",
                            "xltm",
                            "xltx",
                            "xlw",
                            "xml",
                        ]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="requireddocument",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="requireddocument",
            name="title_en",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="requireddocument",
            name="title_mi",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Title"),
        ),
        migrations.AlterModelTable(
            name="roundcontractclause",
            table="round_contract_clause",
        ),
        migrations.CreateModel(
            name="ContractClause",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ordering", models.PositiveIntegerField(default=0, verbose_name="ordering")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "type",
                    common.models.FixedCharField(
                        choices=[("A", "Addition"), ("V", "Variation")],
                        max_length=1,
                        verbose_name="Type",
                    ),
                ),
                ("clause", models.CharField(max_length=100, verbose_name="Clause Number")),
                ("term", models.TextField(max_length=2000, verbose_name="Term")),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clauses",
                        to="portal.contract",
                    ),
                ),
            ],
            options={
                "db_table": "contract_clause",
                "ordering": ["ordering"],
                "abstract": False,
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.RunPython(
            code=portal.migration_utils.set_required_document_format_and_role,
            reverse_code=portal.migration_utils.dummy,
        ),
    ]
