# Generated by Django 5.1.2 on 2024-10-21 00:36

import common.models
import django.db.models.deletion
import model_utils.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0060_publicationstatus_publicationtype_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceFlag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ordering", models.PositiveIntegerField(default=0, verbose_name="ordering")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=400)),
                (
                    "value_choices",
                    models.CharField(
                        help_text="given in the format: 'VALUE1:DESCRIPTION1;VALUE2:DESCRIPTION2;...'",
                        max_length=400,
                    ),
                ),
                ("is_optional", models.BooleanField(default=True)),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_flags",
                        to="portal.round",
                    ),
                ),
            ],
            options={
                "db_table": "performance_flag",
                "ordering": ["ordering"],
                "abstract": False,
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAssessedPerformance",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("updated_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("value", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "comment",
                    models.TextField(
                        blank=True, max_length=1000, null=True, verbose_name="Comment"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "flag",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="portal.performanceflag",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical assessed performance",
                "verbose_name_plural": "historical assessed performances",
                "db_table": "assessed_performance_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="AssessedPerformance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("value", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "comment",
                    models.TextField(
                        blank=True, max_length=1000, null=True, verbose_name="Comment"
                    ),
                ),
                (
                    "flag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.performanceflag"
                    ),
                ),
            ],
            options={
                "db_table": "assessed_performance",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
    ]
