# Generated by Django 5.1.2 on 2024-11-22 01:27

import common.models
import django.core.validators
import django.db.models.deletion
import model_utils.fields
import private_storage.fields
import private_storage.storage.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0061_rename_contractclause_roundcontractclause_and_more_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="file",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="contracts",
                validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=["pdf"])
                ],
                verbose_name="Contract File",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="is_vm_na",
            field=models.BooleanField(default=False, verbose_name="Vision Mātauranga N/A"),
        ),
        migrations.AddField(
            model_name="contract",
            name="schedule2",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="contracts",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "html",
                            "pdf",
                            "fodt",
                            "odt",
                            "ott",
                            "oth",
                            "odm",
                            "doc",
                            "docx",
                            "docm",
                            "docb",
                        ]
                    )
                ],
                verbose_name="Schedule 2",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="toa_applied",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=0,
                help_text="Applied research",
                null=True,
                verbose_name="Applied",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="toa_basic",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=0,
                help_text="Pure basic research",
                null=True,
                verbose_name="Basic",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="toa_experimental",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=0,
                help_text="Experimental development",
                null=True,
                verbose_name="Experimental",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="toa_strategic",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=0,
                help_text="Strategic basic research",
                null=True,
                verbose_name="Strategic",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="vm_ecs",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=0,
                help_text="Contributing to Economic Growth through Distinctive R&D. New Zealand needs its businesses and for-profit enterprises to perform at an optimum level and contribute to economic growth. This theme concerns the development of distinctive products, processes, systems and services from Māori knowledge, resources and people. Of particular interest are products that may be distinctive in the international marketplace.",
                null=True,
                verbose_name="Indigenous Innovation",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="vm_ens",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=0,
                help_text="Achieving Environmental Sustainability through Iwi and Hapū relationships with land and sea. Like all communities, Māori communities aspire to live in sustainable communities dwelling in healthy environments. Much general environmental research is relevant to Māori. Distinctive environmental research arising in Māori communities relates to the expression of iwi and hapū knowledge, culture and experience – including Kaitiakitanga - in New Zealand land and seascapes.",
                null=True,
                verbose_name="Taiao",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="vm_hsw",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=0,
                help_text="Improving Māori Health and Social Well-being. Distinctive challenges to Māori health and social well-being continue to arise within Māori communities disadvantaging them in relation to the general population. Research is needed to meet these ongoing needs.",
                null=True,
                verbose_name="Hauora/Oranga",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="vm_ink",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=0,
                help_text="Exploring Indigenous Knowledge and RS&T. This exploratory theme aims to develop a body of knowledge, as a contribution to RS&T, at the interface between indigenous knowledge including mātauranga Māori – and research, science and technology.",
                null=True,
                verbose_name="Mātauranga",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="vm_rationale",
            field=models.TextField(blank=True, null=True, verbose_name="Rationale"),
        ),
        migrations.AddField(
            model_name="fund",
            name="email",
            field=common.models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Contact email address"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="file",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=["pdf"])
                ],
                verbose_name="Contract File",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="is_vm_na",
            field=models.BooleanField(default=False, verbose_name="Vision Mātauranga N/A"),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="schedule2",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "html",
                            "pdf",
                            "fodt",
                            "odt",
                            "ott",
                            "oth",
                            "odm",
                            "doc",
                            "docx",
                            "docm",
                            "docb",
                        ]
                    )
                ],
                verbose_name="Schedule 2",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="toa_applied",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=0,
                help_text="Applied research",
                null=True,
                verbose_name="Applied",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="toa_basic",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=0,
                help_text="Pure basic research",
                null=True,
                verbose_name="Basic",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="toa_experimental",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=0,
                help_text="Experimental development",
                null=True,
                verbose_name="Experimental",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="toa_strategic",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=0,
                help_text="Strategic basic research",
                null=True,
                verbose_name="Strategic",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="vm_ecs",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=0,
                help_text="Contributing to Economic Growth through Distinctive R&D. New Zealand needs its businesses and for-profit enterprises to perform at an optimum level and contribute to economic growth. This theme concerns the development of distinctive products, processes, systems and services from Māori knowledge, resources and people. Of particular interest are products that may be distinctive in the international marketplace.",
                null=True,
                verbose_name="Indigenous Innovation",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="vm_ens",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=0,
                help_text="Achieving Environmental Sustainability through Iwi and Hapū relationships with land and sea. Like all communities, Māori communities aspire to live in sustainable communities dwelling in healthy environments. Much general environmental research is relevant to Māori. Distinctive environmental research arising in Māori communities relates to the expression of iwi and hapū knowledge, culture and experience – including Kaitiakitanga - in New Zealand land and seascapes.",
                null=True,
                verbose_name="Taiao",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="vm_hsw",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=0,
                help_text="Improving Māori Health and Social Well-being. Distinctive challenges to Māori health and social well-being continue to arise within Māori communities disadvantaging them in relation to the general population. Research is needed to meet these ongoing needs.",
                null=True,
                verbose_name="Hauora/Oranga",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="vm_ink",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=0,
                help_text="Exploring Indigenous Knowledge and RS&T. This exploratory theme aims to develop a body of knowledge, as a contribution to RS&T, at the interface between indigenous knowledge including mātauranga Māori – and research, science and technology.",
                null=True,
                verbose_name="Mātauranga",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="vm_rationale",
            field=models.TextField(blank=True, null=True, verbose_name="Rationale"),
        ),
        migrations.AddField(
            model_name="historicalfund",
            name="email",
            field=common.models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Contact email address"
            ),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="contact",
            field=models.CharField(
                blank=True,
                help_text="Contact - an organisational role or a person name",
                max_length=200,
                null=True,
                verbose_name="Contact",
            ),
        ),
        migrations.AddField(
            model_name="historicalround",
            name="schedule2",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "html",
                            "pdf",
                            "fodt",
                            "odt",
                            "ott",
                            "oth",
                            "odm",
                            "doc",
                            "docx",
                            "docm",
                            "docb",
                        ]
                    )
                ],
                verbose_name="Schedule 2",
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="contact",
            field=models.CharField(
                blank=True,
                help_text="Contact - an organisational role or a person name",
                max_length=200,
                null=True,
                verbose_name="Contact",
            ),
        ),
        migrations.AddField(
            model_name="requiredcontractdocument",
            name="application_required_document",
            field=models.ForeignKey(
                blank=True,
                db_comment="Application required document corresponding to the contract to",
                help_text="Application required document corresponding to the contract to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contract_required_documents",
                to="portal.requireddocument",
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="schedule2",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="rounds",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "html",
                            "pdf",
                            "fodt",
                            "odt",
                            "ott",
                            "oth",
                            "odm",
                            "doc",
                            "docx",
                            "docm",
                            "docb",
                        ]
                    )
                ],
                verbose_name="Schedule 2",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="requires_approval",
            field=models.BooleanField(
                blank=True,
                help_text="Does your research require ethical and regulatory approval?",
                null=True,
                verbose_name="ethical and regulatory approval is required",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="requires_approval",
            field=models.BooleanField(
                blank=True,
                help_text="Does your research require ethical and regulatory approval?",
                null=True,
                verbose_name="ethical and regulatory approval is required",
            ),
        ),
    ]
