# Generated by Django 5.1.6 on 2025-02-25 10:25

import common.models
import django.core.validators
import django.db.models.deletion
import model_utils.fields
import portal.models
import private_storage.fields
import private_storage.storage.files
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0062_contract_file_contract_is_vm_na_contract_schedule2_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="agent_declaration_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="agent_declaration_accepted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="applicant_declaration_accepted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="contact",
            field=models.CharField(
                blank=True,
                help_text="Contact - an organisational role or a person name",
                max_length=200,
                null=True,
                verbose_name="Contact",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                max_length=24,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
                verbose_name="Contact phone number",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="state_changed_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True
            ),
        ),
        migrations.AddField(
            model_name="contractcomment",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="portal.contractcomment",
            ),
        ),
        migrations.AddField(
            model_name="historicalapplication",
            name="agent_declaration_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalapplication",
            name="agent_declaration_accepted_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalapplication",
            name="applicant_declaration_accepted_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="contact",
            field=models.CharField(
                blank=True,
                help_text="Contact - an organisational role or a person name",
                max_length=200,
                null=True,
                verbose_name="Contact",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                max_length=24,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
                verbose_name="Contact phone number",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="state_changed_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalround",
            name="agent_declaration",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalround",
            name="appendix_b",
            field=models.TextField(
                blank=True,
                help_text="Eligibility Criteria (MUST HAVE EXACTLY 1 PAGE! SHOULD BE converted into PDF with OpenOffice or LibreOffice)",
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=["pdf"])
                ],
                verbose_name="Appendix B",
            ),
        ),
        migrations.AddField(
            model_name="historicalround",
            name="applicant_declaration",
            field=models.TextField(
                blank=True,
                help_text="Duly authorised agent (i.e. the research office) declaration.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalround",
            name="awarded_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Awarded amount / Fellowship total budgets",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="roletype",
            name="is_key_person",
            field=models.BooleanField(
                default=True,
                help_text="The role will be included in the contract key personnel list",
                verbose_name="Is Key Person",
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="agent_declaration",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="round",
            name="appendix_b",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                help_text="Eligibility Criteria (MUST HAVE EXACTLY 1 PAGE! SHOULD BE converted into PDF with OpenOffice or LibreOffice)",
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="rounds",
                validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=["pdf"])
                ],
                verbose_name="Appendix B",
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="applicant_declaration",
            field=models.TextField(
                blank=True,
                help_text="Duly authorised agent (i.e. the research office) declaration.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="awarded_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Awarded amount / Fellowship total budgets",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="allocation",
            name="allocation",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Amount of funding (GST excl.)",
                max_digits=15,
                verbose_name="allocation",
            ),
        ),
        migrations.AlterField(
            model_name="allocation",
            name="details",
            field=models.CharField(
                blank=True,
                default="In equal instalments on the 2nd Business Day after the 20th day of each month.",
                help_text="E.g., on the 2nd Business Day after the 20th day of each  month, or receipt of the 2024 interim / final report.",
                max_length=1000,
                null=True,
                verbose_name="Payment details",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="state",
            field=portal.models.StateField(
                choices=[
                    (None, None),
                    ("new", "New"),
                    ("draft", "Draft"),
                    ("tac_accepted", "TAC accepted"),
                    ("in_review", "In referee review"),
                    ("submitted", "Submitted"),
                    ("cancelled", "Cancelled"),
                    ("withdrawn", "Withdrawn"),
                    ("approved", "Approved"),
                    ("accepted", "Accepted"),
                    ("archived", "Archived"),
                    ("funded", "Funded"),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                verbose_name="application state",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="state_changed_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="tac_accepted_at",
            field=model_utils.fields.MonitorField(
                blank=True,
                default=None,
                monitor="state",
                null=True,
                verbose_name="Terms and Conditions accepted at",
                when={"tac_accepted"},
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="state",
            field=portal.models.StateField(
                choices=[
                    (None, None),
                    ("ASD", "Awaiting start date"),
                    ("COM", "Completed"),
                    ("CUR", "Current "),
                    ("DCL", "Declined"),
                    ("SUS", "Suspended"),
                    ("TER", "Terminated"),
                    ("TRN", "Transferred"),
                    ("WTH", "Withdrawn"),
                    ("accepted", "Accepted"),
                    ("approved", "Approved"),
                    ("archived", "Archived"),
                    ("cancelled", "Cancelled"),
                    ("draft", "WIP"),
                    ("new", "new"),
                    ("preliminary", "Preliminary"),
                    ("submitted", "Submitted"),
                    ("released", "Released"),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="contractdocument",
            name="state",
            field=portal.models.StateField(
                choices=[
                    ("accepted", "Accepted"),
                    ("approved", "Approved"),
                    ("archived", "Archived"),
                    ("cancelled", "Cancelled"),
                    ("draft", "WIP"),
                    ("new", "New"),
                    ("released", "Released"),
                    ("submitted", "Submitted"),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="documenttype",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AB", "Award Budget"),
                    ("AF", "Application Form"),
                    ("AIMS", "Research Aims"),
                    ("B", "Budget"),
                    ("CV", "Curriculum Vitae"),
                    ("E", "Ethics Statement"),
                    ("EC", "Eligibility Criteria"),
                    ("F", "Form"),
                    ("HS", "Host Suitability"),
                    ("PB", "Proposal Budget"),
                    ("PT", "Project Timeline"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalallocation",
            name="allocation",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Amount of funding (GST excl.)",
                max_digits=15,
                verbose_name="allocation",
            ),
        ),
        migrations.AlterField(
            model_name="historicalallocation",
            name="details",
            field=models.CharField(
                blank=True,
                default="In equal instalments on the 2nd Business Day after the 20th day of each month.",
                help_text="E.g., on the 2nd Business Day after the 20th day of each  month, or receipt of the 2024 interim / final report.",
                max_length=1000,
                null=True,
                verbose_name="Payment details",
            ),
        ),
        migrations.AlterField(
            model_name="historicalapplication",
            name="state",
            field=portal.models.StateField(
                choices=[
                    (None, None),
                    ("new", "New"),
                    ("draft", "Draft"),
                    ("tac_accepted", "TAC accepted"),
                    ("in_review", "In referee review"),
                    ("submitted", "Submitted"),
                    ("cancelled", "Cancelled"),
                    ("withdrawn", "Withdrawn"),
                    ("approved", "Approved"),
                    ("accepted", "Accepted"),
                    ("archived", "Archived"),
                    ("funded", "Funded"),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                verbose_name="application state",
            ),
        ),
        migrations.AlterField(
            model_name="historicalapplication",
            name="state_changed_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalapplication",
            name="tac_accepted_at",
            field=model_utils.fields.MonitorField(
                blank=True,
                default=None,
                monitor="state",
                null=True,
                verbose_name="Terms and Conditions accepted at",
                when={"tac_accepted"},
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="state",
            field=portal.models.StateField(
                choices=[
                    (None, None),
                    ("ASD", "Awaiting start date"),
                    ("COM", "Completed"),
                    ("CUR", "Current "),
                    ("DCL", "Declined"),
                    ("SUS", "Suspended"),
                    ("TER", "Terminated"),
                    ("TRN", "Transferred"),
                    ("WTH", "Withdrawn"),
                    ("accepted", "Accepted"),
                    ("approved", "Approved"),
                    ("archived", "Archived"),
                    ("cancelled", "Cancelled"),
                    ("draft", "WIP"),
                    ("new", "new"),
                    ("preliminary", "Preliminary"),
                    ("submitted", "Submitted"),
                    ("released", "Released"),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontractdocument",
            name="state",
            field=portal.models.StateField(
                choices=[
                    ("accepted", "Accepted"),
                    ("approved", "Approved"),
                    ("archived", "Archived"),
                    ("cancelled", "Cancelled"),
                    ("draft", "WIP"),
                    ("new", "New"),
                    ("released", "Released"),
                    ("submitted", "Submitted"),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvitation",
            name="accepted_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"accepted"}
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvitation",
            name="bounced_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"bounced"}
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvitation",
            name="expired_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"expired"}
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvitation",
            name="read_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"read"}
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvitation",
            name="sent_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"sent"}
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvitation",
            name="state",
            field=portal.models.StateField(
                choices=[
                    ("accepted", "accepted"),
                    ("autoreplied", "auto-replied"),
                    ("bounced", "bounced"),
                    ("draft", "draft"),
                    ("expired", "expired"),
                    ("read", "read"),
                    ("revoked", "revoked"),
                    ("sent", "sent"),
                    ("submitted", "submitted"),
                ],
                default="draft",
                max_length=100,
                no_check_for_status=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvitation",
            name="state_changed_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvitation",
            name="submitted_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"submitted"}
            ),
        ),
        migrations.AlterField(
            model_name="historicalmember",
            name="authorized_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"authorized"}
            ),
        ),
        migrations.AlterField(
            model_name="historicalmember",
            name="state_changed_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisation",
            name="email",
            field=common.models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="Contracting contact email address",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpanellist",
            name="state_changed_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalreferee",
            name="state_changed_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalreferee",
            name="testified_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"testified"}
            ),
        ),
        migrations.AlterField(
            model_name="historicalreportingscheduleentry",
            name="acknowledged_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"acknowledged"}
            ),
        ),
        migrations.AlterField(
            model_name="historicalround",
            name="appendix_a",
            field=models.TextField(
                blank=True,
                help_text="Declaration regarding compliance with the Society's code of professional standards and ethics (preferably converted into PDF with OpenOffice or LibreOffice)",
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "html",
                            "pdf",
                            "fodt",
                            "odt",
                            "ott",
                            "oth",
                            "odm",
                            "doc",
                            "docx",
                            "docm",
                            "docb",
                        ]
                    )
                ],
                verbose_name="Appendix A",
            ),
        ),
        migrations.AlterField(
            model_name="historicalround",
            name="contract_background",
            field=models.TextField(
                blank=True,
                help_text="Contract background information (point '<b>A</b>' in the contract background)",
                null=True,
                verbose_name="contract background",
            ),
        ),
        migrations.AlterField(
            model_name="historicalround",
            name="schedule2",
            field=models.TextField(
                blank=True,
                help_text="Standard terms and conditions (preferably converted into PDF with OpenOffice or LibreOffice)",
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "html",
                            "pdf",
                            "fodt",
                            "odt",
                            "ott",
                            "oth",
                            "odm",
                            "doc",
                            "docx",
                            "docm",
                            "docb",
                        ]
                    )
                ],
                verbose_name="Schedule 2",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltestimonial",
            name="state_changed_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="accepted_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"accepted"}
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="bounced_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"bounced"}
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="expired_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"expired"}
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="read_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"read"}
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="sent_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"sent"}
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="state",
            field=portal.models.StateField(
                choices=[
                    ("accepted", "accepted"),
                    ("autoreplied", "auto-replied"),
                    ("bounced", "bounced"),
                    ("draft", "draft"),
                    ("expired", "expired"),
                    ("read", "read"),
                    ("revoked", "revoked"),
                    ("sent", "sent"),
                    ("submitted", "submitted"),
                ],
                default="draft",
                max_length=100,
                no_check_for_status=True,
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="state_changed_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="submitted_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"submitted"}
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="authorized_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"authorized"}
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="state_changed_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="email",
            field=common.models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="Contracting contact email address",
            ),
        ),
        migrations.AlterField(
            model_name="panellist",
            name="state_changed_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True
            ),
        ),
        migrations.AlterField(
            model_name="referee",
            name="state_changed_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True
            ),
        ),
        migrations.AlterField(
            model_name="referee",
            name="testified_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"testified"}
            ),
        ),
        migrations.AlterField(
            model_name="reportingscheduleentry",
            name="acknowledged_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True, when={"acknowledged"}
            ),
        ),
        migrations.AlterField(
            model_name="requiredcontractdocument",
            name="document_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="required_contract_documents",
                to="portal.documenttype",
            ),
        ),
        migrations.AlterField(
            model_name="requiredcontractdocument",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AB", "Award Budget"),
                    ("AF", "Application Form"),
                    ("AIMS", "Research Aims"),
                    ("B", "Budget"),
                    ("CV", "Curriculum Vitae"),
                    ("E", "Ethics Statement"),
                    ("EC", "Eligibility Criteria"),
                    ("F", "Form"),
                    ("HS", "Host Suitability"),
                    ("PB", "Proposal Budget"),
                    ("PT", "Project Timeline"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="requireddocument",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AB", "Award Budget"),
                    ("AF", "Application Form"),
                    ("AIMS", "Research Aims"),
                    ("B", "Budget"),
                    ("CV", "Curriculum Vitae"),
                    ("E", "Ethics Statement"),
                    ("EC", "Eligibility Criteria"),
                    ("F", "Form"),
                    ("HS", "Host Suitability"),
                    ("PB", "Proposal Budget"),
                    ("PT", "Project Timeline"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="appendix_a",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                help_text="Declaration regarding compliance with the Society's code of professional standards and ethics (preferably converted into PDF with OpenOffice or LibreOffice)",
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="rounds",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "html",
                            "pdf",
                            "fodt",
                            "odt",
                            "ott",
                            "oth",
                            "odm",
                            "doc",
                            "docx",
                            "docm",
                            "docb",
                        ]
                    )
                ],
                verbose_name="Appendix A",
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="contract_background",
            field=models.TextField(
                blank=True,
                help_text="Contract background information (point '<b>A</b>' in the contract background)",
                null=True,
                verbose_name="contract background",
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="schedule2",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                help_text="Standard terms and conditions (preferably converted into PDF with OpenOffice or LibreOffice)",
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="rounds",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "html",
                            "pdf",
                            "fodt",
                            "odt",
                            "ott",
                            "oth",
                            "odm",
                            "doc",
                            "docx",
                            "docm",
                            "docb",
                        ]
                    )
                ],
                verbose_name="Schedule 2",
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="state_changed_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True
            ),
        ),
    ]
