# Generated by Django 5.1.4 on 2025-03-24 13:45

import common.models
import django.core.validators
import django.db.models.deletion
import model_utils.fields
import portal.migration_utils
import portal.models
import private_storage.fields
import private_storage.storage.files
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0063_application_agent_declaration_accepted_at_and_more"),
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
        ("users", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeType",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "code",
                    common.models.FixedCharField(max_length=2, primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=100)),
                ("definition", models.TextField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "change_type",
                "ordering": ["description"],
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.AlterField(
            model_name="contract",
            name="preamble",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="contracts",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "html",
                            "pdf",
                            "fodt",
                            "odt",
                            "ott",
                            "oth",
                            "odm",
                            "doc",
                            "docx",
                            "docm",
                            "docb",
                        ]
                    )
                ],
                verbose_name="Preamble",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="preamble",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "html",
                            "pdf",
                            "fodt",
                            "odt",
                            "ott",
                            "oth",
                            "odm",
                            "doc",
                            "docx",
                            "docm",
                            "docb",
                        ]
                    )
                ],
                verbose_name="Preamble",
            ),
        ),
        migrations.CreateModel(
            name="ChangeCategory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("code", models.CharField(max_length=2, primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=100)),
                ("definition", models.TextField(blank=True, max_length=200, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_column="category",
                        help_text="Parent category",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="portal.changecategory",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        db_column="type",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.changetype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "variant categories",
                "db_table": "change_category",
                "ordering": ["description"],
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ChangeRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=24,
                        null=True,
                        unique=True,
                        verbose_name="number",
                    ),
                ),
                (
                    "state",
                    portal.models.StateField(
                        choices=[
                            ("accepted", "accepted"),
                            ("acknowledged", "acknowledged"),
                            ("approved", "approved"),
                            ("application", "application"),
                            ("archived", "archived"),
                            ("cancelled", "cancelled"),
                            ("draft", "draft"),
                            ("submitted", "submitted"),
                            ("withdrawn", "withdrawn"),
                        ],
                        default="draft",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="state",
                    ),
                ),
                (
                    "state_changed_at",
                    model_utils.fields.MonitorField(
                        blank=True, default=None, monitor="state", null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "file",
                    private_storage.fields.PrivateFileField(
                        blank=True,
                        null=True,
                        storage=private_storage.storage.files.PrivateFileSystemStorage(),
                        upload_to="changes",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "doc",
                                    "docx",
                                    "dot",
                                    "dotx",
                                    "docm",
                                    "dotm",
                                    "docb",
                                    "odt",
                                    "ott",
                                    "oth",
                                    "odm",
                                    "rtf",
                                    "tex",
                                ]
                            )
                        ],
                        verbose_name="Request Letter",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        db_table="change_request_change_category",
                        related_name="change_requests",
                        to="portal.changecategory",
                        verbose_name="Categories",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_requests",
                        to="portal.contract",
                    ),
                ),
                (
                    "converted_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portal.convertedfile",
                    ),
                ),
                (
                    "new_host",
                    models.ForeignKey(
                        blank=True,
                        help_text="New host organisation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_requests",
                        to="portal.organisation",
                    ),
                ),
                (
                    "subcategories",
                    models.ManyToManyField(
                        blank=True,
                        db_table="change_request_change_subcategory",
                        related_name="+",
                        to="portal.changecategory",
                        verbose_name="Subcategories",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "types",
                    models.ManyToManyField(
                        db_table="change_request_change_type",
                        related_name="change_requests",
                        to="portal.changetype",
                        verbose_name="Types",
                    ),
                ),
            ],
            options={
                "db_table": "change_request",
            },
            bases=(
                portal.models.PdfFileMixin,
                portal.models.ChangeRequestMixin,
                common.models.HelperMixin,
                models.Model,
            ),
        ),
        migrations.RunPython(
            code=portal.migration_utils.add_change_types,
            reverse_code=portal.migration_utils.dummy,
        ),
        migrations.RunPython(
            code=portal.migration_utils.add_change_categories,
            reverse_code=portal.migration_utils.dummy,
        ),
        migrations.AddField(
            model_name="contract",
            name="is_variation",
            field=models.BooleanField(
                default=False, help_text="Is this a variation of another contract?"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derivatives",
                to="portal.contract",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="is_variation",
            field=models.BooleanField(
                default=False, help_text="Is this a variation of another contract?"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="source",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="portal.contract",
            ),
        ),
        migrations.AddField(
            model_name="changerequest",
            name="derivative",
            field=models.ForeignKey(
                blank=True,
                help_text="Derivative contract (variation or extension)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="originated_by",
                to="portal.contract",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="requires_approval",
            field=models.BooleanField(
                default=False,
                help_text="Does your research require ethical and regulatory approval?",
                verbose_name="ethical and regulatory approval is required",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="requires_approval",
            field=models.BooleanField(
                default=False,
                help_text="Does your research require ethical and regulatory approval?",
                verbose_name="ethical and regulatory approval is required",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="changerequest",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="changerequest",
            name="state",
            field=portal.models.StateField(
                choices=[
                    ("accepted", "Accepted"),
                    ("acknowledged", "Acknowledged"),
                    ("approved", "Approved"),
                    ("application", "Application"),
                    ("archived", "Archived"),
                    ("cancelled", "Cancelled"),
                    ("declined", "Declined"),
                    ("draft", "WIP"),
                    ("submitted", "Under Review"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="draft",
                max_length=100,
                no_check_for_status=True,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="changerequest",
            name="types",
            field=models.ManyToManyField(
                db_table="change_request_change_type",
                related_name="change_requests",
                to="portal.changetype",
                verbose_name="Type(s)",
            ),
        ),
        migrations.CreateModel(
            name="ChangeRequestComment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "token",
                    models.CharField(
                        default=portal.models.get_unique_invitation_token,
                        max_length=42,
                        unique=True,
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, max_length=1000, null=True, verbose_name="comment"
                    ),
                ),
                ("alert_date", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "attachment",
                    private_storage.fields.PrivateFileField(
                        blank=True,
                        null=True,
                        storage=private_storage.storage.files.PrivateFileSystemStorage(),
                        upload_to="change_requests",
                        verbose_name="attachment",
                    ),
                ),
                (
                    "change_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="portal.changerequest",
                    ),
                ),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="portal.changerequestcomment",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_request_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="submitted by",
                    ),
                ),
            ],
            options={
                "verbose_name": "comment",
                "verbose_name_plural": "comments",
                "db_table": "change_request_comment",
                "ordering": ["-id"],
                "abstract": False,
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ChangeRequestCommentAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "attachment",
                    private_storage.fields.PrivateFileField(
                        blank=True,
                        null=True,
                        storage=private_storage.storage.files.PrivateFileSystemStorage(),
                        upload_to="change_requests",
                        verbose_name="attachment",
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="portal.changerequestcomment",
                    ),
                ),
            ],
            options={
                "verbose_name": "attachment",
                "db_table": "change_request_comment_attachment",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ChangeRequestCommentRecipient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("email", common.models.EmailField(max_length=200)),
                ("is_cced", models.BooleanField(default=False)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="portal.changerequestcomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "recipient",
                "db_table": "change_request_comment_recipient",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
    ]
