# Generated by Django 5.1.4 on 2025-02-28 12:57

import common.models
import django.core.validators
import django.db.models.deletion
import model_utils.fields
import portal.migration_utils
import portal.models
import private_storage.fields
import private_storage.storage.files
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0063_application_agent_declaration_accepted_at_and_more"),
        ("users", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("code", models.CharField(blank=True, max_length=2, null=True)),
                ("description", models.CharField(max_length=40)),
                ("definition", models.TextField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "change_type",
                "ordering": ["description"],
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ChangeCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("code", models.CharField(blank=True, max_length=2, null=True)),
                ("description", models.CharField(max_length=40)),
                ("definition", models.TextField(blank=True, max_length=200, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.changecategory"
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.changetype"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "variant categories",
                "db_table": "change_category",
                "ordering": ["description"],
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ChangeRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=24, null=True, unique=True, verbose_name="number"
                    ),
                ),
                (
                    "state",
                    portal.models.StateField(
                        choices=[
                            ("accepted", "accepted"),
                            ("acknowledged", "acknowledged"),
                            ("approved", "approved"),
                            ("application", "application"),
                            ("archived", "archived"),
                            ("cancelled", "cancelled"),
                            ("draft", "draft"),
                            ("submitted", "submitted"),
                            ("withdrawn", "withdrawn"),
                        ],
                        default="draft",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="state",
                    ),
                ),
                (
                    "state_changed_at",
                    model_utils.fields.MonitorField(
                        blank=True, default=None, monitor="state", null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "file",
                    private_storage.fields.PrivateFileField(
                        blank=True,
                        null=True,
                        storage=private_storage.storage.files.PrivateFileSystemStorage(),
                        upload_to="changes",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "doc",
                                    "docx",
                                    "dot",
                                    "dotx",
                                    "docm",
                                    "dotm",
                                    "docb",
                                    "odt",
                                    "ott",
                                    "oth",
                                    "odm",
                                    "rtf",
                                    "tex",
                                ]
                            )
                        ],
                        verbose_name="Request Letter",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        db_table="change_request_change_category",
                        related_name="change_requests",
                        to="portal.changecategory",
                        verbose_name="Categories",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.contract"
                    ),
                ),
                (
                    "converted_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portal.convertedfile",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "types",
                    models.ManyToManyField(
                        db_table="change_request_change_type",
                        related_name="change_requests",
                        to="portal.changetype",
                        verbose_name="Types",
                    ),
                ),
            ],
            options={
                "db_table": "change_request",
            },
            bases=(
                portal.models.PdfFileMixin,
                portal.models.ChangeRequestMixin,
                common.models.HelperMixin,
                models.Model,
            ),
        ),
        migrations.RunPython(
            code=portal.migration_utils.add_change_type,
            reverse_code=portal.migration_utils.dummy,
        ),
    ]
