# Generated by Django 5.1.4 on 2025-05-05 17:55

import colorfield.fields
import common.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import portal.migration_utils
import portal.models
import private_storage.fields
import private_storage.storage.files
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("portal", "0063_application_agent_declaration_accepted_at_and_more"),
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
        ("users", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeType",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "code",
                    common.models.FixedCharField(max_length=2, primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=100)),
                ("definition", models.TextField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "change_type",
                "ordering": ["description"],
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.AlterField(
            model_name="contract",
            name="preamble",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="contracts",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "html",
                            "pdf",
                            "fodt",
                            "odt",
                            "ott",
                            "oth",
                            "odm",
                            "doc",
                            "docx",
                            "docm",
                            "docb",
                        ]
                    )
                ],
                verbose_name="Preamble",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="preamble",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "html",
                            "pdf",
                            "fodt",
                            "odt",
                            "ott",
                            "oth",
                            "odm",
                            "doc",
                            "docx",
                            "docm",
                            "docb",
                        ]
                    )
                ],
                verbose_name="Preamble",
            ),
        ),
        migrations.CreateModel(
            name="ChangeCategory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("code", models.CharField(max_length=2, primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=100)),
                ("definition", models.TextField(blank=True, max_length=200, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_column="category",
                        help_text="Parent category",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="portal.changecategory",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        db_column="type",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.changetype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "variant categories",
                "db_table": "change_category",
                "ordering": ["description"],
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ChangeRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=24,
                        null=True,
                        unique=True,
                        verbose_name="number",
                    ),
                ),
                (
                    "state",
                    portal.models.StateField(
                        choices=[
                            ("accepted", "accepted"),
                            ("acknowledged", "acknowledged"),
                            ("approved", "approved"),
                            ("application", "application"),
                            ("archived", "archived"),
                            ("cancelled", "cancelled"),
                            ("draft", "draft"),
                            ("submitted", "submitted"),
                            ("withdrawn", "withdrawn"),
                        ],
                        default="draft",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="state",
                    ),
                ),
                (
                    "state_changed_at",
                    model_utils.fields.MonitorField(
                        blank=True, default=None, monitor="state", null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "file",
                    private_storage.fields.PrivateFileField(
                        blank=True,
                        null=True,
                        storage=private_storage.storage.files.PrivateFileSystemStorage(),
                        upload_to="changes",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "doc",
                                    "docx",
                                    "dot",
                                    "dotx",
                                    "docm",
                                    "dotm",
                                    "docb",
                                    "odt",
                                    "ott",
                                    "oth",
                                    "odm",
                                    "rtf",
                                    "tex",
                                ]
                            )
                        ],
                        verbose_name="Request Letter",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        db_table="change_request_change_category",
                        related_name="change_requests",
                        to="portal.changecategory",
                        verbose_name="Categories",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_requests",
                        to="portal.contract",
                    ),
                ),
                (
                    "converted_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portal.convertedfile",
                    ),
                ),
                (
                    "new_host",
                    models.ForeignKey(
                        blank=True,
                        help_text="New host organisation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_requests",
                        to="portal.organisation",
                    ),
                ),
                (
                    "subcategories",
                    models.ManyToManyField(
                        blank=True,
                        db_table="change_request_change_subcategory",
                        related_name="+",
                        to="portal.changecategory",
                        verbose_name="Subcategories",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "types",
                    models.ManyToManyField(
                        db_table="change_request_change_type",
                        related_name="change_requests",
                        to="portal.changetype",
                        verbose_name="Types",
                    ),
                ),
                (
                    "reply",
                    models.TextField(
                        blank=True,
                        default='<p style="font-family: Arial; font-size: 10px;"></p>',
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "change_request",
            },
            bases=(
                portal.models.PdfFileMixin,
                portal.models.ChangeRequestMixin,
                common.models.HelperMixin,
                models.Model,
            ),
        ),
        migrations.RunPython(
            code=portal.migration_utils.add_change_types,
            reverse_code=portal.migration_utils.dummy,
        ),
        migrations.RunPython(
            code=portal.migration_utils.add_change_categories,
            reverse_code=portal.migration_utils.dummy,
        ),
        migrations.AddField(
            model_name="contract",
            name="is_variation",
            field=models.BooleanField(
                default=False, help_text="Is this a variation of another contract?"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derivatives",
                to="portal.contract",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="is_variation",
            field=models.BooleanField(
                default=False, help_text="Is this a variation of another contract?"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="source",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="portal.contract",
            ),
        ),
        migrations.AddField(
            model_name="changerequest",
            name="derivative",
            field=models.ForeignKey(
                blank=True,
                help_text="Derivative contract (variation or extension)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="originated_by",
                to="portal.contract",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="requires_approval",
            field=models.BooleanField(
                default=False,
                help_text="Does your research require ethical and regulatory approval?",
                verbose_name="ethical and regulatory approval is required",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="requires_approval",
            field=models.BooleanField(
                default=False,
                help_text="Does your research require ethical and regulatory approval?",
                verbose_name="ethical and regulatory approval is required",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="changerequest",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="changerequest",
            name="state",
            field=portal.models.StateField(
                choices=[
                    ("accepted", "Under Review"),
                    ("acknowledged", "Acknowledged"),
                    ("approved", "Approved"),
                    ("application", "Application"),
                    ("archived", "Archived"),
                    ("cancelled", "Cancelled"),
                    ("declined", "Declined"),
                    ("draft", "WIP"),
                    ("submitted", "Received"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="draft",
                max_length=100,
                no_check_for_status=True,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="changerequest",
            name="types",
            field=models.ManyToManyField(
                db_table="change_request_change_type",
                related_name="change_requests",
                to="portal.changetype",
                verbose_name="Type(s)",
            ),
        ),
        migrations.CreateModel(
            name="ChangeRequestComment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "token",
                    models.CharField(
                        default=portal.models.get_unique_invitation_token,
                        max_length=42,
                        unique=True,
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, max_length=1000, null=True, verbose_name="comment"
                    ),
                ),
                ("alert_date", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "attachment",
                    private_storage.fields.PrivateFileField(
                        blank=True,
                        null=True,
                        storage=private_storage.storage.files.PrivateFileSystemStorage(),
                        upload_to="",
                        verbose_name="attachment",
                    ),
                ),
                (
                    "change_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="portal.changerequest",
                    ),
                ),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="portal.changerequestcomment",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="submitted by",
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                "verbose_name": "comment",
                "verbose_name_plural": "comments",
                "db_table": "change_request_comment",
                "ordering": ["-created_at"],
                "abstract": False,
                "default_related_name": "change_request_comments",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name="contractcomment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "comment",
                "verbose_name_plural": "comments",
            },
        ),
        migrations.AlterModelOptions(
            name="reportcomment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "comment",
                "verbose_name_plural": "comments",
            },
        ),
        migrations.AddField(
            model_name="contractcomment",
            name="alert_date",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="contractcomment",
            name="subject",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="reportcomment",
            name="subject",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="academicrecord",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="affiliation",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="allocation",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="applicationdecision",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="applicationdocument",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="applicationfor",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="applicationformtemplate",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="applicationkeyword",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="applicationnumber",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="applicationseo",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="assessedperformance",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="award",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="careerstage",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="changecategory",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="changerequest",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.CreateModel(
            name="ChangeRequestCommentAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "attachment",
                    private_storage.fields.PrivateFileField(
                        blank=True,
                        null=True,
                        storage=private_storage.storage.files.PrivateFileSystemStorage(),
                        upload_to="change_requests",
                        verbose_name="attachment",
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="portal.changerequestcomment",
                    ),
                ),
            ],
            options={
                "verbose_name": "attachment",
                "db_table": "change_request_comment_attachment",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ChangeRequestCommentRecipient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("email", common.models.EmailField(max_length=200)),
                ("is_cced", models.BooleanField(default=False)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="portal.changerequestcomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "recipient",
                "db_table": "change_request_comment_recipient",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.AlterField(
            model_name="changetype",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="conflictofinterest",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contractclause",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contractcomment",
            name="attachment",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="",
                verbose_name="attachment",
            ),
        ),
        migrations.AlterField(
            model_name="contractcomment",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contractcomment",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss",
                to=settings.AUTH_USER_MODEL,
                verbose_name="submitted by",
            ),
        ),
        migrations.AlterField(
            model_name="contractcommentattachment",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contractcommentrecipient",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contractdocument",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contractethicsstatement",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contractfor",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contractkeyword",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contractmember",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contractmembereffort",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contractseo",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="criterion",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="currency",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="curriculumvitae",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="curriculumvitaetemplate",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="documenttype",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="educationlevel",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ethicsstatement",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ethnicity",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="fieldofresearch",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="fieldofstudy",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="fund",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalacademicrecord",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicaladdress",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalaffiliation",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalallocation",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalapplication",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalapplicationnumber",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalassessedperformance",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontractdocument",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontractmember",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontractmembereffort",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalcountry",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalcriterion",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalevaluation",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalfund",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvitation",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalmember",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembereffort",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalnomination",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisation",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalorgname",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalpanel",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalpanellist",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalperson",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalrecognition",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalreferee",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalreport",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalreportedeffort",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalreportedfunding",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalreportingscheduleentry",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalresearchoffice",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalround",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalsocioeconomicobjective",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicaltestimonial",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="identityverification",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="iwigroup",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="letterofsupport",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="maillog",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="membereffort",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="nomination",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="orgidentifiertype",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="orgname",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="panel",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="paneldecision",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="panellist",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="performanceflag",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="personcareerstage",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="personcode",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="personidentifierpattern",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="personidentifiertype",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="personpersonidentifier",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="personprotectionpattern",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="protectionpattern",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="publicationauthor",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="publicationlink",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="publicationstatus",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="publicationtype",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="qualification",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="rcc",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="recognition",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="referee",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="reportcomment",
            name="attachment",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="",
                verbose_name="attachment",
            ),
        ),
        migrations.AlterField(
            model_name="reportcomment",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="reportcomment",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss",
                to=settings.AUTH_USER_MODEL,
                verbose_name="submitted by",
            ),
        ),
        migrations.AlterField(
            model_name="reportcommentattachment",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="reportcommentrecipient",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="reportedaward",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="reportedcollaboration",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="reportedeffort",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="reportedfunding",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="reportedpublicity",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="reportedvisit",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="reportfor",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="reportingscheduleentry",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="reportkeyword",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="reportseo",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="requiredcontractdocument",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="requireddocument",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="researchoffice",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="rispublicationtype",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="roletype",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="roundcontractclause",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="rounddocumenttemplate",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="scheme",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="score",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="scoresheet",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="socioeconomicobjective",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False, null=True
            ),
        ),
        migrations.AlterModelOptions(
            name="contractcomment",
            options={
                "default_related_name": "contract_comments",
                "ordering": ["-created_at"],
                "verbose_name": "comment",
                "verbose_name_plural": "comments",
            },
        ),
        migrations.AlterModelOptions(
            name="reportcomment",
            options={
                "default_related_name": "report_comments",
                "ordering": ["-created_at"],
                "verbose_name": "comment",
                "verbose_name_plural": "comments",
            },
        ),
        migrations.AlterField(
            model_name="contractcomment",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="submitted by",
            ),
        ),
        migrations.AlterField(
            model_name="reportcomment",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="submitted by",
            ),
        ),
        migrations.RenameField(
            model_name="historicalround",
            old_name="colour",
            new_name="background",
        ),
        migrations.RenameField(
            model_name="round",
            old_name="colour",
            new_name="background",
        ),
        migrations.AddField(
            model_name="historicalround",
            name="foreground",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                help_text="Colour used for text headers and fore-grounds",
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="foreground",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                help_text="Colour used for text headers and fore-grounds",
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
            ),
        ),
        migrations.CreateModel(
            name="ResearchPriority",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="name")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, max_length=100, unique=True, verbose_name="slug"
                    ),
                ),
            ],
            options={
                "verbose_name": "Research Priority",
                "verbose_name_plural": "Research Priorities",
                "db_table": "research_priority",
            },
        ),
        migrations.RunPython(
            code=portal.migration_utils.add_research_priorities,
            reverse_code=portal.migration_utils.dummy,
        ),
        migrations.AlterField(
            model_name="contract",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                max_length=24,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed: %(value)s.",
                        regex="\\+?[0123456789 ]{9,15}$",
                    )
                ],
                verbose_name="Contact phone number",
            ),
        ),
        migrations.AlterField(
            model_name="contractmember",
            name="middle_names",
            field=models.CharField(
                blank=True, max_length=280, null=True, verbose_name="middle names"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                max_length=24,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed: %(value)s.",
                        regex="\\+?[0123456789 ]{9,15}$",
                    )
                ],
                verbose_name="Contact phone number",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontractmember",
            name="middle_names",
            field=models.CharField(
                blank=True, max_length=280, null=True, verbose_name="middle names"
            ),
        ),
        migrations.AlterField(
            model_name="historicalnomination",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                max_length=24,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed: %(value)s.",
                        regex="\\+?[0123456789 ]{9,15}$",
                    )
                ],
                verbose_name="Contact phone number",
            ),
        ),
        migrations.AlterField(
            model_name="historicalnomination",
            name="middle_names",
            field=models.CharField(
                blank=True, max_length=280, null=True, verbose_name="middle names"
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisation",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                max_length=24,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed: %(value)s.",
                        regex="\\+?[0123456789 ]{9,15}$",
                    )
                ],
                verbose_name="Contact phone number",
            ),
        ),
        migrations.AlterField(
            model_name="nomination",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                max_length=24,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed: %(value)s.",
                        regex="\\+?[0123456789 ]{9,15}$",
                    )
                ],
                verbose_name="Contact phone number",
            ),
        ),
        migrations.AlterField(
            model_name="nomination",
            name="middle_names",
            field=models.CharField(
                blank=True, max_length=280, null=True, verbose_name="middle names"
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                max_length=24,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed: %(value)s.",
                        regex="\\+?[0123456789 ]{9,15}$",
                    )
                ],
                verbose_name="Contact phone number",
            ),
        ),
        migrations.CreateModel(
            name="ResearchPriorityItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("object_id", models.IntegerField(db_index=True, verbose_name="object ID")),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_tagged_items",
                        to="contenttypes.contenttype",
                        verbose_name="content type",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="portal.researchpriority",
                    ),
                ),
            ],
            options={
                "verbose_name": "item with research priorities",
                "verbose_name_plural": "items with research priorities",
                "db_table": "research_priority_item",
            },
        ),
        migrations.AddField(
            model_name="application",
            name="priorities",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="Research priorities",
                through="portal.ResearchPriorityItem",
                to="portal.ResearchPriority",
                verbose_name="Priorities",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="priorities",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="Research priorities",
                through="portal.ResearchPriorityItem",
                to="portal.ResearchPriority",
                verbose_name="Priorities",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="priorities",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="Research priorities",
                through="portal.ResearchPriorityItem",
                to="portal.ResearchPriority",
                verbose_name="Priorities",
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="priorities",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="Available research priorities",
                through="portal.ResearchPriorityItem",
                to="portal.ResearchPriority",
                verbose_name="Available priorities",
            ),
        ),
        migrations.AddField(
            model_name="historicalround",
            name="is_partial_profile_allowed",
            field=models.BooleanField(
                default=False,
                help_text="Partial profile allowed, applicant is not required to provide a complete user profile",
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="is_partial_profile_allowed",
            field=models.BooleanField(
                default=False,
                help_text="Partial profile allowed, applicant is not required to provide a complete user profile",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="is_tac_accepted",
            field=models.BooleanField(default=False, verbose_name="the T&Cs were accepted"),
        ),
        migrations.AlterField(
            model_name="historicalapplication",
            name="is_tac_accepted",
            field=models.BooleanField(default=False, verbose_name="the T&Cs were accepted"),
        ),
        migrations.AddField(
            model_name="rounddocumenttemplate",
            name="required_document",
            field=models.ForeignKey(
                blank=True,
                help_text="NB! Save the round with the required documents before assigning the themplates to the required documents!",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="templates",
                to="portal.requireddocument",
            ),
        ),
        migrations.AlterField(
            model_name="requireddocument",
            name="document_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="required_documents",
                to="portal.documenttype",
            ),
        ),
        migrations.AlterField(
            model_name="rounddocumenttemplate",
            name="document_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="templates",
                to="portal.documenttype",
            ),
        ),
        migrations.RunPython(
            code=portal.migration_utils.set_document_template_required_document,
            reverse_code=portal.migration_utils.dummy,
        ),
        migrations.AlterField(
            model_name="contract",
            name="state",
            field=portal.models.StateField(
                choices=[
                    (None, None),
                    ("ASD", "Awaiting start date"),
                    ("COM", "Completed"),
                    ("CUR", "Current "),
                    ("DCL", "Declined"),
                    ("SUS", "Suspended"),
                    ("TER", "Terminated"),
                    ("TRN", "Transferred"),
                    ("WTH", "Withdrawn"),
                    ("accepted", "Accepted"),
                    ("approved", "Approved"),
                    ("archived", "Archived"),
                    ("cancelled", "Cancelled"),
                    ("draft", "WIP"),
                    ("new", "new"),
                    ("preliminary", "Preliminary"),
                    ("submitted", "Submitted"),
                    ("released", "Released"),
                    ("current", "Current "),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="state",
            field=portal.models.StateField(
                choices=[
                    (None, None),
                    ("ASD", "Awaiting start date"),
                    ("COM", "Completed"),
                    ("CUR", "Current "),
                    ("DCL", "Declined"),
                    ("SUS", "Suspended"),
                    ("TER", "Terminated"),
                    ("TRN", "Transferred"),
                    ("WTH", "Withdrawn"),
                    ("accepted", "Accepted"),
                    ("approved", "Approved"),
                    ("archived", "Archived"),
                    ("cancelled", "Cancelled"),
                    ("draft", "WIP"),
                    ("new", "new"),
                    ("preliminary", "Preliminary"),
                    ("submitted", "Submitted"),
                    ("released", "Released"),
                    ("current", "Current "),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                verbose_name="state",
            ),
        ),
        migrations.AddField(
            model_name="historicalmember",
            name="converted_file",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="portal.convertedfile",
                verbose_name="converted file",
            ),
        ),
        migrations.AddField(
            model_name="historicalmember",
            name="file",
            field=models.TextField(
                blank=True, max_length=200, null=True, verbose_name="Host support letter"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="converted_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portal.convertedfile",
                verbose_name="converted file",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="file",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                max_length=200,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="members",
                verbose_name="Host support letter",
            ),
        ),
        migrations.AddField(
            model_name="historicalmember",
            name="org",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="portal.organisation",
                verbose_name="organisation",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="org",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portal.organisation",
                verbose_name="organisation",
            ),
        ),
        migrations.AddField(
            model_name="historicalmember",
            name="country",
            field=models.ForeignKey(
                blank=True,
                db_column="country",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="portal.country",
                verbose_name="country",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="country",
            field=models.ForeignKey(
                blank=True,
                db_column="country",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="portal.country",
                verbose_name="country",
            ),
        ),
    ]
