# Generated by Django 5.1.6 on 2025-02-25 13:03

import common.models
import django.core.validators
import django.db.models.deletion
import portal.models
import private_storage.fields
import private_storage.storage.files
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0063_application_agent_declaration_accepted_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VariantRequestCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("code", models.CharField(blank=True, max_length=2, null=True)),
                ("description", models.CharField(max_length=40)),
                ("definition", models.TextField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "variant_request_category",
                "ordering": ["description"],
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="VariantRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "state",
                    portal.models.StateField(
                        choices=[
                            ("accepted", "accepted"),
                            ("acknowledged", "acknowledged"),
                            ("approved", "approved"),
                            ("application", "application"),
                            ("archived", "archived"),
                            ("cancelled", "cancelled"),
                            ("draft", "draft"),
                            ("submitted", "submitted"),
                            ("withdrawn", "withdrawn"),
                        ],
                        default="new",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="state",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "file",
                    private_storage.fields.PrivateFileField(
                        blank=True,
                        null=True,
                        storage=private_storage.storage.files.PrivateFileSystemStorage(),
                        upload_to="variant",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "doc",
                                    "docx",
                                    "dot",
                                    "dotx",
                                    "docm",
                                    "dotm",
                                    "docb",
                                    "odt",
                                    "ott",
                                    "oth",
                                    "odm",
                                    "rtf",
                                    "tex",
                                ]
                            )
                        ],
                        verbose_name="Request Letter",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.contract"
                    ),
                ),
                (
                    "converted_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portal.convertedfile",
                        verbose_name="converted file",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="variant_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ManyToManyField(
                        db_table="variant_request_variant_request_category",
                        to="portal.variantrequestcategory",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "db_table": "variant_request",
            },
            bases=(
                portal.models.PdfFileMixin,
                portal.models.VariantRequestMixin,
                common.models.HelperMixin,
                models.Model,
            ),
        ),
    ]
