# Generated by Django 5.1.4 on 2025-04-01 14:08

import colorfield.fields
import portal.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0064_changetype_alter_contract_preamble_and_more"),
    ]

    operations = [
    ]
