# Generated by Django 5.1.12 on 2025-11-17 02:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import private_storage.fields
import private_storage.storage.files
from django.conf import settings
from django.db import migrations, models

import common.models
import portal.models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("portal", "0065_unaccent"),
        ("users", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("content", models.TextField(verbose_name="Content")),
                ("object_id", models.PositiveIntegerField()),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
            ],
            options={
                "verbose_name": "Note",
                "verbose_name_plural": "Notes",
                "db_table": "note",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name="contract",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="historicalcontract",
            name="notes",
        ),
        migrations.AddField(
            model_name="contractmember",
            name="is_funded",
            field=models.BooleanField(default=True, verbose_name="funded"),
        ),
        migrations.AddField(
            model_name="historicalcontractmember",
            name="is_funded",
            field=models.BooleanField(default=True, verbose_name="funded"),
        ),
        migrations.AddField(
            model_name="historicalmember",
            name="is_funded",
            field=models.BooleanField(default=True, verbose_name="funded"),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="coordinator",
            field=models.ForeignKey(
                blank=True,
                db_comment="stage.source.coordinator_code",
                db_constraint=False,
                limit_choices_to={"affiliations__type": "EMP"},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="portal.person",
                verbose_name="coordinator",
            ),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="provider_type",
            field=models.CharField(
                blank=True, db_comment="stage.source.provider_type", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="sector",
            field=models.CharField(
                blank=True, db_comment="stage.source.sector", max_length=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalperson",
            name="is_maori_decendent",
            field=models.BooleanField(
                blank=True, db_comment="stage.person.maori_descent", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalround",
            name="has_ftes",
            field=models.BooleanField(
                default=False,
                help_text="has FTEs defined at proposal stage",
                verbose_name="has FTEs",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="is_funded",
            field=models.BooleanField(default=True, verbose_name="funded"),
        ),
        migrations.AddField(
            model_name="organisation",
            name="coordinator",
            field=models.ForeignKey(
                blank=True,
                db_comment="stage.source.coordinator_code",
                limit_choices_to={"affiliations__type": "EMP"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coordinator_for",
                to="portal.person",
                verbose_name="coordinator",
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="provider_type",
            field=models.CharField(
                blank=True, db_comment="stage.source.provider_type", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="sector",
            field=models.CharField(
                blank=True, db_comment="stage.source.sector", max_length=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="is_maori_decendent",
            field=models.BooleanField(
                blank=True, db_comment="stage.person.maori_descent", null=True
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="has_ftes",
            field=models.BooleanField(
                default=False,
                help_text="has FTEs defined at proposal stage",
                verbose_name="has FTEs",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="file",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                help_text="Please upload completed application form",
                max_length=200,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="applications",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "odt",
                            "ott",
                            "oth",
                            "odm",
                            "doc",
                            "docx",
                            "docm",
                            "docb",
                        ]
                    )
                ],
                verbose_name="completed application form",
            ),
        ),
        migrations.AlterField(
            model_name="applicationdocument",
            name="file",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                max_length=200,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="applications",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "csv",
                            "ctv",
                            "doc",
                            "docb",
                            "docm",
                            "docx",
                            "dot",
                            "dotm",
                            "dotx",
                            "gif",
                            "jpeg",
                            "jpg",
                            "odm",
                            "odt",
                            "oth",
                            "ott",
                            "pdf",
                            "png",
                            "rtf",
                            "tex",
                            "xls",
                            "xlsb",
                            "xlsm",
                            "xlsx",
                            "xlt",
                            "xltm",
                            "xltx",
                            "xlw",
                            "xml",
                        ]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="applicationformtemplate",
            name="file",
            field=models.FileField(
                max_length=200,
                upload_to=portal.models.round_template_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "doc",
                            "docx",
                            "dot",
                            "dotx",
                            "docm",
                            "dotm",
                            "docb",
                            "odt",
                            "ott",
                            "oth",
                            "odm",
                            "rtf",
                            "tex",
                        ]
                    )
                ],
                verbose_name="Template",
            ),
        ),
        migrations.AlterField(
            model_name="changerequest",
            name="file",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                max_length=200,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="changes",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "doc",
                            "docx",
                            "dot",
                            "dotx",
                            "docm",
                            "dotm",
                            "docb",
                            "odt",
                            "ott",
                            "oth",
                            "odm",
                            "rtf",
                            "tex",
                        ]
                    )
                ],
                verbose_name="Request Letter",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="file",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                max_length=200,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="contracts",
                validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=["pdf"])
                ],
                verbose_name="Contract File",
            ),
        ),
        migrations.AlterField(
            model_name="contractdocument",
            name="file",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                max_length=200,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="contracts",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "csv",
                            "ctv",
                            "doc",
                            "docb",
                            "docm",
                            "docx",
                            "fdot",
                            "dot",
                            "dotm",
                            "dotx",
                            "odm",
                            "odt",
                            "fodt",
                            "oth",
                            "ott",
                            "pdf",
                            "rtf",
                            "tex",
                            "xls",
                            "xlsb",
                            "xlsm",
                            "xlsx",
                            "xlt",
                            "xltm",
                            "xltx",
                            "xlw",
                            "xml",
                        ]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="contractethicsstatement",
            name="file",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                help_text="Please upload human or animal ethics statement.",
                max_length=200,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="contracts",
                verbose_name="ethics statement",
            ),
        ),
        migrations.AlterField(
            model_name="convertedfile",
            name="file",
            field=private_storage.fields.PrivateFileField(
                max_length=200,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to=portal.models.converted_file_path,
            ),
        ),
        migrations.AlterField(
            model_name="curriculumvitae",
            name="file",
            field=private_storage.fields.PrivateFileField(
                max_length=200,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="cv",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "doc",
                            "docb",
                            "docm",
                            "docx",
                            "dot",
                            "dotm",
                            "dotx",
                            "odm",
                            "odt",
                            "oth",
                            "ott",
                            "pdf",
                            "rtf",
                            "tex",
                        ]
                    )
                ],
                verbose_name="file",
            ),
        ),
        migrations.AlterField(
            model_name="curriculumvitaetemplate",
            name="file",
            field=models.FileField(
                max_length=200,
                upload_to=portal.models.round_template_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "doc",
                            "docx",
                            "dot",
                            "dotx",
                            "docm",
                            "dotm",
                            "docb",
                            "odt",
                            "ott",
                            "oth",
                            "odm",
                            "rtf",
                            "tex",
                        ]
                    )
                ],
                verbose_name="Template",
            ),
        ),
        migrations.AlterField(
            model_name="ethicsstatement",
            name="file",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                help_text="Please upload human or animal ethics statement.",
                max_length=200,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="statements",
                verbose_name="ethics statement",
            ),
        ),
        migrations.AlterField(
            model_name="historicalapplication",
            name="file",
            field=models.TextField(
                blank=True,
                help_text="Please upload completed application form",
                max_length=200,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "odt",
                            "ott",
                            "oth",
                            "odm",
                            "doc",
                            "docx",
                            "docm",
                            "docb",
                        ]
                    )
                ],
                verbose_name="completed application form",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="file",
            field=models.TextField(
                blank=True,
                max_length=200,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=["pdf"])
                ],
                verbose_name="Contract File",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontractdocument",
            name="file",
            field=models.TextField(
                blank=True,
                max_length=200,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "csv",
                            "ctv",
                            "doc",
                            "docb",
                            "docm",
                            "docx",
                            "fdot",
                            "dot",
                            "dotm",
                            "dotx",
                            "odm",
                            "odt",
                            "fodt",
                            "oth",
                            "ott",
                            "pdf",
                            "rtf",
                            "tex",
                            "xls",
                            "xlsb",
                            "xlsm",
                            "xlsx",
                            "xlt",
                            "xltm",
                            "xltx",
                            "xlw",
                            "xml",
                        ]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historicalnomination",
            name="file",
            field=models.TextField(
                blank=True,
                help_text="Upload filled-in nominator form",
                max_length=200,
                null=True,
                verbose_name="Nominator form",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreferee",
            name="state",
            field=portal.models.StateField(
                blank=True,
                choices=[
                    ("accepted", "accepted"),
                    ("bounced", "bounced"),
                    ("new", "new"),
                    ("opted_out", "opted out"),
                    ("sent", "sent"),
                    ("testified", "Testified"),
                    ("excluded", "Excluded"),
                    (None, None),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                null=True,
                verbose_name="referee state",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreferee",
            name="survey_token",
            field=models.CharField(
                blank=True, db_index=True, default=None, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalreport",
            name="file",
            field=models.TextField(
                blank=True,
                max_length=200,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "doc",
                            "docx",
                            "dot",
                            "dotx",
                            "docm",
                            "dotm",
                            "docb",
                            "odt",
                            "ott",
                            "oth",
                            "odm",
                            "rtf",
                            "tex",
                        ]
                    )
                ],
                verbose_name="Completed research report",
            ),
        ),
        migrations.AlterField(
            model_name="historicalround",
            name="testimonials_required",
            field=models.BooleanField(
                default=True,
                help_text="required uploaded testimonial/referee report file",
                verbose_name="testimonials required",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltestimonial",
            name="state",
            field=portal.models.StateField(
                choices=[
                    (None, None),
                    ("new", "New"),
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("excluded", "Excluded"),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                verbose_name="testimonial state",
            ),
        ),
        migrations.AlterField(
            model_name="identityverification",
            name="file",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                max_length=200,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="ids",
                verbose_name="Photo Identity",
            ),
        ),
        migrations.AlterField(
            model_name="letterofsupport",
            name="file",
            field=private_storage.fields.PrivateFileField(
                max_length=200,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="letters_of_support",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "odt",
                            "ott",
                            "oth",
                            "odm",
                            "doc",
                            "docx",
                            "docm",
                            "docb",
                        ]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="nomination",
            name="file",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                help_text="Upload filled-in nominator form",
                max_length=200,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="nominations",
                verbose_name="Nominator form",
            ),
        ),
        migrations.AlterField(
            model_name="personidentifiertype",
            name="description",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="referee",
            name="state",
            field=portal.models.StateField(
                blank=True,
                choices=[
                    ("accepted", "accepted"),
                    ("bounced", "bounced"),
                    ("new", "new"),
                    ("opted_out", "opted out"),
                    ("sent", "sent"),
                    ("testified", "Testified"),
                    ("excluded", "Excluded"),
                    (None, None),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                null=True,
                verbose_name="referee state",
            ),
        ),
        migrations.AlterField(
            model_name="referee",
            name="survey_token",
            field=models.CharField(
                blank=True, default=None, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="file",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                max_length=200,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="reports",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "doc",
                            "docx",
                            "dot",
                            "dotx",
                            "docm",
                            "dotm",
                            "docb",
                            "odt",
                            "ott",
                            "oth",
                            "odm",
                            "rtf",
                            "tex",
                        ]
                    )
                ],
                verbose_name="Completed research report",
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="testimonials_required",
            field=models.BooleanField(
                default=True,
                help_text="required uploaded testimonial/referee report file",
                verbose_name="testimonials required",
            ),
        ),
        migrations.AlterField(
            model_name="rounddocumenttemplate",
            name="file",
            field=models.FileField(
                max_length=200,
                upload_to=portal.models.round_template_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "csv",
                            "ctv",
                            "doc",
                            "docb",
                            "docm",
                            "docx",
                            "dot",
                            "dotm",
                            "dotx",
                            "odm",
                            "odt",
                            "oth",
                            "ott",
                            "rtf",
                            "tex",
                            "xls",
                            "xlsb",
                            "xlsm",
                            "xlsx",
                            "xlt",
                            "xltm",
                            "xltx",
                            "xlw",
                            "xml",
                        ]
                    )
                ],
                verbose_name="Template",
            ),
        ),
        migrations.AlterField(
            model_name="scoresheet",
            name="file",
            field=private_storage.fields.PrivateFileField(
                help_text="Upload filled-in for all the applications in bulk",
                max_length=200,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="score-sheets",
                verbose_name="Score Sheet",
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="state",
            field=portal.models.StateField(
                choices=[
                    (None, None),
                    ("new", "New"),
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("excluded", "Excluded"),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                verbose_name="testimonial state",
            ),
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False, null=True
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stared_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "favorite",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"], name="favorite_content_8de248_idx"
                    )
                ],
                "unique_together": {("user", "content_type", "object_id")},
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        # migrations.RemoveField(
        #     model_name="reportkeyword",
        #     name="keyword",
        # ),
        # migrations.RemoveField(
        #     model_name="reportkeyword",
        #     name="report",
        # ),
        migrations.AddField(
            model_name="historicalperson",
            name="is_active",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="is_active",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        # migrations.AlterField(
        #     model_name="contract",
        #     name="keywords",
        #     field=models.ManyToManyField(
        #         blank=True,
        #         db_table="contract_keyword",
        #         related_name="contracts",
        #         to="portal.keyword",
        #         verbose_name="Keywords",
        #     ),
        # ),
        migrations.AlterField(
            model_name="historicalperson",
            name="gender",
            field=common.models.FixedCharField(
                choices=[
                    ("X", "Prefer not to say"),
                    ("N", "Prefer not to answer"),
                    ("M", "Male"),
                    ("F", "Female"),
                    ("D", "Gender diverse"),
                ],
                db_comment="X: Prefer not to say\nN: Prefer not to answer\nM: Male\nF: Female\nD: Gender diverse",
                max_length=1,
                null=True,
                verbose_name="gender",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="gender",
            field=common.models.FixedCharField(
                choices=[
                    ("X", "Prefer not to say"),
                    ("N", "Prefer not to answer"),
                    ("M", "Male"),
                    ("F", "Female"),
                    ("D", "Gender diverse"),
                ],
                db_comment="X: Prefer not to say\nN: Prefer not to answer\nM: Male\nF: Female\nD: Gender diverse",
                max_length=1,
                null=True,
                verbose_name="gender",
            ),
        ),
        # migrations.AlterField(
        #     model_name="report",
        #     name="keywords",
        #     field=models.ManyToManyField(
        #         blank=True,
        #         db_table="report_keyword",
        #         related_name="reports",
        #         to="portal.keyword",
        #         verbose_name="Keywords",
        #     ),
        # ),
        migrations.CreateModel(
            name="ReportTemlate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "ordering",
                    models.PositiveIntegerField(db_index=True, default=0, verbose_name="ordering"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "type",
                    common.models.FixedCharField(
                        choices=[
                            ("A", "Annual"),
                            ("E", "Exchange"),
                            ("F", "Final"),
                            ("I", "Interim"),
                            ("L", "Follow up"),
                        ],
                        help_text="Reporting Type",
                        max_length=1,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=portal.models.round_template_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "doc",
                                    "docx",
                                    "dot",
                                    "dotx",
                                    "docm",
                                    "dotm",
                                    "docb",
                                    "odt",
                                    "ott",
                                    "oth",
                                    "odm",
                                    "rtf",
                                    "tex",
                                ]
                            )
                        ],
                        verbose_name="Application Template",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_templates",
                        to="portal.round",
                    ),
                ),
            ],
            options={
                "db_table": "report_template",
                "ordering": ["ordering"],
                "abstract": False,
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        # migrations.DeleteModel(
        #     name="ContractKeyword",
        # ),
        # migrations.DeleteModel(
        #     name="ReportKeyword",
        # ),
    ]
