# Generated by Django 5.1.14 on 2025-11-20 04:24

import common.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import portal.models
import private_storage.fields
import private_storage.storage.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0066_note_remove_reportkeyword_keyword_and_more"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="reportkeyword",
        #     name="keyword",
        # ),
        # migrations.RemoveField(
        #     model_name="reportkeyword",
        #     name="report",
        # ),
        migrations.RemoveField(
            model_name="reporttemlate",
            name="round",
        ),
        migrations.AlterField(
            model_name="changerequestcommentattachment",
            name="attachment",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                max_length=400,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="change_requests",
                verbose_name="attachment",
            ),
        ),
        # migrations.AlterField(
        #     model_name="contract",
        #     name="keywords",
        #     field=models.ManyToManyField(
        #         blank=True,
        #         db_table="contract_keyword",
        #         related_name="contracts",
        #         to="portal.keyword",
        #         verbose_name="Keywords",
        #     ),
        # ),
        migrations.AlterField(
            model_name="contractcommentattachment",
            name="attachment",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                max_length=400,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="contracts",
                verbose_name="attachment",
            ),
        ),
        # migrations.AlterField(
        #     model_name="report",
        #     name="keywords",
        #     field=models.ManyToManyField(
        #         blank=True,
        #         db_table="report_keyword",
        #         related_name="reports",
        #         to="portal.keyword",
        #         verbose_name="Keywords",
        #     ),
        # ),
        migrations.AlterField(
            model_name="reportcommentattachment",
            name="attachment",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                max_length=400,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="reports",
                verbose_name="attachment",
            ),
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("recipient", models.CharField(db_index=True, max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[("to", "to"), ("cc", "cc"), ("bcc", "bcc")], max_length=10
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="portal.maillog",
                    ),
                ),
            ],
            options={
                "db_table": "recipient",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "ordering",
                    models.PositiveIntegerField(db_index=True, default=0, verbose_name="ordering"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "type",
                    common.models.FixedCharField(
                        choices=[
                            ("A", "Annual"),
                            ("E", "Exchange"),
                            ("F", "Final"),
                            ("I", "Interim"),
                            ("L", "Follow up"),
                        ],
                        help_text="Reporting Type",
                        max_length=1,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=portal.models.round_template_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "doc",
                                    "docx",
                                    "dot",
                                    "dotx",
                                    "docm",
                                    "dotm",
                                    "docb",
                                    "odt",
                                    "ott",
                                    "oth",
                                    "odm",
                                    "rtf",
                                    "tex",
                                ]
                            )
                        ],
                        verbose_name="Application Template",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_templates",
                        to="portal.round",
                    ),
                ),
            ],
            options={
                "db_table": "report_template",
                "ordering": ["ordering"],
                "abstract": False,
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        # migrations.DeleteModel(
        #     name="ContractKeyword",
        # ),
        # migrations.DeleteModel(
        #     name="ReportKeyword",
        # ),
        # migrations.DeleteModel(
        #     name="ReportTemlate",
        # ),
    ]
