# Generated by Django 5.1.14 on 2025-12-19 08:02

import common.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import portal.models
import private_storage.fields
import private_storage.storage.files
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0066_note_remove_reportkeyword_keyword_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ReportTemlate",
            new_name="ReportTemplate",
        ),
        # migrations.RemoveField(
        #     model_name="reportkeyword",
        #     name="keyword",
        # ),
        # migrations.RemoveField(
        #     model_name="reportkeyword",
        #     name="report",
        # ),
        migrations.AlterModelOptions(
            name="currency",
            options={"verbose_name_plural": "currencies"},
        ),
        migrations.RemoveField(
            model_name="historicalreportedfunding",
            name="state",
        ),
        migrations.RemoveField(
            model_name="reportedfunding",
            name="state",
        ),
        migrations.AddField(
            model_name="historicalmember",
            name="cv",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="portal.curriculumvitae",
                verbose_name="curriculum vitae",
            ),
        ),
        migrations.AddField(
            model_name="historicalmember",
            name="research_experience_in_years",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="research experience in years "
            ),
        ),
        migrations.AddField(
            model_name="historicalnomination",
            name="state_changed_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="notify_ro_on_application_submission",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="replaced_org",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                help_text="The organisation that replaced this one.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="portal.organisation",
            ),
        ),
        migrations.AddField(
            model_name="historicalreportedfunding",
            name="agency_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalreportedfunding",
            name="status",
            field=common.models.FixedCharField(
                blank=True,
                choices=[
                    (None, "N/A"),
                    ("I", "In preparation"),
                    ("S", "Submitted"),
                    ("A", "Awarded"),
                    ("U", "Unsuccessful"),
                ],
                max_length=1,
                null=True,
                verbose_name="status",
            ),
        ),
        migrations.AddField(
            model_name="historicalround",
            name="final_report_deferral",
            field=models.SmallIntegerField(
                blank=True, help_text="Final report deferral in months", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalround",
            name="member_letter_of_support_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalround",
            name="member_research_experience_in_years_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalround",
            name="proposed_start_date_stats_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="cv",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="members",
                to="portal.curriculumvitae",
                verbose_name="curriculum vitae",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="research_experience_in_years",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="research experience in years "
            ),
        ),
        migrations.AddField(
            model_name="nomination",
            name="state_changed_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="state", null=True
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="notify_ro_on_application_submission",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organisation",
            name="replaced_org",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="The organisation that replaced this one.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="portal.organisation",
            ),
        ),
        migrations.AddField(
            model_name="reportedfunding",
            name="agency_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="reportedfunding",
            name="status",
            field=common.models.FixedCharField(
                blank=True,
                choices=[
                    (None, "N/A"),
                    ("I", "In preparation"),
                    ("S", "Submitted"),
                    ("A", "Awarded"),
                    ("U", "Unsuccessful"),
                ],
                max_length=1,
                null=True,
                verbose_name="status",
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="final_report_deferral",
            field=models.SmallIntegerField(
                blank=True, help_text="Final report deferral in months", null=True
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="member_letter_of_support_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="round",
            name="member_research_experience_in_years_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="round",
            name="proposed_start_date_stats_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="applicationdocument",
            name="document_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application_documents",
                to="portal.documenttype",
            ),
        ),
        migrations.AlterField(
            model_name="changerequest",
            name="derivative",
            field=models.OneToOneField(
                blank=True,
                help_text="Derivative contract (variation or extension)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="originated_by",
                to="portal.contract",
            ),
        ),
        migrations.AlterField(
            model_name="changerequest",
            name="file",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                max_length=200,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="changes",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "doc",
                            "docb",
                            "docm",
                            "docx",
                            "dot",
                            "dotm",
                            "dotx",
                            "odm",
                            "odt",
                            "oth",
                            "ott",
                            "pdf",
                            "rtf",
                            "tex",
                            "xls",
                            "xlsx",
                        ]
                    )
                ],
                verbose_name="Request Letter",
            ),
        ),
        migrations.AlterField(
            model_name="changerequest",
            name="state",
            field=portal.models.StateField(
                choices=[
                    ("draft", "WIP"),
                    ("acknowledged", "Acknowledged"),
                    ("cancelled", "Cancelled"),
                    ("declined", "Declined"),
                    ("submitted", "Received"),
                    ("accepted", "Under Review"),
                    ("approved", "Approved"),
                    ("withdrawn", "Withdrawn"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=100,
                no_check_for_status=True,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="changerequest",
            name="submitted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="change_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="changerequestcommentattachment",
            name="attachment",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                max_length=400,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="change_requests",
                verbose_name="attachment",
            ),
        ),
        # migrations.AlterField(
        #     model_name="contract",
        #     name="keywords",
        #     field=models.ManyToManyField(
        #         blank=True,
        #         db_table="contract_keyword",
        #         related_name="contracts",
        #         to="portal.keyword",
        #         verbose_name="Keywords",
        #     ),
        # ),
        migrations.AlterField(
            model_name="contractcommentattachment",
            name="attachment",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                max_length=400,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="contracts",
                verbose_name="attachment",
            ),
        ),
        migrations.AlterField(
            model_name="historicalmember",
            name="state",
            field=portal.models.StateField(
                blank=True,
                choices=[
                    ("accepted", "accepted"),
                    ("authorized", "authorized"),
                    ("bounced", "bounced"),
                    ("new", "new"),
                    ("opted_out", "opted out"),
                    ("sent", "sent"),
                    (None, None),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                null=True,
                verbose_name="&nbsp;",
            ),
        ),
        migrations.AlterField(
            model_name="historicalnomination",
            name="state",
            field=portal.models.StateField(
                blank=True,
                choices=[
                    ("accepted", "accepted"),
                    ("bounced", "bounced"),
                    ("draft", "draft"),
                    ("new", "new"),
                    ("sent", "sent"),
                    ("submitted", "submitted"),
                    ("withdrawn", "withdrawn"),
                    ("archived", "Archived"),
                    (None, None),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                null=True,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="historicalperson",
            name="gender",
            field=common.models.FixedCharField(
                blank=True,
                choices=[
                    ("X", "Blank / Prefer not to answer"),
                    ("M", "Male"),
                    ("F", "Female"),
                    ("D", "Another gender"),
                ],
                db_comment="X: Blank / Prefer not to answer\nM: Male\nF: Female\nD: Another gender",
                max_length=1,
                null=True,
                verbose_name="gender",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreferee",
            name="state",
            field=portal.models.StateField(
                blank=True,
                choices=[
                    ("accepted", "accepted"),
                    ("bounced", "bounced"),
                    ("new", "new"),
                    ("opted_out", "opted out"),
                    ("sent", "sent"),
                    ("testified", "Testified"),
                    ("excluded", "Excluded"),
                    (None, None),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                null=True,
                verbose_name="&nbsp;",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreport",
            name="file",
            field=models.TextField(
                blank=True,
                max_length=200,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "doc",
                            "docx",
                            "dot",
                            "dotx",
                            "docm",
                            "dotm",
                            "docb",
                            "odt",
                            "ott",
                            "oth",
                            "odm",
                            "pdf",
                            "rtf",
                            "tex",
                        ]
                    )
                ],
                verbose_name="Completed research report",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreport",
            name="state",
            field=portal.models.StateField(
                choices=[
                    ("accepted", "Accepted"),
                    ("acknowledged", "Acknowledged"),
                    ("approved", "Approved"),
                    ("assessed", "Assessed"),
                    ("archived", "Archived"),
                    ("cancelled", "Cancelled"),
                    ("draft", "Draft"),
                    ("new", "New"),
                    ("submitted", "Submitted"),
                    ("reported", "Reported"),
                    ("assigned", "Assigned"),
                ],
                default="draft",
                max_length=100,
                no_check_for_status=True,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreportedfunding",
            name="agency",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="portal.organisation",
                verbose_name="Funding agency",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreportedfunding",
            name="share",
            field=models.PositiveSmallIntegerField(
                default=100,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Share available",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltestimonial",
            name="state",
            field=portal.models.StateField(
                choices=[
                    ("new", "New"),
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("excluded", "Excluded"),
                    ("archived", "Archived"),
                    (None, None),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                verbose_name="testimonial state",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="state",
            field=portal.models.StateField(
                blank=True,
                choices=[
                    ("accepted", "accepted"),
                    ("authorized", "authorized"),
                    ("bounced", "bounced"),
                    ("new", "new"),
                    ("opted_out", "opted out"),
                    ("sent", "sent"),
                    (None, None),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                null=True,
                verbose_name="&nbsp;",
            ),
        ),
        migrations.AlterField(
            model_name="nomination",
            name="state",
            field=portal.models.StateField(
                blank=True,
                choices=[
                    ("accepted", "accepted"),
                    ("bounced", "bounced"),
                    ("draft", "draft"),
                    ("new", "new"),
                    ("sent", "sent"),
                    ("submitted", "submitted"),
                    ("withdrawn", "withdrawn"),
                    ("archived", "Archived"),
                    (None, None),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                null=True,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="gender",
            field=common.models.FixedCharField(
                blank=True,
                choices=[
                    ("X", "Blank / Prefer not to answer"),
                    ("M", "Male"),
                    ("F", "Female"),
                    ("D", "Another gender"),
                ],
                db_comment="X: Blank / Prefer not to answer\nM: Male\nF: Female\nD: Another gender",
                max_length=1,
                null=True,
                verbose_name="gender",
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="url",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="referee",
            name="state",
            field=portal.models.StateField(
                blank=True,
                choices=[
                    ("accepted", "accepted"),
                    ("bounced", "bounced"),
                    ("new", "new"),
                    ("opted_out", "opted out"),
                    ("sent", "sent"),
                    ("testified", "Testified"),
                    ("excluded", "Excluded"),
                    (None, None),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                null=True,
                verbose_name="&nbsp;",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="file",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                max_length=200,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="reports",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "doc",
                            "docx",
                            "dot",
                            "dotx",
                            "docm",
                            "dotm",
                            "docb",
                            "odt",
                            "ott",
                            "oth",
                            "odm",
                            "pdf",
                            "rtf",
                            "tex",
                        ]
                    )
                ],
                verbose_name="Completed research report",
            ),
        ),
        # migrations.AlterField(
        #     model_name="report",
        #     name="keywords",
        #     field=models.ManyToManyField(
        #         blank=True,
        #         db_table="report_keyword",
        #         related_name="reports",
        #         to="portal.keyword",
        #         verbose_name="Keywords",
        #     ),
        # ),
        migrations.AlterField(
            model_name="report",
            name="state",
            field=portal.models.StateField(
                choices=[
                    ("accepted", "Accepted"),
                    ("acknowledged", "Acknowledged"),
                    ("approved", "Approved"),
                    ("assessed", "Assessed"),
                    ("archived", "Archived"),
                    ("cancelled", "Cancelled"),
                    ("draft", "Draft"),
                    ("new", "New"),
                    ("submitted", "Submitted"),
                    ("reported", "Reported"),
                    ("assigned", "Assigned"),
                ],
                default="draft",
                max_length=100,
                no_check_for_status=True,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="reportcommentattachment",
            name="attachment",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                max_length=400,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="reports",
                verbose_name="attachment",
            ),
        ),
        migrations.AlterField(
            model_name="reportedfunding",
            name="agency",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portal.organisation",
                verbose_name="Funding agency",
            ),
        ),
        migrations.AlterField(
            model_name="reportedfunding",
            name="share",
            field=models.PositiveSmallIntegerField(
                default=100,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Share available",
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="state",
            field=portal.models.StateField(
                choices=[
                    ("new", "New"),
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("excluded", "Excluded"),
                    ("archived", "Archived"),
                    (None, None),
                ],
                default="new",
                max_length=100,
                no_check_for_status=True,
                verbose_name="testimonial state",
            ),
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("recipient", models.CharField(db_index=True, max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[("to", "to"), ("cc", "cc"), ("bcc", "bcc")], max_length=10
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="portal.maillog",
                    ),
                ),
            ],
            options={
                "db_table": "recipient",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ReportedHostedVisit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("orcid", models.CharField(blank=True, editable=False, max_length=20, null=True)),
                (
                    "put_code",
                    models.PositiveIntegerField(
                        blank=True, editable=False, null=True, verbose_name="put-code"
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True, verbose_name="start date")),
                ("end_date", models.DateField(blank=True, null=True, verbose_name="end date")),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=2000, null=True, verbose_name="description"
                    ),
                ),
                ("organisation", models.CharField(max_length=200, verbose_name="organisation")),
                (
                    "visitor",
                    models.CharField(
                        blank=True, max_length=400, null=True, verbose_name="person name"
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        db_column="country",
                        default="NZ",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="portal.country",
                        verbose_name="country",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portal.reportedeffort",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hosted_visits",
                        to="portal.organisation",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_visits",
                        to="portal.report",
                    ),
                ),
            ],
            options={
                "db_table": "reported_hosted_visit",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        # migrations.DeleteModel(
        #     name="ContractKeyword",
        # ),
        # migrations.DeleteModel(
        #     name="ReportKeyword",
        # ),
    ]
