# Generated by Django 6.0.4 on 2026-05-06 01:02

import common.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0069_remove_reportkeyword_keyword_and_more"),
        ("sites", "0004_auto_20210331_1418"),
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "db_table": "assessment",
            },
            bases=(common.models.HelperMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name="publicationtype",
            options={"ordering": ["ordering"]},
        ),
        migrations.AddField(
            model_name="historicalmember",
            name="is_postdoc",
            field=models.BooleanField(
                blank=True,
                db_comment="imported from legacy datam, not editable",
                default=True,
                editable=False,
                help_text="imported from legacy data, not editable",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalmember",
            name="person",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="portal.person",
            ),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="is_approved_host",
            field=models.BooleanField(
                default=False, help_text="The organisation is an approved host institution"
            ),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="is_verified",
            field=models.BooleanField(
                default=False, help_text="The organisation details have been verified"
            ),
        ),
        migrations.AddField(
            model_name="historicalorganisation",
            name="site",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=common.models.Model.get_current_site_id,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sites.site",
            ),
        ),
        migrations.AddField(
            model_name="historicalperson",
            name="has_deceased",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="member",
            name="is_postdoc",
            field=models.BooleanField(
                blank=True,
                db_comment="imported from legacy datam, not editable",
                default=True,
                editable=False,
                help_text="imported from legacy data, not editable",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="person",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="portal.person",
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="is_approved_host",
            field=models.BooleanField(
                default=False, help_text="The organisation is an approved host institution"
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="is_verified",
            field=models.BooleanField(
                default=False, help_text="The organisation details have been verified"
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="site",
            field=models.ForeignKey(
                default=common.models.Model.get_current_site_id,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="sites.site",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="has_deceased",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="publicationtype",
            name="definition",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publicationtype",
            name="ordering",
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name="ordering"),
        ),
        migrations.AlterField(
            model_name="application",
            name="cv",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="portal.curriculumvitae",
                verbose_name="curriculum vitae",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="duration_in_days",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Proposed contract duration in days",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Duration in days",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="number",
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name="number"),
        ),
        migrations.AlterField(
            model_name="historicalapplication",
            name="duration_in_days",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Proposed contract duration in days",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Duration in days",
            ),
        ),
        migrations.AlterField(
            model_name="historicalapplication",
            name="number",
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name="number"),
        ),
        # migrations.AlterField(
        #     model_name="historicalperson",
        #     name="hash_id",
        #     field=models.GeneratedField(
        #         db_column="hash_id",
        #         db_persist=True,
        #         expression=models.Func(
        #             models.F("id"),
        #             function="hex",
        #             output_field=models.CharField(editable=False, max_length=32, unique=True),
        #             template="%(function)s(%(expressions)s)",
        #         ),
        #         output_field=models.CharField(editable=False, max_length=32, unique=True),
        #     ),
        # ),
        # migrations.AlterField(
        #     model_name="person",
        #     name="hash_id",
        #     field=models.GeneratedField(
        #         db_column="hash_id",
        #         db_persist=True,
        #         expression=models.Func(
        #             models.F("id"),
        #             function="hex",
        #             output_field=models.CharField(editable=False, max_length=32, unique=True),
        #             template="%(function)s(%(expressions)s)",
        #         ),
        #         output_field=models.CharField(editable=False, max_length=32, unique=True),
        #     ),
        # ),
        migrations.AlterField(
            model_name="reportedfunding",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="funding",
                to="portal.report",
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(
                fields=("number", "is_preliminary"), name="unique_proposal"
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="assessor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to="portal.report",
            ),
        ),
    ]
