# Generated by Django 6.0.5 on 2026-05-29 04:00

import common.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0070_historicalperson_phone_person_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocation",
            name="contract_yr",
            field=models.DateField(blank=True, null=True, verbose_name="Contract Year"),
        ),
        migrations.AddField(
            model_name="allocation",
            name="financial_yr",
            field=models.DateField(blank=True, null=True, verbose_name="Financial Year"),
        ),
        migrations.AddField(
            model_name="contractmember",
            name="country",
            field=models.ForeignKey(
                blank=True,
                db_column="imported from stage.contract_member.country",
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="portal.country",
            ),
        ),
        migrations.AddField(
            model_name="contractmember",
            name="is_postdoc",
            field=models.BooleanField(
                blank=True,
                db_comment="imported from stage.contract_member.is_postdoc",
                default=None,
                editable=False,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contractmember",
            name="name",
            field=models.CharField(
                blank=True,
                db_comment="imported from stage.contract_member.person_name",
                editable=False,
                max_length=400,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contractmember",
            name="org",
            field=models.ForeignKey(
                blank=True,
                db_column="imported from stage.contract_member.institution",
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="portal.organisation",
            ),
        ),
        migrations.AddField(
            model_name="contractmember",
            name="person",
            field=models.ForeignKey(
                blank=True,
                db_comment="imported from stage.person",
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="portal.person",
            ),
        ),
        migrations.AddField(
            model_name="historicalallocation",
            name="contract_yr",
            field=models.DateField(blank=True, null=True, verbose_name="Contract Year"),
        ),
        migrations.AddField(
            model_name="historicalallocation",
            name="financial_yr",
            field=models.DateField(blank=True, null=True, verbose_name="Financial Year"),
        ),
        migrations.AddField(
            model_name="historicalcontractmember",
            name="country",
            field=models.ForeignKey(
                blank=True,
                db_column="imported from stage.contract_member.country",
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="portal.country",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontractmember",
            name="is_postdoc",
            field=models.BooleanField(
                blank=True,
                db_comment="imported from stage.contract_member.is_postdoc",
                default=None,
                editable=False,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcontractmember",
            name="name",
            field=models.CharField(
                blank=True,
                db_comment="imported from stage.contract_member.person_name",
                editable=False,
                max_length=400,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcontractmember",
            name="org",
            field=models.ForeignKey(
                blank=True,
                db_column="imported from stage.contract_member.institution",
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="portal.organisation",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontractmember",
            name="person",
            field=models.ForeignKey(
                blank=True,
                db_comment="imported from stage.person",
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="portal.person",
            ),
        ),
        migrations.AddField(
            model_name="historicalperson",
            name="org",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="portal.organisation",
                verbose_name="organisation",
            ),
        ),
        migrations.AddField(
            model_name="historicalreport",
            name="assessment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="org",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personnel",
                to="portal.organisation",
                verbose_name="organisation",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="assessment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
