# DATE_FORMAT = "d/m/Y"
DATE_FORMAT = "j/n/Y"
# TIME_FORMAT = "H:i"
TIME_FORMAT = "g:i A"
DATETIME_FORMAT = f"{DATE_FORMAT} {TIME_FORMAT}"
SHORT_DATETIME_FORMAT = DATETIME_FORMAT
SHORT_DATE_FORMAT = DATE_FORMAT
