# Generated by Django 4.2.3 on 2023-07-28 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0037_category_documenttype_title_and_more"),
        ("users", "0005_alter_user_staff_of_sites"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicaluser",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical user",
                "verbose_name_plural": "historical users",
            },
        ),
        migrations.AlterField(
            model_name="historicaluser",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaluser",
            name="title",
            field=models.ForeignKey(
                blank=True,
                db_column="title",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="portal.title",
                verbose_name="title",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="title",
            field=models.ForeignKey(
                blank=True,
                db_column="title",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="portal.title",
                verbose_name="title",
            ),
        ),
    ]
