# Generated by Django 4.2.3 on 2023-08-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_historicaluser_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluser",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
    ]
