From jddskiwgwg2023@gmail.com  Tue Sep 10 17:11:40 2024
Return-Path: <jddskiwgwg2023@gmail.com>
X-Original-To: noreply@portal.pmspaceprizes.org.nz
Delivered-To: noreply@portal.pmspaceprizes.org.nz
Received: from mail-yw1-f174.google.com (mail-yw1-f174.google.com [209.85.128.174])
	by portal.pmscienceprizes.org.nz (Postfix) with ESMTPS id 04186FAEB3
	for <noreply@portal.pmspaceprizes.org.nz>; Tue, 10 Sep 2024 17:11:40 +1200 (NZST)
Received: by mail-yw1-f174.google.com with SMTP id 00721157ae682-6db20e22c85so43606607b3.0
        for <noreply@portal.pmspaceprizes.org.nz>; Mon, 09 Sep 2024 22:11:39 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20230601; t=1725945098; x=1726549898; darn=portal.pmspaceprizes.org.nz;
        h=auto-submitted:precedence:content-disposition
         :content-transfer-encoding:mime-version:subject:references
         :in-reply-to:message-id:date:from:to:from:to:cc:subject:date
         :message-id:reply-to;
        bh=O+DN/ZUb1aJ1x78RSOkVvqdukd598ZBBf4IgYLr7VX8=;
        b=IknslpOa5jnHSgJmgx/2Kr9t2m7dKKHw1y7OG1hsUylDo+7q9v/xTJ0o3SHiGN/HBA
         lSYarSWZon+u6Fr8e5ArtzrhoqycryTjUtlJ0FbTclAXwoXTmdBCJ5sI4DWSxizSCZkb
         2B7Mtg8bUyEJmwUtL9xdXdWETlWTyn1iSCPmNwemLsl/0rEnS3tvHuXVlO9UDbm/OoKo
         K8+7cwNY5k8Z9yom2w2+OW8wo76yOCNFdBdQgQMW+8btmUieyG/9+zV53p+hyElC8xQe
         fFdtUh61hDQj/HZ/GnGfmAtYAXlOJI16oXGBovFw6i96B0nr7LpwXX7s8xSOQ5ZCJ7w3
         r1fg==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20230601; t=1725945098; x=1726549898;
        h=auto-submitted:precedence:content-disposition
         :content-transfer-encoding:mime-version:subject:references
         :in-reply-to:message-id:date:from:to:x-gm-message-state:from:to:cc
         :subject:date:message-id:reply-to;
        bh=O+DN/ZUb1aJ1x78RSOkVvqdukd598ZBBf4IgYLr7VX8=;
        b=JpIQCGaRKc8HjILLM5ddraiZZmudlifP3q0nP/I39DSdyk6hshwNLzHeIGCLqiJ2v6
         mI+p1lF7pJLf/FZDSXR3RpaIfeEfXTEtfAZGRorYfIhg1hu+1TpmJRI+W73HxxTeEdYl
         0Gnf8GvF6k5hme7YIO1/D+7TeXyTHwX2GLm7kizpXFrAVZvLGHFKH7dMEsaV8ltRTHmu
         mv6ceXaGmVMso4M2GARK5JuAILE8Euhx09i0SRGuEAjPkvchIhoCNKLgtTOs2K8dOPhk
         gRrRfvNYRL7DVF5TIRlAmW1TxSV9w+2EGpwgO866O0mqoz5aNWVnFUccY2dJpDm1q6cw
         XNcw==
X-Gm-Message-State: AOJu0Yyw4l7x9Jh9+FDsJbZyMF7yCdBLKg2vFNv8cIpJMIo5SPVQujGA
	t09Cjaok/hqBUzd7BqhaD19v5lB8oRdBCyQ1Cvlvl58SFHSofjodmEda5uhRNTJN0HgpdxWfK2I
	kq03XNHU9yAQZmhlQYTFzaqyulrbV39g6nBWsmHm4G+QOfxaq6/pFSsj7bcN9pXnkV/jvM5/dJd
	TovCFx
X-Google-Smtp-Source: AGHT+IEV/vIDUJ+mjcztB7cnuYfU+xUUO1HcMU/Oh2pKfkcHSnN8ifyo/TpGRyxzdtADC7xKfYdCRyVwM3aZt+DSvtCHIQ2PSZM5F/mXAGwM
X-Received: by 2002:a05:690c:460b:b0:64a:b33a:d954 with SMTP id 00721157ae682-6db45156672mr100972907b3.23.1725945098084;
        Mon, 09 Sep 2024 22:11:38 -0700 (PDT)
To: noreply@portal.pmspaceprizes.org.nz
From: Tester Testeron <jddskiwgwg2023@gmail.com>
Date: Mon, 9 Sep 2024 22:11:37 -0700
Message-ID: <CAA1CNSL7K1ZyhMAfiioxCE5TUTOknFES_N2j_3h3cAxkjtk0sQ@mail.gmail.com>
In-Reply-To: <N1vuYCdndY2N9w@portal.pmspaceprizes.org.nz>
References: <N1vuYCdndY2N9w@portal.pmspaceprizes.org.nz>
Subject: Re: [PM Space Prizes] You have been given access to the PM Space Prizes portal
MIME-Version: 1.0
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: base64
Content-Disposition: inline
Precedence: bulk
X-Autoreply: yes
Auto-Submitted: auto-replied
Status: RO
Content-Length: 3453
Lines: 45

PGRpdiBkaXI9Imx0ciI+dGVzdCB0ZXN0IHRlc3Q8ZGl2Pm5vdCBob21lwqA8L2Rpdj48L2Rpdj48
YnIvPjxici8+LS0gPGJyLz48ZGl2IGRpcj0ibHRyIj48ZGl2PjxkaXYgZGlyPSJsdHIiPjxkaXY+
PGRpdiBkaXI9Imx0ciI+PGRpdiBkaXI9Imx0ciI+PGRpdiBzdHlsZT0iZm9udC1mYW1pbHk6JnF1
b3Q7VGltZXMgTmV3IFJvbWFuJnF1b3Q7O2ZvbnQtc2l6ZToxNnB4O21hcmdpbi10b3A6MHB4O21h
cmdpbi1ib3R0b206MHB4Ij48ZGl2IHN0eWxlPSJmb250LWZhbWlseTpBcmlhbCxIZWx2ZXRpY2Es
c2Fucy1zZXJpZjtmb250LXNpemU6c21hbGw7bWFyZ2luLXRvcDowcHg7bWFyZ2luLWJvdHRvbTow
cHgiPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTomcXVvdDtUaW1lcyBOZXcgUm9tYW4mcXVvdDsi
Pjxmb250IGZhY2U9ImdhcmFtb25kLCBzZXJpZiI+UmFkb21pcnMgQ2lyc2tpcyBBV1PCoDwvZm9u
dD48L3NwYW4+PGZvbnQgZmFjZT0iZ2FyYW1vbmQsIHNlcmlmIj5DU0EswqA8L2ZvbnQ+PHNwYW4g
c3R5bGU9ImZvbnQtZmFtaWx5OiZxdW90O1RpbWVzIE5ldyBSb21hbiZxdW90OyI+PGZvbnQgZmFj
ZT0iZ2FyYW1vbmQsIHNlcmlmIj5NQ0RCQTwvZm9udD48L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQt
ZmFtaWx5OiZxdW90O1RpbWVzIE5ldyBSb21hbiZxdW90OyI+PGZvbnQgZmFjZT0iZ2FyYW1vbmQs
IHNlcmlmIj4swqA8L2ZvbnQ+PC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTomcXVvdDtU
aW1lcyBOZXcgUm9tYW4mcXVvdDsiPjxmb250IGZhY2U9ImdhcmFtb25kLCBzZXJpZiI+TUNBRCw8
L2ZvbnQ+PC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTomcXVvdDtUaW1lcyBOZXcgUm9t
YW4mcXVvdDsiPjxmb250IGZhY2U9ImdhcmFtb25kLCBzZXJpZiI+wqA8L2ZvbnQ+PC9zcGFuPjxz
cGFuIHN0eWxlPSJmb250LWZhbWlseTomcXVvdDtUaW1lcyBOZXcgUm9tYW4mcXVvdDsiPjxmb250
IGZhY2U9ImdhcmFtb25kLCBzZXJpZiI+TUNTRDwvZm9udD48L3NwYW4+PHNwYW4gc3R5bGU9ImZv
bnQtZmFtaWx5OiZxdW90O1RpbWVzIE5ldyBSb21hbiZxdW90OyI+PGZvbnQgZmFjZT0iZ2FyYW1v
bmQsIHNlcmlmIj4swqA8L2ZvbnQ+PC9zcGFuPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTomcXVv
dDtUaW1lcyBOZXcgUm9tYW4mcXVvdDsiPjxmb250IGZhY2U9ImdhcmFtb25kLCBzZXJpZiI+WkNF
PC9mb250Pjxmb250IGZhY2U9ImdhcmFtb25kLCBzZXJpZiI+LCBTY3J1bSBNYXN0ZXI8L2ZvbnQ+
PC9zcGFuPjwvZGl2PjxkaXYgc3R5bGU9ImZvbnQtZmFtaWx5OkFyaWFsLEhlbHZldGljYSxzYW5z
LXNlcmlmO2ZvbnQtc2l6ZTpzbWFsbDttYXJnaW4tdG9wOjBweDttYXJnaW4tYm90dG9tOjBweCI+
PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OiZxdW90O1RpbWVzIE5ldyBSb21hbiZxdW90OyI+PGZv
bnQgZmFjZT0iZ2FyYW1vbmQsIHNlcmlmIj5NOiArNjQgMjIxIDIyMSA0NDIgfCBFOsKgPGEgaHJl
Zj0ibWFpbHRvOnJhZEBub3dpdHdvcmtzLmV1IiB0YXJnZXQ9Il9ibGFuayI+UkFEQG5vd0lUd29y
a3MuZXU8L2E+PC9mb250Pjwvc3Bhbj48L2Rpdj48ZGl2IHN0eWxlPSJmb250LWZhbWlseTpBcmlh
bCxIZWx2ZXRpY2Esc2Fucy1zZXJpZjtmb250LXNpemU6c21hbGw7bWFyZ2luLXRvcDowcHg7bWFy
Z2luLWJvdHRvbTowcHgiPjxhIGhyZWY9Imh0dHA6Ly9uei5saW5rZWRpbi5jb20vaW4vbmFkMjAw
MCIgdGFyZ2V0PSJfYmxhbmsiPjxpbWcgc3JjPSJodHRwczovL2NpNi5nb29nbGV1c2VyY29udGVu
dC5jb20vcHJveHkvVkxpWWhmRWRhczIwalNsQ09mN05oNFdmaWlCLUoyYU9CWlZZQ0FpaFFmTEJB
VTlWYXVudEhUbm5DVEVCZzIwSkVnbkljdHo1ZUNVR2psWUVCX052ZXZTLUM3ME8zLUY0emRfY21v
V1NYNmY0cEZEdjNRaFBLOHpaOWl4QVNEbjE9czAtZC1lMS1mdCNodHRwOi8vcy5jLmxua2QubGlj
ZG4uY29tL3NjZHMvY29tbW9uL3UvaW1nL3dlYnByb21vL2J0bl92aWV3bXlfMTYweDI1LnBuZyIg
d2lkdGg9IjE2MCIgaGVpZ2h0PSIyNSIgYWx0PSJWaWV3IG15IHByb2ZpbGUgb24gTGlua2VkSW4i
IHN0eWxlPSJtYXJnaW46MHB4IDBweCA1cHg7cGFkZGluZzowcHg7Ym9yZGVyOm5vbmU7b3V0bGlu
ZTowcHg7Zm9udC1zaXplOjExcHg7Zm9udC1mYW1pbHk6SGVsdmV0aWNhLEZyZWVTYW5zLCZxdW90
O0xpYmVyYXRpb24gU2FucyZxdW90OyxIZWxtZXQsQXJpYWwsc2Fucy1zZXJpZjt2ZXJ0aWNhbC1h
bGlnbjpiYXNlbGluZTtjb2xvcjpyZ2IoMTAyLDEwMiwxMDIpO2xpbmUtaGVpZ2h0OjEzcHg7dGV4
dC1hbGlnbjpjZW50ZXIiPjwvYT48c3BhbiBzdHlsZT0iY29sb3I6cmdiKDEwMiwxMDIsMTAyKTts
aW5lLWhlaWdodDoxM3B4O3RleHQtYWxpZ246Y2VudGVyIj48Zm9udCBmYWNlPSJIZWx2ZXRpY2Es
IEZyZWVTYW5zLCBMaWJlcmF0aW9uIFNhbnMsIEhlbG1ldCwgQXJpYWwsIHNhbnMtc2VyaWYiPjxz
cGFuIHN0eWxlPSJmb250LXNpemU6MTFweCI+wqA8L3NwYW4+PC9mb250Pjwvc3Bhbj48L2Rpdj48
L2Rpdj48L2Rpdj48L2Rpdj48L2Rpdj48L2Rpdj48L2Rpdj48L2Rpdj48YnIvPg0K

