From MAILER-DAEMON  Mon Sep  2 15:57:34 2024
Return-Path: <>
X-Original-To: noreply@portal.pmscienceprizes.org.nz
Delivered-To: noreply@portal.pmscienceprizes.org.nz
Received: from SY8PR01CU002.outbound.protection.outlook.com (mail-australiaeastazhn15010016.outbound.protection.outlook.com [52.102.200.16])
	by portal.pmscienceprizes.org.nz (Postfix) with ESMTPS id 81092FA2CF
	for <noreply@portal.pmscienceprizes.org.nz>; Mon,  2 Sep 2024 15:57:34 +1200 (NZST)
ARC-Seal: i=1; a=rsa-sha256; s=arcselector10001; d=microsoft.com; cv=none;
 b=FrmiFwwV7HXXSHKOvIb1nOeFCizxsoW6mcck8OElm3sB0MNtNvfHrfarIje6Qa7YPoiOmB/7qrmrtd78VKlHFrNVrQN8JnPyWo58yCcq/8NobB/NrBVxnLI/nPRk+f/6HgdunxpgkDo6nFKmAX4LVxjbe40KwGfH0cmKmtfCoFmUZyYriekaTk8W2q+tk5k3r3iSGGyltjwZVB26HTAlr4piaEPbmUOY+trrwi6dqxGTNiTbNnv7yq1YIxWQ1gle5vn4LyGV7BaS4SDtmQj8/Q856JZXm+DylnaK2OypAyZRyCmgfDxIsqpXJ0lGXFcTryUVnO77jr3MR3Npwbk+LQ==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=microsoft.com;
 s=arcselector10001;
 h=From:Date:Subject:Message-ID:Content-Type:MIME-Version:X-MS-Exchange-AntiSpam-MessageData-ChunkCount:X-MS-Exchange-AntiSpam-MessageData-0:X-MS-Exchange-AntiSpam-MessageData-1;
 bh=2iagHWXxYeUBvQdgeD+aHFnwYfdSnnVx1T6O2wAA5Tc=;
 b=eGXG+IL5kbVYvoPgLFm3F9+ZgnFQ9fTD+G938Bw+R+L6w+4vRGGvtbChLceJdp99qrPMqOZGEPoGWon6deyv/S6pCETGbTKVI57PvXV81Q+QoGfBkJg9GZ8G8WKg/l99v62hx4h2q1pjt8C4qk7fKEzyFZtZ2+p2DJFAOQsPv02x7qJu4VJ/peLMOL7hbp/cqcEIraM4h28YBtBc6IPmRoo5mKpnjJGcb3vLbc9HagQeXwzfJ/97yXbtNEnfkdaH0kKDigb+i8WZYDQKsiYLaj6RGVTc60rVizt/+I92xQ7NcY1QwLIn77lepwlcUPCBM36jt9oV/eAHHJzcZ+/hZg==
ARC-Authentication-Results: i=1; mx.microsoft.com 1; spf=none; dmarc=pass
 action=none header.from=registry.otago.ac.nz; dkim=pass
 header.d=registry.otago.ac.nz; arc=none
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=registry.otago.ac.nz;
 s=selector1;
 h=From:Date:Subject:Message-ID:Content-Type:MIME-Version:X-MS-Exchange-SenderADCheck;
 bh=2iagHWXxYeUBvQdgeD+aHFnwYfdSnnVx1T6O2wAA5Tc=;
 b=zGcTHZNZymnAx9HPkIw13E6qerzG1I0vLhtwxdd1gM3ngYRKggHox2O5GQ6NSh1cUXpLreIu0IlKKPR1IeWi9g4ax5kFnuj274BUNwo4kezCvIzzmeqbiVFGpQru4TbaPpTOLxHalwIgJ3pL15uQ7rUNJeucA7lDj+9Yc+jrHjc=
Received: from SY4PR01MB6555.ausprd01.prod.outlook.com (2603:10c6:10:124::9)
 by MEYPR01MB7580.ausprd01.prod.outlook.com (2603:10c6:220:15d::21) with
 Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.20.7918.24; Mon, 2 Sep
 2024 03:57:32 +0000
Received: from SY4PR01MB6555.ausprd01.prod.outlook.com ([::1]) by
 SY4PR01MB6555.ausprd01.prod.outlook.com ([fe80::acd9:f0a7:605d:4611%2]) with
 Microsoft SMTP Server id 15.20.7918.024; Mon, 2 Sep 2024 03:57:32 +0000
From: TEST AUTO001 <test0001@test.ac.nz>
To: Prime Minister's Science Prizes <noreply@portal.pmscienceprizes.org.nz>
Subject: Automatic reply: [Prime Minister's Science Prizes] You are invited as
 a referee for a Prime Minister's Science Prizes application
Thread-Topic: [Prime Minister's Science Prizes] You are invited as a referee
 for a Prime Minister's Science Prizes application
Thread-Index: AQHa/Ow8CiVbC9YQVUyB6zlV1566fLJD3qGU
Date: Mon, 2 Sep 2024 03:57:32 +0000
Message-ID:
 <bf8f6ab712274253a4ab483e75af92b6@SY4PR01MB6555.ausprd01.prod.outlook.com>
References: <SJDi7gNtKnqLKg@portal.pmscienceprizes.org.nz>
In-Reply-To: <SJDi7gNtKnqLKg@portal.pmscienceprizes.org.nz>
X-MS-Has-Attach:
X-Auto-Response-Suppress: All
X-MS-Exchange-Inbox-Rules-Loop: test0001@test.ac.nz
X-MS-TNEF-Correlator:
authentication-results: dkim=none (message not signed)
 header.d=none;dmarc=none action=none header.from=registry.otago.ac.nz;
x-ms-exchange-parent-message-id:
 <SJDi7gNtKnqLKg@portal.pmscienceprizes.org.nz>
auto-submitted: auto-generated
x-ms-exchange-generated-message-source: Mailbox Rules Agent
x-ms-publictraffictype: Email
x-ms-traffictypediagnostic: SY4PR01MB6555:EE_|MEYPR01MB7580:EE_
x-ms-office365-filtering-correlation-id: aecc864b-b897-4708-619d-08dccb035f40
clutterbypassedbytransportruleoverride: true
x-ms-exchange-senderadcheck: 1
x-ms-exchange-antispam-relay: 0
x-microsoft-antispam:
 BCL:0;ARA:13230040|50650200027|1800799024|366016|376014|80100003;
x-microsoft-antispam-message-info:
 =?iso-8859-4?Q?LnENGjg6bxBmwtfPXRQQENmoW2IYbGJjGWLRI/+e7r28zbRd95Gbtn3YT/?=
 =?iso-8859-4?Q?wiyxHi+7sveKi/Py0O9APZiHNw7gqP/eXH9BxrHfxfgu/A2dmDlzkonTdy?=
 =?iso-8859-4?Q?9SW7ROHn0R1kFMfY0A2Ig+QEehd5bS/PM/YUHfKs0i51dD0v8677GkaeHp?=
 =?iso-8859-4?Q?BKj7ugw9hRS2eAS2HBb8mPsVrXLH9DDu5NC3UiVJxg9Z45OJl+LmNAy6pH?=
 =?iso-8859-4?Q?gB6JkMSR+eKNWILT5QjyoCE2zTVHlI0HWSRnok98MbtYBesnfIZdYYnvEz?=
 =?iso-8859-4?Q?kfvZ79Tu7v/MkRGGIh76R0Xbhn9dmlMkWXE9PWyeZkA9irGCUdBrt+uMYP?=
 =?iso-8859-4?Q?sVY2TqOZBOgV6PWJcP58w/f8lYCVFlRuiONDh08NVsV89uIOQsr0J6Fb6z?=
 =?iso-8859-4?Q?GEk2AZd+2EYienWcavxEDDroxmWuqNTag9F3XLv1GxH40Cx7uk6HUmkxLQ?=
 =?iso-8859-4?Q?oQfn3nryPH/ZCeTjpXYG4dwXJclpt1ko/mFZuW9Nuyu9SJ/2EcD86KhpiO?=
 =?iso-8859-4?Q?dSz2TlMHjQDP69ZjMAZlde0Jbw1thgdTxm9jCVsBGgOUyRs6ZZYLI8VacC?=
 =?iso-8859-4?Q?xLFs3yHjVkjbL1j0eifpb+1+ddj5Xl7kXJnVjRi4/boM/HHAHGPETIFs8y?=
 =?iso-8859-4?Q?sbKCU2DWWUxnXbmF8BQ/J8Phf0KRR45JbXyZBXxW+C7pHmPlyuQhMn21zp?=
 =?iso-8859-4?Q?DsouAqZNLaeK4W2E6vYBYPWnUBi6vmn7Gl1aufHM2r10HbDsu8y7J1YF7B?=
 =?iso-8859-4?Q?+AYH5vUOFPlYAxpWvxx5oVQxabHSj3L1pb0mZ/1DWyjpaoFiQLIUbWLN7N?=
 =?iso-8859-4?Q?hDVBYPxpHVTfwxvnWTYcd4jc9Nhs4xAH9Ej7X3kxKFNIR4/VSYgUjCwnI1?=
 =?iso-8859-4?Q?3FepeoHd4VdRAFE+V5fZ1gH7sH7PQrwn66elQa6lPrODKxOmBRpqH8x8QJ?=
 =?iso-8859-4?Q?Gyc6lXghVf2desXtY8fM5CXBMApgGN11ST2mhYWApJzW4fnffSkD8xJTDT?=
 =?iso-8859-4?Q?KmDLgT5/zNtlSuPdA91XpHQWgstxxQwZPSg3JZxqkJyJqEAL9f3w0+4hU/?=
 =?iso-8859-4?Q?fiDAbsSXvjW1jGeipl0gl5wXozOhrwdfBSSvXq36AEwrF8YS52AZRPL4D5?=
 =?iso-8859-4?Q?2iTZBeaPmfJIz4zLKU30g72XfXpOlyYIn6O01qTbSpFvUV7IOhP28H1sm8?=
 =?iso-8859-4?Q?NE7yFlLiPrI6ifNMFEyIv7YxxNG85qEwbGFv342++uNUqQPEo3pjrl3zD1?=
 =?iso-8859-4?Q?nNnfKtVMwPsIUvtY7NGMbOU1VmFplcR6Gr8W735FprSK4syQJIIppI4Kfd?=
 =?iso-8859-4?Q?etaDnfRXARvcaHcrlek+7BnBsLky/P98lmY8I6g4AdcJMth7Vr8/RDtDQH?=
 =?iso-8859-4?Q?62SSRlkan7zTEzSfDMeO4BylxGn1l+nw=3D=3D?=
x-forefront-antispam-report:
 CIP:255.255.255.255;CTRY:;LANG:en;SCL:1;SRV:;IPV:NLI;SFV:NSPM;H:SY4PR01MB6555.ausprd01.prod.outlook.com;PTR:;CAT:NONE;SFS:(13230040)(50650200027)(1800799024)(366016)(376014)(80100003);DIR:OUT;SFP:1501;
x-ms-exchange-antispam-messagedata-chunkcount: 1
x-ms-exchange-antispam-messagedata-0:
 vjAT+45BSWjsJrwiT80iGmm35SCevSA+y0QXun6CBr/KfFegVsGdwyu7AsooJMULsCpLImRs1iVTFBPyWZLLlY1C+fcH8qhyz4l2UtOh4RA6vuuOZbk9pMbD39FmYaxOfDHokWflGGn/6ZQfMs6jSaMI5oLZ/771Hi4x+ekTGzU8qs20DryK29N3u+tWJtDMCYdCaKiIUcNhcejtcS3g7E5P2Dl2WcS5qG6+5fkLkr72OZm02nqOPN98WWxv0h2Pl6oHFOjBYnwkRK5JuZeb0ivC0e7MGtiyfroGsoquZvE28WDFlUL0ZVpm6JsO6aIA
Content-Type: multipart/alternative;
	boundary="_000_bf8f6ab712274253a4ab483e75af92b6SY4PR01MB6555ausprd01pr_"
MIME-Version: 1.0
X-OriginatorOrg: registry.otago.ac.nz
X-MS-Exchange-CrossTenant-AuthAs: Internal
X-MS-Exchange-CrossTenant-AuthSource: SY4PR01MB6555.ausprd01.prod.outlook.com
X-MS-Exchange-CrossTenant-Network-Message-Id: aecc864b-b897-4708-619d-08dccb035f40
X-MS-Exchange-CrossTenant-originalarrivaltime: 02 Sep 2024 03:57:32.3083
 (UTC)
X-MS-Exchange-CrossTenant-fromentityheader: Hosted
X-MS-Exchange-CrossTenant-id: 0225efc5-78fe-4928-b157-9ef24809e9ba
X-MS-Exchange-Transport-CrossTenantHeadersStamped: MEYPR01MB7580
Status: RO
Content-Length: 2555
Lines: 68

--_000_bf8f6ab712274253a4ab483e75af92b6SY4PR01MB6555ausprd01pr_
Content-Type: text/plain; charset="iso-8859-4"
Content-Transfer-Encoding: quoted-printable

Kia ora koutou


I am on conference leave and then busy with collaborators until Monday 9 Se=
ptember. Please expect some delay in my response to your email. If you have=
 not heard from me after I return please resend your email.


For enquiries regarding the MBIE Drug Delivery Programme, please contact in=
 the first instance Alex Sweetman (alex.sweetman@otago.ac.nz<mailto:alex.sw=
eetman@otago.ac.nz>) .


Ng=E0 mihi nui / many thanks
TEST AUTO001

--_000_bf8f6ab712274253a4ab483e75af92b6SY4PR01MB6555ausprd01pr_
Content-Type: text/html; charset="iso-8859-4"
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/htm=
l4/strict.dtd">
<html>
<head>
<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Diso-8859-=
4">
<meta http-equiv=3D"Content-Style-Type" content=3D"text/css">
<title></title>
<meta name=3D"Generator" content=3D"Cocoa HTML Writer">
<meta name=3D"CocoaVersion" content=3D"2113.65">
<style type=3D"text/css">=0A=
p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 13.3px Times; -webkit-text-str=
oke: #000000}=0A=
p.p2 {margin: 0.0px 0.0px 0.0px 0.0px; font: 13.3px Times; -webkit-text-str=
oke: #000000; min-height: 16.0px}=0A=
span.s1 {font-kerning: none}=0A=
span.s2 {font-kerning: none; -webkit-text-stroke: 0px #000000}=0A=
span.s3 {text-decoration: underline ; font-kerning: none; color: #0000e9}=
=0A=
</style>
</head>
<body>
<p class=3D"p1"><span class=3D"s1">Kia ora koutou</span></p>
<p class=3D"p2"><span class=3D"s1"></span><br>
</p>
<p class=3D"p1"><span class=3D"s1">I am on conference leave and then busy w=
ith collaborators until Monday 9 September. Please expect some delay in my =
response to your email. If you have not heard from me after I return please=
 resend your email.</span></p>
<p class=3D"p2"><span class=3D"s1"></span><br>
</p>
<p class=3D"p1"><span class=3D"s1">For enquiries regarding the </span><span=
 class=3D"s2">MBIE
</span><span class=3D"s1">Drug Delivery Programme, please contact in the fi=
rst instance Alex Sweetman (<a href=3D"mailto:alex.sweetman@otago.ac.nz"><s=
pan class=3D"s3">alex.sweetman@otago.ac.nz</span></a>) .</span></p>
<p class=3D"p2"><span class=3D"s1"></span><br>
</p>
<p class=3D"p1"><span class=3D"s1">Ng=E0 mihi nui / many thanks<br>
TEST AUTO001</span></p>
</body>
</html>

--_000_bf8f6ab712274253a4ab483e75af92b6SY4PR01MB6555ausprd01pr_--

