From MAILER-DAEMON  Wed Oct  5 14:46:58 2022
Return-Path: <>
X-Original-To: noreply@portal.pmscienceprizes.org.nz
Delivered-To: noreply@portal.pmscienceprizes.org.nz
Received: from NAM04-DM6-obe.outbound.protection.outlook.com (mail-dm6nam04hn2209.outbound.protection.outlook.com [52.100.161.209])
	by portal.pmscienceprizes.org.nz (Postfix) with ESMTPS id 31850100B71
	for <noreply@portal.pmscienceprizes.org.nz>; Wed,  5 Oct 2022 14:46:58 +1300 (NZDT)
ARC-Seal: i=1; a=rsa-sha256; s=arcselector9901; d=microsoft.com; cv=none;
 b=afGYUqsQYXxKiOw+/lyWApZunZMrjM1eZPVGK9/zOlMqpta+aK76+69Ofrz3mujE1VxaUl8l6Dk8ZEcf9IPQ4feekiL/VcwdOlz867AXpFirh72kkIE5+mCwquluC603KcIRURGTCF3c7vzw3CnnpGIN0e7h2GxTi61BuCTP06XXqHapK2OylwLkkqbFpQohOP/XjA5ZExTdlkt6EKC27IjwGDDpzP6nJY6RelueOHwSczvXQpe3vDNZr3WCFiuZrVQC7jNcu98XX8C42QR4I7IVOzFJiT3iqde1342yCqFCAqedGkEkiP3U/r7hzjY9iRakx/zSSTHNa7uNs8caVA==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=microsoft.com;
 s=arcselector9901;
 h=From:Date:Subject:Message-ID:Content-Type:MIME-Version:X-MS-Exchange-AntiSpam-MessageData-ChunkCount:X-MS-Exchange-AntiSpam-MessageData-0:X-MS-Exchange-AntiSpam-MessageData-1;
 bh=7xTbeOsHlfyUHk2KjdvoGEGnP5jgyZEX2cYyxnfogus=;
 b=hlmFPD+GA+AUkzQVeqZbFs65jZsUFKxx7xvhNcpHJqQANdRa9Cz/FfrI2RWV46XKrbwkLgeMCT9fYD9QFHUYGlfY8PdhqkpqcCGvR75OQmlJPPH4BZ9fibF/O/2Z67DM2hN3BugJypUGP2J88oD3Vvhr0EKW5ipq5Q1xRPbHXlctsNGO+nKtDlNJNzdt0ENu6X3ql3EtLAZc8rwdSlHU5yQFW0Zu6efdq5MWyiyHe98Xjn7PEev2c1NG309WElHRAlXaFF9HrglulB3Jcyo41dv6lmy40ntJO8GTnXaIopCCM4au13SUKY2xrr/ajGh7N0J1K+oQTKnMYxhHJera9A==
ARC-Authentication-Results: i=1; mx.microsoft.com 1; spf=none; dmarc=pass
 action=none header.from=wjh.harvard.edu; dkim=pass header.d=wjh.harvard.edu;
 arc=none
Received: from SJ0PR07MB9156.namprd07.prod.outlook.com (2603:10b6:a03:3fa::12)
 by BN3PR07MB2529.namprd07.prod.outlook.com (2a01:111:e400:7bbf::14) with
 Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.20.5676.28; Wed, 5 Oct
 2022 01:46:50 +0000
Received: from SJ0PR07MB9156.namprd07.prod.outlook.com ([::1]) by
 SJ0PR07MB9156.namprd07.prod.outlook.com ([fe80::6269:68b7:b68d:98b4%6]) with
 Microsoft SMTP Server id 15.20.5676.031; Wed, 5 Oct 2022 01:46:50 +0000
From: "Yunker, Even" <test-auto002@test.edu>
To: Prime Minister's Science Prizes <noreply@portal.pmscienceprizes.org.nz>
Subject: Automatic reply: [Prime Minister's Science Prizes] You are invited as
 a referee for a Prime Minister's Science Prizes application
Thread-Topic: [Prime Minister's Science Prizes] You are invited as a referee
 for a Prime Minister's Science Prizes application
Thread-Index: AQHY2FxWYSR9zhFSNUiusNFHmaCODq3/B/QI
Date: Wed, 5 Oct 2022 01:46:50 +0000
Message-ID:
 <aa531a43e42f45b3903e17a5d7d24d0d@SJ0PR07MB9156.namprd07.prod.outlook.com>
References: <PfjG5nU9l4bsUw@portal.pmscienceprizes.org.nz>
In-Reply-To: <PfjG5nU9l4bsUw@portal.pmscienceprizes.org.nz>
X-MS-Has-Attach:
X-Auto-Response-Suppress: All
X-MS-Exchange-Inbox-Rules-Loop: test-auto002@test.edu
X-MS-TNEF-Correlator:
authentication-results: dkim=none (message not signed)
 header.d=none;dmarc=none action=none header.from=wjh.harvard.edu;
x-ms-exchange-parent-message-id:
 <PfjG5nU9l4bsUw@portal.pmscienceprizes.org.nz>
auto-submitted: auto-generated
x-ms-exchange-generated-message-source: Mailbox Rules Agent
x-ms-publictraffictype: Email
x-ms-traffictypediagnostic: SJ0PR07MB9156:EE_|BN3PR07MB2529:EE_
x-ms-office365-filtering-correlation-id: 023fa01f-a2d7-4e23-df7e-08daa6737910
x-ms-exchange-senderadcheck: 1
x-ms-exchange-antispam-relay: 0
x-microsoft-antispam: BCL:0;
x-microsoft-antispam-message-info:
 /REc6k4Etqk5WFCTKRTwOQnnbSn9+RVZx52RU5YSvZfeQF0D8boAyl6d2qEPGy25xk7JMQcIB6S//B/MnOTVDvANAFGZ00zBFURuIhB8nss2H7Fg37M3+x9LI9PY3kqhS4evvIoVrqcyKAGSdKehYR3EgnCig5jba4Tca50jrjVbQ4gZmHiY0tffCAR/ShmnlIuy3Yq2FUGtADF0lcFkEDLnRngUFYBK+NI9liOt/kwKfOZsNLV2hdDj77Km3oZBX2u3kInL13LLzo7ceCp9Bd69alPdx5R4stwXU7JvKb/+04Be3HLgbuUq4BjbW70HotbCdGCDVTVwevQ589ueb+lA0Y88PN9XAPty4x1ARIlqjOUA1ywGh6+cI31gz0jlf94Mfrkeg2zwXIdvN2k2tL6HA5E/U0x6CI8h/bkdEJgmQrzkSydYhViDI/o5QrCdIvY+QXMic5wFR57pBBJ3m47wu5bYUYnwpXN1icl/hnYXmblApAwfjfDExNxxCRUWVa2jEBO+Dd/ZN1sGsB2TyzKP1K6fv07QlawOyDyX1o226RHRe0bgB2l6NmaB0E4ocY9NnlRdAsdQztz4X4f/t5rDZZ5dOV8n1iwLBPXrD3wOwn+Ttha6b9JcD4XZHmM4oZlk3RACwpBz4X3LtoWUiEXlLUKXp/5T4gO/3ZaeUD87Hzk3Zxb37E6RQ3GCKOXAI0SH/QiLjNddPUdHdYQcdg==
x-forefront-antispam-report:
 CIP:255.255.255.255;CTRY:;LANG:en;SCL:1;SRV:;IPV:NLI;SFV:NSPM;H:SJ0PR07MB9156.namprd07.prod.outlook.com;PTR:;CAT:NONE;SFS:(13230022)(50650200002)(366004)(136003)(39860400002)(396003)(346002)(376002)(451199015)(786003)(316002)(41320700001)(24736004)(108616005)(9686003)(55016003)(6506007)(5660300002)(8676002)(8936002)(2906002)(41300700001)(7696005)(64756008)(66446008)(66476007)(66556008)(66946007)(78352004)(4744005)(71200400001)(122000001)(83380400001)(88996005)(6916009)(42882007)(498600001)(53652003)(111220200005)(80100003);DIR:OUT;SFP:1501;
x-ms-exchange-antispam-messagedata-chunkcount: 1
x-ms-exchange-antispam-messagedata-0:
 eHXc2Q2CCubdRl7Kfw6QVv1kdnPbrkvL7rFi8YLALnNOzBFNc4QfCA/DrTJefHSdHfLc+K/gn1kiO6cZ6i5/Yw6hWinjYDPMQUD1DlwXS1P3ddzQenFnoQhqB5Gn8ylGGzOLDN8zxA1cJtORP33FvKlr17rRl5nYJWu7/TpCYDqtsNADbyIwdM+UcyfIdCVtKSH6mWRYP08gAR0+PqmisXmN755He/OV+f3RUJbdZXFOe5e4Si0zF4FSdWfSKbyDInC93usOWGUxwdUzfR/ULGNo9MythgRfOstWi3lZjK3srXRV2xvjvqFZVXsYDJBD
Content-Type: multipart/alternative;
	boundary="_000_aa531a43e42f45b3903e17a5d7d24d0dSJ0PR07MB9156namprd07pr_"
MIME-Version: 1.0
X-OriginatorOrg: Wjh.harvard.edu
X-MS-Exchange-CrossTenant-AuthAs: Internal
X-MS-Exchange-CrossTenant-AuthSource: SJ0PR07MB9156.namprd07.prod.outlook.com
X-MS-Exchange-CrossTenant-Network-Message-Id: 023fa01f-a2d7-4e23-df7e-08daa6737910
X-MS-Exchange-CrossTenant-originalarrivaltime: 05 Oct 2022 01:46:50.8632
 (UTC)
X-MS-Exchange-CrossTenant-fromentityheader: Hosted
X-MS-Exchange-CrossTenant-id: 6ffa22f4-4568-4105-ad43-2e3ad4726957
X-MS-Exchange-Transport-CrossTenantHeadersStamped: BN3PR07MB2529
Status: RO
Content-Length: 2564
Lines: 72

--_000_aa531a43e42f45b3903e17a5d7d24d0dSJ0PR07MB9156namprd07pr_
Content-Type: text/plain; charset="Windows-1252"
Content-Transfer-Encoding: quoted-printable


Dear Correspondent,
Email has been coming in far more quickly than I can reply to it. I am prio=
ritizing the time-sensitive messages, and can=92t promise to reply to the g=
rowing backlog of non-urgent correspondence in a timely fashion. I will sav=
e your letter though, and reply as time permits. Thanks for your patience a=
nd understanding.
Best,
Even Yunker


--_000_aa531a43e42f45b3903e17a5d7d24d0dSJ0PR07MB9156namprd07pr_
Content-Type: text/html; charset="Windows-1252"
Content-Transfer-Encoding: quoted-printable

<html xmlns:o=3D"urn:schemas-microsoft-com:office:office" xmlns:w=3D"urn:sc=
hemas-microsoft-com:office:word" xmlns:m=3D"http://schemas.microsoft.com/of=
fice/2004/12/omml" xmlns=3D"http://www.w3.org/TR/REC-html40">
<head>
<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3DWindows-1=
252">
<meta name=3D"Generator" content=3D"Microsoft Word 15 (filtered medium)">
<style><!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
span.EmailStyle17
	{mso-style-type:personal-compose;
	font-family:"Calibri",sans-serif;}
.MsoChpDefault
	{mso-style-type:export-only;
	font-family:"Calibri",sans-serif;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}
--></style>
</head>
<body lang=3D"EN-US" link=3D"#0563C1" vlink=3D"#954F72" style=3D"word-wrap:=
break-word">
<div class=3D"WordSection1">
<p class=3D"MsoNormal" style=3D"text-autospace:none"><o:p>&nbsp;</o:p></p>
<p class=3D"MsoNormal" style=3D"text-autospace:none">Dear Correspondent,&nb=
sp;<o:p></o:p></p>
<p class=3D"MsoNormal" style=3D"text-autospace:none">Email has been coming =
in far more quickly than I can reply to it. I am prioritizing the time-sens=
itive messages, and can=92t promise to reply to the growing backlog of non-=
urgent correspondence in a timely fashion.
 I will save your letter though, and reply as time permits. Thanks for your=
 patience and understanding.&nbsp;<br>
Best,&nbsp;<br>
Even Yunker<o:p></o:p></p>
<p class=3D"MsoNormal" style=3D"text-autospace:none"><o:p>&nbsp;</o:p></p>
</div>
</body>
</html>

--_000_aa531a43e42f45b3903e17a5d7d24d0dSJ0PR07MB9156namprd07pr_--

