From MAILER-DAEMON  Thu Apr 29 05:00:52 2021
Return-Path: <>
X-Original-To: pmspp@pmspp.prodata.nz
Delivered-To: pmspp@pmspp.prodata.nz
Received: by pmspp.prodata.nz (Postfix)
	id 16174FB8FE; Thu, 29 Apr 2021 05:00:52 +0000 (UTC)
Date: Thu, 29 Apr 2021 05:00:52 +0000 (UTC)
From: MAILER-DAEMON@pmspp.prodata.nz (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: pmspp@pmspp.prodata.nz
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="3FD91FA24D.1619672452/pmspp.prodata.nz"
Content-Transfer-Encoding: 8bit
Message-Id: <20210429050052.16174FB8FE@pmspp.prodata.nz>
Status: RO
Content-Length: 3182
Lines: 78

This is a MIME-encapsulated message.

--3FD91FA24D.1619672452/pmspp.prodata.nz
Content-Description: Notification
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 8bit

This is the mail system at host pmspp.prodata.nz.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<nad200djfkajsd04853094543@gmail.com>: host
    gmail-smtp-in.l.google.com[74.125.130.26] said: 550-5.1.1 The email account
    that you tried to reach does not exist. Please try 550-5.1.1
    double-checking the recipient's email address for typos or 550-5.1.1
    unnecessary spaces. Learn more at 550 5.1.1
    https://support.google.com/mail/?p=NoSuchUser o6si2150311pju.88 - gsmtp (in
    reply to RCPT TO command)

--3FD91FA24D.1619672452/pmspp.prodata.nz
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; pmspp.prodata.nz
X-Postfix-Queue-ID: 3FD91FA24D
X-Postfix-Sender: rfc822; pmspp@pmspp.prodata.nz
Arrival-Date: Thu, 29 Apr 2021 05:00:50 +0000 (UTC)

Final-Recipient: rfc822; nad200djfkajsd04853094543@gmail.com
Original-Recipient: rfc822;nad200djfkajsd04853094543@gmail.com
Action: failed
Status: 5.1.1
Remote-MTA: dns; gmail-smtp-in.l.google.com
Diagnostic-Code: smtp; 550-5.1.1 The email account that you tried to reach does
    not exist. Please try 550-5.1.1 double-checking the recipient's email
    address for typos or 550-5.1.1 unnecessary spaces. Learn more at 550 5.1.1
    https://support.google.com/mail/?p=NoSuchUser o6si2150311pju.88 - gsmtp

--3FD91FA24D.1619672452/pmspp.prodata.nz
Content-Description: Undelivered Message
Content-Type: message/rfc822
Content-Transfer-Encoding: 8bit

Return-Path: <pmspp@pmspp.prodata.nz>
Received: from pmspp (localhost [IPv6:::1])
	by pmspp.prodata.nz (Postfix) with ESMTP id 3FD91FA24D
	for <nad200djfkajsd04853094543@gmail.com>; Thu, 29 Apr 2021 05:00:50 +0000 (UTC)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=pmspp.prodata.nz;
	s=20200811; t=1619672450;
	bh=cWbIiUOosWU698p5lOQOBmMBIMonidbiu5XBr1uoNtw=;
	h=Subject:From:To:Reply-To:Date:List-Unsubscribe:From;
	b=beNSqQFD53vIzNU9Lesp0dDz4pvLBtTYk+TV7TjdqsgjdmUKEQ6psmVZDWee6JBkl
	 da9D1M/+sdDOyUjO54p6cIrsC7iiORfSXGisOva7cHOJuB6n0vNAmzM7MPXjXVNhqf
	 prcx6wU1OCBZ9UVkaAsGIxsoWBfQHUNVvC3rv1bg=
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Subject: [Prime Minister's Science Prizes] You are invited to join the PM
 Science Prize
 portal
From: pmspp@pmspp.prodata.nz
To: nad200djfkajsd04853094543@gmail.com
Reply-To: Prime Minister's Science Prizes <admin@prod.prodata.nz>
Date: Thu, 29 Apr 2021 05:00:50 -0000
Message-ID: <Oqc_EntciH0mTw@pmspp.prodata.nz>
List-Unsubscribe: <https://pmspp.prodata.nz/unsubscribe/Oqc_EntciH0mTw>

You are invited to join the PM Science Prize portal. Please follow the link: https://pmspp.prodata.nz/onboard/qEUcbGxv4bQ

--3FD91FA24D.1619672452/pmspp.prodata.nz--

