From Radomirs.Cirskis@royalsociety.org.nz  Thu Nov  9 13:29:01 2023
Return-Path: <Radomirs.Cirskis@royalsociety.org.nz>
X-Original-To: noreply@puanga.royalsociety.org.nz
Delivered-To: noreply@puanga.royalsociety.org.nz
Received: from AUS01-SY4-obe.outbound.protection.outlook.com (mail-sy4aus01on2102.outbound.protection.outlook.com [40.107.107.102])
	by portal.pmscienceprizes.org.nz (Postfix) with ESMTPS id 9C73BFA2C3
	for <noreply@puanga.royalsociety.org.nz>; Thu,  9 Nov 2023 13:29:01 +1300 (NZDT)
ARC-Seal: i=1; a=rsa-sha256; s=arcselector9901; d=microsoft.com; cv=none;
 b=U69Gu2o/h/83mqPsRtbiPOmZWFIxRtXmXqY98TliXPiXTXk5dKTJ2DSgHbkQDrgRZw7MCf/KaghTpvOvrOhOqkF9WocMja6po3ylpgPPhIOy+/heGOWlv7HI1UiKVwEq2VJOUctJB3FGvIpKjgvr/JVaVkyXeYOX3ecaUDOPlMv7KzM0G5ZGryV9GEP2qFjBLVC/zPcIZscyo4RJJ+jIYsrZl0ETOLK41UyDwJN92bc1I1pj8gq6y7/MhQodsJHHeja5duqOaqCyeph1WGvBUqT+nrP7gGkoqG6GX5ZcJnqZ06H0S9Ulz4iOpbUI3BGklLFXd50JK2Z/lhcxZ+Vkfw==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=microsoft.com;
 s=arcselector9901;
 h=From:Date:Subject:Message-ID:Content-Type:MIME-Version:X-MS-Exchange-AntiSpam-MessageData-ChunkCount:X-MS-Exchange-AntiSpam-MessageData-0:X-MS-Exchange-AntiSpam-MessageData-1;
 bh=B3t/UXtogFo2WNUvr0zNmPJtDRe/+8GGtgXnYGgOoQg=;
 b=EkGHRH9tiPlTAp+daO7nF/HWbxEePmp9AqboNyFcDEcRPQRaD3NN/bgCtJcKhJu3+MT/2Hld+CVUFQesUf5s8b4kkOJ0ZzPU0WEkUpoOCaRqzmefpli+ueUnaH47zzU25/aZgRsMNeGz5yF3m4Mg69d/IuFPHeT2pKpunlXQgOIe2DRC66ZhxbLcdzsnHVGnEbEBntt5YZ20eP0PMdUSHuypKH0k1WipFkIx/i1kZ5G6ky6nZI1PBCS1AVwxldWR8I9imXRGuql1b+dJf8WDy/f0n7NM/CkqNHKUNASuW3Hsq5uBEESNmZokm2fcVu+5XugXIbnPsUfcNiq6T7t6dQ==
ARC-Authentication-Results: i=1; mx.microsoft.com 1; spf=pass
 smtp.mailfrom=royalsociety.org.nz; dmarc=pass action=none
 header.from=royalsociety.org.nz; dkim=pass header.d=royalsociety.org.nz;
 arc=none
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=royalsociety.org.nz;
 s=selector1;
 h=From:Date:Subject:Message-ID:Content-Type:MIME-Version:X-MS-Exchange-SenderADCheck;
 bh=B3t/UXtogFo2WNUvr0zNmPJtDRe/+8GGtgXnYGgOoQg=;
 b=u68q8vXS7arfUfvEWdI7xowKipABiRjfXDNUZZ7dCXlC9gkLrMIvInEC9gAXkm1zmKFRkeQ5Vrcot8Iea+5ioyS50QvYl8UzQyyZmV7sXRrESLAYUYfkQ2iWO40IqPZconENjqLpQL8yd2/SU6hOXRw/Nb8tiJNOCquyOxplcUYshFO8MRiVlXirAakndScaWG7sf+4mOV1yH/Vxh/eCdLrs7vL20E3u1J6CBA6aD8NBuwwmZmixtHF+nX8NUBuo0fC1szSBrL5h7KhXuB9AzaPl3B2nLrvV2tawWQG9CBhTefmUheayt7WUTmBI9w4fNe8bfX92bfR63GYsw5ZT9Q==
Received: from SY4P282MB4175.AUSP282.PROD.OUTLOOK.COM (2603:10c6:10:1ca::14)
 by SY7P282MB4581.AUSP282.PROD.OUTLOOK.COM (2603:10c6:10:274::21) with
 Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.20.6977.19; Thu, 9 Nov
 2023 00:28:57 +0000
Received: from SY4P282MB4175.AUSP282.PROD.OUTLOOK.COM
 ([fe80::4965:fcb2:67c0:7533]) by SY4P282MB4175.AUSP282.PROD.OUTLOOK.COM
 ([fe80::4965:fcb2:67c0:7533%4]) with mapi id 15.20.6954.024; Thu, 9 Nov 2023
 00:28:57 +0000
From: Radomirs Cirskis <Radomirs.Cirskis@royalsociety.org.nz>
To: =?iso-8859-4?Q?Ng=E0_Puanga_P=FEtaiao_Fellowships?=
	<noreply@puanga.royalsociety.org.nz>
Subject:
 =?iso-8859-4?Q?Re:_[Ng=E0_Puanga_P=FEtaiao_Fellowships]_Comment_posted_by?=
 =?iso-8859-4?Q?_RADOMIRS_CIRSKIS_(nad2000+admin@gmail.com)_to_NPP-AO1-202?=
 =?iso-8859-4?Q?3-001:_Ng=E0_Puanga_P=FEtaiao_2023_--_SUPER_TRUPPER?=
Thread-Topic:
 =?iso-8859-4?Q?[Ng=E0_Puanga_P=FEtaiao_Fellowships]_Comment_posted_by_RAD?=
 =?iso-8859-4?Q?OMIRS_CIRSKIS_(nad2000+admin@gmail.com)_to_NPP-AO1-2023-00?=
 =?iso-8859-4?Q?1:_Ng=E0_Puanga_P=FEtaiao_2023_--_SUPER_TRUPPER?=
Thread-Index: AQHaEqNcA6FUSGFh4kieB5SLp+KdWLBxIfRA
Date: Thu, 9 Nov 2023 00:28:57 +0000
Message-ID:
 <SY4P282MB4175E0B0BBBD6276C067860DCAAFA@SY4P282MB4175.AUSP282.PROD.OUTLOOK.COM>
References: <-EyTKQEqZyIE8A@puanga.royalsociety.org.nz>
In-Reply-To: <-EyTKQEqZyIE8A@puanga.royalsociety.org.nz>
Accept-Language: en-US
Content-Language: en-US
X-MS-Has-Attach: yes
X-MS-TNEF-Correlator:
msip_labels:
authentication-results: dkim=none (message not signed)
 header.d=none;dmarc=none action=none header.from=royalsociety.org.nz;
x-ms-publictraffictype: Email
x-ms-traffictypediagnostic: SY4P282MB4175:EE_|SY7P282MB4581:EE_
x-ms-office365-filtering-correlation-id: 2b4e7881-6c6e-4450-5109-08dbe0badc90
x-ms-exchange-senderadcheck: 1
x-ms-exchange-antispam-relay: 0
x-microsoft-antispam: BCL:0;
x-microsoft-antispam-message-info:
 4Hz/nT+gdkxaB16Dm8EpC3XjWJwwoZMU+UD/o7LuKR2Y9p5BZF801plT0os6K50G71jJ78mXmSiqOuiZHSmljL7v/fy4Hyusi8pbFxjyQ6Ndf/HeSaHV8JjoYUSVFgu6ySkPVvtGerKHhG9sdYYzULxLsiNY3sLU1OdyK4E2kXVJfbLSqIoz+UkuNIMCNJOEbVEscU7piuuUoRp+FnHjiQtFM6SQ8I9L4zJ1TvLXwQ2dyQSRzcexaPUNKcwvkqga03F6G72GTilIChkoEue3KknmkBHYmosVE7JzhPCK+JUVhwVBGFQAoRQzN4IKtjzOIzmPNj9TEuOxqJew2Rzl/HRGbvb5dgLK+REAtnpqayDOsyN/rX2sOZw5EsxjsUB5Kwcd+vZKEPSy2ZPtYGq8qHtl9V84ziNWRaCZg8cz1DxtnZ/sOAqtrRbYY6ecimszKDU2/447OifGsy4f5Gr9wRXrvzO5PF6aTjV8iWmf3zsyXa0M5gWVo6ADCY1miXIIyJemrhHMplXJ2VOPbc9gubutZaUrGUyr4a+A9lsMlk2zRKBjA+GA9tj9EeZmI86KU+X2E871/0gVJGMlgb4vXgItjgU4RFUkxWwcOeH4fOcCY1m+LZ7Y7FyVqBap9lM1My6zF8ikZRWulTuM1SqNpA==
x-forefront-antispam-report:
 CIP:255.255.255.255;CTRY:;LANG:en;SCL:1;SRV:;IPV:NLI;SFV:NSPM;H:SY4P282MB4175.AUSP282.PROD.OUTLOOK.COM;PTR:;CAT:NONE;SFS:(13230031)(346002)(396003)(136003)(39840400004)(376002)(366004)(230922051799003)(64100799003)(1690799017)(451199024)(186009)(1800799009)(55016003)(19627405001)(478600001)(71200400001)(9686003)(7696005)(6506007)(53546011)(224303003)(38100700002)(166002)(99936003)(122000001)(86362001)(33656002)(41300700001)(5660300002)(66946007)(66476007)(66556008)(76116006)(64756008)(316002)(66446008)(6916009)(83380400001)(26005)(2906002)(38070700009)(52536014)(8936002);DIR:OUT;SFP:1102;
x-ms-exchange-antispam-messagedata-chunkcount: 1
x-ms-exchange-antispam-messagedata-0:
 =?iso-8859-4?Q?kGejjNXDmRJFSBhTAxDSuvueM3+s1JGBOe4ri1g43MqQ9tgJNnypAa/ye8?=
 =?iso-8859-4?Q?VMO+9cSYB9UaK2NMmIjecmbjwfCaR84E0r3NQBxMKSq4IkBxnbnEs7FbZn?=
 =?iso-8859-4?Q?IevFgA+Wi3w5iJ30Z5eI/fvARABNyhEs3PveaG5BrdNBhqJm9iYqRmmJ2y?=
 =?iso-8859-4?Q?1cO6lXglp3b/s6dxV86dsuFN3hqqToNc3MsqVN1UG1Vf/ryt+XsQtUpN3r?=
 =?iso-8859-4?Q?HiQmrlg20R3Ck60yk+tQEEUO9hxZ4ZZ63+tBG0k8PRrupr/sh2koPpkaTK?=
 =?iso-8859-4?Q?dImvmYhGGLBQ/Ix2Xk+iDl77pXTL3t84C7SIcA00EI1VtjZqeAKIrgE+4j?=
 =?iso-8859-4?Q?EGistC0Ud+oG2nTTibtbpe3ZJkKWH+tAbMt7xcUHWqI1rUtSvdyAnZOAc+?=
 =?iso-8859-4?Q?o41+iIAqKZmFPSWzErmJsNw+GBS0bcl0TV3B0oLjgThLzlJ+I17zkwkHFk?=
 =?iso-8859-4?Q?5EtdG/ZHj6fXjZ/olej4WRrebp+NUqVcQb6OrVDodAfVOhmc1ji/fId4P0?=
 =?iso-8859-4?Q?/sT5riiWk1c5OYtLIO2RmhrIRyLpATIUmrD+7PY0uPNceDDjwSZGz+ShlF?=
 =?iso-8859-4?Q?T4grbRJgh3iLeHI+XiPxPn9caUWyjz9psIXK+b/pZdBtNi1J+QpwJbe1M8?=
 =?iso-8859-4?Q?W+BKo3d2s0dMyH53ytifKacLDuaSciFXHibI/7jT5gIWrtIz6lD+J5phxO?=
 =?iso-8859-4?Q?n8AmvaGYWEET+RN/thdI8K4SeudgRsDIsuLLtv87WMoVHsKVbN7vubGPNk?=
 =?iso-8859-4?Q?z7CpboEw77rpcsZjoDeNm+XJYq4gGUoM+5xifCX/kC/BKjTqJvVcILNeR7?=
 =?iso-8859-4?Q?oTuXjavR1LZmYIp97f2LfrTkGvemFCiVWdY8/a6CGkEB9rW5C1TV7WheFU?=
 =?iso-8859-4?Q?+Bfj8O5qf2hD/T3nlI1dcQmryng7OaSuc4W5GkHGpXXXacabmWHAZ8DGS9?=
 =?iso-8859-4?Q?8hpynZbLHfcC8qz5+g8kSEFacOncBZusRo8GVyNIZSD+YltkpnT2lHWNrY?=
 =?iso-8859-4?Q?PmAgYZNXNlhehJ45TkNL7oyMYBIhBVVpoY/u7a7+daxzBv30Ud3md2Lfbw?=
 =?iso-8859-4?Q?1h23K7gqgBoqoON+bbAD4FJoZ197mcyAUWiZiVu8yrzSkRAdd/He637BeL?=
 =?iso-8859-4?Q?vvZ3pH+fyUr60sWL1zq9cQHidHkZTq6P0NN0teXRuCSg+B2/tX26en2wB9?=
 =?iso-8859-4?Q?6MW5OT8OWSxGUbJSHL76DbAjjNpYVOczw3ix2/aoMYEUlU2JUZtDQ145SA?=
 =?iso-8859-4?Q?us3V5xTO5uLke+SV0kNdmMqKX5Q2Krz1im6Yg2UFRm1v2Kez8cCr8eELzk?=
 =?iso-8859-4?Q?tN6bXNej1njfxNf9YuDxf+URGawLl/++NZ0NJIiHcMJttDRXuMyMoUU1lY?=
 =?iso-8859-4?Q?4rHE+bLnwzDUU2FRvkH8FutOyy0OIHERV8KcfXnpVuDfniWOhwLnEYOxml?=
 =?iso-8859-4?Q?+2qlYtNPwT3395QsEWeNDRE58aXN5+ZRkMD+I17S4H+t5/NKM+rN8AmKyo?=
 =?iso-8859-4?Q?ZHSlB2r04GRAvR9eauJD7mMdmG5L2ldslsT7fg60jLgrC1o/Meb4q05hqe?=
 =?iso-8859-4?Q?l1E+WQlqRagDJ6vCVYeSc+FCKd/9QIxpWOvxck4k+s7im7ZYBBfUD9B33x?=
 =?iso-8859-4?Q?mjTHWFbLu03B3esnRcbcY/ANDazBXaWonksuw4VoubjuqNSn5kVRxLtw?=
 =?iso-8859-4?Q?=3D=3D?=
Content-Type: multipart/mixed;
	boundary="_004_SY4P282MB4175E0B0BBBD6276C067860DCAAFASY4P282MB4175AUSP_"
MIME-Version: 1.0
X-OriginatorOrg: royalsociety.org.nz
X-MS-Exchange-CrossTenant-AuthAs: Internal
X-MS-Exchange-CrossTenant-AuthSource: SY4P282MB4175.AUSP282.PROD.OUTLOOK.COM
X-MS-Exchange-CrossTenant-Network-Message-Id: 2b4e7881-6c6e-4450-5109-08dbe0badc90
X-MS-Exchange-CrossTenant-originalarrivaltime: 09 Nov 2023 00:28:57.2006
 (UTC)
X-MS-Exchange-CrossTenant-fromentityheader: Hosted
X-MS-Exchange-CrossTenant-id: 684f9caf-da9b-406a-bede-5d126772ef54
X-MS-Exchange-CrossTenant-mailboxtype: HOSTED
X-MS-Exchange-CrossTenant-userprincipalname: cxGM5co6KjfHKvDSzCz2sXPja6K4E0RWERnrG7iOt4R+ojOSzyOU5D0NrpoAJavc6gXm31r4+3V+Orbq7hOWxWuJUWT1K1uN3l2PUzFM6UM=
X-MS-Exchange-Transport-CrossTenantHeadersStamped: SY7P282MB4581
Status: RO
Content-Length: 7846
Lines: 192

--_004_SY4P282MB4175E0B0BBBD6276C067860DCAAFASY4P282MB4175AUSP_
Content-Type: multipart/alternative;
	boundary="_000_SY4P282MB4175E0B0BBBD6276C067860DCAAFASY4P282MB4175AUSP_"

--_000_SY4P282MB4175E0B0BBBD6276C067860DCAAFASY4P282MB4175AUSP_
Content-Type: text/plain; charset="iso-8859-4"
Content-Transfer-Encoding: quoted-printable

here it goes #2 with an attachment

________________________________
From: Ng=E0 Puanga P=FEtaiao Fellowships <noreply@puanga.royalsociety.org.n=
z>
Sent: Thursday, November 9, 2023 1:26 PM
To: Research Office <ro12345@mailinator.com>; Brand New <brand_new_person_1=
23@mailinator.com>; Radomirs Cirskis <Radomirs.Cirskis@royalsociety.org.nz>=
; Radomirs Cirskis <rcir178@aucklanduni.ac.nz>; nad2000+applicant@gmail.com=
 <nad2000+applicant@gmail.com>
Cc: RADOMIRS CIRSKIS <nad2000+admin@gmail.com>
Subject: [Ng=E0 Puanga P=FEtaiao Fellowships] Comment posted by RADOMIRS CI=
RSKIS (nad2000+admin@gmail.com) to NPP-AO1-2023-001: Ng=E0 Puanga P=FEtaiao=
 2023 -- SUPER TRUPPER


Comment posted by RADOMIRS CIRSKIS (nad2000+admin@gmail.com) to NPP-AO1-202=
3-001: Ng=E0 Puanga P=FEtaiao 2023 -- SUPER TRUPPER.

________________________________
To responde to this message, please, click here: REPLY<https://puanga.proda=
ta.nz/contracts/2/~update#correspondence>
To learn more about Ng=E0 Puanga P=FEtaiao Fellowships administered by the =
Royal Society Te Ap=E0rangi click here<https://www.royalsociety.org.nz/what=
-we-do/funds-and-opportunities/puanga>.

Ng=E0 mihi nui,


[Catalyst Fund Logo Alternative]        [Royal Society Te Ap=E0rangi]



Ng=E0 Puanga P=FEtaiao Fellowships

Waea telephone  +64 4 470 5756
=CFm=BAra email  puanga@royalsociety.org.nz<mailto:International.Applicatio=
ns@royalsociety.org.nz>

Royal Society Te Ap=E0rangi
11 Turnbull Street, Thorndon, Wellington 6011
PO Box 598, Wellington 6140, New Zealand
ROYALSOCIETY.ORG.NZ <http://royalsociety.org.nz/>


Please consider the environment before printing this email. The information=
 contained in this email message is intended only for the addressee and may=
 be confidential. If you are not the intended recipient, please notify us i=
mmediately.

--_000_SY4P282MB4175E0B0BBBD6276C067860DCAAFASY4P282MB4175AUSP_
Content-Type: text/html; charset="iso-8859-4"
Content-Transfer-Encoding: quoted-printable

<html>
<head>
<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Diso-8859-=
4">
<style type=3D"text/css" style=3D"display:none;"> P {margin-top:0;margin-bo=
ttom:0;} </style>
</head>
<body dir=3D"ltr">
<div class=3D"elementToProof" style=3D"font-family: Aptos, Aptos_EmbeddedFo=
nt, Aptos_MSFontService, Calibri, Helvetica, sans-serif; font-size: 11pt; c=
olor: rgb(0, 0, 0);">
here it goes #2 with an attachment</div>
<div class=3D"elementToProof" style=3D"font-family: Aptos, Aptos_EmbeddedFo=
nt, Aptos_MSFontService, Calibri, Helvetica, sans-serif; font-size: 11pt; c=
olor: rgb(0, 0, 0);">
<br>
</div>
<div id=3D"appendonsend"></div>
<hr style=3D"display:inline-block;width:98%" tabindex=3D"-1">
<div id=3D"divRplyFwdMsg" dir=3D"ltr"><font face=3D"Calibri, sans-serif" st=
yle=3D"font-size:11pt" color=3D"#000000"><b>From:</b> Ng=E0 Puanga P=FEtaia=
o Fellowships &lt;noreply@puanga.royalsociety.org.nz&gt;<br>
<b>Sent:</b> Thursday, November 9, 2023 1:26 PM<br>
<b>To:</b> Research Office &lt;ro12345@mailinator.com&gt;; Brand New &lt;br=
and_new_person_123@mailinator.com&gt;; Radomirs Cirskis &lt;Radomirs.Cirski=
s@royalsociety.org.nz&gt;; Radomirs Cirskis &lt;rcir178@aucklanduni.ac.nz&g=
t;; nad2000+applicant@gmail.com &lt;nad2000+applicant@gmail.com&gt;<br>
<b>Cc:</b> RADOMIRS CIRSKIS &lt;nad2000+admin@gmail.com&gt;<br>
<b>Subject:</b> [Ng=E0 Puanga P=FEtaiao Fellowships] Comment posted by RADO=
MIRS CIRSKIS (nad2000+admin@gmail.com) to NPP-AO1-2023-001: Ng=E0 Puanga P=
=FEtaiao 2023 -- SUPER TRUPPER</font>
<div>&nbsp;</div>
</div>
<div>
<p>Comment posted by RADOMIRS CIRSKIS (nad2000+admin@gmail.com) to NPP-AO1-=
2023-001: Ng=E0 Puanga P=FEtaiao 2023 -- SUPER TRUPPER.</p>
<hr>
To responde to this message, please, click here: <a href=3D"https://puanga.=
prodata.nz/contracts/2/~update#correspondence">
REPLY</a> <br>
To learn more about Ng=E0 Puanga P=FEtaiao Fellowships administered by the =
Royal Society Te Ap=E0rangi
<a href=3D"https://www.royalsociety.org.nz/what-we-do/funds-and-opportuniti=
es/puanga">
click here</a>.<br>
<br>
Ng=E0 mihi nui,
<p></p>
<br>
<p style=3D"margin-bottom:12.0pt"><span style=3D"font-size:12.0pt; font-fam=
ily:&quot;Helvetica&quot;,sans-serif; color:black">
<table border=3D"0">
<tbody>
<tr>
<td style=3D"text-align:left"><img border=3D"0" alt=3D"Catalyst Fund Logo A=
lternative" style=3D"max-height:120px; display:inline-block; margin-top:5px=
; margin-bottom:10px; vertical-align:top; width:auto" src=3D"https://puanga=
.royalsociety.org.nz/static/images/puanga.royalsociety.org.nz/MBIE_logo.jpg=
">
</td>
<td style=3D"text-align:right"><img border=3D"0" alt=3D"Royal Society Te Ap=
=E0rangi" style=3D"float:right; max-height:120px; display:inline-block; mar=
gin-top:5px; margin-bottom:10px; vertical-align:top; width:auto" src=3D"htt=
ps://puanga.royalsociety.org.nz/static/images/puanga.royalsociety.org.nz/RS=
_logo.png">
</td>
</tr>
</tbody>
</table>
</span><br>
<br>
<br>
Ng=E0 Puanga P=FEtaiao Fellowships</p>
<table border=3D"0" cellspacing=3D"0" cellpadding=3D"0" style=3D"border-col=
lapse:collapse">
<tbody>
<tr>
<td style=3D"padding:0cm 0cm 0cm 0cm">
<p style=3D"line-height:115%"><b><span style=3D"font-size:8.5pt; line-heigh=
t:115%; color:black">Waea telephone &nbsp;</span></b><span style=3D"font-si=
ze:8.5pt; line-height:115%; color:black">+64 4 470 5756<br>
<b>=CFm=BAra email</span></b><span style=3D"font-size:8.5pt; line-height:11=
5%">&nbsp;</span><span style=3D"font-size:8.5pt; line-height:115%; color:bl=
ack; background:white">
<a href=3D"mailto:International.Applications@royalsociety.org.nz"><span sty=
le=3D"color:black">puanga@royalsociety.org.nz</span></a></span></p>
<p><b><span style=3D"font-size:8.5pt; color:black">Royal Society Te Ap=E0ra=
ngi</span>
</b><span style=3D"font-size:8.5pt; color:black"><br>
11 Turnbull Street, Thorndon, Wellington 6011<br>
PO Box 598, Wellington 6140, New Zealand<br>
<a href=3D"http://royalsociety.org.nz/"><b><span style=3D"color:black">ROYA=
LSOCIETY.ORG.NZ</span>
</b></a></span></p>
<br>
<p><i><span style=3D"font-size:8.0pt; color:black">Please consider the envi=
ronment before printing this email. The information contained in this email=
 message is intended only for the addressee and may be confidential. If you=
 are not the intended recipient, please
 notify us immediately.</span></i></p>
</td>
<td width=3D"25%" valign=3D"bottom" style=3D"width:25.0%; padding:0cm 5.4pt=
 0cm 5.4pt">
</td>
</tr>
</tbody>
</table>
</div>
</body>
</html>

--_000_SY4P282MB4175E0B0BBBD6276C067860DCAAFASY4P282MB4175AUSP_--

--_004_SY4P282MB4175E0B0BBBD6276C067860DCAAFASY4P282MB4175AUSP_
Content-Type: text/csv; name="DocumentType-2023-07-21.csv"
Content-Description: DocumentType-2023-07-21.csv
Content-Disposition: attachment; filename="DocumentType-2023-07-21.csv";
	size=376; creation-date="Thu, 09 Nov 2023 00:28:51 GMT";
	modification-date="Thu, 09 Nov 2023 00:28:56 GMT"
Content-Transfer-Encoding: base64

aWQsY3JlYXRlZF9hdCx1cGRhdGVkX2F0LHJvbGUsbmFtZSxuYW1lX2VuLG5hbWVfbWkNCjQsMjAy
My0wNy0xOSAxODo0MDo0MSwyMDIzLTA3LTE5IDE4OjQwOjQxLEYsUm9sZXMgYW5kIFJlc291cmNl
cyxSb2xlcyBhbmQgUmVzb3VyY2VzLA0KMywyMDIzLTA3LTE5IDE4OjQwOjQxLDIwMjMtMDctMTkg
MTg6NDA6NDEsQixCdWRnZXQsQnVkZ2V0LA0KMiwyMDIzLTA3LTE5IDE4OjQwOjQxLDIwMjMtMDct
MTkgMTg6NDA6NDEsQ1YsQ3VycmljdWx1bSBWaXRhZSxDdXJyaWN1bHVtIFZpdGFlLA0KMSwyMDIz
LTA3LTE5IDE4OjQwOjQxLDIwMjMtMDctMTkgMTg6NDA6NDEsQUYsQXBwbGljYXRpb24gRm9ybSxB
cHBsaWNhdGlvbiBGb3JtLEFwcGxpY2F0aW9uIEZvcm0NCg==

--_004_SY4P282MB4175E0B0BBBD6276C067860DCAAFASY4P282MB4175AUSP_--

