From Radomirs.Cirskis@royalsociety.org.nz  Thu Nov  9 13:29:37 2023
Return-Path: <Radomirs.Cirskis@royalsociety.org.nz>
X-Original-To: noreply@puanga.royalsociety.org.nz
Delivered-To: noreply@puanga.royalsociety.org.nz
Received: from AUS01-SY4-obe.outbound.protection.outlook.com (mail-sy4aus01on2139.outbound.protection.outlook.com [40.107.107.139])
	by portal.pmscienceprizes.org.nz (Postfix) with ESMTPS id 37A30FA2C3
	for <noreply@puanga.royalsociety.org.nz>; Thu,  9 Nov 2023 13:29:37 +1300 (NZDT)
ARC-Seal: i=1; a=rsa-sha256; s=arcselector9901; d=microsoft.com; cv=none;
 b=H51grfHc/ONv+NU+pOgGc2/pwLT2iopRYiGVdhFWaCS+jDMT91oL3v+OoHjQ2+ncnW5MXx+IdKMSNDnVc4FB+Lb+TMgqOG+Mc4/UKI9hURpU6dhTQk1XGlWaWnxbcMUcL35iA37xoG92u4vC9TXJkddbCyU1Q8T+moDtwsHb2D/tzFDjuM/TWuCJd+C14gUrLrCq383O8RAAeC1+1Rr3Vt8tWza29NY7u90hcgtZafC5GmeKq78b36keDR9KVWk8NfL0W5cKJJQJBDFw4VgPrvFUDqQSXHzgIcUegpivoVnnSbIhyVjjg4JqNkStcieSOR4ZgeNw/EOW86BznM93CA==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=microsoft.com;
 s=arcselector9901;
 h=From:Date:Subject:Message-ID:Content-Type:MIME-Version:X-MS-Exchange-AntiSpam-MessageData-ChunkCount:X-MS-Exchange-AntiSpam-MessageData-0:X-MS-Exchange-AntiSpam-MessageData-1;
 bh=J8Mk1akynZX95cMDhOV07hyFsa7f72MKdf2PtIJWE4o=;
 b=OuCcm/zcDyVOev3rFa2HYlvtO6iBWb1ThtLNezttmSABKT/reZ9MbaWyGgR36PeUpsJoDU4UKz9aTGBHrDVejyHc/LwrutYiFYTp/UZj4OQ8xX2A2LUO2akllxYnPQfk2udFOqQimILjvtTHKKQ+/EdcsWuzZiWg3iHDp3W5D1vou4P2LaRM5a8BNcumszvI4Dm+Y+Q7smEl4yySkmzGXVUA0a2cNU7ogGvB52dbgVstFpHaEJx3W7g6aKCdnUt8G9j87FfWly74LV7BZH0lSNNq9oYHLyMEtMVqVV9DhtU/T46mtqGRQn5/gX6WbDZbGPyrSAai4XUcEJbMiBIZaw==
ARC-Authentication-Results: i=1; mx.microsoft.com 1; spf=pass
 smtp.mailfrom=royalsociety.org.nz; dmarc=pass action=none
 header.from=royalsociety.org.nz; dkim=pass header.d=royalsociety.org.nz;
 arc=none
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=royalsociety.org.nz;
 s=selector1;
 h=From:Date:Subject:Message-ID:Content-Type:MIME-Version:X-MS-Exchange-SenderADCheck;
 bh=J8Mk1akynZX95cMDhOV07hyFsa7f72MKdf2PtIJWE4o=;
 b=es37APc+WbPBFwu29hGqe338aDoaN+1Drwz8xjUw7PzyqpzXcQJc6KBFseLgNAM2/5G2izvqKAiYSY4L3ZU2elKDzn8yfdByQkRLszQunnTgYgc5z6VxJ+3LR8ifW7NBZd12b5ettdvSNjfct/JwT6070J+AXt6WbWfu6LQyJWn+FuNea7QPziC18hm1bRUkcbLlqWSKg8yrZ92yag/ZoD4V57viWkZwIZVjFVQGgJz8tRas14d8RZbcJLRGVtqEPJjOP9JfKYCH8dm27dRVLWYje4md9MRv+eXDErexm40pW/TVtMdvB+aq3T1JT2bHnw9ETDX9uSDxPiHVbi1jKg==
Received: from SY4P282MB4175.AUSP282.PROD.OUTLOOK.COM (2603:10c6:10:1ca::14)
 by SY7P282MB4581.AUSP282.PROD.OUTLOOK.COM (2603:10c6:10:274::21) with
 Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.20.6977.19; Thu, 9 Nov
 2023 00:29:31 +0000
Received: from SY4P282MB4175.AUSP282.PROD.OUTLOOK.COM
 ([fe80::4965:fcb2:67c0:7533]) by SY4P282MB4175.AUSP282.PROD.OUTLOOK.COM
 ([fe80::4965:fcb2:67c0:7533%4]) with mapi id 15.20.6954.024; Thu, 9 Nov 2023
 00:29:31 +0000
From: Radomirs Cirskis <Radomirs.Cirskis@royalsociety.org.nz>
To: =?iso-8859-4?Q?Ng=E0_Puanga_P=FEtaiao_Fellowships?=
	<noreply@puanga.royalsociety.org.nz>
Subject:
 =?iso-8859-4?Q?Re:_[Ng=E0_Puanga_P=FEtaiao_Fellowships]_Comment_posted_by?=
 =?iso-8859-4?Q?_RADOMIRS_CIRSKIS_(nad2000+admin@gmail.com)_to_NPP-AO1-202?=
 =?iso-8859-4?Q?3-001:_Ng=E0_Puanga_P=FEtaiao_2023_--_SUPER_TRUPPER?=
Thread-Topic:
 =?iso-8859-4?Q?[Ng=E0_Puanga_P=FEtaiao_Fellowships]_Comment_posted_by_RAD?=
 =?iso-8859-4?Q?OMIRS_CIRSKIS_(nad2000+admin@gmail.com)_to_NPP-AO1-2023-00?=
 =?iso-8859-4?Q?1:_Ng=E0_Puanga_P=FEtaiao_2023_--_SUPER_TRUPPER?=
Thread-Index: AQHaEqNgMRflmWrbCEaqhw/ou7a5FbBxIjNT
Date: Thu, 9 Nov 2023 00:29:31 +0000
Message-ID:
 <SY4P282MB4175E645A387C10B0CAD0F50CAAFA@SY4P282MB4175.AUSP282.PROD.OUTLOOK.COM>
References: <IV8vJ7P1dFFG4g@puanga.royalsociety.org.nz>
In-Reply-To: <IV8vJ7P1dFFG4g@puanga.royalsociety.org.nz>
Accept-Language: en-US
Content-Language: en-US
X-MS-Has-Attach:
X-MS-TNEF-Correlator:
msip_labels:
authentication-results: dkim=none (message not signed)
 header.d=none;dmarc=none action=none header.from=royalsociety.org.nz;
x-ms-publictraffictype: Email
x-ms-traffictypediagnostic: SY4P282MB4175:EE_|SY7P282MB4581:EE_
x-ms-office365-filtering-correlation-id: b506d9de-3b67-4698-b516-08dbe0baf13f
x-ms-exchange-senderadcheck: 1
x-ms-exchange-antispam-relay: 0
x-microsoft-antispam: BCL:0;
x-microsoft-antispam-message-info:
 fVUa6C6KyHxkeRFLBYCfRRexc85WWTsxvwEhuWGAD2bcThI69FiAcL3MctjUaHS3lRDJ0nByqJxXlpwjYiBvR6CmYYu4nhFkw0oOXy5CI4/c+afjKazMvr0pzIMW3J+7m/9Z8sJsd+cQM6huGptzEdIfSj4+40WB3bXy5Q3AmO8gx9zUw3btO8d4bLSy0LKm/izMXigWufNgt5smmkIw1ZeWSuC91onkhLL9u1jfysMYOzC2lCEbIez+W+Ljew3sZfAPTl4fZiVCEqhw87HxZs0/3j7df9yBvcoC8dEom0l1Vafo6MDDqe6y7UMU2Qp+aXXUdv8wVYpTl+QRZAVmieQz56++ZiiOERm1hrVWLw0VuazXHWXqNGNQSCs4akyb+O5rudgAJ6ozp8LTGGrkBk/LucLkPlt45xHSUcDGEz9i9rKuQuv+GEqruIbUo2UyyHaSG3gsHB/MK3ndlgiq+NPED9afr8QR1tZ5+usjwKshaMxYN8TvOprIDklEg2KEBYp9ppvzwo6qO+ze1udz4xDkCtUH2NZ8KdoVLFGDysqihnpAGwGL4lo240XHoa18XxWILj8UK2C9wtzhWB9netSjbaVHD/nA0NzBNuLzqDoDhjGb5LWcBUqsx+R2RJSgH6X3Q44mINRZ45a60hDLFQ==
x-forefront-antispam-report:
 CIP:255.255.255.255;CTRY:;LANG:en;SCL:1;SRV:;IPV:NLI;SFV:NSPM;H:SY4P282MB4175.AUSP282.PROD.OUTLOOK.COM;PTR:;CAT:NONE;SFS:(13230031)(346002)(396003)(136003)(39840400004)(376002)(366004)(230922051799003)(64100799003)(1690799017)(451199024)(186009)(1800799009)(55016003)(19627405001)(478600001)(71200400001)(45080400002)(9686003)(7696005)(6506007)(53546011)(224303003)(38100700002)(166002)(122000001)(86362001)(33656002)(41300700001)(5660300002)(66946007)(66476007)(66556008)(76116006)(64756008)(316002)(66446008)(6916009)(83380400001)(26005)(2906002)(38070700009)(52536014)(8936002);DIR:OUT;SFP:1102;
x-ms-exchange-antispam-messagedata-chunkcount: 1
x-ms-exchange-antispam-messagedata-0:
 =?iso-8859-4?Q?4ZmIrXf8kAiIco+V67xT4E+KzyntE1ljVh2FDj8mZhkGNiidCFGWpFWQHN?=
 =?iso-8859-4?Q?q+VIXgt2oWgj0CtBrGDfZ9RU+crbvMH56W75JXJQqhW+4ocDv7DGT62sd3?=
 =?iso-8859-4?Q?u81yyeb9qVJeIJEvu0MoeDN2BFMsTaeWLBstBa38ODHdXJh9t6gyA2Xw1f?=
 =?iso-8859-4?Q?PIwMN0SYJNTG02GgHvh8Mm76iaW9vnSD5pE2/WwZ14rtepx2TQi71BqsbX?=
 =?iso-8859-4?Q?QGRHc2cQFft6Jmb05urbTnDbNMeCUQ4Ac0Z/pHn+Li3TlaIHT/H3kWAvyq?=
 =?iso-8859-4?Q?Rp8BDZdMjWuBmu9jb9N+2MaHDA7DBXRFRDyC2mn2obWe5CNLSNK7ukU2Iu?=
 =?iso-8859-4?Q?MjdiUqP892L2Lu/b2mwJkBW/VeTucg+Yzz9GZoqebrA9iJj78/Vict+CMc?=
 =?iso-8859-4?Q?IuZ2jJC4n5j1chu7F/zl3Wu3oEoC5oIoHUOCaRbMi8U8+NE+1nwLx1OsSr?=
 =?iso-8859-4?Q?rQ94lrAAewI9WF/kPe2tcBiGiXIovqqnESYrM47HcwvyddbfQRh/JzKF2E?=
 =?iso-8859-4?Q?yIoMdxfyQz8CL6eK+Q5PtnbY0fcJEXtqif6VrT8mgJLMTQxGcK6VkTA07N?=
 =?iso-8859-4?Q?UqMqeTsG1vCEy2bWaSXmhwZFQDWUJt2uvO9C9N52JDaOV+LlNENzzCKR1l?=
 =?iso-8859-4?Q?amUJwz9C4vlN4q7qpOHzSAcp8DH3CaN5YNCZcqiyTPnNvXp4NVasnybgsZ?=
 =?iso-8859-4?Q?8B7Y5udR/+xyO3E3zsA5HyVoUltbZvBLBBzRQ/+q7uA0nkX4D9Vg5syF9F?=
 =?iso-8859-4?Q?7ShwC9hBxgEZsVrDVy+S7G/6IzJCaAl5laV48GR0h4yly/YV6yxtptC204?=
 =?iso-8859-4?Q?iNlWAwPX4MUaq9ZTNyhX83YPbrcHAJXC8hGcax3mqCzccK/uCqb8wXP0Pe?=
 =?iso-8859-4?Q?j5s0tv/yr7AeN1nHYBDZKluIfrw7ijTqRPthmMI/JVA2hrpbGPDy40bcMx?=
 =?iso-8859-4?Q?nQ3GMUrJhMju7SKl8ENK//sbMoA29gVSK7khnRiZtuQEP29EsADmcvPyDR?=
 =?iso-8859-4?Q?tXmOtnfYMS8DQ+p+7FBOSsSo4Zv5fNRpBceZvUH1RSM7w4ZZN3S59eGD02?=
 =?iso-8859-4?Q?BSkadlEIClY7YS3mq3HGpQKCP7kCpDJTWVtMdJgZmP9oL2GBUDI9c+UEuc?=
 =?iso-8859-4?Q?kn7k75s0+auL/wjzkQFo6+PiWvrZc64i38cJMm+bWO2PRcY7JF2OaSU90M?=
 =?iso-8859-4?Q?/FSREm2ZHz01EV7PifqXc8LEySsErPO70QfjAXYOsjOzgZS/l5dBJR8kA5?=
 =?iso-8859-4?Q?3SKvy+KuH93Y9bBp0kVU8/NVPEVZHULaJ4plxWkzBK5lJe7//9gW30tmWx?=
 =?iso-8859-4?Q?7XlQmkS5c8erfeB14Llg3pdYhqJWy56XNLspGlxhvvmBygMbhRm8dUTinn?=
 =?iso-8859-4?Q?4LHjI5ipBmDQrzAQVALfP++zq+AbnIYfda2yx4HNiQFbdf4ccepi8/p0iW?=
 =?iso-8859-4?Q?KT6cygicCWYTapegkAZcjvh5g2WVLCi2nwnDZwoPnfH/l2urqbnBUA0DMV?=
 =?iso-8859-4?Q?6GHHB1Lzijl4/5LNMJqU5LUX6qtwj3jtU2SJ6DpXYCrOvokoTPCUjkdHpC?=
 =?iso-8859-4?Q?CDwx74/4Lxdnsra57ETMcFDRYeoZS3qJU7x8kWPPrl6PeiPMr0VjTmgJj3?=
 =?iso-8859-4?Q?bkHfCwCpwW5NICHgsY4GovmVmdXv4uODOfwMrbOlPBwUEgPeN2Vv2fAg?=
 =?iso-8859-4?Q?=3D=3D?=
Content-Type: multipart/alternative;
	boundary="_000_SY4P282MB4175E645A387C10B0CAD0F50CAAFASY4P282MB4175AUSP_"
MIME-Version: 1.0
X-OriginatorOrg: royalsociety.org.nz
X-MS-Exchange-CrossTenant-AuthAs: Internal
X-MS-Exchange-CrossTenant-AuthSource: SY4P282MB4175.AUSP282.PROD.OUTLOOK.COM
X-MS-Exchange-CrossTenant-Network-Message-Id: b506d9de-3b67-4698-b516-08dbe0baf13f
X-MS-Exchange-CrossTenant-originalarrivaltime: 09 Nov 2023 00:29:31.8809
 (UTC)
X-MS-Exchange-CrossTenant-fromentityheader: Hosted
X-MS-Exchange-CrossTenant-id: 684f9caf-da9b-406a-bede-5d126772ef54
X-MS-Exchange-CrossTenant-mailboxtype: HOSTED
X-MS-Exchange-CrossTenant-userprincipalname: 4qwI0iDU/cGI3tmNFXLxiTc5OYk5Ttzz7rhom3qPD4pMYxVTXLH2JaFaaBked5nCtWVKs5a00Jzp+zTjgrIb175f4M8oxg0/mnxaa9jtspI=
X-MS-Exchange-Transport-CrossTenantHeadersStamped: SY7P282MB4581
Content-Length: 6545
Lines: 164

--_000_SY4P282MB4175E645A387C10B0CAD0F50CAAFASY4P282MB4175AUSP_
Content-Type: text/plain; charset="iso-8859-4"
Content-Transfer-Encoding: quoted-printable

replay to a comment w/o attachment... from outlook
________________________________
From: Ng=E0 Puanga P=FEtaiao Fellowships <noreply@puanga.royalsociety.org.n=
z>
Sent: Thursday, November 9, 2023 1:26 PM
To: Research Office <ro12345@mailinator.com>; Brand New <brand_new_person_1=
23@mailinator.com>; Radomirs Cirskis <Radomirs.Cirskis@royalsociety.org.nz>=
; Radomirs Cirskis <rcir178@aucklanduni.ac.nz>; nad2000+applicant@gmail.com=
 <nad2000+applicant@gmail.com>
Cc: RADOMIRS CIRSKIS <nad2000+admin@gmail.com>
Subject: [Ng=E0 Puanga P=FEtaiao Fellowships] Comment posted by RADOMIRS CI=
RSKIS (nad2000+admin@gmail.com) to NPP-AO1-2023-001: Ng=E0 Puanga P=FEtaiao=
 2023 -- SUPER TRUPPER


Comment posted by RADOMIRS CIRSKIS (nad2000+admin@gmail.com) to NPP-AO1-202=
3-001: Ng=E0 Puanga P=FEtaiao 2023 -- SUPER TRUPPER.

________________________________
To responde to this message, please, click here: REPLY<https://puanga.proda=
ta.nz/contracts/2/~update#correspondence>
To learn more about Ng=E0 Puanga P=FEtaiao Fellowships administered by the =
Royal Society Te Ap=E0rangi click here<https://www.royalsociety.org.nz/what=
-we-do/funds-and-opportunities/puanga>.

Ng=E0 mihi nui,


[Catalyst Fund Logo Alternative]        [Royal Society Te Ap=E0rangi]



Ng=E0 Puanga P=FEtaiao Fellowships

Waea telephone  +64 4 470 5756
=CFm=BAra email  puanga@royalsociety.org.nz<mailto:International.Applicatio=
ns@royalsociety.org.nz>

Royal Society Te Ap=E0rangi
11 Turnbull Street, Thorndon, Wellington 6011
PO Box 598, Wellington 6140, New Zealand
ROYALSOCIETY.ORG.NZ <http://royalsociety.org.nz/>


Please consider the environment before printing this email. The information=
 contained in this email message is intended only for the addressee and may=
 be confidential. If you are not the intended recipient, please notify us i=
mmediately.

--_000_SY4P282MB4175E645A387C10B0CAD0F50CAAFASY4P282MB4175AUSP_
Content-Type: text/html; charset="iso-8859-4"
Content-Transfer-Encoding: quoted-printable

<html>
<head>
<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Diso-8859-=
4">
<style type=3D"text/css" style=3D"display:none;"> P {margin-top:0;margin-bo=
ttom:0;} </style>
</head>
<body dir=3D"ltr">
<div style=3D"font-family: Aptos, Aptos_EmbeddedFont, Aptos_MSFontService, =
Calibri, Helvetica, sans-serif; font-size: 11pt; color: rgb(0, 0, 0);" clas=
s=3D"elementToProof">
replay to a comment w/o attachment... from outlook</div>
<div id=3D"appendonsend"></div>
<hr style=3D"display:inline-block;width:98%" tabindex=3D"-1">
<div id=3D"divRplyFwdMsg" dir=3D"ltr"><font face=3D"Calibri, sans-serif" st=
yle=3D"font-size:11pt" color=3D"#000000"><b>From:</b> Ng=E0 Puanga P=FEtaia=
o Fellowships &lt;noreply@puanga.royalsociety.org.nz&gt;<br>
<b>Sent:</b> Thursday, November 9, 2023 1:26 PM<br>
<b>To:</b> Research Office &lt;ro12345@mailinator.com&gt;; Brand New &lt;br=
and_new_person_123@mailinator.com&gt;; Radomirs Cirskis &lt;Radomirs.Cirski=
s@royalsociety.org.nz&gt;; Radomirs Cirskis &lt;rcir178@aucklanduni.ac.nz&g=
t;; nad2000+applicant@gmail.com &lt;nad2000+applicant@gmail.com&gt;<br>
<b>Cc:</b> RADOMIRS CIRSKIS &lt;nad2000+admin@gmail.com&gt;<br>
<b>Subject:</b> [Ng=E0 Puanga P=FEtaiao Fellowships] Comment posted by RADO=
MIRS CIRSKIS (nad2000+admin@gmail.com) to NPP-AO1-2023-001: Ng=E0 Puanga P=
=FEtaiao 2023 -- SUPER TRUPPER</font>
<div>&nbsp;</div>
</div>
<div>
<p>Comment posted by RADOMIRS CIRSKIS (nad2000+admin@gmail.com) to NPP-AO1-=
2023-001: Ng=E0 Puanga P=FEtaiao 2023 -- SUPER TRUPPER.</p>
<hr>
To responde to this message, please, click here: <a href=3D"https://puanga.=
prodata.nz/contracts/2/~update#correspondence">
REPLY</a> <br>
To learn more about Ng=E0 Puanga P=FEtaiao Fellowships administered by the =
Royal Society Te Ap=E0rangi
<a href=3D"https://www.royalsociety.org.nz/what-we-do/funds-and-opportuniti=
es/puanga">
click here</a>.<br>
<br>
Ng=E0 mihi nui,
<p></p>
<br>
<p style=3D"margin-bottom:12.0pt"><span style=3D"font-size:12.0pt; font-fam=
ily:&quot;Helvetica&quot;,sans-serif; color:black">
<table border=3D"0">
<tbody>
<tr>
<td style=3D"text-align:left"><img border=3D"0" alt=3D"Catalyst Fund Logo A=
lternative" style=3D"max-height:120px; display:inline-block; margin-top:5px=
; margin-bottom:10px; vertical-align:top; width:auto" src=3D"https://puanga=
.royalsociety.org.nz/static/images/puanga.royalsociety.org.nz/MBIE_logo.jpg=
">
</td>
<td style=3D"text-align:right"><img border=3D"0" alt=3D"Royal Society Te Ap=
=E0rangi" style=3D"float:right; max-height:120px; display:inline-block; mar=
gin-top:5px; margin-bottom:10px; vertical-align:top; width:auto" src=3D"htt=
ps://puanga.royalsociety.org.nz/static/images/puanga.royalsociety.org.nz/RS=
_logo.png">
</td>
</tr>
</tbody>
</table>
</span><br>
<br>
<br>
Ng=E0 Puanga P=FEtaiao Fellowships</p>
<table border=3D"0" cellspacing=3D"0" cellpadding=3D"0" style=3D"border-col=
lapse:collapse">
<tbody>
<tr>
<td style=3D"padding:0cm 0cm 0cm 0cm">
<p style=3D"line-height:115%"><b><span style=3D"font-size:8.5pt; line-heigh=
t:115%; color:black">Waea telephone &nbsp;</span></b><span style=3D"font-si=
ze:8.5pt; line-height:115%; color:black">+64 4 470 5756<br>
<b>=CFm=BAra email</span></b><span style=3D"font-size:8.5pt; line-height:11=
5%">&nbsp;</span><span style=3D"font-size:8.5pt; line-height:115%; color:bl=
ack; background:white">
<a href=3D"mailto:International.Applications@royalsociety.org.nz"><span sty=
le=3D"color:black">puanga@royalsociety.org.nz</span></a></span></p>
<p><b><span style=3D"font-size:8.5pt; color:black">Royal Society Te Ap=E0ra=
ngi</span>
</b><span style=3D"font-size:8.5pt; color:black"><br>
11 Turnbull Street, Thorndon, Wellington 6011<br>
PO Box 598, Wellington 6140, New Zealand<br>
<a href=3D"http://royalsociety.org.nz/"><b><span style=3D"color:black">ROYA=
LSOCIETY.ORG.NZ</span>
</b></a></span></p>
<br>
<p><i><span style=3D"font-size:8.0pt; color:black">Please consider the envi=
ronment before printing this email. The information contained in this email=
 message is intended only for the addressee and may be confidential. If you=
 are not the intended recipient, please
 notify us immediately.</span></i></p>
</td>
<td width=3D"25%" valign=3D"bottom" style=3D"width:25.0%; padding:0cm 5.4pt=
 0cm 5.4pt">
</td>
</tr>
</tbody>
</table>
</div>
</body>
</html>

--_000_SY4P282MB4175E645A387C10B0CAD0F50CAAFASY4P282MB4175AUSP_--

