From g.jfskdfjs@org111.ac.nz  Wed Aug 14 15:02:33 2024
Return-Path: <g.jfskdfjs@org111.ac.nz>
X-Original-To: app@xn--twhia-fwa.royalsociety.org.nz
Delivered-To: app@xn--twhia-fwa.royalsociety.org.nz
Received: from AUS01-ME3-obe.outbound.protection.outlook.com (mail-me3aus01on2173.outbound.protection.outlook.com [40.107.108.173])
	by portal.pmscienceprizes.org.nz (Postfix) with ESMTPS id 11FD5FA163
	for <app@xn--twhia-fwa.royalsociety.org.nz>; Wed, 14 Aug 2024 15:02:33 +1200 (NZST)
ARC-Seal: i=1; a=rsa-sha256; s=arcselector10001; d=microsoft.com; cv=none;
 b=YZLOorVT5DUnZVlu47NPqgKCwi1OvsFTHCIsx3D+bBgyj9UHumuNX036hpkFfqtB7QEIycHhu1GhmWgeL0CKC1ioBvI2xMlXq3xsWcBcykjN1kp7mm+XLpDz8oZHE6sv4gMBI6DsyNp75W2qKPK0cwNmLEjU81JgcryO1ObR0wZn/HbddspZiYJuviLdxlz/QZXjnPaO0hS3Vfm8DPzUh03E/6hGCWAid4GGG2j15BI0mMWyEizJNbjCbqMzUtLgGYHTNOvsBnI7vG3uhrTKoG9jTAzECZeqcj3zmfoCJkd4cylmPpnCa12VD8tSOnZUJpR/3vwBCPD4HCjR9SzNnQ==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=microsoft.com;
 s=arcselector10001;
 h=From:Date:Subject:Message-ID:Content-Type:MIME-Version:X-MS-Exchange-AntiSpam-MessageData-ChunkCount:X-MS-Exchange-AntiSpam-MessageData-0:X-MS-Exchange-AntiSpam-MessageData-1;
 bh=5PjxeoeL0s+eG15rP7cbSXA6whmIJ/Y/2fXj3zqT6vQ=;
 b=Svv5pR7vCMvvDDztzffxZEqS88LNIPQgwt9TXjgcm01xpywEYkUC9DGQ6ckCJTr4McUnFA8oMV487TJ9re+BzN5TMfPhAKN5qjMiykIO6gezPEsvyTCrdl4VbWq+KsqchLF8fK13O3rtXBZ9MJkQQNLcW1Tjx/hqmjrV8Q3oBHP4MfserrlUUYrI5v2qilZ4DBmRBtd5ehDP9rtl3XpEL3LxadTrRPCe9hy6kKTK0SuwZ44U6bQuwQeOLJq62HkgzfwOmY01NAiso4dt0KU08vXfePVaqNcz0CCtafGXrRFpDcJNR628ryLrGmyIF+RivhrgNJTW9b2zZ817Ze5a3g==
ARC-Authentication-Results: i=1; mx.microsoft.com 1; spf=pass
 smtp.mailfrom=org111.ac.nz; dmarc=pass action=none
 header.from=org111.ac.nz; dkim=pass header.d=org111.ac.nz; arc=none
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=org111.ac.nz;
 s=selector1;
 h=From:Date:Subject:Message-ID:Content-Type:MIME-Version:X-MS-Exchange-SenderADCheck;
 bh=5PjxeoeL0s+eG15rP7cbSXA6whmIJ/Y/2fXj3zqT6vQ=;
 b=r7MOHsr1pelQ2xhQL+DB+Cr39tkNW+UKXMNo0BTKqjpTX2w9bqWHzHINZ4EKvgvb2z8ONDS2K4NuDe25g2tPei3KTF/o0hB+B+BtrLNopkm0vZeIfYYQ6C23FXHfZqhbADbDft+f9Fz+utW7hABGJ9Ei9WWy69rYrgUwJmsW6u4=
Received: from SY7P300MB0720.AUSP300.PROD.OUTLOOK.COM (2603:10c6:10:288::5) by
 ME0P300MB1439.AUSP300.PROD.OUTLOOK.COM (2603:10c6:220:24a::20) with Microsoft
 SMTP Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id
 15.20.7849.22; Wed, 14 Aug 2024 03:02:30 +0000
Received: from SY7P300MB0720.AUSP300.PROD.OUTLOOK.COM
 ([fe80::fbff:fff1:8b9b:ee0f]) by SY7P300MB0720.AUSP300.PROD.OUTLOOK.COM
 ([fe80::fbff:fff1:8b9b:ee0f%4]) with mapi id 15.20.7849.021; Wed, 14 Aug 2024
 03:02:30 +0000
From: Wgxigsg jfskdfjs <g.pooiuy@org111.ac.nz>
To: =?iso-8859-4?Q?app=40t=E0whia=2Eroyalsociety=2Eorg=2Enz?=
	<app@xn--twhia-fwa.royalsociety.org.nz>
Subject:
 =?iso-8859-4?Q?Read:_[T=E0whia_Te_Mana_Fellowships]_You_are_invited_as_a_?=
 =?iso-8859-4?Q?referee_for_a_T=E0whia_Te_Mana_Fellowships_application?=
Thread-Topic:
 =?iso-8859-4?Q?[T=E0whia_Te_Mana_Fellowships]_You_are_invited_as_a_refere?=
 =?iso-8859-4?Q?e_for_a_T=E0whia_Te_Mana_Fellowships_application?=
Thread-Index: AQHa7dc2wJdfcOwJxEi842coJq83ibImER0A
Date: Wed, 14 Aug 2024 03:02:30 +0000
Message-ID:
 <SY7P300MB07204081E8E0FC9AA81D5D68C3872@SY7P300MB0720.AUSP300.PROD.OUTLOOK.COM>
In-Reply-To: <qQCmQ6ElGlCXRw@xn--twhia-fwa.royalsociety.org.nz>
Accept-Language: en-GB, en-US
Content-Language: en-US
X-MS-Has-Attach:
X-MS-TNEF-Correlator:
authentication-results: dkim=none (message not signed)
 header.d=none;dmarc=none action=none header.from=org111.ac.nz;
x-ms-publictraffictype: Email
x-ms-traffictypediagnostic: SY7P300MB0720:EE_|ME0P300MB1439:EE_
x-ms-office365-filtering-correlation-id: 31292b91-7430-410c-3a2e-08dcbc0d898b
x-ms-exchange-senderadcheck: 1
x-ms-exchange-antispam-relay: 0
x-microsoft-antispam: BCL:0;ARA:13230040|376014|366016|1800799024|38070700018;
x-microsoft-antispam-message-info:
 =?iso-8859-4?Q?tHjiUs3TnrVWOvLOQXo1Or6YE4618KKGHxlEKTgn5RPcxsLawUVGzt18Lm?=
 =?iso-8859-4?Q?6sOaIMpULNYzzbJJexccu2zleZh+PKQhnDRh6Y9dEtS3uhJB0Mv2/mZXaJ?=
 =?iso-8859-4?Q?gwPhHqGTsGmPmk9pb73DLLgY/YMAVROHdOu/lHmHCtEvxoQ4IVn5hQ2v0k?=
 =?iso-8859-4?Q?DJFa95vYh28AdKOByQMPSO4XxSoiQgmdznNAA+N4mZdHx8jocf0ZQiltG+?=
 =?iso-8859-4?Q?2Of8zWqK8tfyhULcGoyLPHSNS5hjkr0s0pbYRUUcdblBYLmSNDHgfcJOhx?=
 =?iso-8859-4?Q?Riy1MwrGlnpecAIBpy0deghLggpLdUDu72fQGuG6Ky6TzT7qls1C2BbIri?=
 =?iso-8859-4?Q?79FbBA0hVk1OkAjaECi3LKefs5dWfXH9Y24IcC6dH0WdQ4zwjaMSJt9FCA?=
 =?iso-8859-4?Q?MUhjT4bQD+nkJHNhMb9wNAFT6nD28pSkHHL050m0jnn/rTJBdu0fEeWNnM?=
 =?iso-8859-4?Q?72ezVkTDVtJiE+SG+OW221euTsWkTrVbHYfs1rKxTf5xZ5z8Ofik29gWfN?=
 =?iso-8859-4?Q?oPsSXM1rHzWNKVZYpnu3kkiFdy7drsMmd8L+MxV+5ciete30hfVKCi7iSr?=
 =?iso-8859-4?Q?+SKKPz8Lim4o+unNjH+YmAxYB9dcuEWr43HZ/mDBeE5Fgg56tDW2302vwB?=
 =?iso-8859-4?Q?6lpdw6zYx1w0BARnRZejCqj89f2ZBgapukifjvTTiiOy4nLNEHYJPhbaXn?=
 =?iso-8859-4?Q?tvBZZuJu4/EKuQYS28x2UdRLsmtZgTA05gTJ9Kw/+0XwtdobncclavVMna?=
 =?iso-8859-4?Q?uyz1TO5f5hi2t2LynHY9GjhE9tTTrQZto1z6HUI47zd+B4EIUig+9uJONx?=
 =?iso-8859-4?Q?6TNISILe+oX4KkJ2r1jSWMNsQ1/gtso7ecClxOh2qyR6k5rG6gwGU8UO1+?=
 =?iso-8859-4?Q?s143Uk3BlvHsHG5TLK7BY6u7yfOjlX3fHzxl7jz953Yy9JJjZqelPMWOWE?=
 =?iso-8859-4?Q?d2LEQqlyHUKcEPg5eCwRgK8p3C3XDfg8+6zoC4XK+oLHKy+MLDcDoVbrBl?=
 =?iso-8859-4?Q?P9uMsE07mO5b08zL2YWNHKpVtSEFfTNQ8OrYW3nxTr1MR9JYFHF+6QlMvq?=
 =?iso-8859-4?Q?9pJoHyrM7yI9/zK6Fj1S3s401XbXZiYin9SYfhYQeS4gJNEqJ2WDSiYP2q?=
 =?iso-8859-4?Q?6KRnGfhtVa4bc4655m5hr4fpAtoOGLyw/+8LnZzR7Z6rTiS+ZL?=
x-forefront-antispam-report:
 CIP:255.255.255.255;CTRY:;LANG:en;SCL:1;SRV:;IPV:NLI;SFV:NSPM;H:SY7P300MB0720.AUSP300.PROD.OUTLOOK.COM;PTR:;CAT:NONE;SFS:(13230040)(376014)(366016)(1800799024)(38070700018);DIR:OUT;SFP:1102;
x-ms-exchange-antispam-messagedata-chunkcount: 1
x-ms-exchange-antispam-messagedata-0:
 =?iso-8859-4?Q?RCygRVAAGFkiwjH7eGhjCRfp8dO8TAV92CtLbH2Y4mjYXIQLQ/R1nscHk6?=
 =?iso-8859-4?Q?46eQjBMvAEzrdtPwuURQTh8vSPsbJJHx4wz4PRt6oG/OlYB+KX3E50XjHT?=
 =?iso-8859-4?Q?J6CamyDDVxTZfKJKb/qXBY4wSh61dR5rHfuCakDPqbFCqLZCFo/B/aR+nK?=
 =?iso-8859-4?Q?/6OEFBQTZeiRtiMK0FZs/am6U3+Wyc03VoTpXOn+QgJ21RyeE2bhwTytwt?=
 =?iso-8859-4?Q?cPzD373nqu81R3vRO2wplOUDoqJCUlpDK4pz7pZWcZFFEiZcjJ8i+bZP3b?=
 =?iso-8859-4?Q?sY73nljNlNx+PSN7lGhRfWA1Q62aQhJAp4+5RBZkx0KAS6PCVwY8rXdWhO?=
 =?iso-8859-4?Q?Orh82EilmxQR9P6RLyIcZTypl8Uh3T/5CJJzr+vX4Kd1svhrh59IdPgTge?=
 =?iso-8859-4?Q?/49vG4qDwZNk6pSjztvF6qxQ54SxDb5omQNY0FoIVp9B6TEQ9+cY0MrMSN?=
 =?iso-8859-4?Q?8KtAUjgLnejyAD3Cp+RK9lTpu0RUNqZ2bgXx59HD1nZlbsupAxyJDOxyO/?=
 =?iso-8859-4?Q?vVjuaNpCAvzopW0fbYHhWGl+XBoJOp7uLsa8Qz5NUjFWjd1JEPUfHjY12Y?=
 =?iso-8859-4?Q?ICQPs/AkhrQlQ5f+IwlDT9guKXsOsijlzPHJcvBkXPJhzSXbfk7kvc+w+U?=
 =?iso-8859-4?Q?jalqiGRWvqVYnVdUZ+Lxpy+NZeFCE1+X6Cg2lhdFnzucLWVMHcwax5mCgQ?=
 =?iso-8859-4?Q?5OeUJybmj85izvpWfHoZrbdByYcPDztIZRz9vghuO25zOCWmo68RiC6T0Y?=
 =?iso-8859-4?Q?2q9CO08gdtINYILbC3AJLhDbIk/etAi34hJimPeVGaE5zMyTV7ozLl+05l?=
 =?iso-8859-4?Q?haZh2p/7GDgirbZtYliZf+tyaCEfHijvnRCb1D2QAmcT1fwORrAHH2Pa9j?=
 =?iso-8859-4?Q?lMaMcIzAVrlN2tShvxYxXqr23J5y2KzJKCoOmU6wGNzH2+5s4SgUFG9Hbu?=
 =?iso-8859-4?Q?j++I+5sdnJCme9DZs79s4/Lxp5odRTSVYK6RIDw2wTBuphworSnhDhgy73?=
 =?iso-8859-4?Q?w6O2qGiVmIBSaOk27zhUoj//On1SPDs6U+/RYAZnU5yVi17yPbRqPHGfnt?=
 =?iso-8859-4?Q?dI5lF+EumlPlTULnc6EoRfLmYE3WB1kAZpYhAzgHGbBJT438hqc70xT3F7?=
 =?iso-8859-4?Q?SWjTnYHcmdk9eGKE5jVczZ20GOg9IkhL7TWtqIjDTuI/zv5gCWzG/pWvh7?=
 =?iso-8859-4?Q?ofwY710VfGuwS1WURWsGBhB4bqbRRQ0B+dXytHwQcWVak2eK9FLQoaUIP/?=
 =?iso-8859-4?Q?WqGHS7keAAhag6bJ3Kn230f4gtgBciNT/oPfCOksfzkBdG+VZnmnO/mb3k?=
 =?iso-8859-4?Q?UUARgWm/dgsYv2ZUUAVz0E0xpOYRNKMBJ8QjRoWjzXvXRljW+DKh2Pop58?=
 =?iso-8859-4?Q?puTmhZRlDW4bZibqA6Jf3areUALJTKAgEADFkv8ZPMT2lJZVtMFGqrf34g?=
 =?iso-8859-4?Q?Qe40tkNcHhsF5QZYgZu/yF4o7SjQLTOk9vbo/bPaDqnz04bwq4jF0yjoOL?=
 =?iso-8859-4?Q?eN7DfUyjQDXZOX7ZVx/2Q4ZgSz6htg2J9wQ4SIdKsdunyYm6S/ifwJO8Gw?=
 =?iso-8859-4?Q?qWbGdrq4Zs1h5P6MBvTww2/xWJ01ODlpKv2cZMDjgGE7kL3c2xBhjaNtv/?=
 =?iso-8859-4?Q?2K1UfXdXnqMdpzHc63u1e/HiyjUUzjpR72VZAlW5YT1k2eHou+1vl0Tw?=
 =?iso-8859-4?Q?=3D=3D?=
Content-Type: multipart/report;
	boundary="_000_SY7P300MB07204081E8E0FC9AA81D5D68C3872SY7P300MB0720AUSP_";
	report-type=disposition-notification
MIME-Version: 1.0
X-OriginatorOrg: org111.ac.nz
X-MS-Exchange-CrossTenant-AuthAs: Internal
X-MS-Exchange-CrossTenant-AuthSource: SY7P300MB0720.AUSP300.PROD.OUTLOOK.COM
X-MS-Exchange-CrossTenant-Network-Message-Id: 31292b91-7430-410c-3a2e-08dcbc0d898b
X-MS-Exchange-CrossTenant-originalarrivaltime: 14 Aug 2024 03:02:30.7609
 (UTC)
X-MS-Exchange-CrossTenant-fromentityheader: Hosted
X-MS-Exchange-CrossTenant-id: d1b36e95-0d50-42e9-958f-b63fa906beaa
X-MS-Exchange-CrossTenant-mailboxtype: HOSTED
X-MS-Exchange-CrossTenant-userprincipalname: eV1PFZjrSDdFRnG6IOSST5EB8cMxJYUfEP081KfFjg1/T8WlYsUSLl13zkWD3Ngv8uO92ZOlXrR6XWLvGp2zftHkRFNe8RRn/S9nWIyF2mU=
X-MS-Exchange-Transport-CrossTenantHeadersStamped: ME0P300MB1439
Status: RO
Content-Length: 2059
Lines: 59

--_000_SY7P300MB07204081E8E0FC9AA81D5D68C3872SY7P300MB0720AUSP_
Content-Type: multipart/alternative;
	boundary="_002_SY7P300MB07204081E8E0FC9AA81D5D68C3872SY7P300MB0720AUSP_"

--_002_SY7P300MB07204081E8E0FC9AA81D5D68C3872SY7P300MB0720AUSP_
Content-Type: text/plain; charset="iso-8859-4"
Content-Transfer-Encoding: quoted-printable

Your message

   To: Wgxigsg jfskdfjs
   Subject: [T=E0whia Te Mana Fellowships] You are invited as a referee for=
 a T=E0whia Te Mana Fellowships application
   Sent: Wednesday, August 14, 2024 11:18:49 AM (UTC+12:00) org111, Welli=
ngton

 was read on Wednesday, August 14, 2024 3:02:29 PM (UTC+12:00) org111, We=
llington.

--_002_SY7P300MB07204081E8E0FC9AA81D5D68C3872SY7P300MB0720AUSP_
Content-Type: text/html; charset="iso-8859-4"
Content-Transfer-Encoding: quoted-printable

<html>
<head>
<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Diso-8859-=
4">
<meta name=3D"Generator" content=3D"Microsoft Exchange Server">
<!-- converted from text --><style><!-- .EmailQuote { margin-left: 1pt; pad=
ding-left: 4pt; border-left: #800000 2px solid; } --></style>
</head>
<body>
<font size=3D"2"><span style=3D"font-size:11pt;">
<div class=3D"PlainText">Your message <br>
<br>
&nbsp;&nbsp; To: Wgxigsg jfskdfjs<br>
&nbsp;&nbsp; Subject: [T=E0whia Te Mana Fellowships] You are invited as a r=
eferee for a T=E0whia Te Mana Fellowships application<br>
&nbsp;&nbsp; Sent: Wednesday, August 14, 2024 11:18:49 AM (UTC+12:00) Auckl=
and, Wellington<br>
<br>
&nbsp;was read on Wednesday, August 14, 2024 3:02:29 PM (UTC+12:00) Aucklan=
d, Wellington.</div>
</span></font>
</body>
</html>

--_002_SY7P300MB07204081E8E0FC9AA81D5D68C3872SY7P300MB0720AUSP_--

--_000_SY7P300MB07204081E8E0FC9AA81D5D68C3872SY7P300MB0720AUSP_
Content-Type: message/disposition-notification

Final-recipient: RFC822; g.jfskdfjs@org111.ac.nz
Disposition: automatic-action/MDN-sent-automatically; displayed
X-MSExch-Correlation-Key: bgQwnyBr5kS+03Z+9z9UVA==
X-Display-Name: Wgxigsg jfskdfjs


--_000_SY7P300MB07204081E8E0FC9AA81D5D68C3872SY7P300MB0720AUSP_--

