From p.tester001@org111.ac.nz  Mon Sep  2 18:10:37 2024
Return-Path: <p.tester001@org111.ac.nz>
X-Original-To: app@portal.pmscienceprizes.org.nz
Delivered-To: app@portal.pmscienceprizes.org.nz
Received: from AUS01-SY4-obe.outbound.protection.outlook.com (mail-sy4aus01on2156.outbound.protection.outlook.com [40.107.107.156])
	by portal.pmscienceprizes.org.nz (Postfix) with ESMTPS id E10B6FAFBE
	for <app@portal.pmscienceprizes.org.nz>; Mon,  2 Sep 2024 18:10:37 +1200 (NZST)
ARC-Seal: i=1; a=rsa-sha256; s=arcselector10001; d=microsoft.com; cv=none;
 b=N+oeZ9SxvjfzUk2IHgKFkTFxQhw8ldlrrVHOUNoBaHFZs4GRlxyHFrssDoUJhTdyRI4VulKJXbEx5woqAByM3FOnTfGCDznk7mAhp8Zbm7CLoFj8sE681jTu/R4l/FZCOInVdvwP/i7MzfrmEz44URH/1nDP3m3wyqsK4/VUcguVDRC57qhH4W6mcTla4/Sb0anLWi7eTzMcVtJIwxZ+osMHkGT1hcD9P0I614S67DH48JVIA4hK9T9tCvVOxH/p3xN2F5Gfety6KgDaseaMByvUD5VyN8jKuCOv88kIcecq3BIFp8r/0yA/w8WwwasaY0HvLAT1GGgep0owWUgOWg==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=microsoft.com;
 s=arcselector10001;
 h=From:Date:Subject:Message-ID:Content-Type:MIME-Version:X-MS-Exchange-AntiSpam-MessageData-ChunkCount:X-MS-Exchange-AntiSpam-MessageData-0:X-MS-Exchange-AntiSpam-MessageData-1;
 bh=yRlqdsVwy02Zz7LHmS6QgWNhO/ME65uuJbJ24G+HZ0k=;
 b=epTLvNhPnzcqyv8RuUKJLuweVTZB7MOioQ0fqajrqt1bMrM76TTdt8I9GidnMFOgqhoNa4eSdOikdlHIxBxVi2CpKsvNHFzdeUezgT+kV/bb/vR/e4aIFCWnFXhYVSJ3y3/CTUTzsVGExXE6bw7w1jVf7MKV08zxgdiaMeXmvnInxqKM9MKxpV0eZY3DT6D+UFZZxV5JM4ntMpH28slROYkSu1KwYlmifccTyHQ1WlzhgPeJgGNL9xvv1h8oDaM5765I8QKoa6iRWUT6kUIa6H8UBBDeeMZskXbe+/0oVDqnVJoXUqK0NakHQSVrmC1SDup8loKVdE1kPbT9ywXe4Q==
ARC-Authentication-Results: i=1; mx.microsoft.com 1; spf=pass
 smtp.mailfrom=org111.ac.nz; dmarc=pass action=none
 header.from=org111.ac.nz; dkim=pass header.d=org111.ac.nz; arc=none
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=org111.ac.nz;
 s=selector1;
 h=From:Date:Subject:Message-ID:Content-Type:MIME-Version:X-MS-Exchange-SenderADCheck;
 bh=yRlqdsVwy02Zz7LHmS6QgWNhO/ME65uuJbJ24G+HZ0k=;
 b=jmZVzTS9juBq8qRBokiyn/YJZcF/X9a5e2w+omJYHjSlJzJZwD1HiN7nsRY8DyrCymtmMTNm8K3l1gCmQVbdGFIKiKp01Tdp9UL/66MsvVw/Ca/b2pu6/6x0z9rdpBF/BdfJgi1tgP+opF6arYeid/Nr9VW73+RkhIRU+SowAZc=
Received: from ME0P300MB0455.AUSP300.PROD.OUTLOOK.COM (2603:10c6:220:22d::12)
 by ME0P300MB0400.AUSP300.PROD.OUTLOOK.COM (2603:10c6:220:232::21) with
 Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.20.7918.24; Mon, 2 Sep
 2024 06:10:36 +0000
Received: from ME0P300MB0455.AUSP300.PROD.OUTLOOK.COM
 ([fe80::bf7c:6566:c4a0:eff9]) by ME0P300MB0455.AUSP300.PROD.OUTLOOK.COM
 ([fe80::bf7c:6566:c4a0:eff9%7]) with mapi id 15.20.7918.024; Mon, 2 Sep 2024
 06:10:36 +0000
From: Tester tester001 <p.tester001@org111.ac.nz>
To: "app@portal.pmscienceprizes.org.nz" <app@portal.pmscienceprizes.org.nz>
Subject: Read: [Prime Minister's Science Prizes] You are invited as a referee
 for a Prime Minister's Science Prizes application
Thread-Topic: [Prime Minister's Science Prizes] You are invited as a referee
 for a Prime Minister's Science Prizes application
Thread-Index: AQHa/OxG8eCrCZMvWEak2AgILDMIBw==
Date: Mon, 2 Sep 2024 06:10:36 +0000
Message-ID: <e8a5c34227bd4399908ef6d36f0a2e14@org111.ac.nz>
Accept-Language: en-GB, en-US
Content-Language: en-GB
X-MS-Has-Attach:
X-MS-TNEF-Correlator:
authentication-results: dkim=none (message not signed)
 header.d=none;dmarc=none action=none header.from=org111.ac.nz;
x-ms-publictraffictype: Email
x-ms-traffictypediagnostic: ME0P300MB0455:EE_|ME0P300MB0400:EE_
x-ms-office365-filtering-correlation-id: 09976443-dcbc-4afc-cc9f-08dccb15f5f2
x-ms-exchange-senderadcheck: 1
x-ms-exchange-antispam-relay: 0
x-microsoft-antispam: BCL:0;ARA:13230040|366016|1800799024|376014;
x-microsoft-antispam-message-info:
 =?us-ascii?Q?QYULxkEEM3R/4PByCQoeJ9IsdCIPuuusK8c/StsW8aNURzrlOsECP9Yi6AZ8?=
 =?us-ascii?Q?urtR0Ly27IRHW5BD35FKmS/8zFU6s6rq15MGz8ffNjLZwaLjbomIK4Pkc9Fg?=
 =?us-ascii?Q?ZA2CXjv4Nl3iq9JMbbTRu20QIFTp3b3rA5jP0I7v63PytQj2aa6s4Co1FFc1?=
 =?us-ascii?Q?QDDEmzIIqkvg8FgplgUUlufrpk+87AaWVXeGOAyKSAJSo6QNOpA5s3+GOKDi?=
 =?us-ascii?Q?Sow1YhxmI8ZnZPElThCwMNpCktSyyL6TVJEqBB264bJjT0M/OFYL5YocGOL7?=
 =?us-ascii?Q?eQPImVpP9zzx6hX1W8FLUDFu2yJ8fDV291KuaEmkEOvO57QoBsMhowWkA2wR?=
 =?us-ascii?Q?sG8k9mvfG6kcA/W7kE1rl8sQCp0yQUyJsFFcBNG4u1Rul4evRXjklnTMwMYZ?=
 =?us-ascii?Q?Lyp7jveu8GkrWNlBK+4bbcWrl1VVZwtLJNDzzVsBdusTfUIF4cIoQmAJH+58?=
 =?us-ascii?Q?MeRy6T/gjAWkYpMIJLw6SIzSjdw6wAClYSDl2HwKwwmaWGMbhXvQjesz28I0?=
 =?us-ascii?Q?0PmGrXwuDxkaf8auRsOHnM5URhuFS4WYSqZQYm0Ddlh/rpooXgEXgyn/S/nD?=
 =?us-ascii?Q?LU4BqiHJEUJZz9vRXGesHCfRSZ3hHgKliEbtHqSO/HG1XTOSfZtjnTxA+1ZO?=
 =?us-ascii?Q?bDNBBIjLtuIoIYsgK4vkYcEay8FIe87iDX3c7pFVaWihKv5vt+DnGACgDjfY?=
 =?us-ascii?Q?Mq/fq7jKi90Lh4BOUab5I9T6gYms5Qv2J76j4Dr/KHIkiriN4/bCpT3NFgeE?=
 =?us-ascii?Q?gSphbCuxbIvq1f0oEwFIlWSehMjHIiyMq2c3nbsjuLqb2v0Ot4TbqIPiOtT4?=
 =?us-ascii?Q?ykjIqo280+y/WUgZ/hqQvtHgB77uguMkuLBcIpJ6w+o7L+ZbDSU+AAPJM87K?=
 =?us-ascii?Q?p8cf99V7PbQrw+wyYmY3K63Ob1e7HI+Ay7pBBeyf8PbxjC8I/l/I3btgv3AY?=
 =?us-ascii?Q?HtpwZhC68JBv7ygcqorSs2aRN0WCNQ1zaWuYQ8mjZem6zTipBHPcds7JNnkp?=
 =?us-ascii?Q?1ABNEYzgN41RIWZ1Z0K9j2/+VU/XHZQe8cr3RszafzdRX3U1ePCf2pt1iC3G?=
 =?us-ascii?Q?/i4mKuIaA3O9oEoWTTBBGTaEc8NkJw=3D=3D?=
x-forefront-antispam-report:
 CIP:255.255.255.255;CTRY:;LANG:en;SCL:1;SRV:;IPV:NLI;SFV:NSPM;H:ME0P300MB0455.AUSP300.PROD.OUTLOOK.COM;PTR:;CAT:NONE;SFS:(13230040)(366016)(1800799024)(376014);DIR:OUT;SFP:1102;
x-ms-exchange-antispam-messagedata-chunkcount: 1
x-ms-exchange-antispam-messagedata-0:
 =?us-ascii?Q?9baGBiQUOm1qDYmawlTgKvqWnt18X1bo00/n84jM6A/dDDjt9vNlmNqBgMsG?=
 =?us-ascii?Q?ZSlvZzhatp5iLuQAajY3yrQRzLqhVRcpBfNOpw6ZTGE10mF18W0I3ilTN8mV?=
 =?us-ascii?Q?htHPaC0qbgZLy/mJ8ioNqwrLN/siEaTdu559ij5P5Qd7xK+NA10OOp9thpug?=
 =?us-ascii?Q?OFGGrXKuBTA8TG/Up/GcNM5BWmDg0uIDZi3jSwLZZAalSqfFzemb/sugZpMz?=
 =?us-ascii?Q?0+UzGFTLzYcrs1HdwiRJHqV7NAWtmLiHp7ID6jQBWhw4aCy7mD76IVHP3dbK?=
 =?us-ascii?Q?ngVb2k7EmZ775432RRVvmTTfu8ek5NStyD0SCrduaDGD3vciUXkUrWazii//?=
 =?us-ascii?Q?r2Bp5WZnh6VMgNXyq10M08sVDk1nYxGDVKPaPx8oKq/MZ9g7Qxi94icl0MmU?=
 =?us-ascii?Q?8ckXoPZxBjvk2sFwjA4FZ8KWvQ9qnDuop9WaqrL793roWfQTdySu1nLsHG9n?=
 =?us-ascii?Q?09MCatMFNj6UjHbDvWesRuGMvO5Nujq5/P3yDRX+FUWE0xdTcjdZSwcpcGhj?=
 =?us-ascii?Q?cdR6AnhQ78/IKfQqd4gf/33Y8490i45OqvbJfbS8soUwY0AweDeO0vyc5cYQ?=
 =?us-ascii?Q?ZwwSCe2CzjysgAcAn/HAH+l/0p2fXfO9MeUVCaeknjeI4X6IPqu+iUGN/Oqz?=
 =?us-ascii?Q?uVglTNo4gvCVtp36dLjaIK4IOBnPSqg4JgXkMMe9MGGwS7BDTirGQHLWeWrf?=
 =?us-ascii?Q?0WjflqE9KzNkcFiOa2t0+p868EwccFYS3lM3O/C+z04zVYUtYLeexBIbv3g4?=
 =?us-ascii?Q?ap81zEKSs0KfJHrljasB7Z4MI1940O4/rgVNLXMZgOqFZlCVKX9OBhvaSvTC?=
 =?us-ascii?Q?g02ghSNBHPR0QTJNbHToJN9cX/vNImrG/+I+EMlrIZS++L5akYmZVuYJlf+T?=
 =?us-ascii?Q?z6ZENyUU0U6S3oRb53fwD+9DaIdJi45oe3dtt+hC09aQefd96xITvzPzgxIV?=
 =?us-ascii?Q?NfQCfCQoJ9MuJgJcWxEcOUQnSDZoBGQvIV9bMXHGPM9oi3E4LrMdXPpP4cBC?=
 =?us-ascii?Q?xU6dqRTGQ3FQcgTrYdjPnEStEqYHxrPMhzEyQOTSgbWFqch8xMEArwO5C+HV?=
 =?us-ascii?Q?0LEirgAKBTDpB6DCRxBipzNARN0NUhNYi0qL1PbxYvBlN2ihaI5ZxvGU/mxr?=
 =?us-ascii?Q?Pa4Vh5U1U09GyE/npZSE3JOKERx4nRCzaPhe5Rw2bj6+i6dlkC17Xsu3GbqP?=
 =?us-ascii?Q?2+TuxVEpWx+bJsLlgAXBQRwCSddf4Q0MfQizpA/LFsMazObcoq2aUXhpCA84?=
 =?us-ascii?Q?S55le9v3OfZ1tTJ0pIugTTB+fm//J0gbhoqBtijfXMLG6hurlmbVy4aQSomW?=
 =?us-ascii?Q?/K5wCYtMJqwYZk66G0zNFNTPax4fyXsJ67VLl/OvemmLpzJPzNEO0W8UWCEa?=
 =?us-ascii?Q?GgDFrJAPA9/0xEHuHaWaZVd+kBRq7bDwPQ6qmnOYjbPngCv6flckav6D7SWH?=
 =?us-ascii?Q?WwQMyYcHr5h3CC+sTKiOofBuG3PG8fIhAbj0tzf+Na46wgaWOH+XMA=3D=3D?=
Content-Type: multipart/report;
	boundary="_000_e8a5c34227bd4399908ef6d36f0a2e14org111acnz_";
	report-type=disposition-notification
MIME-Version: 1.0
X-OriginatorOrg: org111.ac.nz
X-MS-Exchange-CrossTenant-AuthAs: Internal
X-MS-Exchange-CrossTenant-AuthSource: ME0P300MB0455.AUSP300.PROD.OUTLOOK.COM
X-MS-Exchange-CrossTenant-Network-Message-Id: 09976443-dcbc-4afc-cc9f-08dccb15f5f2
X-MS-Exchange-CrossTenant-originalarrivaltime: 02 Sep 2024 06:10:36.0607
 (UTC)
X-MS-Exchange-CrossTenant-fromentityheader: Hosted
X-MS-Exchange-CrossTenant-id: d1b36e95-0d50-42e9-958f-b63fa906beaa
X-MS-Exchange-CrossTenant-mailboxtype: HOSTED
X-MS-Exchange-CrossTenant-userprincipalname: dtZrRwqS4Ermi/++YefJifnaO7jOH7ZF777MUKl2JXoxG8FeuIsYp5ODQuqqgLKb/VwzcNC/coo4+z+gyMwe4UCcYkAId99Gf5XIEOkV9gc=
X-MS-Exchange-Transport-CrossTenantHeadersStamped: ME0P300MB0400
Status: RO
Content-Length: 2013
Lines: 58

--_000_e8a5c34227bd4399908ef6d36f0a2e14org111acnz_
Content-Type: multipart/alternative;
	boundary="_002_e8a5c34227bd4399908ef6d36f0a2e14org111acnz_"

--_002_e8a5c34227bd4399908ef6d36f0a2e14org111acnz_
Content-Type: text/plain; charset="us-ascii"
Content-Transfer-Encoding: quoted-printable

Your message

   To: Tester tester001
   Subject: [Prime Minister's Science Prizes] You are invited as a referee =
for a Prime Minister's Science Prizes application
   Sent: 02 September 2024 15:57:24 (UTC+12:00) org111, Wellington

 was read on 02 September 2024 18:10:36 (UTC+12:00) org111, Wellington.

--_002_e8a5c34227bd4399908ef6d36f0a2e14org111acnz_
Content-Type: text/html; charset="us-ascii"
Content-Transfer-Encoding: quoted-printable

<html>
<head>
<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Dus-ascii"=
>
<meta name=3D"Generator" content=3D"Microsoft Exchange Server">
<!-- converted from text --><style><!-- .EmailQuote { margin-left: 1pt; pad=
ding-left: 4pt; border-left: #800000 2px solid; } --></style>
</head>
<body>
<font size=3D"2"><span style=3D"font-size:11pt;">
<div class=3D"PlainText">Your message <br>
<br>
&nbsp;&nbsp; To: Tester tester001<br>
&nbsp;&nbsp; Subject: [Prime Minister's Science Prizes] You are invited as =
a referee for a Prime Minister's Science Prizes application<br>
&nbsp;&nbsp; Sent: 02 September 2024 15:57:24 (UTC+12:00) org111, Welling=
ton<br>
<br>
&nbsp;was read on 02 September 2024 18:10:36 (UTC+12:00) org111, Wellingt=
on.</div>
</span></font>
</body>
</html>

--_002_e8a5c34227bd4399908ef6d36f0a2e14org111acnz_--

--_000_e8a5c34227bd4399908ef6d36f0a2e14org111acnz_
Content-Type: message/disposition-notification

Final-recipient: RFC822; p.tester001@org111.ac.nz
Disposition: automatic-action/MDN-sent-automatically; displayed
X-MSExch-Correlation-Key: 24ranpRqzUqWfSPBCg0yjw==
Original-Message-ID: <st1iihgl6UV0Mg@portal.pmscienceprizes.org.nz>
X-Display-Name: Tester tester001


--_000_e8a5c34227bd4399908ef6d36f0a2e14org111acnz_--

