From nad2000@gmail.com  Thu Oct 17 11:34:38 2024
Return-Path: <nad2000@gmail.com>
X-Original-To: reports@prodata.nz
Delivered-To: reports@prodata.nz
Received: from mail-yb1-f171.google.com (mail-yb1-f171.google.com [209.85.219.171])
	by mail.prodata.nz (Postfix) with ESMTPS id 22444F9F0B
	for <reports@prodata.nz>; Thu, 17 Oct 2024 11:34:38 +1300 (NZDT)
Received: by mail-yb1-f171.google.com with SMTP id 3f1490d57ef6-e2975432b8cso379958276.1
        for <reports@prodata.nz>; Wed, 16 Oct 2024 15:34:38 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20230601; t=1729118076; x=1729722876; darn=prodata.nz;
        h=to:subject:message-id:date:from:in-reply-to:references:mime-version
         :from:to:cc:subject:date:message-id:reply-to;
        bh=KQ/tbRrVT5TxRSf7YsIn66ES/oWqGnxtSizKXf6f1TA=;
        b=nPqLOL2ZHTOxmwD9G0PjcK7JXKUD0qC7/5a31/lBJMwyBIPYyrS17AV/UqENI1Hr/e
         7gCleG/Jx3Zw1zLSBkL++Bn6Gbry0xcH8dBeqFaxJzaUWctCXakgD92UoegbbA/dgu2d
         z0o0F9C3VXPbCkmR7hUdCHIzDFSu0dLS3dTdmMuEq73oikj2BoNQ1uDH4sE5ib/8r7VS
         0luyQl4qSFrg3v0SOoR8Wkhk7AXVDTtlmRVUoqZWiX0CXVAAmk/B09G9RBi/YJw+HHjx
         4dChsWBTlX7KhDdOa9mODZgLWaOS0mecQn1wmXVZnOJvLRkPuTDm2PG+q+X1KXXf1xcF
         x5Wg==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20230601; t=1729118076; x=1729722876;
        h=to:subject:message-id:date:from:in-reply-to:references:mime-version
         :x-gm-message-state:from:to:cc:subject:date:message-id:reply-to;
        bh=KQ/tbRrVT5TxRSf7YsIn66ES/oWqGnxtSizKXf6f1TA=;
        b=vdFmnBYv+T73S6D16ORv48j78RrC7W/PnRYYC1uCl6k0gBLevLNpU6D/S/3Ve1lJxe
         7zOArsmymczLwrqtmJ2UFqSolJToNWLvdjLlgu58HToYxLQioN3txRi4rQ5Hkn/8RD37
         yUoIJcm1R7SMAY8W8TYsuDkl34w0QJC0+vRSwrFIg/4Qqrm7voc4FI+rm3vh1LR1whq2
         Ndy3M2CbXsp7L6NyP01AEPNAYNCrcHzZ1XR8r9Me3iJLe4rtfJv1WJHPrLG0TUle1kqb
         w4x+4UrLJCEc3Mhj3DlWZc2a8yfNe0LOMYiQ2HWXNhfckCyCsbLi7IOwIFQ7qSXWf6hb
         Qp2A==
X-Gm-Message-State: AOJu0Yx2zvp+7Jk+S6ZYuh3gHx95/hJRztqrsLG1I1512p2238nJBj8a
	foZ5AvcrF0VAAV8iuG2XONFUKV/8iCSeOeu3CjS2zraJyQUyqrLkGzIOhu9/5Cdk3PhtsUDywos
	MpdGa0PmEIXxj8VwXOn7M03xZpkp9
X-Google-Smtp-Source: AGHT+IHAORzI555hQdsU2DVJ9cWpxGScv9ESWsBZx7GZZSEusOCPaRwXmcq+IZSh5pboP8qsuh3/2Kz3gWpukW0pbr4=
X-Received: by 2002:a05:6902:124f:b0:e29:45cb:625e with SMTP id
 3f1490d57ef6-e2945cb7630mr13398809276.41.1729118076036; Wed, 16 Oct 2024
 15:34:36 -0700 (PDT)
MIME-Version: 1.0
References: <agAFtGv-RUOJIw@pmspp.prodata.nz>
In-Reply-To: <agAFtGv-RUOJIw@pmspp.prodata.nz>
From: Damien <nad2000@gmail.com>
Date: Thu, 17 Oct 2024 11:34:24 +1300
Message-ID: <CAA1CNSJos3p+rjrMvOcuR2q7LfThWQU7mtFW_751Yqey-b8vEw@mail.gmail.com>
Subject: Re: [Prime Minister's Science Prizes] Comment posted by RADOMIRS
 CIRSKIS (nad2000+admin@gmail.com) to 1:A:JKJJL-98434: test project
To: "Prime Minister's Science Prizes" <reports@prodata.nz>
Content-Type: multipart/mixed; boundary="000000000000b3693306249fac9c"
Status: RO
Content-Length: 8189
Lines: 159

--000000000000b3693306249fac9c
Content-Type: multipart/alternative; boundary="000000000000b3693106249fac9a"

--000000000000b3693106249fac9a
Content-Type: text/plain; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable

well done!
Radomirs Cirskis AWS CSA, MCDBA, MCAD, MCSD, ZCE, Scrum Master
M: +64 221 221 442 | E: RAD@nowITworks.eu <rad@nowitworks.eu>
[image: View my profile on LinkedIn] <http://nz.linkedin.com/in/nad2000>


On Thu, 17 Oct 2024 at 11:33, Prime Minister's Science Prizes <
reports@prodata.nz> wrote:

> Comment posted by RADOMIRS CIRSKIS (nad2000+admin@gmail.com) to 1:A:JKJJL=
-98434:
> test project:
>
> test test test
> ------------------------------
> To responde to this message, please, click here: REPLY
> <https://pmspp.prodata.nz/reports/1/~update#correspondence>
> To learn more about the Prime Minister=E2=80=99s Science Prizes click her=
e
> <https://www.pmscienceprizes.org.nz/>.
>
> Ng=C4=81 mihi nui,
>
> [image: PM=E2=80=99s Science Prizes Logo Alternative]
>
> Ng=C4=81 Kaiwhakahaere o Te Puiaki P=C5=ABtaiao a Te Pirimia
> Prime Minister=E2=80=99s Science Prize Secretariat
>
> *Waea telephone  *+64 4 470 5762
> *=C4=AAm=C4=93ra email*  pmscienceprizes@royalsociety.org.nz
>
> *C/- Royal Society Te Ap=C4=81rangi *
> 11 Turnbull Street, Thorndon, Wellington 6011
> PO Box 598, Wellington 6140, New Zealand
> *ROYALSOCIETY.ORG.NZ * <http://royalsociety.org.nz/>
>
> *Please consider the environment before printing this email. The
> information contained in this email message is intended only for the
> addressee and may be confidential. If you are not the intended recipient,
> please notify us immediately.*
>

--000000000000b3693106249fac9a
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable

<div dir=3D"ltr"><div class=3D"gmail_default" style=3D"font-family:arial na=
rrow,sans-serif">well done!</div><div><div dir=3D"ltr" class=3D"gmail_signa=
ture" data-smartmail=3D"gmail_signature"><div dir=3D"ltr"><div><div dir=3D"=
ltr"><div><div dir=3D"ltr"><div dir=3D"ltr"><div style=3D"font-family:&quot=
;Times New Roman&quot;;font-size:16px;margin-top:0px;margin-bottom:0px"><di=
v style=3D"font-family:Arial,Helvetica,sans-serif;font-size:small;margin-to=
p:0px;margin-bottom:0px"><span style=3D"font-family:&quot;Times New Roman&q=
uot;"><font face=3D"garamond, serif">Radomirs Cirskis AWS=C2=A0</font></spa=
n><font face=3D"garamond, serif">CSA,=C2=A0</font><span style=3D"font-famil=
y:&quot;Times New Roman&quot;"><font face=3D"garamond, serif">MCDBA</font><=
/span><span style=3D"font-family:&quot;Times New Roman&quot;"><font face=3D=
"garamond, serif">,=C2=A0</font></span><span style=3D"font-family:&quot;Tim=
es New Roman&quot;"><font face=3D"garamond, serif">MCAD,</font></span><span=
 style=3D"font-family:&quot;Times New Roman&quot;"><font face=3D"garamond, =
serif">=C2=A0</font></span><span style=3D"font-family:&quot;Times New Roman=
&quot;"><font face=3D"garamond, serif">MCSD</font></span><span style=3D"fon=
t-family:&quot;Times New Roman&quot;"><font face=3D"garamond, serif">,=C2=
=A0</font></span><span style=3D"font-family:&quot;Times New Roman&quot;"><f=
ont face=3D"garamond, serif">ZCE</font><font face=3D"garamond, serif">, Scr=
um Master</font></span></div><div style=3D"font-family:Arial,Helvetica,sans=
-serif;font-size:small;margin-top:0px;margin-bottom:0px"><span style=3D"fon=
t-family:&quot;Times New Roman&quot;"><font face=3D"garamond, serif">M: +64=
 221 221 442 | E:=C2=A0<a href=3D"mailto:rad@nowitworks.eu" target=3D"_blan=
k">RAD@nowITworks.eu</a></font></span></div><div style=3D"font-family:Arial=
,Helvetica,sans-serif;font-size:small;margin-top:0px;margin-bottom:0px"><a =
href=3D"http://nz.linkedin.com/in/nad2000" target=3D"_blank"><img src=3D"ht=
tp://s.c.lnkd.licdn.com/scds/common/u/img/webpromo/btn_viewmy_160x25.png" w=
idth=3D"160" height=3D"25" alt=3D"View my profile on LinkedIn" style=3D"mar=
gin:0px 0px 5px;padding:0px;border:none;outline:0px;font-size:11px;font-fam=
ily:Helvetica,FreeSans,&quot;Liberation Sans&quot;,Helmet,Arial,sans-serif;=
vertical-align:baseline;color:rgb(102,102,102);line-height:13px;text-align:=
center"></a><span style=3D"color:rgb(102,102,102);line-height:13px;text-ali=
gn:center"><font face=3D"Helvetica, FreeSans, Liberation Sans, Helmet, Aria=
l, sans-serif"><span style=3D"font-size:11px">=C2=A0</span></font></span></=
div></div></div></div></div></div></div></div></div></div><br></div><br><di=
v class=3D"gmail_quote"><div dir=3D"ltr" class=3D"gmail_attr">On Thu, 17 Oc=
t 2024 at 11:33, Prime Minister&#39;s Science Prizes &lt;<a href=3D"mailto:=
reports@prodata.nz">reports@prodata.nz</a>&gt; wrote:<br></div><blockquote =
class=3D"gmail_quote" style=3D"margin:0px 0px 0px 0.8ex;border-left:1px sol=
id rgb(204,204,204);padding-left:1ex"><div><p>Comment posted by RADOMIRS CI=
RSKIS (<a href=3D"mailto:nad2000%2Badmin@gmail.com" target=3D"_blank">nad20=
00+admin@gmail.com</a>) to <u></u>1:A:JKJJL-98434: test project<u></u>:</p>=
<p>test test test</p><hr>To responde to this message, please, click here: <=
a href=3D"https://pmspp.prodata.nz/reports/1/~update#correspondence" target=
=3D"_blank">REPLY</a>

<br>To learn more about the Prime Minister=E2=80=99s Science Prizes
<a href=3D"https://www.pmscienceprizes.org.nz/" target=3D"_blank">click her=
e</a>.<br>
<br>Ng=C4=81 mihi nui,<br>
<p style=3D"margin-bottom:12pt"><span style=3D"font-size:12pt;font-family:H=
elvetica,sans-serif;color:black"><img border=3D"0" width=3D"298" height=3D"=
96" style=3D"width: 3.1041in; height: 1in;" src=3D"https://pmspp.prodata.nz=
/static/images/alt_logo.jpg" alt=3D"PM=E2=80=99s Science Prizes Logo Altern=
ative"></span><br>
<br>
Ng=C4=81 Kaiwhakahaere o Te Puiaki P=C5=ABtaiao a Te Pirimia<br>
Prime Minister=E2=80=99s Science Prize Secretariat</p>
<table border=3D"0" cellspacing=3D"0" cellpadding=3D"0" style=3D"border-col=
lapse:collapse">
<tbody><tr><td style=3D"padding:0cm">
<p style=3D"line-height:115%"><b><span style=3D"font-size:8.5pt;line-height=
:115%;color:black">Waea telephone =C2=A0</span></b><span style=3D"font-size=
:8.5pt;line-height:115%;color:black">+64 4 470 5762<br>
<b><u></u>=C4=AAm=C4=93ra email</b></span><span style=3D"font-size:8.5pt;li=
ne-height:115%">=C2=A0</span><span style=3D"font-size:8.5pt;line-height:115=
%;color:black;background:white">
<a href=3D"mailto:pmscienceprizes@royalsociety.org.nz" target=3D"_blank">
<span style=3D"color:black">pmscienceprizes@royalsociety.org.nz</span></a><=
/span></p>
<p><b><span style=3D"font-size:8.5pt;color:black">C/- Royal Society Te Ap=
=C4=81rangi</span>
</b><span style=3D"font-size:8.5pt;color:black"><br>
11 Turnbull Street, Thorndon, Wellington 6011<br>
PO Box 598, Wellington 6140, New Zealand<br>
<a href=3D"http://royalsociety.org.nz/" target=3D"_blank"><b><span style=3D=
"color:black">ROYALSOCIETY.ORG.NZ</span>
</b></a></span></p><br>
<p><i><span style=3D"font-size:8pt;color:black">Please consider the environ=
ment before
printing this email. The information contained in this email message is int=
ended only
for the addressee and may be confidential. If you are not the intended reci=
pient, please
 notify us immediately.</span></i></p>
</td><td width=3D"25%" valign=3D"bottom" style=3D"width:25%;padding:0cm 5.4=
pt"></td>
</tr></tbody></table></div>
</blockquote></div>

--000000000000b3693106249fac9a--
--000000000000b3693306249fac9c
Content-Type: text/csv; charset="US-ASCII"; name="DocumentType-2023-07-21.csv"
Content-Disposition: attachment; filename="DocumentType-2023-07-21.csv"
Content-Transfer-Encoding: base64
Content-ID: <f_m2cg8zaj0>
X-Attachment-Id: f_m2cg8zaj0

aWQsY3JlYXRlZF9hdCx1cGRhdGVkX2F0LHJvbGUsbmFtZSxuYW1lX2VuLG5hbWVfbWkNCjQsMjAy
My0wNy0xOSAxODo0MDo0MSwyMDIzLTA3LTE5IDE4OjQwOjQxLEYsUm9sZXMgYW5kIFJlc291cmNl
cyxSb2xlcyBhbmQgUmVzb3VyY2VzLA0KMywyMDIzLTA3LTE5IDE4OjQwOjQxLDIwMjMtMDctMTkg
MTg6NDA6NDEsQixCdWRnZXQsQnVkZ2V0LA0KMiwyMDIzLTA3LTE5IDE4OjQwOjQxLDIwMjMtMDct
MTkgMTg6NDA6NDEsQ1YsQ3VycmljdWx1bSBWaXRhZSxDdXJyaWN1bHVtIFZpdGFlLA0KMSwyMDIz
LTA3LTE5IDE4OjQwOjQxLDIwMjMtMDctMTkgMTg6NDA6NDEsQUYsQXBwbGljYXRpb24gRm9ybSxB
cHBsaWNhdGlvbiBGb3JtLEFwcGxpY2F0aW9uIEZvcm0NCg==
--000000000000b3693306249fac9c--

